local E, _, _, P = unpack(ElvUI)
local L = E.Libs.ACL:GetLocale('ElvUI', E.global.general.locale)
local _G = _G

-- Eltruism installer options
function ElvUI_EltreumUI:InstallerOptions()
	ElvUI_EltreumUI.Options.args.installer = E.Libs.ACH:Group(E:TextGradient(L["Installer"], 0.50, 0.70, 1, 0.67, 0.95, 1), L["Install, Reinstall or Update various parts of Eltruism"], 2, 'tab')
	ElvUI_EltreumUI.Options.args.installer.icon = 'Interface\\AddOns\\ElvUI_EltreumUI\\Media\\Icons\\install'
	ElvUI_EltreumUI.Options.args.installer.args.tab1 = E.Libs.ACH:Group(L["General"], nil, 1)
	ElvUI_EltreumUI.Options.args.installer.args.tab1.args.description1 = E.Libs.ACH:Description(L["Eltruism Installer"], 2, nil, 'Interface\\AddOns\\ElvUI_EltreumUI\\Media\\Textures\\EltreumHeader', nil, 3240, 1)
	ElvUI_EltreumUI.Options.args.installer.args.tab1.args.eltruisminstaller = E.Libs.ACH:Execute(L["Launch Eltruism Installer"], L["Launches the Eltruism install prompt"], 3, function() E:GetModule('PluginInstaller'):Queue(ElvUI_EltreumUI.InstallerData) E:ToggleOptions() end,nil,false,'full')
	ElvUI_EltreumUI.Options.args.installer.args.tab1.args.description2 = E.Libs.ACH:Description(L["Eltruism Settings"], 4, nil, 'Interface\\AddOns\\ElvUI_EltreumUI\\Media\\Textures\\EltreumHeader', nil, 3240, 1)
	ElvUI_EltreumUI.Options.args.installer.args.tab1.args.resetupdateeltruism = E.Libs.ACH:Execute(L["Reset/Update Eltruism Settings"], L["Resets/Updates Eltruism Settings to Eltreum's Defaults"], 5, function() ElvUI_EltreumUI:UpdateEltruismSettings() E:StaticPopup_Show('CONFIG_RL') end,nil,false,'full')
	ElvUI_EltreumUI.Options.args.installer.args.tab1.args.description3 = E.Libs.ACH:Description(L["ElvUI Settings"], 6, nil, 'Interface\\AddOns\\ElvUI_EltreumUI\\Media\\Textures\\EltreumHeader', nil, 3240, 1)
	ElvUI_EltreumUI.Options.args.installer.args.tab1.args.updateelvui = E.Libs.ACH:Execute(L["Reset/Update ElvUI Settings"], L["Resets/Updates ElvUI Settings to Eltreum's Defaults"], 7, function() ElvUI_EltreumUI:UpdateElvUISettings() E:StaticPopup_Show('CONFIG_RL') end,nil,false,'full')
	ElvUI_EltreumUI.Options.args.installer.args.tab1.args.description11 = E.Libs.ACH:Description(L["Reinstall"].." ".._G.CHAT_LABEL, 22, nil, 'Interface\\AddOns\\ElvUI_EltreumUI\\Media\\Textures\\EltreumHeader', nil, 3240, 1)
	ElvUI_EltreumUI.Options.args.installer.args.tab1.args.resetchat = E.Libs.ACH:Execute(L["Reset Chat to ElvUI Settings"], nil, 23, function()
		E:SetupChat()
		ElvUI_EltreumUI:Print(L["ElvUI Chat has been set."])
		--for classic chat lfg
		local lfg
		if E.global.general.locale == "enUS" then
			lfg = "LookingForGroup"
		elseif E.global.general.locale == "deDE" then
			lfg = "SucheNachGruppe"
		elseif E.global.general.locale == "esMX" or E.global.general.locale == "esES" then
			lfg = "BuscarGrupo"
		elseif E.global.general.locale == "frFR" then
			lfg = "RechercheDeGroupe"
		elseif E.global.general.locale == "ruRU" then
			lfg = "ПоискСпутников"
		elseif E.global.general.locale == "zhTW" then
			lfg = "尋求組隊"
		else
			lfg = "LookingForGroup"
		end
		if not E.Retail then --remove lfg spam from general and creat tab for it
			if lfg then
				_G.ChatFrame_RemoveChannel(_G.ChatFrame1, lfg)
				_G.FCF_OpenNewWindow()
				_G.ChatFrame_RemoveAllMessageGroups(_G.ChatFrame5)
				_G.FCF_SetWindowName(_G.ChatFrame5, 'LFG')
				_G.ChatFrame_AddChannel(_G.ChatFrame5, lfg)
				_G.FCFTab_UpdateColors(_G.ChatFrame5Tab)
				_G.FCFDock_SelectWindow(_G.GENERAL_CHAT_DOCK, _G.ChatFrame1)
			end
		end
	end,nil,false,'full')
	ElvUI_EltreumUI.Options.args.installer.args.tab1.args.description12 = E.Libs.ACH:Description(L["Skip Plugins"], 24, nil, 'Interface\\AddOns\\ElvUI_EltreumUI\\Media\\Textures\\EltreumHeader', nil, 3240, 1)
	ElvUI_EltreumUI.Options.args.installer.args.tab1.args.skipplugin = E.Libs.ACH:Execute(L["Skip Plugins install message"], L["Make the warnings to install profiles for other plugins stop"], 25, function()
		E.private.ElvUI_EltreumUI.isInstalled.sle = true
		E.private.ElvUI_EltreumUI.isInstalled.windtools = true
		E.private.ElvUI_EltreumUI.isInstalled.projectazilroka = true
	end,nil,false,'full')
	ElvUI_EltreumUI.Options.args.installer.args.tab1.args.description13 = E.Libs.ACH:Description(L["Database Check"], 26, nil, 'Interface\\AddOns\\ElvUI_EltreumUI\\Media\\Textures\\EltreumHeader', nil, 3240, 1)
	ElvUI_EltreumUI.Options.args.installer.args.tab1.args.databasecheck = E.Libs.ACH:Execute(L["Run Database Check"], L["Perform a Database Check if you are updating from a very old version as some settings have changed places and the Database Check will convert them"], 27, function() ElvUI_EltreumUI:DatabaseConversions(true) end,nil,false,'full')
	ElvUI_EltreumUI.Options.args.installer.args.tab1.args.description4 = E.Libs.ACH:Description(L["Clear Details! Damage Meter tables to free up memory"], 28, nil, 'Interface\\AddOns\\ElvUI_EltreumUI\\Media\\Textures\\EltreumHeader', nil, 3240, 1)
	ElvUI_EltreumUI.Options.args.installer.args.tab1.args.detailscache= E.Libs.ACH:Execute(L["Clear Details Tables"], L["Set Details tables to be empty"], 29, function() ElvUI_EltreumUI:EmptyDetailsTable() end,nil,false,'full')
	ElvUI_EltreumUI.Options.args.installer.args.tab2 = E.Libs.ACH:Group(L["Nameplates"], nil, 4)
	ElvUI_EltreumUI.Options.args.installer.args.tab2.args.description1 = E.Libs.ACH:Description(L["Reset Nameplates"], 2, nil, 'Interface\\AddOns\\ElvUI_EltreumUI\\Media\\Textures\\EltreumHeader', nil, 3240, 1)
	ElvUI_EltreumUI.Options.args.installer.args.tab2.args.resetnameplate = E.Libs.ACH:Execute(L["Reset nameplates to Eltruism settings"], nil, 3, function() ElvUI_EltreumUI:SetupNamePlates() ElvUI_EltreumUI:ResolutionOutline() end,nil,false,'full')
	ElvUI_EltreumUI.Options.args.installer.args.tab2.args.description2 = E.Libs.ACH:Description(L["Reset Style Filters"], 4, nil, 'Interface\\AddOns\\ElvUI_EltreumUI\\Media\\Textures\\EltreumHeader', nil, 3240, 1)
	ElvUI_EltreumUI.Options.args.installer.args.tab2.args.resetstylefilter = E.Libs.ACH:Execute(L["Reset Nameplate Style Filters"], nil, 5, function() ElvUI_EltreumUI:SetupStyleFilters() end,nil,false,'full')
	ElvUI_EltreumUI.Options.args.installer.args.tab3 = E.Libs.ACH:Group(L["Layouts"], nil, 4)
	ElvUI_EltreumUI.Options.args.installer.args.tab3.args.description1 = E.Libs.ACH:Description(L["Reinstall DPS Layout"], 2, nil, 'Interface\\AddOns\\ElvUI_EltreumUI\\Media\\Textures\\EltreumHeader', nil, 3240, 1)
	ElvUI_EltreumUI.Options.args.installer.args.tab3.args.resetdpslayout = E.Libs.ACH:Execute(L["Reset layout to Eltruism DPS/Tank"], nil, 3, function() E.data:SetProfile('Eltreum DPS/Tank ('..E.mynameRealm..')') ElvUI_EltreumUI:SetupGeneralLayout() ElvUI_EltreumUI:SetupLayoutDPS() end,nil,false,'full')
	ElvUI_EltreumUI.Options.args.installer.args.tab3.args.description2 = E.Libs.ACH:Description(L["Reinstall Healer Layout"], 4, nil, 'Interface\\AddOns\\ElvUI_EltreumUI\\Media\\Textures\\EltreumHeader', nil, 3240, 1)
	ElvUI_EltreumUI.Options.args.installer.args.tab3.args.resethealerlayout = E.Libs.ACH:Execute(L["Reset layout to Eltruism Healer"], nil, 5, function() E.data:SetProfile('Eltreum Healer ('..E.mynameRealm..')') ElvUI_EltreumUI:SetupGeneralLayout() ElvUI_EltreumUI:SetupLayoutHealer() end,nil,false,'full')
	ElvUI_EltreumUI.Options.args.installer.args.tab3.args.description3 = E.Libs.ACH:Description(L["Reinstall Eltruism Datatext"], 6, nil, 'Interface\\AddOns\\ElvUI_EltreumUI\\Media\\Textures\\EltreumHeader', nil, 3240, 1)
	ElvUI_EltreumUI.Options.args.installer.args.tab3.args.resetdatatext = E.Libs.ACH:Execute(L["Reset/Add Eltruism Datatext Panel"], nil, 7, function() ElvUI_EltreumUI:SetupDataText() E:UpdateMoverPositions() end,nil,false,'full')
	ElvUI_EltreumUI.Options.args.installer.args.tab3.args.description4 = E.Libs.ACH:Description(L["Reinstall Thin Layout"], 8, nil, 'Interface\\AddOns\\ElvUI_EltreumUI\\Media\\Textures\\EltreumHeader', nil, 3240, 1)
	ElvUI_EltreumUI.Options.args.installer.args.tab3.args.thinmode = E.Libs.ACH:Execute(E.NewSign..L["Reset layout to Eltruism Thin"], nil, 9, function() E.data:SetProfile('Eltreum Thin ('..E.mynameRealm..')') ElvUI_EltreumUI:SetupGeneralLayout() ElvUI_EltreumUI:SetupLayoutThin() end,nil,false,'full')
	ElvUI_EltreumUI.Options.args.installer.args.tab3.args.description5 = E.Libs.ACH:Description(L["Alternative unitframe layouts"], 21, nil, 'Interface\\AddOns\\ElvUI_EltreumUI\\Media\\Textures\\EltreumHeader', nil, 3240, 1, "full")
	ElvUI_EltreumUI.Options.args.installer.args.tab3.args.description6 = E.Libs.ACH:Description(L["DPS/Tank layouts were created with pure dps classes in mind, if you play a class with more raid cooldowns like a Shaman, Druid or Paladin you might want to use the alternative layout in order to make it easier for you to use your cooldowns on the members of your group"], 22, nil, nil, nil, nil, nil, "full")
	ElvUI_EltreumUI.Options.args.installer.args.tab3.args.alternative = E.Libs.ACH:Execute(L["Alternative Layout"], nil, 23, function() ElvUI_EltreumUI:AlternativeGroupsDPS() end, nil, false, "full")
	ElvUI_EltreumUI.Options.args.installer.args.tab3.args.original = E.Libs.ACH:Execute(L["Original Layout"], nil, 23, function() ElvUI_EltreumUI:OriginalGroupsDPS() end, nil, false, "full")
	ElvUI_EltreumUI.Options.args.installer.args.tab3.args.description7 = E.Libs.ACH:Description(_G.EDIT_MODE_LAYOUT_HYPERLINK_TEXT or "", 24, nil, 'Interface\\AddOns\\ElvUI_EltreumUI\\Media\\Textures\\EltreumHeader', nil, 3240, 1, nil, not E.Retail)
	ElvUI_EltreumUI.Options.args.installer.args.tab3.args.blizzeditmodelayout = E.Libs.ACH:Execute(E.Retail and _G.HUD_EDIT_MODE_IMPORT_LAYOUT.." ".._G.EDIT_MODE_LAYOUT_HYPERLINK_TEXT or "", nil, 25, function() ElvUI_EltreumUI:NewRetailEditModeLayout() end,nil,false,'full',nil,nil,nil, not E.Retail)
	ElvUI_EltreumUI.Options.args.installer.args.tab4 = E.Libs.ACH:Group(L["Aura Filters"], nil, 4)
	ElvUI_EltreumUI.Options.args.installer.args.tab4.args.description0 = E.Libs.ACH:Description(L["Choose to show all debuffs/buffs or use default Filters"], 1)
	ElvUI_EltreumUI.Options.args.installer.args.tab4.args.general = E.Libs.ACH:Group(L["All"], nil, 1)
	ElvUI_EltreumUI.Options.args.installer.args.tab4.args.general.args.description1 = E.Libs.ACH:Description(L["Apply To All"], 1, nil, 'Interface\\AddOns\\ElvUI_EltreumUI\\Media\\Textures\\EltreumHeader', nil, 3240, 1)
	ElvUI_EltreumUI.Options.args.installer.args.tab4.args.general.args.minimal = E.Libs.ACH:Execute(L["All"], nil, 3, function() ElvUI_EltreumUI:SetupAllAuras('Everything') end,nil,false,'full')
	ElvUI_EltreumUI.Options.args.installer.args.tab4.args.general.args.eltruism = E.Libs.ACH:Execute("Eltruism", nil, 3, function() ElvUI_EltreumUI:SetupAllAuras('Eltruism') end,nil,false,'full')
	ElvUI_EltreumUI.Options.args.installer.args.tab4.args.general.args.all = E.Libs.ACH:Execute(L["Minimal"], nil, 3, function() ElvUI_EltreumUI:SetupAllAuras('Minimal') end,nil,false,'full')
	ElvUI_EltreumUI.Options.args.installer.args.tab4.args.player = E.Libs.ACH:Group(L["Player"], nil, 2)
	ElvUI_EltreumUI.Options.args.installer.args.tab4.args.player.args.description1 = E.Libs.ACH:Description(L["Select how auras will be displayed for Player"], 1, nil, 'Interface\\AddOns\\ElvUI_EltreumUI\\Media\\Textures\\EltreumHeader', nil, 3240, 1)
	ElvUI_EltreumUI.Options.args.installer.args.tab4.args.player.args.allbuffs = E.Libs.ACH:Execute(L["All Player Buffs"], L["Set filters to show more buffs on Player"], 2, function() ElvUI_EltreumUI:SetupBuffs('player', 'Everything') end,nil,false,'full')
	ElvUI_EltreumUI.Options.args.installer.args.tab4.args.player.args.alldebuffs = E.Libs.ACH:Execute(L["All Player Debuffs"], L["Set filters to show more debuffs on Player"], 3, function() ElvUI_EltreumUI:SetupDebuffs('player', 'Everything') end,nil,false,'full')
	ElvUI_EltreumUI.Options.args.installer.args.tab4.args.player.args.description2 = E.Libs.ACH:Description(nil, 4, nil, 'Interface\\AddOns\\ElvUI_EltreumUI\\Media\\Textures\\EltreumHeader', nil, 3240, 1)
	ElvUI_EltreumUI.Options.args.installer.args.tab4.args.player.args.eltruismbuffs = E.Libs.ACH:Execute(L["Eltruism Player Buffs"], L["Set filters to be Eltruism defaults on Player"], 5, function() ElvUI_EltreumUI:SetupBuffs('player', 'Eltruism') end,nil,false,'full')
	ElvUI_EltreumUI.Options.args.installer.args.tab4.args.player.args.eltruismdebuffs = E.Libs.ACH:Execute(L["Eltruism Player Debuffs"], L["Set filters to be Eltruism defaults on Player"], 6, function() ElvUI_EltreumUI:SetupDebuffs('player', 'Eltruism') end,nil,false,'full')
	ElvUI_EltreumUI.Options.args.installer.args.tab4.args.player.args.description3 = E.Libs.ACH:Description(nil, 7, nil, 'Interface\\AddOns\\ElvUI_EltreumUI\\Media\\Textures\\EltreumHeader', nil, 3240, 1)
	ElvUI_EltreumUI.Options.args.installer.args.tab4.args.player.args.minimalbuffs = E.Libs.ACH:Execute(L["Minimal Buffs"], nil, 8, function() ElvUI_EltreumUI:SetupBuffs('player', 'Minimal') end,nil,false,'full')
	ElvUI_EltreumUI.Options.args.installer.args.tab4.args.player.args.minimaldebuffs = E.Libs.ACH:Execute(L["Minimal Debuffs"], nil, 9, function() ElvUI_EltreumUI:SetupDebuffs('player', 'Minimal') end,nil,false,'full')
	ElvUI_EltreumUI.Options.args.installer.args.tab4.args.target = E.Libs.ACH:Group(TARGET, nil, 2)
	ElvUI_EltreumUI.Options.args.installer.args.tab4.args.target.args.target = E.Libs.ACH:Description(L["Select how auras will be displayed for Target"], 1, nil, 'Interface\\AddOns\\ElvUI_EltreumUI\\Media\\Textures\\EltreumHeader', nil, 3240, 1)
	ElvUI_EltreumUI.Options.args.installer.args.tab4.args.target.args.allbuffs = E.Libs.ACH:Execute(L["All Target Buffs"], L["Set filters to show more buffs on Target"], 2, function() ElvUI_EltreumUI:SetupBuffs('target', 'Everything') end,nil,false,'full')
	ElvUI_EltreumUI.Options.args.installer.args.tab4.args.target.args.alldebuffs = E.Libs.ACH:Execute(L["All Target Debuffs"], L["Set filters to show more debuffs on Target"], 3, function() ElvUI_EltreumUI:SetupDebuffs('target', 'Everything') end,nil,false,'full')
	ElvUI_EltreumUI.Options.args.installer.args.tab4.args.target.args.description2 = E.Libs.ACH:Description(nil, 4, nil, 'Interface\\AddOns\\ElvUI_EltreumUI\\Media\\Textures\\EltreumHeader', nil, 3240, 1)
	ElvUI_EltreumUI.Options.args.installer.args.tab4.args.target.args.eltruismbuffs = E.Libs.ACH:Execute(L["Eltruism Target Buffs"], L["Set filters to be Eltruism defaults on Target"], 5, function() ElvUI_EltreumUI:SetupBuffs('target', 'Eltruism') end,nil,false,'full')
	ElvUI_EltreumUI.Options.args.installer.args.tab4.args.target.args.eltruismdebuffs = E.Libs.ACH:Execute(L["Eltruism Target Debuffs"], L["Set filters to be Eltruism defaults on Target"], 6, function() ElvUI_EltreumUI:SetupDebuffs('target', 'Eltruism') end,nil,false,'full')
	ElvUI_EltreumUI.Options.args.installer.args.tab4.args.target.args.description3 = E.Libs.ACH:Description(nil, 7, nil, 'Interface\\AddOns\\ElvUI_EltreumUI\\Media\\Textures\\EltreumHeader', nil, 3240, 1)
	ElvUI_EltreumUI.Options.args.installer.args.tab4.args.target.args.minimalbuffs = E.Libs.ACH:Execute(L["Minimal Buffs"], nil, 8, function() ElvUI_EltreumUI:SetupBuffs('target', 'Minimal') end,nil,false,'full')
	ElvUI_EltreumUI.Options.args.installer.args.tab4.args.target.args.minimaldebuffs = E.Libs.ACH:Execute(L["Minimal Debuffs"], nil, 9, function() ElvUI_EltreumUI:SetupDebuffs('target', 'Minimal') end,nil,false,'full')
	ElvUI_EltreumUI.Options.args.installer.args.tab4.args.focus = E.Libs.ACH:Group(_G.POWER_TYPE_FOCUS or "", nil, 2, nil, nil, nil, nil, E.Classic)
	ElvUI_EltreumUI.Options.args.installer.args.tab4.args.focus.args.description1 = E.Libs.ACH:Description(L["Select how auras will be displayed for Focus"], 1, nil, 'Interface\\AddOns\\ElvUI_EltreumUI\\Media\\Textures\\EltreumHeader', nil, 3240, 1)
	ElvUI_EltreumUI.Options.args.installer.args.tab4.args.focus.args.allbuffs = E.Libs.ACH:Execute(L["All Focus Buffs"], L["Set filters to show more buffs on Focus"], 2, function() ElvUI_EltreumUI:SetupBuffs('focus', 'Everything') end,nil,false,'full')
	ElvUI_EltreumUI.Options.args.installer.args.tab4.args.focus.args.alldebuffs = E.Libs.ACH:Execute(L["All Focus Debuffs"], L["Set filters to show more debuffs on Focus"], 3, function() ElvUI_EltreumUI:SetupDebuffs('focus', 'Everything') end,nil,false,'full')
	ElvUI_EltreumUI.Options.args.installer.args.tab4.args.focus.args.description2 = E.Libs.ACH:Description(nil, 4, nil, 'Interface\\AddOns\\ElvUI_EltreumUI\\Media\\Textures\\EltreumHeader', nil, 3240, 1)
	ElvUI_EltreumUI.Options.args.installer.args.tab4.args.focus.args.eltruismbuffs = E.Libs.ACH:Execute(L["Eltruism Focus Buffs"], L["Set filters to be Eltruism defaults on Focus"], 5, function() ElvUI_EltreumUI:SetupBuffs('focus', 'Eltruism') end,nil,false,'full')
	ElvUI_EltreumUI.Options.args.installer.args.tab4.args.focus.args.eltruismdebuffs = E.Libs.ACH:Execute(L["Eltruism Focus Debuffs"], L["Set filters to be Eltruism defaults on Focus"], 6, function() ElvUI_EltreumUI:SetupDebuffs('focus', 'Eltruism') end,nil,false,'full')
	ElvUI_EltreumUI.Options.args.installer.args.tab4.args.focus.args.description3 = E.Libs.ACH:Description(nil, 7, nil, 'Interface\\AddOns\\ElvUI_EltreumUI\\Media\\Textures\\EltreumHeader', nil, 3240, 1)
	ElvUI_EltreumUI.Options.args.installer.args.tab4.args.focus.args.minimalbuffs = E.Libs.ACH:Execute(L["Minimal Buffs"], nil, 8, function() ElvUI_EltreumUI:SetupBuffs('focus', 'Minimal') end,nil,false,'full')
	ElvUI_EltreumUI.Options.args.installer.args.tab4.args.focus.args.minimaldebuffs = E.Libs.ACH:Execute(L["Minimal Debuffs"], nil, 9, function() ElvUI_EltreumUI:SetupDebuffs('focus', 'Minimal') end,nil,false,'full')
	ElvUI_EltreumUI.Options.args.installer.args.tab4.args.boss = E.Libs.ACH:Group(L["Boss"], nil, 2, nil, nil, nil, nil, E.Classic)
	ElvUI_EltreumUI.Options.args.installer.args.tab4.args.boss.args.description1 = E.Libs.ACH:Description(L["Select how auras will be displayed for Boss"], 1, nil, 'Interface\\AddOns\\ElvUI_EltreumUI\\Media\\Textures\\EltreumHeader', nil, 3240, 1)
	ElvUI_EltreumUI.Options.args.installer.args.tab4.args.boss.args.allbuffs = E.Libs.ACH:Execute(L["All Boss Buffs"], L["Set filters to show more buffs on Boss"], 2, function() ElvUI_EltreumUI:SetupBuffs('boss', 'Everything') end,nil,false,'full')
	ElvUI_EltreumUI.Options.args.installer.args.tab4.args.boss.args.alldebuffs = E.Libs.ACH:Execute(L["All Boss Debuffs"], L["Set filters to show more debuffs on Boss"], 3, function() ElvUI_EltreumUI:SetupDebuffs('boss', 'Everything') end,nil,false,'full')
	ElvUI_EltreumUI.Options.args.installer.args.tab4.args.boss.args.description2 = E.Libs.ACH:Description(nil, 4, nil, 'Interface\\AddOns\\ElvUI_EltreumUI\\Media\\Textures\\EltreumHeader', nil, 3240, 1)
	ElvUI_EltreumUI.Options.args.installer.args.tab4.args.boss.args.eltruismbuffs = E.Libs.ACH:Execute(L["Eltruism Boss Buffs"], L["Set filters to be Eltruism defaults on Boss"], 5, function() ElvUI_EltreumUI:SetupBuffs('boss', 'Eltruism') end,nil,false,'full')
	ElvUI_EltreumUI.Options.args.installer.args.tab4.args.boss.args.eltruismdebuffs = E.Libs.ACH:Execute(L["Eltruism Boss Debuffs"], L["Set filters to be Eltruism defaults on Boss"], 6, function() ElvUI_EltreumUI:SetupDebuffs('boss', 'Eltruism') end,nil,false,'full')
	ElvUI_EltreumUI.Options.args.installer.args.tab4.args.boss.args.description3 = E.Libs.ACH:Description(nil, 7, nil, 'Interface\\AddOns\\ElvUI_EltreumUI\\Media\\Textures\\EltreumHeader', nil, 3240, 1)
	ElvUI_EltreumUI.Options.args.installer.args.tab4.args.boss.args.minimalbuffs = E.Libs.ACH:Execute(L["Minimal Buffs"], nil, 8, function() ElvUI_EltreumUI:SetupBuffs('boss', 'Minimal') end,nil,false,'full')
	ElvUI_EltreumUI.Options.args.installer.args.tab4.args.boss.args.minimaldebuffs = E.Libs.ACH:Execute(L["Minimal Debuffs"], nil, 9, function() ElvUI_EltreumUI:SetupDebuffs('boss', 'Minimal') end,nil,false,'full')
	ElvUI_EltreumUI.Options.args.installer.args.tab4.args.nameplate = E.Libs.ACH:Group(L["Nameplates"], nil, 2)
	ElvUI_EltreumUI.Options.args.installer.args.tab4.args.nameplate.args.description1 = E.Libs.ACH:Description(L["Select how auras will be displayed for Nameplates"], 1, nil, 'Interface\\AddOns\\ElvUI_EltreumUI\\Media\\Textures\\EltreumHeader', nil, 3240, 1)
	ElvUI_EltreumUI.Options.args.installer.args.tab4.args.nameplate.args.allbuffs = E.Libs.ACH:Execute(L["All Nameplate Buffs"], L["Set filters to show more buffs on Nameplates"], 2, function() ElvUI_EltreumUI:SetupBuffs('nameplate', 'Everything') end,nil,false,'full')
	ElvUI_EltreumUI.Options.args.installer.args.tab4.args.nameplate.args.alldebuffs = E.Libs.ACH:Execute(L["All Nameplate Debuffs"], L["Set filters to show more debuffs on Nameplates"], 3, function() ElvUI_EltreumUI:SetupDebuffs('nameplate', 'Everything') end,nil,false,'full')
	ElvUI_EltreumUI.Options.args.installer.args.tab4.args.nameplate.args.description2 = E.Libs.ACH:Description(nil, 4, nil, 'Interface\\AddOns\\ElvUI_EltreumUI\\Media\\Textures\\EltreumHeader', nil, 3240, 1)
	ElvUI_EltreumUI.Options.args.installer.args.tab4.args.nameplate.args.eltruismbuffs = E.Libs.ACH:Execute(L["Eltruism Nameplate Buffs"], L["Set filters to be Eltruism defaults on Nameplates"], 5, function() ElvUI_EltreumUI:SetupBuffs('nameplate', 'Eltruism') end,nil,false,'full')
	ElvUI_EltreumUI.Options.args.installer.args.tab4.args.nameplate.args.eltruismdebuffs = E.Libs.ACH:Execute(L["Eltruism Nameplate Debuffs"], L["Set filters to be Eltruism defaults on Nameplates"], 6, function() ElvUI_EltreumUI:SetupDebuffs('nameplate', 'Eltruism') end,nil,false,'full')
	ElvUI_EltreumUI.Options.args.installer.args.tab4.args.nameplate.args.description3 = E.Libs.ACH:Description(nil, 7, nil, 'Interface\\AddOns\\ElvUI_EltreumUI\\Media\\Textures\\EltreumHeader', nil, 3240, 1)
	ElvUI_EltreumUI.Options.args.installer.args.tab4.args.nameplate.args.minimalbuffs = E.Libs.ACH:Execute(L["Minimal Buffs"], nil, 8, function() ElvUI_EltreumUI:SetupBuffs('nameplate', 'Minimal') end,nil,false,'full')
	ElvUI_EltreumUI.Options.args.installer.args.tab4.args.nameplate.args.minimaldebuffs = E.Libs.ACH:Execute(L["Minimal Debuffs"], nil, 9, function() ElvUI_EltreumUI:SetupDebuffs('nameplate', 'Minimal') end,nil,false,'full')
	ElvUI_EltreumUI.Options.args.installer.args.tab4.args.party = E.Libs.ACH:Group(_G.PARTY, nil, 2)
	ElvUI_EltreumUI.Options.args.installer.args.tab4.args.party.args.description1 = E.Libs.ACH:Description(L["Select how auras will be displayed for Party"], 1, nil, 'Interface\\AddOns\\ElvUI_EltreumUI\\Media\\Textures\\EltreumHeader', nil, 3240, 1)
	ElvUI_EltreumUI.Options.args.installer.args.tab4.args.party.args.allbuffs = E.Libs.ACH:Execute(L["All Party Buffs"], L["Set filters to show more buffs on Party"], 2, function() ElvUI_EltreumUI:SetupBuffs('party', 'Everything') end,nil,false,'full')
	ElvUI_EltreumUI.Options.args.installer.args.tab4.args.party.args.alldebuffs = E.Libs.ACH:Execute(L["All Party Debuffs"], L["Set filters to show more debuffs on Party"], 3, function() ElvUI_EltreumUI:SetupDebuffs('party', 'Everything') end,nil,false,'full')
	ElvUI_EltreumUI.Options.args.installer.args.tab4.args.party.args.description2 = E.Libs.ACH:Description(nil, 4, nil, 'Interface\\AddOns\\ElvUI_EltreumUI\\Media\\Textures\\EltreumHeader', nil, 3240, 1)
	ElvUI_EltreumUI.Options.args.installer.args.tab4.args.party.args.eltruismbuffs = E.Libs.ACH:Execute(L["Eltruism Party Buffs"], L["Set filters to be Eltruism defaults on Party"], 5, function() ElvUI_EltreumUI:SetupBuffs('party', 'Eltruism') end,nil,false,'full')
	ElvUI_EltreumUI.Options.args.installer.args.tab4.args.party.args.eltruismdebuffs = E.Libs.ACH:Execute(L["Eltruism Party Debuffs"], L["Set filters to be Eltruism defaults on Party"], 6, function() ElvUI_EltreumUI:SetupDebuffs('party', 'Eltruism') end,nil,false,'full')
	ElvUI_EltreumUI.Options.args.installer.args.tab4.args.party.args.description3 = E.Libs.ACH:Description(nil, 7, nil, 'Interface\\AddOns\\ElvUI_EltreumUI\\Media\\Textures\\EltreumHeader', nil, 3240, 1)
	ElvUI_EltreumUI.Options.args.installer.args.tab4.args.party.args.minimalbuffs = E.Libs.ACH:Execute(L["Minimal Buffs"], nil, 8, function() ElvUI_EltreumUI:SetupBuffs('party', 'Minimal') end,nil,false,'full')
	ElvUI_EltreumUI.Options.args.installer.args.tab4.args.party.args.minimaldebuffs = E.Libs.ACH:Execute(L["Minimal Debuffs"], nil, 9, function() ElvUI_EltreumUI:SetupDebuffs('party', 'Minimal') end,nil,false,'full')
	ElvUI_EltreumUI.Options.args.installer.args.tab4.args.raid = E.Libs.ACH:Group(_G.RAID, nil, 2)
	ElvUI_EltreumUI.Options.args.installer.args.tab4.args.raid.args.description1 = E.Libs.ACH:Description(L["Select how auras will be displayed for Raid"], 1, nil, 'Interface\\AddOns\\ElvUI_EltreumUI\\Media\\Textures\\EltreumHeader', nil, 3240, 1)
	ElvUI_EltreumUI.Options.args.installer.args.tab4.args.raid.args.allbuffs = E.Libs.ACH:Execute(L["All Raid Buffs"], L["Set filters to show more buffs on Raid"], 2, function() ElvUI_EltreumUI:SetupBuffs('raid', 'Everything') end,nil,false,'full')
	ElvUI_EltreumUI.Options.args.installer.args.tab4.args.raid.args.alldebuffs = E.Libs.ACH:Execute(L["All Raid Debuffs"], L["Set filters to show more debuffs on Raid"], 3, function() ElvUI_EltreumUI:SetupDebuffs('raid', 'Everything') end,nil,false,'full')
	ElvUI_EltreumUI.Options.args.installer.args.tab4.args.raid.args.description2 = E.Libs.ACH:Description(nil, 4, nil, 'Interface\\AddOns\\ElvUI_EltreumUI\\Media\\Textures\\EltreumHeader', nil, 3240, 1)
	ElvUI_EltreumUI.Options.args.installer.args.tab4.args.raid.args.eltruismbuffs = E.Libs.ACH:Execute(L["Eltruism Raid Buffs"], L["Set filters to be Eltruism defaults on Raid"], 5, function() ElvUI_EltreumUI:SetupBuffs('raid', 'Eltruism') end,nil,false,'full')
	ElvUI_EltreumUI.Options.args.installer.args.tab4.args.raid.args.eltruismdebuffs = E.Libs.ACH:Execute(L["Eltruism Raid Debuffs"], L["Set filters to be Eltruism defaults on Raid"], 6, function() ElvUI_EltreumUI:SetupDebuffs('raid', 'Eltruism') end,nil,false,'full')
	ElvUI_EltreumUI.Options.args.installer.args.tab4.args.raid.args.description3 = E.Libs.ACH:Description(nil, 7, nil, 'Interface\\AddOns\\ElvUI_EltreumUI\\Media\\Textures\\EltreumHeader', nil, 3240, 1)
	ElvUI_EltreumUI.Options.args.installer.args.tab4.args.raid.args.minimalbuffs = E.Libs.ACH:Execute(L["Minimal Buffs"], nil, 8, function() ElvUI_EltreumUI:SetupBuffs('raid', 'Minimal') end,nil,false,'full')
	ElvUI_EltreumUI.Options.args.installer.args.tab4.args.raid.args.minimaldebuffs = E.Libs.ACH:Execute(L["Minimal Debuffs"], nil, 9, function() ElvUI_EltreumUI:SetupDebuffs('raid', 'Minimal') end,nil,false,'full')
	ElvUI_EltreumUI.Options.args.installer.args.tab4.args.aurabar = E.Libs.ACH:Group(L["Aura Bars"], nil, 2)
	ElvUI_EltreumUI.Options.args.installer.args.tab4.args.aurabar.args.description1 = E.Libs.ACH:Description(L["Select how auras will be displayed for Aura Bars"], 1, nil, 'Interface\\AddOns\\ElvUI_EltreumUI\\Media\\Textures\\EltreumHeader', nil, 3240, 1)
	ElvUI_EltreumUI.Options.args.installer.args.tab4.args.aurabar.args.alldebuffs = E.Libs.ACH:Execute(_G.ALL, nil, 3, function() ElvUI_EltreumUI:SetupDebuffs('aurabar', 'Everything') end,nil,false,'full')
	ElvUI_EltreumUI.Options.args.installer.args.tab4.args.aurabar.args.description2 = E.Libs.ACH:Description(nil, 4, nil, 'Interface\\AddOns\\ElvUI_EltreumUI\\Media\\Textures\\EltreumHeader', nil, 3240, 1)
	ElvUI_EltreumUI.Options.args.installer.args.tab4.args.aurabar.args.eltruismdebuffs = E.Libs.ACH:Execute("Eltruism", nil, 5, function() ElvUI_EltreumUI:SetupDebuffs('aurabar', 'Eltruism') end,nil,false,'full')
	ElvUI_EltreumUI.Options.args.installer.args.tab4.args.aurabar.args.description3 = E.Libs.ACH:Description(nil, 6, nil, 'Interface\\AddOns\\ElvUI_EltreumUI\\Media\\Textures\\EltreumHeader', nil, 3240, 1)
	ElvUI_EltreumUI.Options.args.installer.args.tab4.args.aurabar.args.minimalbuffs = E.Libs.ACH:Execute(L["Minimal"], nil, 7, function() ElvUI_EltreumUI:SetupBuffs('aurabar', 'Minimal') end,nil,false,'full')
	ElvUI_EltreumUI.Options.args.installer.args.tab5 = E.Libs.ACH:Group(L["Gradient"], nil, 4, 'tab')
	ElvUI_EltreumUI.Options.args.installer.args.tab5.args.export = E.Libs.ACH:Group(L["Export"], nil, 1, 'tab')
	ElvUI_EltreumUI.Options.args.installer.args.tab5.args.export.args.input = E.Libs.ACH:Input(L["Exported Gradient Data:"], nil, 1, 27, "full", function() return ElvUI_EltreumUI:ExportImportGradient(nil,"export") end, function() return end)
	ElvUI_EltreumUI.Options.args.installer.args.tab5.args.export.args.input.disableButton = true
	ElvUI_EltreumUI.Options.args.installer.args.tab5.args.import = E.Libs.ACH:Group(L["Import"], nil, 2, 'tab')
	ElvUI_EltreumUI.Options.args.installer.args.tab5.args.import.args.input = E.Libs.ACH:Input(L["Import Gradient Data"], nil, 1, 27, "full", function() return "" end, function(_, data) ElvUI_EltreumUI:ExportImportGradient(data,"import") end)
	ElvUI_EltreumUI.Options.args.installer.args.tab5.args.import.args.input.focusSelect = true
end
