local ElvUI_EltreumUI, E, L, V, P, G = unpack(select(2, ...))

function ElvUI_EltreumUI:AuraOptions()
	local aurafilters = {
		type = 'group',
		name = L["Aura Filters"],
		icon = 'Interface\\AddOns\\ElvUI_EltreumUI\\Media\\Icons\\aurafilter',
		childGroups = "tab",
		order = 85,
		args = {
			player = {
				type = 'group',
				name = L["Player"],
				order = 2,
				args = {
					headerline1 = {
						order = 1,
						type = "description",
						name = L["Select how auras will be displayed for Player"],
						width = 'full',
						image = function() return 'Interface\\AddOns\\ElvUI_EltreumUI\\Media\\Textures\\EltreumHeader', 3240, 1 end,
					},
					playerallbuffs = {
						order = 6,
						type = 'execute',
						name = L["All Player Buffs"],
						desc = L["Set filters to show more buffs on Player"],
						width = 'double',
						func = function() ElvUI_EltreumUI:SetupBuffs('player', 'Everything') end,
					},
					playeralldebuffs = {
						order = 6,
						type = 'execute',
						name = L["All Player Debuffs"],
						desc = L["Set filters to show more debuffs on Player"],
						width = 'double',
						func = function() ElvUI_EltreumUI:SetupDebuffs('player', 'Everything') end,
					},
					playerEltruismbuffs = {
						order = 9,
						type = 'execute',
						name = L["Eltruism Player Buffs"],
						desc = L["Set filters to be Eltruism defaults on Player"],
						width = 'double',
						func = function() ElvUI_EltreumUI:SetupBuffs('player', 'Eltruism') end,
					},
					playerEltruismdebuffs = {
						order = 9,
						type = 'execute',
						name = L["Eltruism Player Debuffs"],
						desc = L["Set filters to be Eltruism defaults on Player"],
						width = 'double',
						func = function() ElvUI_EltreumUI:SetupDebuffs('player', 'Eltruism') end,
					},
				},
			},
			target = {
				type = 'group',
				name = L["Target"],
				order = 2,
				args = {
					headerline1 = {
						order = 1,
						type = "description",
						name = L["Select how auras will be displayed for Target"],
						width = 'full',
						image = function() return 'Interface\\AddOns\\ElvUI_EltreumUI\\Media\\Textures\\EltreumHeader', 3240, 1 end,
					},
					targetalldebuffs = {
						order = 6,
						type = 'execute',
						name = L["All Target Debuffs"],
						desc = L["Set filters to show more debuffs on Target"],
						width = 'double',
						func = function() ElvUI_EltreumUI:SetupDebuffs('target', 'Everything') end,
					},
					targetallbuffs = {
						order = 6,
						type = 'execute',
						name = L["All Target Buffs"],
						desc = L["Set filters to show more buffs on Target"],
						width = 'double',
						func = function() ElvUI_EltreumUI:SetupBuffs('target', 'Everything') end,
					},
					targetEltruismdebuffs = {
						order = 9,
						type = 'execute',
						name = L["Eltruism Target Debuffs"],
						desc = L["Set filters to be Eltruism defaults on Target"],
						width = 'double',
						func = function() ElvUI_EltreumUI:SetupDebuffs('target', 'Eltruism') end,
					},
					targetEltruismbuffs = {
						order = 9,
						type = 'execute',
						name = L["Eltruism Target Buffs"],
						desc = L["Set filters to be Eltruism defaults on Target"],
						width = 'double',
						func = function() ElvUI_EltreumUI:SetupBuffs('target', 'Eltruism') end,
					},
				},
			},
			focus= {
				type = 'group',
				name = L["Focus"],
				order = 2,
				args = {
					headerline1 = {
						order = 1,
						type = "description",
						name = L["Select how auras will be displayed for Focus"],
						width = 'full',
						image = function() return 'Interface\\AddOns\\ElvUI_EltreumUI\\Media\\Textures\\EltreumHeader', 3240, 1 end,
					},
					focusallbuffs = {
						order = 6,
						type = 'execute',
						name = L["All Focus Buffs"],
						desc = L["Set filters to show more buffs on Focus"],
						width = 'double',
						func = function() ElvUI_EltreumUI:SetupBuffs('focus', 'Everything') end,
					},
					focusalldebuffs = {
						order = 6,
						type = 'execute',
						name = L["All Focus Debuffs"],
						desc = L["Set filters to show more debuffs on Focus"],
						width = 'double',
						func = function() ElvUI_EltreumUI:SetupDebuffs('focus', 'Everything') end,
					},
					focusEltruismbuffs = {
						order = 9,
						type = 'execute',
						name = L["Eltruism Focus Buffs"],
						desc = L["Set filters to be Eltruism defaults on Focus"],
						width = 'double',
						func = function() ElvUI_EltreumUI:SetupBuffs('focus', 'Eltruism') end,
					},
					focusEltruismdebuffs = {
						order = 9,
						type = 'execute',
						name = L["Eltruism Focus Debuffs"],
						desc = L["Set filters to be Eltruism defaults on Focus"],
						width = 'double',
						func = function() ElvUI_EltreumUI:SetupDebuffs('focus', 'Eltruism') end,
					},
				}
			},
			nameplate= {
				type = 'group',
				name = L["Nameplates"],
				order = 2,
				args = {
					headerline1 = {
						order = 1,
						type = "description",
						name = L["Select how auras will be displayed for Nameplates"],
						width = 'full',
						image = function() return 'Interface\\AddOns\\ElvUI_EltreumUI\\Media\\Textures\\EltreumHeader', 3240, 1 end,
					},
					nameplateallbuffs = {
						order = 6,
						type = 'execute',
						name = L["All Nameplate Buffs"],
						desc = L["Set filters to show more buffs on Nameplates"],
						width = 'double',
						func = function() ElvUI_EltreumUI:SetupBuffs('nameplate', 'Everything') end,
					},
					nameplatealldebuffs = {
						order = 6,
						type = 'execute',
						name = L["All Nameplate Debuffs"],
						desc = L["Set filters to show more debuffs on Nameplates"],
						width = 'double',
						func = function() ElvUI_EltreumUI:SetupDebuffs('nameplate', 'Everything') end,
					},
					nameplateEltruismbuffs = {
						order = 9,
						type = 'execute',
						name = L["Eltruism Nameplate Buffs"],
						desc = L["Set filters to be Eltruism defaults on Nameplates"],
						width = 'double',
						func = function() ElvUI_EltreumUI:SetupBuffs('nameplate', 'Eltruism') end,
					},
					nameplateEltruismdebuffs = {
						order = 9,
						type = 'execute',
						name = L["Eltruism Nameplate Debuffs"],
						desc = L["Set filters to be Eltruism defaults on Nameplates"],
						width = 'double',
						func = function() ElvUI_EltreumUI:SetupDebuffs('nameplate', 'Eltruism') end,
					},
				}
			},
		},
	}
	return aurafilters
end
