local ElvUI_EltreumUI, E, L, V, P, G = unpack(select(2, ...))

function ElvUI_EltreumUI:ChatOptions()
	local chat = {
		type = 'group',
		name = L["Chat"],
		icon = 'Interface\\AddOns\\ElvUI_EltreumUI\\Media\\Icons\\chat',
		order = 85,
		args = {
			chatOptions = {
				order = 1,
				type = 'group',
				inline = true,
				name = L["Chat Options"],
				args = {
					chatfadeenable = {
						order = 1,
						type = 'toggle',
						name = L["Enable ElvUI Chat modifications"],
						width = 'full',
						desc = L["Add fade over time, and mouse over to left and right chat panels"],
						get = function() return E.db.ElvUI_EltreumUI.chat.enable end,
						set = function(_, value) E.db.ElvUI_EltreumUI.chat.enable = value E:StaticPopup_Show('CONFIG_RL') end,
					},
					header1 = {
						order = 3,
						type = "description",
						name = "",
						width = 'full',
						image = function() return 'Interface\\AddOns\\ElvUI_EltreumUI\\Media\\Textures\\EltreumHeader', 3240, 1 end,
					},
					gap1 = {
						order = 4,
						type = "description",
						name = "",
						width = 'full',
					},
					description2 = {
						order = 4,
						type = "description",
						name = L["Add mouse over to the left chat panel"],
					},
					leftmouseover = {
						order = 5,
						type = 'toggle',
						name = L["Left Chat Mouse Over"],
						desc = L["Toggle the option"],
						width = 'full',
						disabled = function() return not E.db.ElvUI_EltreumUI.chat.enable end,
						get = function() return E.db.ElvUI_EltreumUI.chat.leftmouseover end,
						set = function(_, value) E.db.ElvUI_EltreumUI.chat.leftmouseover = value E:StaticPopup_Show('CONFIG_RL') end,
					},
					gap2 = {
						order = 6,
						type = "description",
						name = "",
						width = 'full',
						image = function() return 'Interface\\AddOns\\ElvUI_EltreumUI\\Media\\Textures\\EltreumHeader', 3240, 1 end,
					},
					description3 = {
						order = 6,
						type = "description",
						name = L["Add a fade to the left chat panel, controlled by ElvUI Chat > Text Fade > Inactivity Timer"],
					},
					leftfade = {
						order = 7,
						type = 'toggle',
						name = L["Left Inactivity Fader"],
						width = 'full',
						desc = L["Toggle the option"],
						disabled = function() return not E.db.ElvUI_EltreumUI.chat.enable end,
						get = function() return E.db.ElvUI_EltreumUI.chat.leftfader end,
						set = function(_, value) E.db.ElvUI_EltreumUI.chat.leftfader = value E:StaticPopup_Show('CONFIG_RL') end,
					},
					gap3 = {
						order = 8,
						type = "description",
						name = "",
						width = 'full',
						image = function() return 'Interface\\AddOns\\ElvUI_EltreumUI\\Media\\Textures\\EltreumHeader', 3240, 1 end,
					},
					description4 = {
						order = 8,
						type = "description",
						name = L["Add mouse over to the left chat panel"],
					},
					rightmouseover = {
						order = 9,
						type = 'toggle',
						name = L["Right Chat Mouse Over"],
						desc = L["Toggle the option"],
						width = 'full',
						disabled = function() return not E.db.ElvUI_EltreumUI.chat.enable end,
						get = function() return E.db.ElvUI_EltreumUI.chat.rightmouseover end,
						set = function(_, value) E.db.ElvUI_EltreumUI.chat.rightmouseover = value E:StaticPopup_Show('CONFIG_RL') end,
					},
					gap4 = {
						order = 10,
						type = "description",
						name = "",
						width = 'full',
						image = function() return 'Interface\\AddOns\\ElvUI_EltreumUI\\Media\\Textures\\EltreumHeader', 3240, 1 end,
					},
					description5 = {
						order = 10,
						type = "description",
						name = L["Add a fade to the right chat panel, controlled by ElvUI Chat > Text Fade > Inactivity Timer"],
					},
					rightfade = {
						order = 11,
						type = 'toggle',
						name = L["Right Inactivity Fader"],
						desc = L["Toggle the option"],
						width = 'full',
						disabled = function() return not E.db.ElvUI_EltreumUI.chat.enable end,
						get = function() return E.db.ElvUI_EltreumUI.chat.rightfader end,
						set = function(_, value) E.db.ElvUI_EltreumUI.chat.rightfader = value E:StaticPopup_Show('CONFIG_RL') end,
					},
					gap5 = {
						order = 12,
						type = "description",
						name = L["Combat Hide"],
						width = 'full',
						image = function() return 'Interface\\AddOns\\ElvUI_EltreumUI\\Media\\Textures\\EltreumHeader', 3240, 1 end,
					},
					leftcombathide = {
						order = 13,
						type = 'toggle',
						name = L["Hide Left Chat in Combat"],
						width = 'full',
						desc = L["Toggle the option"],
						disabled = function() return not E.db.ElvUI_EltreumUI.chat.enable end,
						get = function() return E.db.ElvUI_EltreumUI.chat.leftcombathide end,
						set = function(_, value) E.db.ElvUI_EltreumUI.chat.leftcombathide = value E:StaticPopup_Show('CONFIG_RL') end,
					},
					rightcombathide = {
						order = 14,
						type = 'toggle',
						name = L["Hide Right Chat in Combat"],
						width = 'full',
						desc = L["Toggle the option"],
						disabled = function() return not E.db.ElvUI_EltreumUI.chat.enable end,
						get = function() return E.db.ElvUI_EltreumUI.chat.rightcombathide end,
						set = function(_, value) E.db.ElvUI_EltreumUI.chat.rightcombathide = value E:StaticPopup_Show('CONFIG_RL') end,
					},
					gap6 = {
						order = 15,
						type = "description",
						name = L["Invert left mouse click so that chat starts faded and mouse click will make it stop fading"],
						width = 'full',
						image = function() return 'Interface\\AddOns\\ElvUI_EltreumUI\\Media\\Textures\\EltreumHeader', 3240, 1 end,
					},
					invertmouse = {
						order = 16,
						type = 'toggle',
						name = L["Invert Mouse Click"],
						width = 'full',
						desc = L["Toggle the option on"],
						disabled = function() return not E.db.ElvUI_EltreumUI.chat.enable end,
						get = function() return E.db.ElvUI_EltreumUI.chat.invertclick end,
						set = function(_, value) E.db.ElvUI_EltreumUI.chat.invertclick = value E:StaticPopup_Show('CONFIG_RL') end,
					},
					gap7 = {
						order = 17,
						type = "description",
						name = L["Add color to some chat messages"],
						width = 'full',
						image = function() return 'Interface\\AddOns\\ElvUI_EltreumUI\\Media\\Textures\\EltreumHeader', 3240, 1 end,
					},
					colorsysmsgs = {
						order = 18,
						type = 'toggle',
						name = L["Enable"],
						width = 'full',
						desc = L["Toggle the option on"],
						disabled = function() return not E.db.ElvUI_EltreumUI.chat.enable end,
						get = function() return E.db.ElvUI_EltreumUI.chat.colorsysmsg end,
						set = function(_, value) E.db.ElvUI_EltreumUI.chat.colorsysmsg = value end,
					},
					gap8 = {
						order = 19,
						type = "description",
						name = L["Enhance Item Links in Chat"],
						width = 'full',
						image = function() return 'Interface\\AddOns\\ElvUI_EltreumUI\\Media\\Textures\\EltreumHeader', 3240, 1 end,
					},
					chatlooticons = {
						order = 20,
						type = 'toggle',
						name = L["Enable Chat Icons"],
						width = 'full',
						desc = L["Toggle the option on"],
						disabled = function() return not E.db.ElvUI_EltreumUI.chat.enable end,
						get = function() return E.db.ElvUI_EltreumUI.chat.looticons end,
						set = function(_, value) E.db.ElvUI_EltreumUI.chat.looticons = value end,
					},
					chatitemlevels = {
						order = 21,
						type = 'toggle',
						name = L["Enable Item Levels"],
						width = 'full',
						desc = L["Toggle the option on"],
						disabled = function() return not E.db.ElvUI_EltreumUI.chat.enable or not E.db.ElvUI_EltreumUI.chat.looticons end,
						get = function() return E.db.ElvUI_EltreumUI.chat.itemlevels end,
						set = function(_, value) E.db.ElvUI_EltreumUI.chat.itemlevels = value end,
					},
					gap9 = {
						order = 22,
						type = "description",
						name = L["Customize the Chat tabs"],
						width = 'full',
						image = function() return 'Interface\\AddOns\\ElvUI_EltreumUI\\Media\\Textures\\EltreumHeader', 3240, 1 end,
					},
					darkchat = {
						order = 23,
						type = 'execute',
						name = L["Dark Chat"],
						--width = 'double',
						func = function() ElvUI_EltreumUI:DarkChat() E:StaticPopup_Show('CONFIG_RL') end,
					},
					lightchat = {
						order = 24,
						type = 'execute',
						name = L["Transparent Chat"],
						--width = 'double',
						func = function() ElvUI_EltreumUI:TransparentChat() E:StaticPopup_Show('CONFIG_RL') end,
					},
				},
			},
		},
	}
	return chat
end
