local ElvUI_EltreumUI, E, L, V, P, G = unpack(select(2, ...))

function ElvUI_EltreumUI:CursorOptions()
local cursor = {
	type = 'group',
	name = L["Cursor"],
	icon = 'Interface\\AddOns\\ElvUI_EltreumUI\\Media\\Icons\\cursor',
	order = 85,
	childGroups = "tab",
	args = {
		cursorgeneral = {
			order = 1,
			type = 'group',
			name= "General",
			args = {
				enable = {
					order = 1,
					type = 'toggle',
					name = L["Enable cursor rings for Casts, GCD and Combat"],
					desc = L["Add a rings around the mouse cursor for GCD, casts and combat"],
					width = 'full',
					get = function() return E.db.ElvUI_EltreumUI.cursor.enable end,
					set = function(_, value) E.db.ElvUI_EltreumUI.cursor.enable = value end,
				},
				enablecombat = {
					order = 2,
					type = 'toggle',
					name = L["Enable cursor only during combat"],
					desc = L["Cursor will only show during combat"],
					width = 'full',
					disabled = function() return not E.db.ElvUI_EltreumUI.cursor.enable end,
					get = function() return E.db.ElvUI_EltreumUI.cursor.combat end,
					set = function(_, value) E.db.ElvUI_EltreumUI.cursor.combat = value E:StaticPopup_Show('PRIVATE_RL') end,
				},
				enablecd = {
					order = 3,
					type = 'toggle',
					name = L["Enable cooldown tracking"],
					desc = L["Add a cooldown icon when trying to use skills that are on cooldown, and a cooldown flash when they are ready"],
					width = 'full',
					disabled = function() return not E.db.ElvUI_EltreumUI.cursor.enable end,
					get = function() return E.db.ElvUI_EltreumUI.cursor.cooldown end,
					set = function(_, value) E.db.ElvUI_EltreumUI.cursor.cooldown = value E:StaticPopup_Show('PRIVATE_RL') end,
				},
				enablepetcd = {
					order = 4,
					type = 'toggle',
					name = L["Enable pet cooldown tracking"],
					desc = L["Add a cooldown icon when trying to use skills that are on cooldown, and a cooldown flash when they are ready"],
					width = 'full',
					disabled = function() return not E.db.ElvUI_EltreumUI.cursor.enable end,
					get = function() return E.db.ElvUI_EltreumUI.cursor.petcooldown end,
					set = function(_, value) E.db.ElvUI_EltreumUI.cursor.petcooldown = value E:StaticPopup_Show('PRIVATE_RL') end,
				},
				fixlag = {
					order = 5,
					type = 'select',
					name = L["Attempt to fix Cursor Lag"],
					desc = L["Software cursor is how the cursor was before Battle for Azeroth, Hardware cursor is faster but will cause problems with addons that attach to it"],
					--width = 'full',
					values = {
						["0"] = L["Software Cursor"],
						["1"] = L["Hardware Cursor"],
					},
					style = 'radio',
					get = function() return C_CVar.GetCVar('HardwareCursor') end,
					set = function(_, value) E.db.ElvUI_EltreumUI.cursor.fixlag = value SetCVar('HardwareCursor', value) end,
				},
				header1 = {
					order = 20,
					type = "description",
					name= L["Change the size of the World of Warcraft Cursor"],
					width = 'full',
					image = function() return 'Interface\\AddOns\\ElvUI_EltreumUI\\Media\\Textures\\EltreumHeader', 3240, 1 end,
				},
				setsize = {
					order = 21,
					type = 'select',
					name = L["Select a size"],
					desc = L["Choose this size"],
					values = {
						["-1"] = L["Autodetect"],
						["0"] = '32x32',
						["1"] = '48x48',
						["2"] = '64x64',
						["3"] = '128x128',
					},
					style = 'radio',
					get = function() return E.db.ElvUI_EltreumUI.cursor.size end,
					set = function(_,value) ElvUI_EltreumUI:CursorSize(value) end,
				},
				header99 = {
					order = 97,
					type = "description",
					name= L["Cooldown Sound"],
					width = 'full',
					image = function() return 'Interface\\AddOns\\ElvUI_EltreumUI\\Media\\Textures\\EltreumHeader', 3240, 1 end,
				},
				enablecdsound = {
					order = 98,
					type = 'toggle',
					name = L["Play a Sound when attempting to use a skill that is on cooldown."],
					width = 'full',
					disabled = function() return not E.db.ElvUI_EltreumUI.cursor.cooldown end,
					get = function() return E.db.ElvUI_EltreumUI.cursor.cooldownsound end,
					set = function(_, value) E.db.ElvUI_EltreumUI.cursor.cooldownsound = value E:StaticPopup_Show('PRIVATE_RL') end,
				},
				cdsound = {
					order = 99,
					type = 'select',
					width = "double",
					dialogControl = 'LSM30_Sound',
					name = L["Select a Sound"],
					desc = L["Choose a Sound from SharedMedia files"],
					values = AceGUIWidgetLSMlists.sound,
					get = function() return E.db.ElvUI_EltreumUI.cursor.cooldownfile end,
					disabled = function() return not E.db.ElvUI_EltreumUI.cursor.cooldownsound or not E.db.ElvUI_EltreumUI.cursor.cooldown end,
					set = function(self,key) E.db.ElvUI_EltreumUI.cursor.cooldownfile = key E:StaticPopup_Show('CONFIG_RL') end,
				},
			},
		},
		cursorcolors = {
			order = 6,
			type = 'group',
			name = L["Cursor Colors"],
			args = {
				nicegap17 = {
					order = 11,
					type = "description",
					name = L["Cursor Colors "]..'|cffff0000('..L["Requires a Reload"]..")|r",
					width = 'full',
				},
				header12 = {
					order = 11,
					type = "description",
					name = "",
					width = 'full',
					image = function() return 'Interface\\AddOns\\ElvUI_EltreumUI\\Media\\Textures\\EltreumHeader', 3240, 1 end,
				},
				castclasscolor = {
					type = 'toggle',
					name = L["Class Colored Casts"],
					order = 12,
					desc = L["Use Class Colors for Cast"],
					disabled = function() return not E.db.ElvUI_EltreumUI.cursor.enable end,
					get = function() return E.db.ElvUI_EltreumUI.cursorcast.classcolor end,
					set = function(_, value) E.db.ElvUI_EltreumUI.cursorcast.classcolor = value E:StaticPopup_Show('CONFIG_RL') end,
				},
				colorcast = {
					order = 13,
					type = 'color',
					name = L["Custom Color Cast"],
					hasAlpha = false,
					disabled = function() return not E.db.ElvUI_EltreumUI.cursor.enable end,
					disabled = function() return E.db.ElvUI_EltreumUI.cursorcast.classcolor end,
					get = function()
						local cursorcast = E.db.ElvUI_EltreumUI.cursorcast
						local d = P.ElvUI_EltreumUI.cursorcast
						return cursorcast.r, cursorcast.g, cursorcast.b, cursorcast.a, d.r, d.g, d.b, d.a
					end,
					set = function(_, r, g, b, a)
						local cursorcast = E.db.ElvUI_EltreumUI.cursorcast
						cursorcast.r, cursorcast.g, cursorcast.b = r, g, b
					end,
				},
				nicegap1 = {
					order = 14,
					type = "description",
					name = "",
					width = 'full',
				},
				gcdclasscolor = {
					type = 'toggle',
					name = L["Class Colored GCD"],
					order = 14,
					desc = L["Use Class Colors for GCD"],
					disabled = function() return not E.db.ElvUI_EltreumUI.cursor.enable end,
					get = function() return E.db.ElvUI_EltreumUI.cursorgcd.classcolor end,
					set = function(_, value) E.db.ElvUI_EltreumUI.cursorgcd.classcolor = value E:StaticPopup_Show('CONFIG_RL') end,
				},
				colorgcd = {
					order = 15,
					type = 'color',
					name = L["Custom Color GCD"],
					hasAlpha = false,
					disabled = function() return E.db.ElvUI_EltreumUI.cursorgcd.classcolor or (not E.db.ElvUI_EltreumUI.cursor.enable ) end,
					get = function()
						local cursorgcd = E.db.ElvUI_EltreumUI.cursorgcd
						local d = P.ElvUI_EltreumUI.cursorgcd
						return cursorgcd.r, cursorgcd.g, cursorgcd.b, cursorgcd.a, d.r, d.g, d.b, d.a
					end,
					set = function(_, r, g, b, a)
						local cursorgcd = E.db.ElvUI_EltreumUI.cursorgcd
						cursorgcd.r, cursorgcd.g, cursorgcd.b = r, g, b
					end,
				},
				nicegap2 = {
					order = 16,
					type = "description",
					name = "",
					width = 'full',
				},
				cursorcursorclasscolor = {
					type = 'toggle',
					name = L["Class Colored Combat"],
					order = 16,
					desc = L["Use Class Colors for Cursor"],
					disabled = function() return not E.db.ElvUI_EltreumUI.cursor.enable end,
					get = function() return E.db.ElvUI_EltreumUI.cursorcursor.classcolor end,
					set = function(_, value) E.db.ElvUI_EltreumUI.cursorcursor.classcolor = value E:StaticPopup_Show('CONFIG_RL') end,
				},
				cursorcursorcolor = {
					order = 17,
					type = 'color',
					name = L["Custom Color Combat"],
					hasAlpha = false,
					disabled = function() return E.db.ElvUI_EltreumUI.cursorcursor.classcolor or (not E.db.ElvUI_EltreumUI.cursor.enable) end,
					get = function()
						local cursorcursor = E.db.ElvUI_EltreumUI.cursorcursor
						local d = P.ElvUI_EltreumUI.cursorcursor
						return cursorcursor.r, cursorcursor.g, cursorcursor.b, cursorcursor.a, d.r, d.g, d.b, d.a
					end,
					set = function(_, r, g, b, a)
						local cursorcursor = E.db.ElvUI_EltreumUI.cursorcursor
						cursorcursor.r, cursorcursor.g, cursorcursor.b = r, g, b
					end,
				},
			},
		},
		cursortype = {
			order = 7,
			type = 'group',
			name = L["Cursor Type"],
			args = {
				topbar = {
					order = 0,
					type = "description",
					name = L["Choose a type of cursor by clicking it"],
					width = 'full',
					image = function() return 'Interface\\AddOns\\ElvUI_EltreumUI\\Media\\Textures\\EltreumHeader', 3240, 1 end,
				},
				gap = {
					order = 1,
					type = "description",
					name = "",
					width = 'full',
				},
				gap2 = {
					order = 2,
					type = "description",
					name = "",
					width = 'full',
				},
				gap3 = {
					order = 3,
					type = "description",
					name = "",
					width = 'full',
				},
				currentring = {
					order = 5,
					type = 'description',
					name = function() return L["Currently selected cursor: "]..ElvUI_EltreumUI:CurrentTypeofCursor() end,
					desc = L["Choose a type of cursor by clicking it"],
				},
				showring1 = {
					order = 90,
					type = "execute",
					image = 'Interface\\AddOns\\ElvUI_EltreumUI\\Media\\Textures\\Cursor\\ring1',
					name = L["Type 1"],
					desc = L["The Cursor will use this type as its texture"],
					func = function() E.db.ElvUI_EltreumUI.cursor.ring = 'Interface\\AddOns\\ElvUI_EltreumUI\\Media\\Textures\\Cursor\\ring1.tga' E:StaticPopup_Show('CONFIG_RL') end,
				},
				showring2 = {
					order = 91,
					type = "execute",
					image = 'Interface\\AddOns\\ElvUI_EltreumUI\\Media\\Textures\\Cursor\\ring2',
					name = L["Type 2"],
					desc = 'The Cursor will use this type as its texture',
					confirm = true,
					func = function() E.db.ElvUI_EltreumUI.cursor.ring = 'Interface\\AddOns\\ElvUI_EltreumUI\\Media\\Textures\\Cursor\\ring2.tga' E:StaticPopup_Show('CONFIG_RL') end,
				},
				showring3 = {
					order = 92,
					type = "execute",
					image = 'Interface\\AddOns\\ElvUI_EltreumUI\\Media\\Textures\\Cursor\\ring3',
					name = L["Type 3"],
					desc = L["The Cursor will use this type as its texture"],
					confirm = true,
					func = function() E.db.ElvUI_EltreumUI.cursor.ring = 'Interface\\AddOns\\ElvUI_EltreumUI\\Media\\Textures\\Cursor\\ring3.tga' E:StaticPopup_Show('CONFIG_RL') end,
				},
				showring4 = {
					order = 93,
					type = "execute",
					image = 'Interface\\AddOns\\ElvUI_EltreumUI\\Media\\Textures\\Cursor\\ring4',
					name = L["Type 4"],
					desc = L["The Cursor will use this type as its texture"],
					confirm = true,
					func = function() E.db.ElvUI_EltreumUI.cursor.ring = 'Interface\\AddOns\\ElvUI_EltreumUI\\Media\\Textures\\Cursor\\ring4.tga' E:StaticPopup_Show('CONFIG_RL') end,
				},
				showring5 = {
					order = 94,
					type = "execute",
					image = 'Interface\\AddOns\\ElvUI_EltreumUI\\Media\\Textures\\Cursor\\ring5',
					name = L["Type 5"],
					desc = L["The Cursor will use this type as its texture"],
					confirm = true,
					func = function() E.db.ElvUI_EltreumUI.cursor.ring = 'Interface\\AddOns\\ElvUI_EltreumUI\\Media\\Textures\\Cursor\\ring5.tga' E:StaticPopup_Show('CONFIG_RL') end,
				},
				showring6 = {
					order = 95,
					type = "execute",
					image = 'Interface\\AddOns\\ElvUI_EltreumUI\\Media\\Textures\\Cursor\\ring6',
					name = L["Type 6"],
					desc = L["The Cursor will use this type as its texture"],
					confirm = true,
					func = function() E.db.ElvUI_EltreumUI.cursor.ring = 'Interface\\AddOns\\ElvUI_EltreumUI\\Media\\Textures\\Cursor\\ring6.tga' E:StaticPopup_Show('CONFIG_RL') end,
				},
				showring7 = {
					order = 96,
					type = "execute",
					image = 'Interface\\AddOns\\ElvUI_EltreumUI\\Media\\Textures\\Cursor\\ring7',
					name = L["Type 7"],
					desc = L["The Cursor will use this type as its texture"],
					confirm = true,
					func = function() E.db.ElvUI_EltreumUI.cursor.ring = 'Interface\\AddOns\\ElvUI_EltreumUI\\Media\\Textures\\Cursor\\ring7.tga' E:StaticPopup_Show('CONFIG_RL') end,
				},
				showring8 = {
					order = 97,
					type = "execute",
					image = 'Interface\\AddOns\\ElvUI_EltreumUI\\Media\\Textures\\Cursor\\ring8',
					name = L["Type 8"],
					desc = L["The Cursor will use this type as its texture"],
					confirm = true,
					func = function() E.db.ElvUI_EltreumUI.cursor.ring = 'Interface\\AddOns\\ElvUI_EltreumUI\\Media\\Textures\\Cursor\\ring8.tga' E:StaticPopup_Show('CONFIG_RL') end,
				},
				showring9 = {
					order = 98,
					type = "execute",
					image = 'Interface\\AddOns\\ElvUI_EltreumUI\\Media\\Textures\\Cursor\\ring9',
					name = L["Type 9"],
					desc = L["The Cursor will use this type as its texture"],
					confirm = true,
					func = function() E.db.ElvUI_EltreumUI.cursor.ring = 'Interface\\AddOns\\ElvUI_EltreumUI\\Media\\Textures\\Cursor\\ring9.tga' E:StaticPopup_Show('CONFIG_RL') end,
				},
				showring10 = {
					order = 99,
					type = "execute",
					image = 'Interface\\AddOns\\ElvUI_EltreumUI\\Media\\Textures\\Cursor\\ring10',
					name = L["Type 10"],
					desc = L["The Cursor will use this type as its texture"],
					confirm = true,
					func = function() E.db.ElvUI_EltreumUI.cursor.ring = 'Interface\\AddOns\\ElvUI_EltreumUI\\Media\\Textures\\Cursor\\ring10.tga' E:StaticPopup_Show('CONFIG_RL') end,
				},
			},
		},
		cursorsize = {
			order = 3,
			type = 'group',
			name = L["Cursor Sizes"],
			args = {
				header1 = {
					order = 18,
					type = "description",
					name = "",
					width = 'full',
					image = function() return 'Interface\\AddOns\\ElvUI_EltreumUI\\Media\\Textures\\EltreumHeader', 3240, 1 end,
				},
				nicegap3 = {
					order = 18,
					type = "description",
					name = L["Cursor Sizes "]..'|cffff0000('..L["Requires a Reload"]..")|r",
					width = 'full',
				},
				castradius = {
					type = 'range',
					name = L["Cast Radius (Default: 25)"],
					desc = L["Set the radius of the cast cursor"],
					order = 19,
					min = 10,
					max = 50,
					step = 1,
					width = "full",
					get = function() return E.db.ElvUI_EltreumUI.cursorcast.radius end,
					set = function(_, value) E.db.ElvUI_EltreumUI.cursorcast.radius = value end,
				},
				castthickness = {
					type = 'range',
					name = L["Cast Thickness (Default: 5)"],
					desc = L["Set the radius of the cast cursor"],
					order = 19,
					min = 1,
					max = 10,
					step = 1,
					width = "full",
					get = function() return E.db.ElvUI_EltreumUI.cursorcast.thickness end,
					set = function(_, value) E.db.ElvUI_EltreumUI.cursorcast.thickness = value end,
				},
				gcdradius = {
					type = 'range',
					name = L["GCD Radius (Default: 20)"],
					desc = L["Set the radius of the gcd cursor"],
					order = 19,
					min = 10,
					max = 50,
					step = 1,
					width = "full",
					get = function() return E.db.ElvUI_EltreumUI.cursorgcd.radius end,
					set = function(_, value) E.db.ElvUI_EltreumUI.cursorgcd.radius = value end,
				},
				gcdthickness = {
					type = 'range',
					name = L["GCD Thickness (Default: 5)"],
					desc = L["Set the thickness of the gcd cursor"],
					order = 19,
					min = 1,
					max = 10,
					step = 1,
					width = "full",
					get = function() return E.db.ElvUI_EltreumUI.cursorgcd.thickness end,
					set = function(_, value) E.db.ElvUI_EltreumUI.cursorgcd.thickness = value end,
				},
				cursorcursorradius = {
					type = 'range',
					name = L["Combat Cursor Radius (Default: 15)"],
					desc = L["Set the radius of the combat cursor"],
					order = 19,
					min = 10,
					max = 50,
					step = 1,
					width = "full",
					get = function() return E.db.ElvUI_EltreumUI.cursorcursor.radius end,
					set = function(_, value) E.db.ElvUI_EltreumUI.cursorcursor.radius = value end,
				},
				cursorcursorthickness = {
					type = 'range',
					name = L["Combat Cursor Thickness (Default: 5)"],
					desc = L["Set the thickness of the combat cursor"],
					order = 19,
					min = 1,
					max = 10,
					step = 1,
					width = "full",
					get = function() return E.db.ElvUI_EltreumUI.cursorcursor.thickness end,
					set = function(_, value) E.db.ElvUI_EltreumUI.cursorcursor.thickness = value end,
				},
			},
		},
	},
}
return cursor
end
