local ElvUI_EltreumUI, E, L, V, P, G = unpack(select(2, ...))

function ElvUI_EltreumUI:MiscOptions()
	local misc = {
		type = 'group',
		name = L["Misc"],
		icon = 'Interface\\AddOns\\ElvUI_EltreumUI\\Media\\Icons\\misc',
		order = 85,
		args = {
			header0 = {
				order = 1,
				type = "description",
				name = L["Show Eltruism Game Menu Button"],
				width = 'full',
				image = function() return 'Interface\\AddOns\\ElvUI_EltreumUI\\Media\\Textures\\EltreumHeader', 3240, 1 end,
			},
			gamemenu = {
				type = 'toggle',
				name = L["Enable"],
				order = 2,
				get = function() return E.db.ElvUI_EltreumUI.otherstuff.gamemenu end,
				set = function(_, value) E.db.ElvUI_EltreumUI.otherstuff.gamemenu = value E:StaticPopup_Show('CONFIG_RL') end,
			},
			header1 = {
				order = 3,
				type = "description",
				name = L["Show Buffs in Arena and hide them outside (will overwrite Eltruism default settings)"],
				width = 'full',
				image = function() return 'Interface\\AddOns\\ElvUI_EltreumUI\\Media\\Textures\\EltreumHeader', 3240, 1 end,
			},
			arenabuffs = {
				type = 'toggle',
				name = L["Enable"],
				order = 4,
				get = function() return E.db.ElvUI_EltreumUI.otherstuff.arenabuffs end,
				set = function(_, value) E.db.ElvUI_EltreumUI.otherstuff.arenabuffs = value E:StaticPopup_Show('CONFIG_RL') end,
			},
			header2 = {
				order = 5,
				type = "description",
				name = L["Hide Arena Frames in Arena due to Gladius/Gladdy or another addon"],
				width = 'full',
				image = function() return 'Interface\\AddOns\\ElvUI_EltreumUI\\Media\\Textures\\EltreumHeader', 3240, 1 end,
			},
			arenaUF = {
				type = 'toggle',
				name = L["Enable"],
				order = 6,
				get = function() return E.db.ElvUI_EltreumUI.otherstuff.arenaunitframes end,
				set = function(_, value) E.db.ElvUI_EltreumUI.otherstuff.arenaunitframes = value E:StaticPopup_Show('CONFIG_RL') end,
			},
			header3 = {
				order = 7,
				type = "description",
				name = L["Hide Raid Unitframes in battlegrounds due to addons like Battleground Enemies"],
				width = 'full',
				image = function() return 'Interface\\AddOns\\ElvUI_EltreumUI\\Media\\Textures\\EltreumHeader', 3240, 1 end,
			},
			bgUF = {
				type = 'toggle',
				name = L["Enable"],
				order = 8,
				get = function() return E.db.ElvUI_EltreumUI.otherstuff.bgunitframes end,
				set = function(_, value) E.db.ElvUI_EltreumUI.otherstuff.bgunitframes = value E:StaticPopup_Show('CONFIG_RL') end,
			},
			header122 = {
				order = 10,
				type = "description",
				name = "",
				width = 'full',
				image = function() return 'Interface\\AddOns\\ElvUI_EltreumUI\\Media\\Textures\\EltreumHeader', 3240, 1 end,
			},
			xpdatabar = {
				order = 11,
				type = "toggle",
				name = L["Dynamically toggle the mouseover of the Experience Bar"],
				desc = L["Shows XP bar when below max level, makes it mouseover when max level"],
				width = 'full',
				get = function() return E.db.ElvUI_EltreumUI.otherstuff.dynamicxpbar end,
				set = function(_, value) E.db.ElvUI_EltreumUI.otherstuff.dynamicxpbar = value E:StaticPopup_Show('CONFIG_RL') end,
			},
			headerdarksouls = {
				order = 24,
				type = "description",
				name = "",
				width = 'full',
				image = function() return 'Interface\\AddOns\\ElvUI_EltreumUI\\Media\\Textures\\EltreumHeader', 3240, 1 end,
			},
			darksouls = {
				order = 25,
				type = "toggle",
				name = L["Enable a Dark Souls death animation"],
				desc = L["Plays an animation when you die"],
				width = 'full',
				disabled = function() return E.db.ElvUI_EltreumUI.otherstuff.playerdeathgta or E.db.ElvUI_EltreumUI.otherstuff.playerdeathcustom end,
				get = function() return E.db.ElvUI_EltreumUI.otherstuff.playerdeath end,
				set = function(_, value) E.db.ElvUI_EltreumUI.otherstuff.playerdeath = value end,
			},
			gta = {
				order = 26,
				type = "toggle",
				name = L["Enable a GTA death animation"],
				desc = L["Plays an animation when you die"],
				width = 'full',
				disabled = function() return E.db.ElvUI_EltreumUI.otherstuff.playerdeath or E.db.ElvUI_EltreumUI.otherstuff.playerdeathcustom end,
				get = function() return E.db.ElvUI_EltreumUI.otherstuff.playerdeathgta end,
				set = function(_, value) E.db.ElvUI_EltreumUI.otherstuff.playerdeathgta = value end,
			},
			customdeath = {
				order = 27,
				type = "toggle",
				name = L["Enable a Custom death animation"],
				desc = L["Plays an animation when you die"],
				width = 'full',
				disabled = function() return E.db.ElvUI_EltreumUI.otherstuff.playerdeathgta or E.db.ElvUI_EltreumUI.otherstuff.playerdeath end,
				get = function() return E.db.ElvUI_EltreumUI.otherstuff.playerdeathcustom end,
				set = function(_, value) E.db.ElvUI_EltreumUI.otherstuff.playerdeathcustom = value end,
			},
			customdeathtext = {
				order = 28,
				type = 'input',
				name = L["Custom Death Text"],
				desc = L["The text displayed when you die using the custom text option"],
				--width = 'double',
				disabled = function() return E.db.ElvUI_EltreumUI.otherstuff.playerdeathgta or E.db.ElvUI_EltreumUI.otherstuff.playerdeath or (not E.db.ElvUI_EltreumUI.otherstuff.playerdeathcustom) end,
				get = function() return E.db.ElvUI_EltreumUI.otherstuff.playerdeathcustomtext end,
				set = function(_, value) E.db.ElvUI_EltreumUI.otherstuff.playerdeathcustomtext = tostring(value) E:StaticPopup_Show('PRIVATE_RL') end,
			},
			header8 = {
				order = 29,
				type = "description",
				name = "",
				width = 'full',
				image = function() return 'Interface\\AddOns\\ElvUI_EltreumUI\\Media\\Textures\\EltreumHeader', 3240, 1 end,
			},
			combatextindicator = {
				order = 30,
				type = "toggle",
				name = L["Enable Entering/Leaving Combat Indicator Texts"],
				desc = L["Adds a +Combat and -Combat for when entering and leaving combat"],
				width = 'full',
				get = function() return E.db.ElvUI_EltreumUI.loottext.combatindicator end,
				set = function(_, value) E.db.ElvUI_EltreumUI.loottext.combatindicator = value E:StaticPopup_Show('CONFIG_RL') end,
			},
			header9987 = {
				order = 33,
				type = "description",
				name = "",
				width = 'full',
				image = function() return 'Interface\\AddOns\\ElvUI_EltreumUI\\Media\\Textures\\EltreumHeader', 3240, 1 end,
			},
			rollsound = {
				order = 34,
				type = "toggle",
				name = L["Add Sounds to /roll when someone gets a 1 or a 100"],
				desc = L["Plays a sound if someone rolls 1 or 100 out 100"],
				width = 'full',
				get = function() return E.db.ElvUI_EltreumUI.chat.rollsound end,
				set = function(_, value) E.db.ElvUI_EltreumUI.chat.rollsound = value PlaySoundFile("Interface\\AddOns\\ElvUI_EltreumUI\\Media\\sound\\WillSmith-Ahaha.ogg", "Master") E:StaticPopup_Show('CONFIG_RL') end,
			},
			header9 = {
				order = 35,
				type = "description",
				name = "",
				width = 'full',
				image = function() return 'Interface\\AddOns\\ElvUI_EltreumUI\\Media\\Textures\\EltreumHeader', 3240, 1 end,
			},
			worldtext = {
				order = 36,
				type = "description",
				name = L["Change the Scale of the World Text"],
				desc = L["Such as the floating XP, floating reputation changes and others"],
				width = 'full',
			},
			worldtextscale = {
				type = 'range',
				name = L["Select the size of the World Text"],
				order = 37,
				min = 0.2,
				max = 5,
				step = 0.1,
				width = "full",
				get = function() return E.db.ElvUI_EltreumUI.otherstuff.worldtextscale end,
				set = function(_, value) E.db.ElvUI_EltreumUI.otherstuff.worldtextscale = value ElvUI_EltreumUI:WorldTextScale(value) end,
			},
			header15 = {
				order = 47,
				type = "description",
				name = "",
				width = 'full',
				image = function() return 'Interface\\AddOns\\ElvUI_EltreumUI\\Media\\Textures\\EltreumHeader', 3240, 1 end,
			},
			autossdesc = {
				order = 48,
				type = "description",
				name = L["Automatically take Screenshots"],
				desc = L["Automatically take Screenshots"],
				width = 'full',
			},
			autossenable = {
				order = 49,
				name = L["Enable"],
				type = "toggle",
				desc = L["Automatically take Screenshots such as when leveling up"],
				width = 'full',
				get = function() return E.db.ElvUI_EltreumUI.otherstuff.screenshot end,
				set = function(_, value) E.db.ElvUI_EltreumUI.otherstuff.screenshot = value E:StaticPopup_Show('CONFIG_RL') end,
			},
			header16 = {
				order = 50,
				type = "description",
				name = "",
				width = 'full',
				image = function() return 'Interface\\AddOns\\ElvUI_EltreumUI\\Media\\Textures\\EltreumHeader', 3240, 1 end,
			},
			blizzcombattextdesc = {
				order = 51,
				type = "description",
				name = L["Blizzard Floating Combat Text"],
				desc = L["Enable or disable Blizzard's default Floating Combat Text"],
				width = 'full',
			},
			blizzcombatexttoggle = {
				order = 52,
				name = L["Disable Combat Text"],
				type = "toggle",
				desc = L["Enable or disable Blizzard's default Floating Combat Text"],
				width = 'full',
				get = function() return E.db.ElvUI_EltreumUI.otherstuff.blizzcombattext end,
				set = function(_, value) E.db.ElvUI_EltreumUI.otherstuff.blizzcombattext = value E:StaticPopup_Show('CONFIG_RL') end,
			},
			blizzcombatextmana = {
				order = 53,
				name = L["Enable Resource Gains"],
				type = "toggle",
				desc = L["Enable or disable Blizzard's default Floating Combat Text for Mana/Rage/Energy and other resouces"],
				width = 'full',
				get = function() return E.db.ElvUI_EltreumUI.otherstuff.blizzcombatmana end,
				set = function(_, value) E.db.ElvUI_EltreumUI.otherstuff.blizzcombatmana = value E:StaticPopup_Show('CONFIG_RL') end,
			},
			header197876 = {
				order = 54,
				type = "description",
				name = L["Stealth"],
				width = 'full',
				image = function() return 'Interface\\AddOns\\ElvUI_EltreumUI\\Media\\Textures\\EltreumHeader', 3240, 1 end,
			},
			stealthframeoptions = {
				order = 55,
				type = 'toggle',
				name = L["Add a vignette effect while in stealth"],
				width = 'full',
				desc = L["Turn the effect on"],
				get = function() return E.db.ElvUI_EltreumUI.stealthOptions.stealtheffect end,
				set = function(_, value) E.db.ElvUI_EltreumUI.stealthOptions.stealtheffect = value end,
			},
			headerdelete = {
				order = 56,
				type = "description",
				name = L["Item Deletion"],
				width = 'full',
				image = function() return 'Interface\\AddOns\\ElvUI_EltreumUI\\Media\\Textures\\EltreumHeader', 3240, 1 end,
			},
			autotypedelete = {
				order = 57,
				type = 'toggle',
				name = L["Automatically type DELETE on the popup"],
				width = 'full',
				desc = L["Will not delete the item, will simply type DELETE instead you needing to type it"],
				get = function() return E.db.ElvUI_EltreumUI.otherstuff.delete end,
				set = function(_, value) E.db.ElvUI_EltreumUI.otherstuff.delete = value E:StaticPopup_Show('CONFIG_RL') end,
			},
			headermailsound = {
				order = 58,
				type = "description",
				name = L["Play a Sound when receiving mail"],
				width = 'full',
				image = function() return 'Interface\\AddOns\\ElvUI_EltreumUI\\Media\\Textures\\EltreumHeader', 3240, 1 end,
			},
			enablesoundmail = {
				type = 'toggle',
				name = L["Enable"],
				width = "full",
				order = 59,
				get = function() return E.db.ElvUI_EltreumUI.otherstuff.mailsoundenable end,
				set = function(_, value) E.db.ElvUI_EltreumUI.otherstuff.mailsoundenable = value end,
			},
			sharedmediasoundmail = {
				order = 60,
				type = 'select',
				width = "double",
				dialogControl = 'LSM30_Sound',
				name = L["Select a Sound"],
				desc = L["Choose a Sound from SharedMedia files"],
				values = AceGUIWidgetLSMlists.sound,
				get = function() return E.db.ElvUI_EltreumUI.otherstuff.mailsound end,
				disabled = function() return not E.db.ElvUI_EltreumUI.otherstuff.mailsoundenable end,
				set = function(self,key) E.db.ElvUI_EltreumUI.otherstuff.mailsound = key E:StaticPopup_Show('CONFIG_RL') end,
			},
			header578 = {
				order = 61,
				type = "description",
				name = "",
				width = 'full',
				image = function() return 'Interface\\AddOns\\ElvUI_EltreumUI\\Media\\Textures\\EltreumHeader', 3240, 1 end,
			},
			apswap = {
				order = 62,
				type = 'execute',
				name = L["Swap Action Paging and visibility for Bar1 and Bar4"],
				--desc = "",
				width = 'full',
				confirm = true,
				func = function() ElvUI_EltreumUI:ActionPagingSwap() E:StaticPopup_Show('CONFIG_RL') end,
			},
		},
	}
	return misc
end
