local ElvUI_EltreumUI, E, L, V, P, G = unpack(select(2, ...))

function ElvUI_EltreumUI:PartyOptions()
	local partyraidsettings = {
		type = 'group',
		name = L["Party/Raid"],
		icon = 'Interface\\AddOns\\ElvUI_EltreumUI\\Media\\Icons\\party',
		order = 85,
		args = {
			headergap1 = {
				order = 1,
				type = "description",
				name = L["Play a sound when someone dies in Party or Raid"],
				width = 'full',
				image = function() return 'Interface\\AddOns\\ElvUI_EltreumUI\\Media\\Textures\\EltreumHeader', 3240, 1 end,
			},
			enablesound = {
				type = 'toggle',
				name = L["Enable"],
				width = "full",
				order = 6,
				get = function() return E.db.ElvUI_EltreumUI.partyraiddeath.enable end,
				set = function(_, value) E.db.ElvUI_EltreumUI.partyraiddeath.enable = value end,
			},
			disablebgs = {
				type = 'toggle',
				name = L["Disable in Battlegrounds/Arenas"],
				width = "full",
				order = 7,
				disabled = function() return not E.db.ElvUI_EltreumUI.partyraiddeath.enable end,
				get = function() return E.db.ElvUI_EltreumUI.partyraiddeath.bgdisable end,
				set = function(_, value) E.db.ElvUI_EltreumUI.partyraiddeath.bgdisable = value end,
			},
			sharedmediasound = {
				order = 8,
				type = 'select',
				width = "double",
				dialogControl = 'LSM30_Sound',
				name = L["Select a Sound"],
				desc = L["Choose a Sound from SharedMedia files"],
				values = AceGUIWidgetLSMlists.sound,
				get = function() return E.db.ElvUI_EltreumUI.partyraiddeath.playerdeathsound end,
				disabled = function() return not E.db.ElvUI_EltreumUI.partyraiddeath.enable end,
				set = function(self,key) E.db.ElvUI_EltreumUI.partyraiddeath.playerdeathsound = key E:StaticPopup_Show('CONFIG_RL') end,
			},
			layoutdescriptiongap2 = {
				order = 13,
				type = 'description',
				name = "",
				width = "full",
			},
			headergapisntances = {
				order = 13,
				type = "description",
				name = L["Instance Texts"],
				width = 'full',
				image = function() return 'Interface\\AddOns\\ElvUI_EltreumUI\\Media\\Textures\\EltreumHeader', 3240, 1 end,
			},
			instancetextenable = {
				type = 'toggle',
				name = L["Enable"],
				width = "full",
				order = 14,
				get = function() return E.db.ElvUI_EltreumUI.instances.enable end,
				set = function(_, value) E.db.ElvUI_EltreumUI.instances.enable = value end,
			},
			instancecolor = {
				order = 15,
				type = 'color',
				name = L["Instance Text Color"],
				hasAlpha = false,
				width = "full",
				disabled = function() return (not E.db.ElvUI_EltreumUI.instances.enable) end,
				get = function() return E.db.ElvUI_EltreumUI.instances.r, E.db.ElvUI_EltreumUI.instances.g, E.db.ElvUI_EltreumUI.instances.b, 1, P.ElvUI_EltreumUI.instances.r, P.ElvUI_EltreumUI.instances.g, P.ElvUI_EltreumUI.instances.b, 1 end,
				set = function(_, r, g, b, a) E.db.ElvUI_EltreumUI.instances.r, E.db.ElvUI_EltreumUI.instances.g, E.db.ElvUI_EltreumUI.instances.b = r, g, b end,
			},
			instancefontsize = {
				type = 'range',
				name = L["Font Size"],
				desc = L["Instance text Font Size"],
				order = 16,
				min = 4,
				max = 72,
				step = 1,
				width = "double",
				disabled = function() return (not E.db.ElvUI_EltreumUI.instances.enable) end,
				get = function() return E.db.ElvUI_EltreumUI.instances.fontsize end,
				set = function(_, value) E.db.ElvUI_EltreumUI.instances.fontsize = tonumber(value) end,
			},
			headergapisntance2 = {
				order = 17,
				type = "description",
				name = "",
				width = 'full',
				image = function() return 'Interface\\AddOns\\ElvUI_EltreumUI\\Media\\Textures\\EltreumHeader', 3240, 1 end,
			},
			DungeonNormal = {
				order = 80,
				type = 'input',
				name = L["Dungeon"],
				desc = L["The text displayed when in a normal dungeon"],
				--width = 'double',
				disabled = function() return (not E.db.ElvUI_EltreumUI.instances.enable) end,
				get = function() return E.db.ElvUI_EltreumUI.instances.DungeonNormal end,
				set = function(_, value) E.db.ElvUI_EltreumUI.instances.DungeonNormal = tostring(value) E:StaticPopup_Show('PRIVATE_RL') end,
			},
			DungeonHeroic = {
				order = 80,
				type = 'input',
				name = L["Dungeon (Heroic)"],
				desc = L["The text displayed when in a heroic dungeon"],
				--width = 'double',
				disabled = function() return (not E.db.ElvUI_EltreumUI.instances.enable) end,
				get = function() return E.db.ElvUI_EltreumUI.instances.DungeonHeroic end,
				set = function(_, value) E.db.ElvUI_EltreumUI.instances.DungeonHeroic = tostring(value) E:StaticPopup_Show('PRIVATE_RL') end,
			},
			Raid = {
				order = 80,
				type = 'input',
				name = L["Raid (Normal)"],
				desc = L["The text displayed when in a normal raid"],
				--width = 'double',
				disabled = function() return (not E.db.ElvUI_EltreumUI.instances.enable) end,
				get = function() return E.db.ElvUI_EltreumUI.instances.Raid end,
				set = function(_, value) E.db.ElvUI_EltreumUI.instances.Raid = tostring(value) E:StaticPopup_Show('PRIVATE_RL') end,
			},
		},
	}
	return partyraidsettings
end
