local ElvUI_EltreumUI, E, L, V, P, G = unpack(select(2, ...))

function ElvUI_EltreumUI:ProfileOptions()
	local profiles = {
		type = 'group',
		name = L["Addons"],
		icon = 'Interface\\AddOns\\ElvUI_EltreumUI\\Media\\Icons\\addon',
		order = 85,
		childGroups = "tab",
		args = {
			elvui = {
				type = 'group',
				name = L["ElvUI Plugins"],
				order = 1,
				args = {
					header1 = {
						order = 1,
						type = "description",
						name = "Azilroka Addons",
						width = 'full',
						image = function() return 'Interface\\AddOns\\ElvUI_EltreumUI\\Media\\Textures\\EltreumHeader', 3240, 1 end,
					},
					addonskins = {
						order = 2,
						type = 'execute',
						name = '|cff16C3F2AddOn|r|cFFFFFFFFSkins|r',
						desc = L["Reset to Eltruism defaults."],
						confirm = true,
						width = 'double',
						func = function() ElvUI_EltreumUI:AddonSetupAS() E:StaticPopup_Show('CONFIG_RL') end,
					},
					projectazilroka = {
						order = 3,
						type = 'execute',
						name = '|cFF16C3F2Project|r|cFFFFFFFFAzilroka|r',
						desc = L["Reset to Eltruism defaults."],
						confirm = true,
						width = 'double',
						func = function() ElvUI_EltreumUI:AddonSetupPA() E:StaticPopup_Show('CONFIG_RL') end,
					},
					dynamicstatusicons = {
						order = 4,
						type = 'execute',
						name = '|cFF16C3F2Dynamic Status |r|cFFFFFFFFIcons|r',
						desc = L["Reset to Eltruism defaults."],
						confirm = true,
						width = 'double',
						func = function() ElvUI_EltreumUI:SetupDynamicStatusIcons() E:StaticPopup_Show('CONFIG_RL') end,
					},
				},
			},
			bossmods = {
				type = 'group',
				name = L["BossMods Profiles"],
				order = 2,
				args = {
					header1 = {
						order = 1,
						type = "description",
						name = "",
						width = 'full',
						image = function() return 'Interface\\AddOns\\ElvUI_EltreumUI\\Media\\Textures\\EltreumHeader', 3240, 1 end,
					},
					bigwigs = {
						order = 1,
						type = 'execute',
						name = 'BigWigs',
						desc = L["Reset to Eltruism defaults."],
						width = 'double',
						func = function() ElvUI_EltreumUI:AddonSetupBW() E:StaticPopup_Show('CONFIG_RL') end,
					},
					dbm = {
						order = 2,
						type = 'execute',
						name = 'DBM',
						desc = L["Reset to Eltruism defaults."],
						width = 'double',
						func = function() ElvUI_EltreumUI:AddonSetupDBM() E:StaticPopup_Show('CONFIG_RL') end,
					},
					headermrt = {
						order = 17,
						type = "description",
						name = "",
						width = 'full',
						image = function() return 'Interface\\AddOns\\ElvUI_EltreumUI\\Media\\Textures\\EltreumHeader', 3240, 1 end,
					},
					mrt = {
						order = 18,
						type = 'execute',
						name = 'Method Raid Tools',
						desc = L["Reset to Eltruism defaults."],
						width = 'double',
						func = function() ElvUI_EltreumUI:AddonSetupMRT() E:StaticPopup_Show('CONFIG_RL') end,
					},
				},
			},
			addons = {
				type = 'group',
				name = L["Addon Profiles"],
				order = 3,
				args = {
					header1 = {
						order = 1,
						type = "description",
						name = "",
						width = 'full',
						image = function() return 'Interface\\AddOns\\ElvUI_EltreumUI\\Media\\Textures\\EltreumHeader', 3240, 1 end,
					},
					dynamiccam = {
						order = 2,
						type = 'execute',
						name = 'Dynamic Cam',
						desc = L["Reset to Eltruism defaults."],
						width = 'double',
						func = function() ElvUI_EltreumUI:AddonSetupDynamicCam() E:StaticPopup_Show('CONFIG_RL') end,
					},
					header2 = {
						order = 3,
						type = "description",
						name = "",
						width = 'full',
						image = function() return 'Interface\\AddOns\\ElvUI_EltreumUI\\Media\\Textures\\EltreumHeader', 3240, 1 end,
					},
					immersion = {
						order = 4,
						type = 'execute',
						name = 'Immersion',
						desc = L["Reset to Eltruism defaults."],
						width = 'double',
						func = function() ElvUI_EltreumUI:AddonSetupImmersion() E:StaticPopup_Show('CONFIG_RL') end,
					},
					header3 = {
						order = 5,
						type = "description",
						name = "",
						width = 'full',
						image = function() return 'Interface\\AddOns\\ElvUI_EltreumUI\\Media\\Textures\\EltreumHeader', 3240, 1 end,
					},
					nameplatesct = {
						order = 6,
						type = 'execute',
						name = 'NameplateSCT',
						desc = L["Reset to Eltruism defaults."],
						width = 'double',
						func = function() ElvUI_EltreumUI:AddonSetupNameplateSCT() E:StaticPopup_Show('CONFIG_RL') end,
					},
					fct = {
						order = 6,
						type = 'execute',
						name = 'ElvUI Floating Combat Text',
						desc = L["Reset to Eltruism defaults."],
						width = 'double',
						func = function() ElvUI_EltreumUI:AddonSetupFCT() E:StaticPopup_Show('CONFIG_RL') end,
					},
					header7 = {
						order = 7,
						type = "description",
						name = "Details Profiles",
						width = 'full',
						image = function() return 'Interface\\AddOns\\ElvUI_EltreumUI\\Media\\Textures\\EltreumHeader', 3240, 1 end,
					},
					details = {
						order = 8,
						type = 'execute',
						name = L["Details v1 - Blizzard Flat Icons"],
						desc = L["Reset to Eltruism defaults."],
						width = 'double',
						func = function() ElvUI_EltreumUI:AddonSetupDT() E:StaticPopup_Show('CONFIG_RL') end,
					},
					details2 = {
						order = 9,
						type = 'execute',
						name = L["Details v2 - Releaf Transparent Icons"],
						desc = L["Reset to Eltruism defaults."],
						width = 'double',
						func = function() ElvUI_EltreumUI:AddonSetupDTReleaf() E:StaticPopup_Show('CONFIG_RL') end,
					},
					details3 = {
						order = 10,
						type = 'execute',
						name = L["Details v3 - Releaf Solid Icons"],
						desc = L["Reset to Eltruism defaults."],
						width = 'double',
						func = function() ElvUI_EltreumUI:AddonSetupDTReleafv3() E:StaticPopup_Show('CONFIG_RL') end,
					},
					header5411 = {
						order = 11,
						type = "description",
						name = "",
						width = 'full',
						image = function() return 'Interface\\AddOns\\ElvUI_EltreumUI\\Media\\Textures\\EltreumHeader', 3240, 1 end,
					},
					questie = {
						order = 12,
						type = 'execute',
						name = 'Questie',
						desc = L["Reset to Eltruism defaults."],
						width = 'double',
						func = function() ElvUI_EltreumUI:AddonSetupQuestie() E:StaticPopup_Show('CONFIG_RL') end,
					},
					header11 = {
						order = 13,
						type = "description",
						name = "PvP Addons",
						width = 'full',
						image = function() return 'Interface\\AddOns\\ElvUI_EltreumUI\\Media\\Textures\\EltreumHeader', 3240, 1 end,
					},
					gladdy = {
						order = 14,
						type = 'execute',
						name = 'Gladddy',
						desc = L["Reset to Eltruism defaults."],
						width = 'double',
						func = function() ElvUI_EltreumUI:SetupGladdy() E:StaticPopup_Show('CONFIG_RL') end,
					},
					gladius = {
						order = 15,
						type = 'execute',
						name = 'Gladius',
						desc = L["Reset to Eltruism defaults."],
						width = 'double',
						func = function() ElvUI_EltreumUI:SetupGladius() E:StaticPopup_Show('CONFIG_RL') end,
					},
					--[[gladiusex = {
						order = 15,
						type = 'execute',
						name = 'GladiusEX',
						desc = L["Reset to Eltruism defaults."],
						width = 'double',
						func = function() ElvUI_EltreumUI:AddonSetupGladiusEx() E:StaticPopup_Show('CONFIG_RL') end,
					},]]
					capping = {
						order = 16,
						type = 'execute',
						name = 'Capping',
						desc = L["Reset to Eltruism defaults."],
						width = 'double',
						func = function() ElvUI_EltreumUI:GetCappingProfile() E:StaticPopup_Show('CONFIG_RL') end,
					},
				},
			},
		},
	}
	return profiles
end
