local ElvUI_EltreumUI, E, L, V, P, G = unpack(select(2, ...))

function ElvUI_EltreumUI:QuestOptions()
	local quests = {
		type = 'group',
		name = L["Quests"],
		icon = 'Interface\\AddOns\\ElvUI_EltreumUI\\Media\\Icons\\quest',
		order = 85,
		args = {
			headergaphere = {
				order = 1,
				type = "description",
				name = "",
				width = 'full',
				image = function() return 'Interface\\AddOns\\ElvUI_EltreumUI\\Media\\Textures\\EltreumHeader', 3240, 1 end,
			},
			autoaccept = {
				order = 2,
				type = 'toggle',
				name = L["Enable Automatically accepting/turning in Quests when not holding CTRL/SHIFT/ALT"],
				desc = L["You will automatically accept and turn in quests that do not require gold, are not weekly and are not daily"],
				width = 'full',
				get = function() return E.db.ElvUI_EltreumUI.questsettings.autoaccept end,
				set = function(_, value) E.db.ElvUI_EltreumUI.questsettings.autoaccept= value E:StaticPopup_Show('CONFIG_RL') end,
			},
			autoacceptinvert = {
				order = 3,
				type = 'toggle',
				name = L["Invert CTRL/SHIFT/ALT"],
				desc = L["You will only accept and turn in quests if you hold CTRL/SHIFT/ALT while talking to the NPC"],
				width = 'full',
				get = function() return E.db.ElvUI_EltreumUI.questsettings.autoacceptinvert end,
				set = function(_, value) E.db.ElvUI_EltreumUI.questsettings.autoacceptinvert = value E:StaticPopup_Show('CONFIG_RL') end,
			},
			headergaphereitembar = {
				order = 4,
				type = "description",
				name = L["Quest Item Bar"],
				width = 'full',
				image = function() return 'Interface\\AddOns\\ElvUI_EltreumUI\\Media\\Textures\\EltreumHeader', 3240, 1 end,
			},
			questitembar = {
				order = 5,
				type = 'toggle',
				name = L["Enable Quest Item Bar"],
				desc = L["Add a Quest Item bar, keybind can be changed in Key Bindings > ElvUI Eltruism"],
				width = 'full',
				get = function() return E.db.ElvUI_EltreumUI.questsettings.questitems end,
				set = function(_, value) E.db.ElvUI_EltreumUI.questsettings.questitems = value E:StaticPopup_Show('CONFIG_RL') end,
			},
			questitembarab1 = {
				order = 6,
				type = 'toggle',
				name = L["Quest Item Bar follows visibility settings for ElvUI Action Bar 1"],
				desc = L["The Quest Item Bar will appear only when ElvUI Action Bar 1 appears, following its settings"],
				width = 'full',
				disabled = function() return (not E.db.ElvUI_EltreumUI.questsettings.questitems) or E.db.ElvUI_EltreumUI.questsettings.questitemsfade end,
				get = function() return E.db.ElvUI_EltreumUI.questsettings.questitemsbar1 end,
				set = function(_, value) E.db.ElvUI_EltreumUI.questsettings.questitemsbar1 = value E:StaticPopup_Show('CONFIG_RL') end,
			},
			questitembarmouseover = {
				order = 7,
				type = 'toggle',
				name = L["Quest Item Bar Button Mouse Over"],
				desc = L["Each Button in the Quest Item Bar will appear only if the cursor is over it"],
				width = 'full',
				disabled = function() return (not E.db.ElvUI_EltreumUI.questsettings.questitems) or E.db.ElvUI_EltreumUI.questsettings.questitemsbar1 end,
				get = function() return E.db.ElvUI_EltreumUI.questsettings.questitemsfade end,
				set = function(_, value) E.db.ElvUI_EltreumUI.questsettings.questitemsfade = value E:StaticPopup_Show('CONFIG_RL') end,
			},
			questitemsbarsize = {
				type = 'range',
				name = L["Quest Item Bar Button Size"],
				desc = L["Change the size of the button on the Quest Item Bar"],
				order = 8,
				min = 10,
				max = 100,
				step = 1,
				width = "double",
				disabled = function() return not E.db.ElvUI_EltreumUI.questsettings.questitems end,
				get = function() return E.db.ElvUI_EltreumUI.questsettings.questitemsize end,
				set = function(_, value) E.db.ElvUI_EltreumUI.questsettings.questitemsize = value E:StaticPopup_Show('CONFIG_RL') end,
			},
			headergaphere1 = {
				order = 9,
				type = "description",
				name = "",
				width = 'full',
				image = function() return 'Interface\\AddOns\\ElvUI_EltreumUI\\Media\\Textures\\EltreumHeader', 3240, 1 end,
			},
			questsettings = {
				order = 96,
				type = 'toggle',
				name = L["Collapse Quests during Encounters/Boss Fights"],
				desc = L["Collapse Quests when the boss fight starts"],
				width = 'full',
				get = function() return E.db.ElvUI_EltreumUI.questsettings.enable end,
				set = function(_, value) E.db.ElvUI_EltreumUI.questsettings.enable = value E:StaticPopup_Show('CONFIG_RL') end,
			},
			headergaphere2 = {
				order = 97,
				type = "description",
				name = "",
				width = 'full',
				image = function() return 'Interface\\AddOns\\ElvUI_EltreumUI\\Media\\Textures\\EltreumHeader', 3240, 1 end,
			},
			questcombatsettings = {
				order = 98,
				type = 'toggle',
				width = 'full',
				name = L["Collapse Quests during any combat event"],
				desc = L["Collapse Quests when you enter combat"],
				get = function() return E.db.ElvUI_EltreumUI.questsettings.combatenable end,
				set = function(_, value) E.db.ElvUI_EltreumUI.questsettings.combatenable = value E:StaticPopup_Show('CONFIG_RL')end,
			},
			arenaquestsettings = {
				order = 99,
				type = 'toggle',
				width = 'full',
				name = L["Hide Quests during Battlegrounds and Arenas"],
				desc = L["Hide Quests during Battlegrounds and Arenas"],
				get = function() return E.db.ElvUI_EltreumUI.questsettings.arena end,
				set = function(_, value) E.db.ElvUI_EltreumUI.questsettings.arena = value E:StaticPopup_Show('CONFIG_RL') end,
			},
		},
	}
	return quests
end
