-- German localization by Khornan
--local L = LibStub("AceLocale-3.0"):NewLocale("ElvUI_EltreumUI", "deDE")
local L = ElvUI[1].Libs.ACL:NewLocale("ElvUI", "deDE")
if not L then return end

-- Core
L["4K resolution detected, setting fonts to default mode."] = "4K Auflösung erkannt, Schrift wird auf Standard gesetzt."
L["1440p resolution detected, setting fonts to outline mode."] = "1440p Auflösung erkannt, die Schrift wird auf Kontur gesetzt."
L["1080p resolution detected, setting fonts to outline mode."] = "1080p Auflösung erkannt, die Schrift wird auf Kontur gesetzt."
L["Fonts were set to Outline due to your resolution."] = "Schriftarten werden auf Kontur gesetzt aufgrund Ihrer Auflösung."
L["EltruismConsumables"] = true
--Install
L["General CVars have been set."] = "General CVars wurden geladen."
L["NamePlate CVars have been set."] = "NamePlate CVars wurden geladen."
L["AddOnSkins profile has been set."] = "AddOnSkins Profil wurde geladen."
L["Immersion profile has been set."] = "Immersion Profil wurde geladen."
L["BigWigs profile has been set."] = "BigWigs Profil wurde geladen."
L["DBM profile has been set."] = "DBM Profil has wwurde geladen."
L["Details profile has been set."] = "Details Profil wurde geladen."
L["Dynamic Cam profile has been set."] = "Dynamic Cam Profil wurde geladen."
L["GladiusEx profile has been set."] = "GladiusEx Profil wurde geladen."
L["Method Raid Tools profile has been set."] = "Method Raid Tools Profil wurde geladen."
L["ProjectAzilroka profile has been set."] = "ProjectAzilroka Profil wurde geladen."
L["Questie profile has been set."] = "Questie Profil wurde geladen."
L["NameplateSCT profile has been set."] = "NameplateSCT Profil wurde geladen."
L["Floating Combat Text profile has been set."] = "Floating Combat Text Profil wurde geladen."
L["Gladius profile has been set."] = "Gladius Profi wurde geladen."
L["Gladdy profile has been set."] = "Gladdy Profil wurde geladen."
L["Area does not support waypoints"] = "Gebiet unterstützt keine Wegpunkte"
L["Unsupported format"] = "Nicht unterstütztes Format"
L["Unsupported format or Area does not support waypoints"] = "Nicht unterstütztes Format oder Gebiet unterstützt keine Wegpunkte"
L["WARNING"] = "WARNUNG"
L["Make sure to install "] = "Vergewissere dich, dass Installiert wird "
L["Shadow and Light"] = true
L[" and "] = " und "
L["WindTools"] = true
L[" before starting this installation process"] = " bevor die Installation gestartet wird"
L["Curse doesn't allow selective dependencies for addons when it comes to World of Warcraft versions"] = "Curse akzeptiert keine ausgewählten Abhängigkeiten wenn es um World of Warcraft Versionen geht"
L[" are required for Retail but not Classic that's why you are seeing this screen"] = " wird für Retail benötigt, nicht für Classic, deshalb siehst du diesen Screen"
L["Download them before continuing"] = "Downloade es bevor du weitermachst"
L[" before starting this installation process"] = " bevor du den Installationprozess startest"
L["AddOnSkins"] = true
L["ProjectAzilroka"] = true
L["This prompt will help you install "] = "Diese Eingabeaufforderung wird dir beim Installieren helfen "
L[" and import its settings"] = " und seine Einstellungen importieren"
L["Please read the instructions to avoid issues"] = "Bitte lese die Instruktionen um Fehler zu vermeiden"
L["Skip Install"] = "Überspringe Installtion"
L["Layouts"] = true
L["Please select the role for your character, which will create a new profile.\nThis process can take a few seconds"] = "Bitte wähle die Rolle deines Charakters für welches ein Profil erstellt wird.\nDieser Prozess dauert ein paar Sekunden"

L["Importance: "] = "Wichtig: "
L["Very High"] = true
L["Fonts"] = true
L["Eltruism uses Kimberley as the default font"] = "Eltruism benutzt Kimberley als Standard Schrift"
L["You can replace it with one of the following:"] = "Du kannst sie durch eine der folgenden Möglichkeiten ersetzen:"
L["Optional"] = true
L["Import GladiusEx profile, remember to disable ElvUI Arena Frames"] = "Importiert GladiusEx Profil, Vergesse nicht ElvUI Arena Frames zu deaktivieren"
L["You will need to change the profile in /gex profile options"] = "Du musst das Profil unter /gex Profil in Optionen ändern"
L["Your current settings will be lost, please back them up"] = "Die aktuellen Einstellungen gehen verloren, bitte sichere sie"
L["Import "] = "Importieren "
L["GladiusEx adds many features not available on Elvui Arena frames"] = "GladiusEx fügt viele Features in Elvui Arena Frames hinzu"
L["Such as diminishing cooldowns, enemy cast tracker, cooldown tracker"] = "Wie zum Beispiel die Diminishing Cooldowns, Enemy Cast Tracker, Cooldown Tracker"
L["Import Details! profile with dual panels"] = "Importiere Details! Profil mit zwei panels"
L["You can right click the bottom right arrow to toggle the Details! Window"] = "Du kannst mit der rechten Maustaste auf den Pfeil unten rechts klicken, um das Fenster Details! umzuschalten"
L["Remember to swap the second window to Healing Done or Tiny Threat"] = "Vergiss nicht das zweite Fenster auf Healing Done oder Tiny Threat zu stellen"
L["Make sure to run Details! install before importing"] = "Stelle sicher, dass du Details! installiert hast bevor du importierst"
L["Details is an advanced combat parser"] = "Details ist ein erweiterter Kampf Parser"
L["It uses less memory and is more efficient than alternatives"] = "Details benötigt wenig Speicher und ist effizenter als andere Alternativen"
L["And has many plugins to choose from"] = "Und hat viele Plugins zur Auswahl"
L["Boss Mods"] = true
L["Import DBM or Bigwigs profiles"] = "Importiere DBM oder Bigwigs Profile"
L["These profiles are setup with DBM English Calanon and Bigwigs Voice"] = "Diese Profile werden mit DBM English Calanon und Bigwigs Voice eingerichtet"
L["Your current settings will be lost with overwrite, please back them up"] = "Die aktuellen Einstellungen werden Überschrieben, bitte vorher sichern"
L["DBM is not installed or enabled so BigWigs will be used"] = "DBM ist nicht Installiert oder Aktiviert, es wird BigWigs benutzt"
L["BigWigs uses BigWigs voice in its profile"] = "BigWigs benutzt BigWigs Voice in seinem Profil"
L["BigWigs is not installed or enabled so DBM will be used"] = "BigWigs ist nicht Installiert oder Aktiviert, es wird DBM benutzt"
L["DBM uses DBM English by Calanon as a voice pack"] = "DBM benutzt DBM Englisch by Calanon als voice pack"
L["Both DBM and BigWigs are not installed or enabled"] = "DBM und BigWigs sind nicht Installiert oder Aktiviert"
L["No boss mods found"] = "Es wurden keine Boss Mods gefunden"
L["Boss mods are highly recommended for modern encounters"] = "Boss Mods sind für den aktuellen Content sehr empfohlen"
L["MRT Raid Tools"] = true
L["Import MRT profile with raid cooldowns and other settings"] = "Importiert MRT Profil mit Raid Cooldowns und anderen Einstellungen"
L["You will need to swap to this profile in MRT"] = "Du musst dieses Profiel in MRT dann auswählen"
L["Overwrite"] = "Überschreiben"
L["Copy"] = "Kopieren"
L["MRT is a suite of tools for raiding"] = "MRT ist ein Tolles zum Tool zum Raiden"
L["Includes tracking raid cooldowns and creating notes"] = "Trackt Raid Cooldowns und man kann Notizen erstellen"
L["Alongside attendance and other features"] = "Sowie die Raidanwesenheit überprüfen und viele andere Features"
L["Combat Text"] = "Kampftext"
L["Import profiles for NameplateSCT or ElvUI Floating Combat Text"] = "Importiere Profil für NameplateSCT oder ElvUI Floating Combat Text"
L["FCT profile will be used"] = "FCT Profil wird benutzt"
L["NameplateSCT profile will be used"] = "NameplateSCT Profil wird benutzt"
L["Combat text addons enhance the default Blizzard Combat Text"] = "Kampftext Addons verbessern/erweitern den Standard Blizzard Kampftext"
L["NameplateSCT and FCT make the combat text float from the nameplate/frame"] = "NameplateSCT und FCT werden am Namplate angezeigt"
L["And add effects to them with minimal memory usage"] = "Und fügt Effekte mit wenig Speicher verbrauch hinzu"
L["settings configured for "] = "einstellungen konfiguriert für "
L[" is not installed or enabled"] = " ist nicht Installiert oder Aktiviert"
L["NameplateSCT and FCT are not installed or enabled"] = "NameplateSCT und FCT sind nicht Installiert oder Aktiviert"
L["Immersion is an addon that changes the quest dialog with npcs"] = "Immersion ist ein Addon welches die Quest Dialoge mit NPC's ändert"
L["It transforms them into a talking head with dialog options on the side"] = "Er verwandelt sie in einen sprechenden Kopf mit Dialogoptionen an der Seite"
L["Including the ability to press number keys to select an option"] = "Einschließlich der Möglichkeit, Zifferntasten zu drücken, um eine Option auszuwählen"
L["Import Dynamic Cam profile"] = "Importiere Dynamic Cam Profil"
L["You might need to swap profiles in DynamicCam settings"] = "Eventuell musst du die Profile in DynamicCam Einstellungen Austauschen"
L["DynamicCam is addon that modifies the behavior of the camera"] = "DynamicCam ist ein Addon welches das Verhalten der Kamera ändert"
L["The profile uses some effects while questing"] = "Das Profil verwendet einige Effekte während des Questen"
L["But in instances the effects are disabled"] = "Aber in Instanzen sind sie Deaktiviert"
L["Welcome"] = "Willkommen"
L["Join the Discord if you have any questions or issues (English Support)"] = "Join unseren Discord wenn du irgendwelche Fragen oder Probleme hast(English Support)"
L["Installation Complete"] = "Installation Abgeschlossen"
L["You have completed the installation process"] = "Du hast die Installation Abgeschlossen"
L["Please click Finished to reload the UI"] = "Klicke bitte auf Finish Button zum reloaden der UI"
L["Finished"] = true
L["Import Questie profile"] = "Importiert Questie Profil"
L["You will need to reload and wait for questie to rebuild the database"] = "Du musst Reloaden und warten bis Questie's Database neu erstellt wurde"
L["Questie is not installed or enabled"] = "Questie ist nicht Installiert oder Aktiviert"
L["Questie is an addon that modifies the objective tracker"] = "Questie ist ein Addon, dass das Questfenster modifiziert"
L["As such Questie adds a lot of features to it not available by default"] = "Questie fügt eine Reihe von Funktionen hinzu, die Standardmäßig nicht verfügbar sind"
L["Including TomTom support"] = "Enthält TomTom Support"
L["Arenas"] = "Arena"
L["Import profiles for Gladius or Gladdy"] = "Importiere Profile für Gladius oder Gladdy"
L["You might need to swap profiles to Eltreum in their settings"] = "Möglicherweise musst du das Profil wechseln in Eltreum's Einstellungen"
L["Gladius is not installed or enabled"] = "Gladius ist nicht Installiert oder Aktiviert"
L["Gladdy profile will be used"] = "Gladdy Profil wird benutzt"
L["Gladdy is not installed or enabled"] = "Gladdy ist nicht Installiert oder Aktiviert"
L["Gladius profile will be used"] = "Gladius Profil wird benutzt"
L["Gladdy and Gladius are not installed or enabled"] = "Gladdy und Gladius sind nicht Installiert oder Aktiviert"
L["Arena unitframes enhance the default Blizzard unitframes"] = "Arena Unitframes erweitert die Standard Blizzard Unitframes"
L["Giving them additional features like DR tracking, trinket tracking, buffs and cooldowns"] = "Du erhältst zusätzliche Funktionen wie DR Tracking, Trinket Tracking, Buffs und Cooldowns"
L["Being used by players for many years since 2008"] = "Wird seit vielen Jahren von Spielern genutzt (2008)"
L["ElvUI NamePlates were setup."] = "ElvUI NamePlates sind eingerichtet worden."
L["NamePlate Style Filters were set."] = "NamePlate Style Filters sind eingerichtet worden."
L["Abbreviates the unit name once it goes over 16 characters, made by Azilroka"] = "Kürzt den Einheiten Namen sobald es über 16 Zeichen geht, made by Azilroka"
L["Shows Class Icons by Blizzard on all targets"] = "Zeigt Klassen Icons von Blizzard bei allen Zielen"
L["Shows Class Icons by Blizzard only on Player targets"] = "Zeigt Klassen Icons von Blizzard nur bei Spieler Zielen"
L["updated to "] = "aktualisiert auf "
L["Layout has been set."] = "Layout wurde gesetzt."
L["The alternative layout was made for the Eltruism DPS/Tank profile, please switch to it to use it"] = "Das Alternative Layout ist für das Eltruism DPS/Tank Profil gemacht, bitte switche zu diesen um es zu benutzen"
L["The original layout was made for the Eltruism DPS/Tank profile, please switch to it to use it"] = "Das Original Layout ist für das Eltruism DPS/Tank Profil gemacht, bitte switche zu diesen um es zu benutzen"
L["You need to be using an Eltruism profile in order to use this function"] = "Du musst ein Eltruismus-Profil verwenden, um diese Funktion nutzen zu können."
L["Debuff filters were setup"] = "Debuff Filter wurden eingestellt"
L["Buff filters were setup"] = "Buff Filter wurden eingestellt"
L["ElvUI Chat has been set."] = "ElvUI Chat wurde festgelegt"
-- Datatext
L["Eltruism Ammo"] = true
-- Fonts
L["Your custom font has been set."] = "Deine benutzerdefinierte Schriftart wurde festgelegt."
L["Kimberley Font has been set."] = "Kimberley Font wurde eingestellt."
L["Exo2 Font has been set."] = "Exo2 Font wurde eingestellt."
L["GothamNarrow Black Font has been set."] = "GothamNarrow Black Font wurde eingestellt."
L["Roboto Font has been set."] = "Roboto Font wurde eingestellt."
--LootText
L["Soul Ash"] = true -- the currency exactly as it is in game, or the function will not work for the location
--Options
L["Installer"] = true
L["Reinstall the plugin to reset settings"] = "Installiere das Plugin neu, um die Einstellungen zurückzusetzen"
L["Install"] = "Installieren"
L["Reset nameplates to Eltruism settings"] = "Resetet Nameplates zu Eltruism Einstellungen"
L["A.F.K"] = true -- away from keyboard, can be longer in other languages
L["Play music while you are AFK"] = "Spielt Musik während du AFK bist"
L["Enable"] = "Aktivieren"
L["Cursor"] = true
L["Change the size of the World of Warcraft Cursor"] = "Änder die Größe des World of Warcraft Cursor"
L["Select a size"] = "Wähle eine Größe aus"
L["Choose this size"] = "Wählt diese Größe aus"
L["Autodetect"] = true
L["Add GCD, Cast and Combat indicator rings to the cursor"] = "Fügt ein GCD und ein Cast Ring zum Cursor hinzu"
L["Enable cooldown tracking"] = true
L["Add a cooldown icon when trying to use skills that are on cooldown, and a cooldown flash when they are ready"] = true
L["Enable cursor rings for Casts, GCD and Combat"] = "Aktiviert Cursor Ring für Zauber, GCD und Kampf"
L["Add a rings around the mouse cursor for GCD, casts and combat"] = "Fügt ein Ring für den GCD zum Mauszeiger hinzu, Zauber und Kampf"
L["Choose a type of cursor by clicking it"] = "Wähle ein Cursor Typ"
L["Currently selected cursor: "] = "Aktuell ausgewählter Cursor: "
L["Type 1"] = true
L["Type 2"] = true
L["Type 3"] = true
L["Type 4"] = true
L["Type 5"] = true
L["Type 6"] = true
L["Type 7"] = true
L["Type 8"] = true
L["Type 9"] = true
L["Type 10"] = true
L["The Cursor will use this type as its texture"] = "Der Cursor wird diesen Typ als Textur verwenden"
L["Cursor Colors "] = "Cursor Farbe "
L["Requires a Reload"] = "Benötigt ein Reload"
L["Class Colored Casts"] = "Klassengefärbter Zauber"
L["Use Class Colors for Cast"] = "Benutze Klassenfarbe für Zauber"
L["Custom Color Cast"] = "Individuelle Farbe für Zauber"
L["Class Colored GCD"] = "Klassengefärbter GCD"
L["Use Class Colors for GCD"] = "Benutze Klassenfarbe für GCD"
L["Custom Color GCD"] = "Individuelle Farbe für GCD"
L["Class Colored Combat"] = "Klassenfarbe Kampf"
L["Use Class Colors for Cursor"] = "Benutze Klassenfarbe für Cursor"
L["Custom Color Combat"] = "Individuelle Farbe für Kampf"
L["Cast Radius (Default: 25)"] = "Zauber Radius (Standard: 25)"
L["Set the radius of the cast cursor"] = "Radius des Zauber Cursors Einstellen"
L["Cast Thickness (Default: 5)"] = "Zauber Dicke (Standard: 5)"
L["GCD Radius (Default: 20)"] = "GCD Radius (Standard: 20)"
L["Set the radius of the gcd cursor"] = "Radius des GCD Cursor Einstellen"
L["GCD Thickness (Default: 5)"] = "GCD Dicke (Standard: 5)"
L["Set the thickness of the gcd cursor"] = "Wähle die Dicke des GCD Cursor"
L["Combat Cursor Radius (Default: 15)"] = "Kampf Cursor Radius (Standard: 15)"
L["Set the radius of the combat cursor"] = "Radius des Kampf Cursor"
L["Combat Cursor Thickness (Default: 5)"] = "Kampf Cursor Dicke (Standard: 5)"
L["Set the thickness of the combat cursor"] = "Wähle die Dicke des Kampf Cursor"
L["Aura Filters"] = true
L["For Shadowlands, import aura filters by copying the code below and going into Profiles > Import Profile."] = "Für Shadowlands, importiere Aura Filter indem du den Code unten kopierst und dann im Profil importierst > Importiere Profil."
L["Setup Aura Filters to show all"] = "Setze Aura Filter zu Zeige alle"
L["All Player Buffs"] = "Alle Spieler Buffs"
L["Set filters to show more buffs on Player"] = "Setze Filter um mehr Buffs auf dem Spieler anzuzeigen"
L["All Player Debuffs"] = "Alle Spieler Debuffs"
L["Set filters to show more debuffs on Player"] = "Setze Filter um mehr Debuffs auf dem Spieler anzuzeigen"
L["All Target Debuffs"] = "Alle Ziel Debuffs"
L["Set filters to show more debuffs on Target"] = "Setze Filter um mehr Debuffs auf dem Ziel anzuzeigen"
L["All Target Buffs"] = "Alle Ziel Buffs"
L["Set filters to show more buffs on Target"] = "Setze Filter um mehr Buffs auf dem Ziel anzuzeigen"
L["All Focus Buffs"] = "Alle Focus Buffs"
L["Set filters to show more buffs on Focus"] = "Setze Filter um mehr Buffs auf dem Focus anzuzeigen"
L["All Focus Debuffs"] = "Alle Focus Debuffs"
L["Set filters to show more debuffs on Focus"] = "Setze Filter um mehr Debuffs auf dem Focus anzuzeigen"
L["All Boss Buffs"] = "Alle Boss Buffs"
L["Set filters to show more buffs on Boss"] = "Setze Filter um mehr Buffs auf dem Boss anzuzeigen"
L["All Boss Debuffs"] = "Alle Boss Debuffs"
L["Set filters to show more debuffs on Boss"] = "Setze Filter um mehr Debuffs auf dem Bosss anzuzeigen"
L["All Nameplate Buffs"] = "Alle Nameplates Buffs"
L["Set filters to show more buffs on Nameplates"] = "Setze Filter um mehr Buffs auf den Nameplates anzuzeigen"
L["All Nameplate Debuffs"] = "Alle Nameplates Debuffs"
L["Set filters to show more debuffs on Nameplates"] = "Setze Filter um mehr Debuffs auf den Nameplates anzuzeigen"
L["Setup Aura Filters to be Eltruism/ElvUI defaults"] = "Einstellen der Aura Filter auf Eltruism/ElvUI Standard"
L["Eltruism Player Buffs"] = "Eltruism Spieler Buffs"
L["Set filters to be Eltruism/ElvUI defaults on Player"] = "Filter einstellen auf Eltruism/ElvUI Standard auf Spieler"
L["Eltruism Player Debuffs"] = "Eltruism Spieler Debuffs"
L["Eltruism Target Debuffs"] = "Eltruism Ziel Debuffs"
L["Set filters to be Eltruism/ElvUI defaults on Target"] = "Filter einstellen auf Eltruism/ElvUI Standard auf Ziele"
L["Eltruism Target Buffs"] = "Eltruism Ziel Buffs"
L["Eltruism Focus Buffs"] = "Eltruism Focus Buffs"
L["Set filters to be Eltruism/ElvUI defaults on Focus"] = "Filter einstellen auf Eltruism/ElvUI Standard auf Focus"
L["Eltruism Focus Debuffs"] = "Eltruism Focus Debuffs"
L["Eltruism Boss Buffs"] = "Eltruism Boss Buffs"
L["Set filters to be Eltruism/ElvUI defaults on Boss"] = "Filter einstellen auf Eltruism/ElvUI Standard auf Boss"
L["Eltruism Boss Debuffs"] = "Eltruism Boss Debuffs"
L["Eltruism Nameplate Buffs"] = "Eltruism Nameplate Buffs"
L["Set filters to be Eltruism/ElvUI defaults on Nameplates"] = "Filter einstellen auf Eltruism/ElvUI Standard auf Nameplates"
L["Eltruism Nameplate Debuffs"] = "Eltruism Nameplate Debuffs"
L["Addons"] = true
L["ElvUI Plugins"] = true
L["Reset to Eltruism defaults."] = "Reset auf Eltruism Standard."
L["BossMods Profiles"] = "BossMods Profile"
L["Addon Profiles"] = "Addon Profile"
L["Combat Music"] = "Musik im Kampf"
L["Play music during combat"] = "Spielt Musik im Kampf"
L["Enable music during combat"] = "Aktiviere Musik im Kampf"
L["Disable in Instances"] = "Deaktiviere in Instanzen"
L["Disable music during combat in instances"] = "Deaktiviere Musik während des Kampfes in Instanzen"
L["Path to file"] = "Pfad zur Datei"
L["Example: "] = "Beispiel: "
L["CVars"] = true -- i dont know if this gets localized
L["Setup CVars"] = "Einstellung CVars"
L["General CVars"] = "Allgemeine CVars"
L["It will set these CVars:"] = "Setze diese CVars:"
L["Party/Raid"] = "Gruppe/Raid"
L["Play a sound when someone dies in Party or Raid"] = "Einen Ton abspielen, wenn jemand stirbt in der Gruppe oder im Raid"
L["Select a Sound"] = "Wähle einen Sound aus"
L["Alternative unitframe layouts"] = "Alternativer Unitframe Layout"
L["DPS/Tank layouts were created with pure dps classes in mind, if you play a class with more raid cooldowns like a Shaman, Druid or Paladin you might want to use the alternative layout in order to make it easier for you to use your cooldowns on the members of your group"] = "DPS/Tank Layout wurden mit Blick auf reine DPS-Klassen erstellt, wenn du eine Klasse mit mehr Raid Cooldowns wie ein Schamane, Druide oder Paladin kannst du das alternative Layout verwenden, damit ihr eure Abklingzeiten leichter auf die Mitglieder eurer Gruppe anwenden könnt."
L["Alternative Layout"] = "Alternatives Layout"
L["Original Layout"] = "Original Layout"
L["Media"] = "Medien"
L["Setup Media"] = "Einstellung Medien"
L["Reset all Media"] = "Resete alle Medien"
L["Reset Fonts, Textures, Skins to Eltreum UI defaults."] = "Resete Schriftarten, Texturen, Skins zu Eltreum UI Standard."
L["Set the fonts used in Eltruism. Kimberley is the default font"] = "Wähle die Schriftart welche in Eltruism verwendet wird. Kimberley ist die Standard Schriftart"
L["This will set all ElvUI fonts as Kimberley"] = "Das wird alle ElvUI Schriftarten auf Kimberley Schrift setzen"
L["This will set all ElvUI fonts as Exo2"] = "Das wird alle ElvUI Schriftarten auf Exo2 Schrift setzen"
L["This will set all ElvUI fonts as Gotham"] = "Das wird alle ElvUI Schriftarten auf Gotham Schrift setzen"
L["This will set all ElvUI fonts as Roboto"] = "Das wird alle ElvUI Schriftarten auf Roboto Schrift setzen"
L["Or choose a custom font"] = "Oder benutze eine benutzerdefinierte Schriftart"
L["Choose a different font from the preselected ones"] = "Wähle eine andere Schriftart von den vorausgewählten"
L["Set the Font Outlines everywhere. Use Default to return to Eltruism default settings"] = "Setzte die Kontur der Schrift überall. Benutze Standard für die Eltruism Standard Einstellungen"
L["Defaults"] = "Standard"
L["This will set fonts to Eltruism defaults, recommended for 4K"] = "Das setzt Eltruism Schriftarten auf Standard, empfohlen für 4K"
L["None"] = true  --as in no font outline
L["This will set fonts to no outline"] = "Dies setzt die Schriftarten auf keine Kontur"
L["Outline"] = "Kontur"
L["This will set fonts to use outline, recommended for 1440p and 1080p"] = "Dies führt zur Verwendung von Kontur bei der Schrift, Empfohlen für 1440p und 1080p"
L["Thick Outline"] = "Dicke Kontur"
L["This will set fonts to use thick outline"] = "Dadurch wird die Schriftart so eingestellt, dass eine dicke Kontur verwendet wird"
L["Change the look of frames to Dark or Light mode"] = "Ändert das aussehen der Frames zu Dark oder Light mode"
L["Dark Mode"] = true
L["This will set colors to black with class colors when losing health"] = "Stellt die Farben auf schwarz mit Klassenfarben beim Verlust von Gesundheit"
L["Light Mode"] = true
L["This will set colors to class based with black backgrounds when losing health"] = "Stellt die Farben auf Klassenfarbe mit schwarz beim Verlust von Gesundheit"
L["Dynamic Datatext that changes according to class to show Ammo or Soul Shards when playing Hunter, Warrior, Rogue or Warlock"] = "Dynamische Datentexte die sich je nach Klasse ändert und beim Spielen Munition oder Seelensplitter anzeigt Jäger, Krieger, Schurken oder Hexenmeister"
L["Enable the Dynamic Datatext"] = "Aktiviere die Dynamischen Datentexte"
L["Expand the Talents to show the entire tree"] = "Die Talente erweitern um den gesamten Baum anzuzeigen"
L["Expanded Talents"] = "Talente erweitern"
L["Expand Talents to cover the full tree"] = "Die Talente erweitern um den gesamten Baum anzuzeigen"
L["Nameplates"] = true
L["Class Colored Nameplate Options"] = "Klassenfarben Nameplates Optionen"
L["Hover"] = "Mouseover"
L["Change the color of the hover to be class colored"] = "Ändert die Farbe bei Mouseover in Klassenfarbe"
L["Border"] = "Rahmen"
L["Change the color of the border glow to be class bordered in nameplates"] = "Ändert die Farbe des Rahmen Leuchtens umrandet in Klassenfarbe bei den Nameplates"
L["Target Texture"] = "Ziel Textur"
L["Change the texture of the nameplate to be a class gradient"] = "Ändert die Textur der Nameplates zu ein Klassenfarbverlauf"
L["Control how Nameplates behave"] = "Kontrolliert wie sich Nameplates verhalten"
L["Show Friendly Nameplates but Hide Healthbar"] = "Zeigt freundliche Nameplates an aber versteckt die Gesundheitsleiste"
L["Hide Friendly Nameplates inside Instances"] = "Versteckt freundliche Nameplates in Instanzen"
L["Hide Friendly Nameplates everywhere"] = "Versteckt freundliche Nameplates überall"
L["Wide nameplate debuffs and buffs"] = "Breite Nameplates Debuffs und Buffs"
L["Make Buffs and Debuffs Wide on Nameplates"] = "Macht Buffs und Debuffs Breit auf Nameplates"
L["Toggle On and Off"] = "Umschalten On und Off"
L["Enemy Nameplate Level"] = "Level bei Feindlichen Nameplates"
L["Hide level on enemy nameplates when you are max level"] = "Verstecke Level bei Feindlichen Nameplates wenn du auf max Level bist"
L["Nameplate Power Bar"] = true
L["Enable Nameplate Power Bar"] = "Aktiviere Nameplate Power Bar"
L["Enable an extra Power Bar on Nameplates for missing powers"] = "Aktiviere eine zusätzliche Power Bar auf den Nameplates für fehlende Kräfte"
L["Enable Auto-adjusting Buffs/Debuffs"] = "Aktiviere Automatische Anpassung der Buffs/Debuffs"
L["Enable Auto-adjusting the position of Buffs/Debuffs"] = "Aktiviere Automatische Anpassung der Postition der Buffs/Debuffs"
L["Enable Auto-adjusting the Vertical Position of the Power Bar"] = "Aktiviere Automatische Anpassung der Vertikalen Postion der Power Bar"
L["Power Bar will move automatically based on class/spec/druid form"] = "Power Bar bewegt sich Automatisch ausgehend von der Klasse/Talenten/Druidenform"
L["Select the Y Offset for the Power Bar (Default 16)"] = "Wähle den Y Offset für die Power Bar (Standard 16)"
L["Set Y Offset"] = "Setze Y Offset"
L["Select the Horizontal Size of the Power Bar (Default 132)"] = "Wähle die Horizontale Größe der Power Bar (Standard 132)"
L["Set Horizontal Size"] = "Setze die Horizontale Größe"
L["Select the Vertical Size of the Power Bar (Default 6)"] = "Wähle die Vertikale Größe der Power Bar (Standard 6)"
L["Set Vertical Size"] = "Setze die Vertikale Größe"
L["Choose the Power Bar Texture"] = "Wähle die Power Bar Textur"
L["Select a Texture"] = "Wähle eine Textur"
L["Select the power types to be displayed:"] = "Wähle den Power Typ welcher angezeigt werden soll:"
L["Mana"] = true
L["Rage"] = "Wut"
L["Energy"] = "Energie"
L["Loot"] = true
L["Show a floating loot text"] = "Zeigt ein Floating Loot Text"
L["Choose which types of text:"] = "Wähle die Textart aus:"
L["Honor"] = "Ehre"
L["Currency"] = "Währung"
L["Pets"] = true
L["Change the scale of LootText"] = "Ändere die Skalierung des Loot Textes"
L["Set the size of LootText"] = "Setze die Größe des Loot Text"
L["Reset Scale"] = "Resete Skalierung"
L["Return LootText to its default scale"] = "Setze Loot Text zur Standard Skalierung"
L["Change the strata of the Loot Text"] = "Ändere die Strata des Loot Textes"
L["Set the level that LootText will be drawn to this"] = "Setze das Stratalevel des Loot Textes welcher angezeigt werden soll"
L["Background"] = true
L["Low"] = true
L["Medium"] = true
L["High"] = true
L["Dialog"] = true
L["Change the Horizontal Position of LootText (Default = 0)"] = "Ändere die Horizontale Position des Loot Textes (Standard = 0)"
L["Set X offset"] = "Setze X Offset"
L["Change the Vertical Position of LootText (Default = 200)"] = "Ändere die Vertikale Position des Loot Textes (Standard = 200)"
L["Set Y offset"] = "Setze Y Offset"
L["Change the font of LootText to be that the ElvUI Default Font found in General"] = "Ändere die Schriftart des Loot Textes welches in ElvUI Default Font in den Allgemeinen Einstellungen gefunden wird"
L["Use ElvUI General Font"] = "Benutze ElvUI General Font"
L["Change the font of LootText"] = "Ändere die Schriftart des Loot Texte"
L["Chat"] = true
L["Chat Options"] = "Chat Optionen"
L["Enable ElvUI Chat modifications"] = "Aktiviere ElvUI Chat Modifikationen"
L["Add fade over time, and mouse over to left and right chat panels"] = "Fügt Verblassen und Mouseover des linken und rechten Chat Panels hinzu"
L["Add mouse over to the left chat panel"] = "Mouseover des linken Chat Panels hinzufügen"
L["Left Chat Mouse Over"] = "Linker Chat Mouseover"
L["Toggle the option"] = "Umschalten der Option"
L["Add a fade to the left chat panel, controlled by ElvUI Chat > Text Fade > Inactivity Timer"] = "Fügt verblassen zum linken Chatfenster hinzu, Gesteuert von ElvUI Chat > Text Verblassen > Inaktiv Timer"
L["Left Inactivity Fader"] = "Links Verblassen wenn Inaktiv"
L["Add mouse over to the left chat panel"] = "Fügt Mouseover zu Linken Chat Fenster hinzu"
L["Right Chat Mouse Over"] = "Rechter Chat Mouseover"
L["Add a fade to the right chat panel, controlled by ElvUI Chat > Text Fade > Inactivity Timer"] = "Fügt verblassen zum rechten Chatfenster hinzu, Gesteuert von ElvUI Chat > Text Verblassen > Inaktiv Timer"
L["Right Inactivity Fader"] = "Rechts Verblassen wenn Inaktiv"
L["Combat Hide"] = "Verstecke im Kampf"
L["Hide Left Chat in Combat"] = "Verstecke linken Chat im Kampf"
L["Hide Right Chat in Combat"] = "Verstecke rechten Chat im Kampf"
L["Invert left mouse click so that chat starts faded and mouse click will make it stop fading"] = "Invertiere den linken Mausklick, so dass der Chat ausgeblendet wird und ein Mausklick das Ausblenden beendet"
L["Invert Mouse Click"] = "Mausklick invertieren"
L["Toggle the option on"] = "Schalte die Option ein"
L["Stealth Vignette"] = true
L["Toggle a Stealth Effect"] = "Umschalten des Stealth Effekts"
L["Add a vignette effect while in stealth"] = "Fügt einen Vignette Effekt hinzu während man im stealth ist"
L["Turn the effect on"] = "Schalte den Effekt ein"
L["You can set your Weakauras to anchor to custom locations making it easier to move them"] = "Du kannst Weakauraen an benutzerdefinierten Positionen verankern, um sie leichter zu bewegen"
L["In order to use this feature, simply go to your Weakaura, and go to its Group options, scroll down to Position Settings and set the Anchored To Select Frame, then type either |cff82B4ffEltruismWA|r or |cff82B4ffEltruismConsumables|r to anchor the weakaura to the preset location"] = "Um diese Funktion zu nutzen, gehen einfach zu der Weakaura und gehe dort zu Group options, Scrolle runter zu Position Settings und stelle die Option Anchored To Select Frame ein, dann gebe entweder |cff82B4ffEltruismWA|r oder |cff82B4ffEltruismConsumables|r ein"
L["Setting "] = "Einstellung "
L[" or "] = " oder "
L[" as the anchor will move them to the locations, keep in mind you might need to change the X and Y offset of the weakaura to zero"] = " da der Anker sie an die entsprechenden Stellen verschiebt, musst du möglicherweise den X- und Y-Offset der Weakaura auf Null setzen"
L["Join the Discord if you have any questions or issues"] = "Joine den Discord wenn du Fragen oder Probleme hast"
L["Keep in mind the discord is in English"] = "Denke daran, dass der Discord auf Englisch ist"
L["Changelog"] = true
L["Select a version:"] = "Wähle eine Version:"
L["Choose a version to see its changelog"] = "Wähle eine Version um den Changelog zu sehen"
L["Credits"] = true
L["Author"] = true
L["Credits and Thank yous"] = "Credits und Vielen Dank!"
L["License"] = "Lizenz"
L["Support"] = "Support"
L["New commits, basically a preview of fixes or upcoming features"] = "Neue commits, eine Vorschau auf Fehlerbehebungen oder kommende Funktionen"
L["Report issues and problems here:"] = "Fragen und Probleme hier melden:"
L["Addon on Tukui:"] = "Addon auf Tukui:"
L["Addon on CurseForge:"] = "Addon auf CurseForge:"
L["Custom Glow"] = "Benutzerdefiniertes Leuchten"
L["Replace Blizzards Default Glow with a Custom Glow"] = "Ersetzt Blizzards Standard Leuchten durch ein benutzerdefiniertes Leuchten"
L["Select a Type"] = "Wähle ein Typ"
L["Autocast"] = true
L["Pixel"] = true
L["Blizzard"] = true  -- the company not the weather effect
L["Adds a Blizzard style glow using class color"] = "Fügt ein Leuchten im Blizzard-Stil mit Klassenfarbe hinzu"
L["Glow Colors"] = "Leuchtende Farben"
L["Use Class Colors"] = "Benutze Klassenfarben"
L["Toggle Class Colored glows"] = "Wähle Klassenfarben Leuchten"
L["Custom Color"] = "Benutzerdefinierte Farbe"
L["Pixel Glow"] = "Pixel Leuchten"
L["Pixel Border"] = "Pixel Rahmen"
L["Enable a border for the Pixel Glow"] = "Aktviere ein Rahmen für das Pixel Leuchten"
L["Number of Pixels (Default is 9)"] = "Nummer der Pixel (Standard ist 9)"
L["Set the number of pixels in pixel glow"] = "Wähler die Zahl der Pixel im Pixel Leuchten"
L["Pixel Frequency (Default is 1)"] = "Pixel Frequenz (Standard ist 1)"
L["Set the frequency pixel glow"] = "Wähle die Frequenz des Pixel Leuchtens"
L["Pixel Length (Default is 3)"] = "Pixel Länge (Standard ist 3)"
L["Set the length of pixels"] = "Lege die Länge der Pixel fest"
L["Pixel Thickness (Default is 5)"] = "Pixel Dicke (Standard ist 5)"
L["Set the thickness of pixels"] = "Lege die Dicker der Pixel fest"
L["Pixel Horizontal Offset (Default is 5)"] = "Pixel Horizontaler Offset (Standard ist 5)"
L["Set the horizontal offset of pixels"] = "Setzt den Horizontalen Offset der Pixel fest"
L["Pixel Vertical Offset (Default is 5)"] = "Pixel Vertikaler Offset (Standard ist 5)"
L["Set the vertical offset of pixels"] = "Setzt den Vertikalen Offset der Pixel fest"
L["Autocast Glow"] = "Autocast Leuchten"
L["Autocast Particle Groups (Default is 8)"] = "Autocast Partikel Gruppe (Standard 8)"
L["Set the number of groups for autocast, for each group you get 4 particles"] = "Lege die Anzahl der Gruppen für Autocast fest, für jede Gruppe erhält man 4 Partikel"
L["Autocast Frequency (Default is 0.8)"] = "Autocast Frequenz (Standard ist 0.8)"
L["Speed for Autocast, set to negative to inverse direction of rotation"] = "Geschwindigkeit Autocast, auf negativ setzen, um die Drehrichtung umzukehren"
L["Autocast Scale (Default is 2)"] = "Autocast Skalierung (Standard ist 2)"
L["Change the size of Autocast"] = "Ändere die Größe des Autocasts"
L["Autocast Horizontal Offset (Default is 5)"] = "Horizontaler Autocast Offset (Standard ist 5)"
L["Set the horizontal offset of autocast"] = "Sete den Horizontalen Offset der Autocasts"
L["Autocast Vertical Offset (Default is 5)"] = "Vertikaler Autocast Offset (Standard ist 5)"
L["Set the vertical offset of autocast"] = "Sete den Vertikalen Offset der Autocast"
L["Blizzard Glow"] = "Blizzard Leuchten"
L["Blizzard Frequency (Default is 0.5)"] = "Blizzard Frequenz (Standard ist 0.5)"
L["Speed for Blizzard glow"] = "Geschwindigkeit des Blizzard Leuchten"
L["Quests"] = true
L["Collapse Quests during Encounters/Boss Fights"] = "Zusammenklappen der Quests während Begegnungen/Boss Kämpfen"
L["Collapse Quests when the boss fight starts"] = "Zusammenklappen der Quests wenn der Boss Kampf startet"
L["Maps"] = "Karten"
L["Add a time to arrive below the waypoint"] = "Hinzufügen einer Ankunftszeit zu dem Wegpunkt"
L["The time will be calculated based on player speed and distance"] = "Die Zeit wird anhand der Geschwindigkeit und der Entfernung des Spielers berechnet."
L["If the player is not moving then *** will show up since time cannot be calculated"] = "Wenn sich der Spieler nicht bewegt, dann wird *** angezeigt, da die Zeit nicht berechnet werden kann"
L["If you move away from the waypoint the time will just increase"] = "Wenn du dich vom Wegpunkt entfernst, wird die Zeit einfach verlängert."
L["Add an ETA to waypoints"] = "Fügt die geschätzte Zeit bis zum Eintreffen des Wegpunktes hinzu"
L["Enable the /way and /waypoint commands"] = "Aktiviert den /way und /waypoint Befehl"
L["You can type /way or /waypoint"] = "Du kannst Folgendes eingeben /way oder /waypoint"
L["Use formats such as:"] = "Benutze Formate wie:"
L["XX YY, XX.XX YY.YY, XX,XX YY,YY and XXX YYY"] = true
L["Other Formats can end up causing errors"] = "Andere Formate können zu Fehlern führen"
L["Enable the /way and /waypoint commands"] = "Aktiviert den /way und /waypoint Befehl"
L["Astral power"] = true
L["Runic power"] = true
L["Insanity"] = true
L["Maelstrom"] = true
L["Fury"] = true
L["Focus"] = "Fokus"
L["Select a type of music"] = "Wähle eine Art von Musik"
L["Racial Music"] = "Völker Music"
L["Class Music"] = "Klassen Musik"
L["Skin Level Up, Boss Loot and Instance Entrance frames to be class colored"] = true
L["Enable the Skins"] = true
L["Expand Hunter Stables to show all pets and improve search"] = true
L["Enable the Expanded Stable"] = true
L["Expand Transmog Window to better show your character"] = true
L["Enable the Wider Transmog Window"] = true
L["Auto open the Rogue Order Hall, to avoid opening hold CTRL or SHIFT or ALT while talking to the NPC"] = true
L["Enable the Rogue Order Hall Auto Open"] = true
L["Enable Floating Reputation Changes"] = true
L["Enable the Floating Rep Text"] = true
L["Buffs have been updated for Open World"] = true
L["Buffs have been updated for Arenas"] = true

--missing texts from February 2022
L["Eltruism Installer"] = true
L["Launch Eltruism Installer"] = true
L["Reset Eltruism Settings"] = true
L["Launches the Eltruism install prompt"] = true
L["Resets Eltruism Settings to Eltreum's Defaults"] = true
L["Reset nameplates to Eltruism settings"] = true
L["Reset Chat to ElvUI Settings"] = true
L["Reset layout to Eltruism DPS/Tank"] = true
L["Reset layout to Eltruism Healer"] = true
L["Skip Plugins install message"] = true
L["Details v1 - Blizzard Flat Icons"] = true
L["Details v2 - Releaf Transparent Icons"] = true
L["Details v3 - Releaf Solid Icons"] = true
L["Enable Borders"] = true
L["Change the size of the borders:"] = true
L["Actionbar Thickness"] = true
L["Unitframe Thickness"] = true
L["(All settings require a reload)"] = true
L["Action bar 1"] = true
L["Action bar 2"] = true
L["Action bar 3"] = true
L["Action bar 4"] = true
L["Action bar 5"] = true
L["Action bar 6"] = true
L["Target Border"] = true
L["Target of Target Border"] = true
L["Border X offset"] = true
L["Player Border"] = true
L["Player Castbar Border"] = true
L["Target Castbar Border"] = true
L["Target of Target Border"] = true
L["Nameplate Power Bar Border"] = true
L["Nameplate Power Bar Thickness"] = true
L["Enable Fast Loot"] = true
L["Decrease the time it takes for auto loot to work, works with TSM"] = true
L['Enable Fast Loot with Loot Quality Filter'] = true
L["Enable filtering item quality, items can still be looted by holding Shift or the mod key setup in Interface"] = true
L['Enable Fast Loot with Wishlist Filter'] = true
L["Items not on the wishlist will not be looted, items can still be looted by holding Shift or the mod key setup in Interface"] = true
L["Enable Wishlist Loot Warning"] = true
L["Show a toast if an item in the wishlist is looted"] = true
L["Enable Automatically Closing Loot Window"] = true
L["Loot Window will automatically close when using filters and the item desired is not found"] = true
L["Enable Screenshotting if an item from the wishlist is looted"] = true
L["Loot Window will automatically close when using filters and the item desired is not found"] = true
L["Minimum Loot Quality Filter"] = true
L["Poor"] = true
L["Common"] = true
L["Uncommon"] = true
L["Rare"] = true
L["Epic"] = true
L["Only items of this quality or better will be looted when using Fast Loot Filter"] = true
L["Item Wishlist (type the Item ID)"] = true
L["Items in your wishlist will display a warning when looted"] = true
L["Invalid Item, you need to add an itemID which can be found in the tooltip or in Wowhead"] = true
L["Remove item from Wishlist"] = true
L["Remove"] = true
L["Add color to some chat messages"] = true
L["Enhance Item Links in Chat"] = true
L['Enable Chat Icons'] = true
L["Enable Item Levels"] = true
L["Customize the Chat tabs"] = true
L["Dark Chat"] = true
L["Transparent Chat"] = true
L["Make more texts use ElvUI font settings"] = true
L["Such as the Zones, Mail and others"] = true
L["Skin Objective Frame (when Shadow and Light and Windtools are not loaded)"] = true
L['Enable Wowhead Button on Quest Log'] = true
L["Show a button for Wowhead quest links"] = true
L['Enable Skin'] = true
L["Skin the Objective/Quest Frame"] = true
L["Remove Blizzard's Boss Emote Frame"] = true
L["Customize the player castbar spark"] = true
L["Cursor Sizes"] = true
L["Select how auras will be displayed for Player"] = true
L["Select how auras will be displayed for Target"] = true
L["Select how auras will be displayed for Focus"] = true
L["Select how auras will be displayed for Boss"] = true
L["Select how auras will be displayed for Nameplates"] = true
L["Enable cursor only during combat"] = true
L["Cursor will only show during combat"] = true
L["Enable cooldown tracking"] = true
L["Add a cooldown icon when trying to use skills that are on cooldown, and a cooldown flash when they are ready"] = true
L["Attempt to fix Cursor Lag"] = true
L["Software cursor is how the cursor was before Battle for Azeroth, Hardware cursor is faster but will cause problems with addons that attach to it"] = true
L["Software Cursor"] = true
L["Hardware Cursor"] = true
L["Enable on Action Bars"] = true
L["Enable on Pet Bar"] = true
L["Enable on Nameplate"] = true
L["Add a glow when buffs or debuffs are expiring on nameplates"] = true
L["Adds an autocast style glow using class color"] = true
L["Adds a pixel style glow using class color"] = true
L["Preview the Glow"] = true
L["Preview"] = true
L["Preview the Glow, you will need to toggle it off and on to update the glow"] = true
L["Action Bars"] = true
L["Pet Bar"] = true
L["Nameplate Buff/Debuff"] = true
L["Customize CVars"] = true
L["Nameplate Other Bottom Inset"] = true
L["In screen % the inset from the Bottom"] = true
L["Nameplate Other Top Inset"] = true
L["In screen % the inset from the Top"] = true
L["Nameplate Target Radial Position"] = true
L["When target is off screen, position its nameplate radially around sides and bottom."] = true
L["Target Only"] = true
L["All in Combat"] = true
L["Camera Distance Max Zoom Factor"] = true
L["Maximum Camera Zoom Out"] = true
L["Hide Minimap while in Combat"] = true
L["Automatically hide the Minimap in combat"] = true
L["Dynamically toggle the mouseover of the Experience Bar"] = true
L["Shows XP bar when below max level, makes it mouseover when max level"] = true
L["Enable Entering/Leaving Combat Indicator Texts"] = true
L["Adds a +Combat and -Combat for when entering and leaving combat"] = true
L["Enable a Dark Souls death animation"] = true
L["Plays an animation when you die"] = true
L["Add Sounds to /roll when someone gets a 1 or a 100"] = true
L["Plays a sound if someone rolls 1 or 100 out 100"] = true
L["Change the Scale of the World Text"] = true
L["Such as the floating XP, floating reputation changes and others"] = true
L["Select the size of the World Text"] = true
L["Hide Talking Head"] = true
L["Prevent Blizzard's Talking Head from appearing"] = true
L["Automatically take Screenshots"] = true
L["Automatically take Screenshots such as when leveling up"] = true
L["Stealth"] = true
L["Item Deletion"] = true
L["Automatically type DELETE on the popup"] = true
L["Will not delete the item, will simply type DELETE instead you needing to type it"] = true
L["Blizzard Floating Combat Text"] = true
L["Disable Combat Text"] = true
L["Enable or disable Blizzard's default Floating Combat Text"] = true
L["Enable Resource Gains"] = true
L["Enable or disable Blizzard's default Floating Combat Text for Mana/Rage/Energy and other resouces"] = true
L["Swap Action Paging and visibility for Bar1 and Bar4"] = true
L["Enable Boss Music"] = true
L["Disable Combat Music in Instances"] = true
L["Normal Combat Music"] = true
L["Name of file inside Interface\\Addons"] = true
L["Boss Combat Music"] = true
L["Player Class Texture"] = true
L["Target Class Texture"] = true
L["Change the texture of the nameplate to be a class gradient of the player's class"] = true
L["Change the texture of the nameplate to be a class gradient of the target's class"] = true
L["Enable Automatically accepting/turning in Quests when not holding CTRL/SHIFT/ALT"] = true
L["You will automatically accept and turn in quests that do not require gold, are not weekly and are not daily"] = true
L["Accept Daily and Weekly quests"] = true
L["You will also automatically accept Daily and Weekly Quests"] = true
L["Invert CTRL/SHIFT/ALT"] = true
L["You will only accept and turn in quests if you hold CTRL/SHIFT/ALT while talking to the NPC"] = true
L["Quest Item Bar"] = true
L["Enable Quest Item Bar"] = true
L["Add a Quest Item bar, keybind can be changed in Keybinds > ElvUI Eltruism"] = true
L["Add a Quest Item bar, keybind can be changed in Key Bindings > ElvUI Eltruism"] = true
L["Quest Item Bar follows visibility settings for ElvUI Action Bar 1"] = true
L["The Quest Item Bar will appear only when ElvUI Action Bar 1 appears, following its settings"] = true
L["Quest Item Bar Button Mouse Over"] = true
L["Each Button in the Quest Item Bar will appear only if the cursor is over it"] = true
L["Quest Item Bar Button Size"] = true
L["Change the size of the button on the Quest Item Bar"] = true
L["Character Panel"] = true
L["Expand Character Art"] = true
L["Expand Character Panel"] = true
L["Add Crest to Character Panel"] = true
L["Art Alpha"] = true
L["Change the transparency of the Art"] = true
L["Add Class Icons to Character Panel"] = true
L["Enable this option"] = true
L["Use Blizzard Icons"] = true
L["Enable Blizzard Icons"] = true
L["Use Blizzard Icons colored by Releaf"] = true
L["Enable Releaf Icons"] = true
L["Add Shadows to Frames"] = true
L["Add Shadows to some frames"] = true
L["Enable General Shadows"] = true
L["Add Shadows to frames like Player, target, Chats and others"] = true
L["Other Shadows (can become CPU/Memory Intensive)"] = true
L["Nameplate Health"] = true
L["Add Shadows to Nameplate Healthbars"] = true
L["Nameplate Aura"] = true
L["Add Shadows to Nameplate Auras"] = true
L["Nameplate Portrait"] = true
L["Add Shadows to Nameplate Portraits"] = true
L["Nameplate Power"] = true
L["Add Shadows to Nameplate Powers"] = true
L["Nameplate Castbar"] = true
L["Add Shadows to Nameplate Castbars"] = true
L["Unitframe Aura"] = true
L["Add Shadows to Unitframe Auras"] = true
L["ActionBars"] = true
L["Add Shadows to Actionbars"] = true
L["Aura"] = true
L["Add Aura Shadows (Aura list next to the minimap)"] = true
L["Choose the Border Texture to be used:"] = true
L["Change the size of the borders:"] = true
L["Bar 1 X offset"] = true
L["Bar 1 Y offset"] = true
L["Bar 2 X offset"] = true
L["Bar 2 Y offset"] = true
L["Bar 3 X offset"] = true
L["Bar 3 Y offset"] = true
L["Bar 4 X offset"] = true
L["Bar 4 Y offset"] = true
L["Bar 5 X offset"] = true
L["Bar 5 Y offset"] = true
L["Bar 6 X offset"] = true
L["Bar 6 Y offset"] = true
L["How to use the Anchors"] = true
L["Open WeakAuras, go to your group Weakauras and in Group change Position Settings > Anchored To > Select Frame > EltruismWA or EltruismConsumables"] = true
L["Hide Quests during Battlegrounds and Arenas"] = true
L["Eltruism uses a 0.7 scale, but ElvUI can calculate the best scale for you using the Automatic Scale option"] = true
L["Very High (but Optional)"] = true
L['DPS\nTank'] = true
L['Healer'] = true
L['Automatic\nScale'] = true
L['Alternative\nFrames'] = true
L["Or change it later in Eltruism > Media options"] = true
L["Eltruism Modes"] = true
L["Eltruism uses Dark Mode and Transparent chat by default"] = true
L["You can switch to Light Mode and/or Dark Chat by clicking the buttons below"] = true
L["Transparent\nChat"] = true
L['Details! DPS Meter'] = true
L['Choose the type of icons Details! will use:'] = true
L['PVP/PVE Addons'] = true
L["Import GladiusEx profile for arenas, remember to disable ElvUI Arena Frames"] = true
L['GladiusEx'] = true
L["Import Questie profile, which uses the DBM radar"] = true
L["Questie"] = true
L["Import DBM or BigWigs profiles for dungeons and raids. (Uses DBM English Calanon and Bigwigs Voice)"] = true
L["Import Method Raid Tools profile with raid cooldowns and other settings"] = true
L["Import profiles for Gladdy"] = true
L["Gladdy is not installed or enabled (You can find the Gladius profile in Eltruism Settings)"] = true
L["Gladius profile can be found in Eltruism > Addons, please check it there"] = true
L["You have none of these addons installed or enabled"] = true
L["QOL Addons"] = true
L["Import a profile for Simpy's ElvUI FCT configured for Eltruism"] = true
L["Import a profile for NameplateSCT configured for Eltruism"] = true
L["NameplateSCT and ElvUI FCT are not installed or enabled"] = true
L["Shaman Totems"] = true
L["Enable on Shaman Totems"] = true
L["Enable on Shaman Fire Totem"] = true
L["Enable on Shaman Earth Totem"] = true
L["Enable on Shaman Water Totem"] = true
L["Enable on Shaman Air Totem"] = true
L["Shaman Fire Totem"] = true
L["Shaman Earth Totem"] = true
L["Shaman Water Totem"] = true
L["Shaman Air Totem"] = true
L["Use Type Colors"] = true
L["Grey Background"] = true
L["Black Background"] = true
L["DPS/Tank layouts were created with pure dps classes in mind, if you play a class with more raid cooldowns like a Shaman, Druid or Paladin you might want to use the alternative layout in order to make it easier for you to use your cooldowns on the members of your group"] = true
--didnt export earlier
L["Use Type Colors"] = true
L["Grey Background"] = true
L["Black Background"] = true
L["Show Buffs in Arena and hide them outside (will overwrite Eltruism default settings)"] = true
L["Hide Arena Frames in Arena due to Gladius/Gladdy or another addon"] = true
L["Hide Raid Unitframes in battlegrounds due to addons like Battleground Enemies"] = true
L["Hide Arena Frames in Arena due to Gladius/GladiusEX or another addon"] = true
L["Enable Combat Music"] = true
L["Disable in Battlegrounds/Arenas"] = true
L["Nameplate Power Bar"] = true
L["Nameplate Powerbar Position"] = true
L["Nameplate Powerbar Size"] = true
L["Nameplate Powerbar Position"] = true
L["Background Color"] = true
L["Skin Objective Frame"] = true
L['Enable Wowhead Button'] = true
L["Skin Profession Frame"] = true
L["Skin the Profession/Tradeskill Frame"] = true
L["Sockets and Enchants"] = true
L["Add Sockets and Enchants to the Character Panel"] = true
L["Item Levels"] = true
L["Ilvl Anchor Point"] = true
L["Choose where the Ilvl will be attach to on the items"] = true
L["Ilvl Font Outline"] = true
L["Choose the Ilvl font outline"] = true
L["Automatically swap the Character Stats to your main ones"] = true
L["Add Item Levels to the Character Panel"] = true
L["You can support the group with your class, if you select DPS/Tank then its recommended to click Alternative Frames after clicking DPS/Tank"] = "Du kannst die Gruppe mit deiner Klasse unterstützen! Wenn du DPS/Tank wählst dann wird Empfohlen auf Alternative Frames zu klicken nachdem du auf DPS/Tank geklickt hast"
L["And has many plugins to choose from"] = "Es gibt viele Plugins zur Auswahl"
L["Enable a GTA death animation"] = true
L["Import profiles for Gladius"] = "Importiere Profile für Gladius"
L["Import profiles for Gladdy"] = "Importiere Profile für Gladdy"
L["Both Gladdy and Gladius are not installed or enabled"] = "Gladdy und Gladius sind nicht Installiert oder Aktiviert"
L["Open Eltruism Configuration Panel"] = true
L['Enable for Error Frame'] = true
L['Enable for Boss Emote Frame'] = true
L['Enable for Zones, Mail and others'] = true
L["Only loads when Questie is not enabled"] = true
L["Customize Unitframe textures"] = true
L["Choose custom textures for some unitframes"] = true
L["Enable Custom Textures"] = true
L["Player Texture"] = true
L["Target of Target Texture"] = true
L["Focus Texture"] = true
