-- German localization
local L = ElvUI[1].Libs.ACL:NewLocale("ElvUI", "deDE", true, true)
if not L then return end
-- Core
L["4K resolution detected, setting fonts to default mode."] = "4K Auflösung erkannt, Schrift wird auf Standard gesetzt."
L["1440p resolution detected, setting fonts to outline mode."] = "1440p Auflösung erkannt, die Schrift wird auf Kontur gesetzt."
L["1080p resolution detected, setting fonts to outline mode."] = "1080p Auflösung erkannt, die Schrift wird auf Kontur gesetzt."
L["Fonts were set to Outline due to your resolution."] = "Schriftarten werden auf Kontur gesetzt aufgrund Ihrer Auflösung."
L["EltruismConsumables"] = true
--Install
L["General CVars have been set."] = "General CVars wurden geladen."
L["NamePlate CVars have been set."] = "NamePlate CVars wurden geladen."
L["AddOnSkins profile has been set."] = "AddOnSkins Profil wurde geladen."
L["Immersion profile has been set."] = "Immersion Profil wurde geladen."
L["BigWigs profile has been set."] = "BigWigs Profil wurde geladen."
L["DBM profile has been set."] = "DBM Profil has wwurde geladen."
L["Details profile has been set."] = "Details Profil wurde geladen."
L["Dynamic Cam profile has been set."] = "Dynamic Cam Profil wurde geladen."
L["GladiusEx profile has been set."] = "GladiusEx Profil wurde geladen."
L["Method Raid Tools profile has been set."] = "Method Raid Tools Profil wurde geladen."
L["ProjectAzilroka profile has been set."] = "ProjectAzilroka Profil wurde geladen."
L["Questie profile has been set."] = "Questie Profil wurde geladen."
L["NameplateSCT profile has been set."] = "NameplateSCT Profil wurde geladen."
L["Floating Combat Text profile has been set."] = "Floating Combat Text Profil wurde geladen."
L["Gladius profile has been set."] = "Gladius Profi wurde geladen."
L["Gladdy profile has been set."] = "Gladdy Profil wurde geladen."
L["Area does not support waypoints"] = "Gebiet unterstützt keine Wegpunkte"
L["Unsupported format"] = "Nicht unterstütztes Format"
L["Unsupported format or Area does not support waypoints"] = "Nicht unterstütztes Format oder Gebiet unterstützt keine Wegpunkte"
L["WARNING"] = "WARNUNG"
L["Make sure to install "] = "Vergewissere dich, dass Installiert wird "
L["Shadow and Light"] = true
L[" and "] = " und "
L["WindTools"] = true
L[" before starting this installation process"] = " bevor die Installation gestartet wird"
L["Curse doesn't allow selective dependencies for addons when it comes to World of Warcraft versions"] = "Curse akzeptiert keine ausgewählten Abhängigkeiten wenn es um World of Warcraft Versionen geht"
L[" are required for Retail but not Classic that's why you are seeing this screen"] = " wird für Retail benötigt, nicht für Classic, deshalb siehst du diesen Screen"
L["Download them before continuing"] = "Downloade es bevor du weitermachst"
L[" before starting this installation process"] = " bevor du den Installationprozess startest"
L["AddOnSkins"] = true
L["ProjectAzilroka"] = true
L["This prompt will help you install "] = "Diese Eingabeaufforderung wird dir beim Installieren helfen "
L[" and import its settings"] = " und seine Einstellungen importieren"
L["Please read the instructions to avoid issues"] = "Bitte lese die Instruktionen um Fehler zu vermeiden"
L["Skip Install"] = "Überspringe Installtion"
L["Layouts"] = true
L["Please select the role for your character, which will create a new profile"] = "Bitte wähle die Rolle deines Charakters für welches ein Profil erstellt wird"
L["This process can take a few seconds"] = "Dieser Prozess dauert ein paar Sekunden"
L["You can support the group with your class, if you select DPS/Tank then its recommended to click Alt Frames after clicking DPS/Tank"] = "Du kannst die Gruppe mit deiner Klasse unterstützen! Wenn du DPS/Tank wählst dann wird Empfohlen auf Alt Frames zu klicken nachdem du auf DPS/Tank geklickt hast"
L["Importance: "] = "Wichtig: "
L["Very High"] = true
L["Fonts"] = true
L["Eltruism uses Kimberley as the default font"] = "Eltruism benutzt Kimberley als Standard Schrift"
L["You can replace it with one of the following:"] = "Du kannst sie durch eine der folgenden Möglichkeiten ersetzen:"
L["Optional"] = true
L["Import GladiusEx profile, remember to disable ElvUI Arena Frames"] = "Importiert GladiusEx Profil, Vergesse nicht ElvUI Arena Frames zu deaktivieren"
L["You will need to change the profile in /gex profile options"] = "Du musst das Profil unter /gex Profil in Optionen ändern"
L["Your current settings will be lost, please back them up"] = "Die aktuellen Einstellungen gehen verloren, bitte sichere sie"
L["Import "] = "Importieren "
L["GladiusEx adds many features not available on Elvui Arena frames"] = "GladiusEx fügt viele Features in Elvui Arena Frames hinzu"
L["Such as diminishing cooldowns, enemy cast tracker, cooldown tracker"] = "Wie zum Beispiel die Diminishing Cooldowns, Enemy Cast Tracker, Cooldown Tracker"
L["Import Details! profile with dual panels"] = "Importiere Details! Profil mit zwei panels"
L["You can right click the bottom right arrow to toggle the Details! Window"] = "Du kannst mit der rechten Maustaste auf den Pfeil unten rechts klicken, um das Fenster Details! umzuschalten"
L["Remember to swap the second window to Healing Done or Tiny Threat"] = "Vergiss nicht das zweite Fenster auf Healing Done oder Tiny Threat zu stellen"
L["Make sure to run Details! install before importing"] = "Stelle sicher, dass du Details! installiert hast bevor du importierst"
L["Details is an advanced combat parser"] = "Details ist ein erweiterter Kampf Parser"
L["It uses less memory and is more efficient than alternatives"] = "Details benötigt wenig Speicher und ist effizenter als andere Alternativen"
L["And has many plugins to choose from"] = "Und hat viele Plugins zur Auswahl"
L["Boss Mods"] = true
L["Import DBM or Bigwigs profiles"] = "Importiere DBM oder Bigwigs Profile"
L["These profiles are setup with DBM English Calanon and Bigwigs Voice"] = "Diese Profile werden mit DBM English Calanon und Bigwigs Voice eingerichtet"
L["Your current settings will be lost with overwrite, please back them up"] = "Die aktuellen Einstellungen werden Überschrieben, bitte vorher sichern"
L["DBM is not installed or enabled so BigWigs will be used"] = "DBM ist nicht Installiert oder Aktiviert, es wird BigWigs benutzt"
L["BigWigs uses BigWigs voice in its profile"] = "BigWigs benutzt BigWigs Voice in seinem Profil"
L["BigWigs is not installed or enabled so DBM will be used"] = "BigWigs ist nicht Installiert oder Aktiviert, es wird DBM benutzt"
L["DBM uses DBM English by Calanon as a voice pack"] = "DBM benutzt DBM Englisch by Calanon als voice pack"
L["Both DBM and BigWigs are not installed or enabled"] = "DBM und BigWigs sind nicht Installiert oder Aktiviert"
L["No boss mods found"] = "Es wurden keine Boss Mods gefunden"
L["Boss mods are highly recommended for modern encounters"] = "Boss Mods sind für den aktuellen Content sehr empfohlen"
L["MRT Raid Tools"] = true
L["Import MRT profile with raid cooldowns and other settings"] = "Importiert MRT Profil mit Raid Cooldowns und anderen Einstellungen"
L["You will need to swap to this profile in MRT"] = "Du musst dieses Profiel in MRT dann auswählen"
L["Overwrite"] = "Überschreiben"
L["Copy"] = "Kopieren"
L["MRT is a suite of tools for raiding"] = "MRT ist ein Tolles zum Tool zum Raiden"
L["Includes tracking raid cooldowns and creating notes"] = "Trackt Raid Cooldowns und man kann Notizen erstellen"
L["Alongside attendance and other features"] = "Sowie die Raidanwesenheit überprüfen und viele andere Features"
L["Combat Text"] = "Kampftext"
L["Import profiles for NameplateSCT or ElvUI Floating Combat Text"] = "Importiere Profil für NameplateSCT oder ElvUI Floating Combat Text"
L["FCT profile will be used"] = "FCT Profil wird benutzt"
L["NameplateSCT profile will be used"] = "NameplateSCT Profil wird benutzt"
L["Combat text addons enhance the default Blizzard Combat Text"] = "Kampftext Addons verbessern/erweitern den Standard Blizzard Kampftext"
L["NameplateSCT and FCT make the combat text float from the nameplate/frame"] = "NameplateSCT und FCT werden am Namplate angezeigt"
L["And add effects to them with minimal memory usage"] = "Und fügt Effekte mit wenig Speicher verbrauch hinzu"
L["settings configured for "] = "einstellungen konfiguriert für "
L[" is not installed or enabled"] = " ist nicht Installiert oder Aktiviert"
L["NameplateSCT and FCT are not installed or enabled"] = "NameplateSCT und FCT sind nicht Installiert oder Aktiviert"
L["Immersion is an addon that changes the quest dialog with npcs"] = "Immersion ist ein Addon welches die Quest Dialoge mit NPC's ändert"
L["It transforms them into a talking head with dialog options on the side"] = "Er verwandelt sie in einen sprechenden Kopf mit Dialogoptionen an der Seite"
L["Including the ability to press number keys to select an option"] = "Einschließlich der Möglichkeit, Zifferntasten zu drücken, um eine Option auszuwählen"
L["Import Dynamic Cam profile"] = "Importiere Dynamic Cam Profil"
L["You might need to swap profiles in DynamicCam settings"] = "Eventuell musst du die Profile in DynamicCam Einstellungen Austauschen"
L["DynamicCam is addon that modifies the behavior of the camera"] = "DynamicCam ist ein Addon welches das Verhalten der Kamera ändert"
L["The profile uses some effects while questing"] = "Das Profil verwendet einige Effekte während des Questen"
L["But in instances the effects are disabled"] = "Aber in Instanzen sind sie Deaktiviert"
L["Welcome"] = "Willkommen"
L["Join the Discord if you have any questions or issues (English Support)"] = "Join unseren Discord wenn du irgendwelche Fragen oder Probleme hast(English Support)"
L["Installation Complete"] = "Installation Abgeschlossen"
L["You have completed the installation process, please click Finished to reload the UI"] = "Du hast die Installation Abgeschlossen, klicke bitte auf Finish Button zum reloaden der UI"
L["Finished"] = true
L["Import Questie profile"] = "Importiert Questie Profil"
L["You will need to reload and wait for questie to rebuild the database"] = "Du musst Reloaden und warten bis Questie's Database neu erstellt wurde"
L["Questie is not installed or enabled"] = "Questie ist nicht Installiert oder Aktiviert"
L["Questie is an addon that modifies the objective tracker"] = "Questie ist ein Addon, dass das Questfenster modifiziert"
L["As such Questie adds a lot of features to it not available by default"] = "Questie fügt eine Reihe von Funktionen hinzu, die Standardmäßig nicht verfügbar sind"
L["Including TomTom support"] = "Enthält TomTom Support"
L["Arenas"] = "Arena"
L["Import profiles for Gladius or Gladdy"] = "Importiere Profile für Gladius oder Gladdy"
L["You might need to swap profiles to Eltreum in their settings"] = "Möglicherweise musst du das Profil wechseln in Eltreum's Einstellungen"
L["Gladius is not installed or enabled"] = "Gladius ist nicht Installiert oder Aktiviert"
L["Gladdy profile will be used"] = "Gladdy Profil wird benutzt"
L["Gladdy is not installed or enabled"] = "Gladdy ist nicht Installiert oder Aktiviert"
L["Gladius profile will be used"] = "Gladius Profil wird benutzt"
L["Gladdy and Gladius are not installed or enabled"] = "Gladdy und Gladius sind nicht Installiert oder Aktiviert"
L["Arena unitframes enhance the default Blizzard unitframes"] = "Arena Unitframes erweitert die Standard Blizzard Unitframes"
L["Giving them additional features like DR tracking, trinket tracking, buffs and cooldowns"] = "Du erhältst zusätzliche Funktionen wie DR Tracking, Trinket Tracking, Buffs und Cooldowns"
L["Being used by players for many years since 2008"] = "Wird seit vielen Jahren von Spielern genutzt (2008)"
L["ElvUI NamePlates were setup."] = "ElvUI NamePlates sind eingerichtet worden."
L["NamePlate Style Filters were set."] = "NamePlate Style Filters sind eingerichtet worden."
L["Abbreviates the unit name once it goes over 16 characters, made by Azilroka"] = "Kürzt den Einheiten Namen sobald es über 16 Zeichen geht, made by Azilroka"
L["Shows Class Icons by Blizzard on all targets"] = "Zeigt Klassen Icons von Blizzard bei allen Zielen"
L["Shows Class Icons by Blizzard only on Player targets"] = "Zeigt Klassen Icons von Blizzard nur bei Spieler Zielen"
L["updated to "] = "aktualisiert auf "
L["Layout has been set."] = "Layout wurde gesetzt."
L["The alternative layout was made for the Eltruism DPS/Tank profile, please switch to it to use it"] = "Das Alternative Layout ist für das Eltruism DPS/Tank Profil gemacht, bitte switche zu diesen um es zu benutzen"
L["The original layout was made for the Eltruism DPS/Tank profile, please switch to it to use it"] = "Das Original Layout ist für das Eltruism DPS/Tank Profil gemacht, bitte switche zu diesen um es zu benutzen"
L["You need to be using an Eltruism profile in order to use this function"] = "Du musst ein Eltruismus-Profil verwenden, um diese Funktion nutzen zu können."
L["Debuff filters were setup"] = "Debuff Filter wurden eingestellt"
L["Buff filters were setup"] = "Buff Filter wurden eingestellt"
L["ElvUI Chat has been Set"] = "ElvUI Chat wurde festgelegt"
-- Datatext
L["Eltruism Ammo"] = true
-- Fonts
L["Your custom font has been set."] = "Deine benutzerdefinierte Schriftart wurde festgelegt."
L["Kimberley Font has been set."] = "Kimberley Font wurde eingestellt."
L["Exo2 Font has been set."] = "Exo2 Font wurde eingestellt."
L["GothamNarrow Black Font has been set."] = "GothamNarrow Black Font wurde eingestellt."
L["Roboto Font has been set."] = "Roboto Font wurde eingestellt."
--LootText
L["Soul Ash"] = true -- the currency exactly as it is in game, or the function will not work for the location
--Options
L["Installer"] = true
L["Reinstall the plugin to reset settings"] = "Installiere das Plugin neu, um die Einstellungen zurückzusetzen"
L["Install"] = "Installieren"
L["Reset nameplates to Eltruism settings"] = "Resetet Nameplates zu Eltruism Einstellungen"
L["A.F.K"] = true -- away from keyboard, can be longer in other languages
L["Play music while you are AFK"] = "Spielt Musik während du AFK bist"
L["Enable"] = "Aktivieren"
L["Cursor"] = true
L["Change the size of the World of Warcraft Cursor"] = "Änder die Größe des World of Warcraft Cursor"
L["Select a size"] = "Wähle eine Größe aus"
L["Choose this size"] = "Wählt diese Größe aus"
L["Autodetect"] = true
L["Add GCD, Cast and Combat indicator rings to the cursor"] = "Fügt ein GCD und ein Cast Ring zum Cursor hinzu"
L["Enable cooldown tracking"] = true
L["Add a cooldown icon when trying to use skills that are on cooldown, and a cooldown flash when they are ready"] = true
L["Enable cursor rings for Casts, GCD and Combat"] = "Aktiviert Cursor Ring für Zauber, GCD und Kampf"
L["Add a rings around the mouse cursor for GCD, casts and combat"] = "Fügt ein Ring für den GCD zum Mauszeiger hinzu, Zauber und Kampf"
L["Choose a type of cursor by clicking it"] = "Wähle ein Cursor Typ"
L["Currently selected cursor: "] = "Aktuell ausgewählter Cursor: "
L["Type 1"] = true
L["Type 2"] = true
L["Type 3"] = true
L["Type 4"] = true
L["Type 5"] = true
L["Type 6"] = true
L["Type 7"] = true
L["Type 8"] = true
L["Type 9"] = true
L["Type 10"] = true
L["The Cursor will use this type as its texture"] = "Der Cursor wird diesen Typ als Textur verwenden"
L["Cursor Colors "] = "Cursor Farbe "
L["Requires a Reload"] = "Benötigt ein Reload"
L["Class Colored Casts"] = "Klassengefärbter Zauber"
L["Use Class Colors for Cast"] = "Benutze Klassenfarbe für Zauber"
L["Custom Color Cast"] = "Individuelle Farbe für Zauber"
L["Class Colored GCD"] = "Klassengefärbter GCD"
L["Use Class Colors for GCD"] = "Benutze Klassenfarbe für GCD"
L["Custom Color GCD"] = "Individuelle Farbe für GCD"
L["Class Colored Combat"] = "Klassenfarbe Kampf"
L["Use Class Colors for Cursor"] = "Benutze Klassenfarbe für Cursor"
L["Custom Color Combat"] = "Individuelle Farbe für Kampf"
L["Cast Radius (Default: 25)"] = "Zauber Radius (Standard: 25)"
L["Set the radius of the cast cursor"] = "Radius des Zauber Cursors Einstellen"
L["Cast Thickness (Default: 5)"] = "Zauber Dicke (Standard: 5)"
L["GCD Radius (Default: 20)"] = "GCD Radius (Standard: 20)"
L["Set the radius of the gcd cursor"] = "Radius des GCD Cursor Einstellen"
L["GCD Thickness (Default: 5)"] = "GCD Dicke (Standard: 5)"
L["Set the thickness of the gcd cursor"] = "Wähle die Dicke des GCD Cursor"
L["Combat Cursor Radius (Default: 15)"] = "Kampf Cursor Radius (Standard: 15)"
L["Set the radius of the combat cursor"] = "Radius des Kampf Cursor"
L["Combat Cursor Thickness (Default: 5)"] = "Kampf Cursor Dicke (Standard: 5)"
L["Set the thickness of the combat cursor"] = "Wähle die Dicke des Kampf Cursor"
L["Aura Filters"] = true
L["For Shadowlands, import aura filters by copying the code below and going into Profiles > Import Profile."] = "Für Shadowlands, importiere Aura Filter indem du den Code unten kopierst und dann im Profil importierst > Importiere Profil."
L["Setup Aura Filters to show all"] = "Setze Aura Filter zu Zeige alle"
L["All Player Buffs"] = true
L["Set filters to show more buffs on Player"] = true
L["All Player Debuffs"] = true
L["Set filters to show more debuffs on Player"] = true
L["All Target Debuffs"] = true
L["Set filters to show more debuffs on Target"] = true
L["All Target Buffs"] = true
L["Set filters to show more buffs on Target"] = true
L["All Focus Buffs"] = true
L["Set filters to show more buffs on Focus"] = true
L["All Focus Debuffs"] = true
L["Set filters to show more debuffs on Focus"] = true
L["All Boss Buffs"] = true
L["Set filters to show more buffs on Boss"] = true
L["All Boss Debuffs"] = true
L["Set filters to show more debuffs on Boss"] = true
L["All Nameplate Buffs"] = true
L["Set filters to show more buffs on Nameplates"] = true
L["All Nameplate Debuffs"] = true
L["Set filters to show more debuffs on Nameplates"] = true
L["Setup Aura Filters to be Eltruism/ElvUI defaults"] = true
L["Eltruism Player Buffs"] = true
L["Set filters to be Eltruism/ElvUI defaults on Player"] = true
L["Eltruism Player Debuffs"] = true
L["Eltruism Target Debuffs"] = true
L["Set filters to be Eltruism/ElvUI defaults on Target"] = true
L["Eltruism Target Buffs"] = true
L["Eltruism Focus Buffs"] = true
L["Set filters to be Eltruism/ElvUI defaults on Focus"] = true
L["Eltruism Focus Debuffs"] = true
L["Eltruism Boss Buffs"] = true
L["Set filters to be Eltruism/ElvUI defaults on Boss"] = true
L["Eltruism Boss Debuffs"] = true
L["Eltruism Nameplate Buffs"] = true
L["Set filters to be Eltruism/ElvUI defaults on Nameplates"] = true
L["Eltruism Nameplate Debuffs"] = true
L["Addons"] = true
L["ElvUI Plugins"] = true
L["Reset to Eltruism defaults."] = true
L["BossMods Profiles"] = true
L["Addon Profiles"] = true
L["Combat Music"] = true
L["Play music during combat"] = true
L["Enable music during combat"] = true
L["Disable in Instances"] = true
L["Disable music during combat in instances"] = true
L["Path to file"] = true
L["Example: "] = true
L["CVars"] = true -- i dont know if this gets localized
L["Setup CVars"] = true
L["General CVars"] = true
L["It will set these CVars:"] = true
L["Party/Raid"] = true
L["Play a sound when someone dies in Party or Raid"] = true
L["Select a Sound"] = true
L["Alternative unitframe layouts"] = true
L["DPS/Tank layouts were created with pure dps classes in mind, if you play a class with more raid cooldowns like a Shaman, Druid or Paladin you might want to use the alternative layout in order to make it easier for you to use your cooldowns on the members of your group"] = true
L["Alternative Layout"] = true
L["Original Layout"] = true
L["Media"] = true
L["Setup Media"] = true
L["Reset all Media"] = true
L["Reset Fonts, Textures, Skins to Eltreum UI defaults."] = true
L["Set the fonts used in Eltruism. Kimberley is the default font"] = true
L["This will set all ElvUI fonts as Kimberley"] = true
L["This will set all ElvUI fonts as Exo2"] = true
L["This will set all ElvUI fonts as Gotham"] = true
L["This will set all ElvUI fonts as Roboto"] = true
L["Or choose a custom font"] = true
L["Choose a different font from the preselected ones"] = true
L["Set the Font Outlines everywhere. Use Default to return to Eltruism default settings"] = true
L["Defaults"] = true
L["This will set fonts to Eltruism defaults, recommended for 4K"] = true
L["None"] = true  --as in no font outline
L["This will set fonts to no outline"] = true
L["Outline"] = true
L["This will set fonts to use outline, recommended for 1440p and 1080p"] = true
L["Thick Outline"] = true
L["This will set fonts to use thick outline"] = true
L["Change the look of frames to Dark or Light mode"] = true
L["Dark Mode"] = true
L["This will set colors to black with class colors when losing health"] = true
L["Light Mode"] = true
L["This will set colors to class based with black backgrounds when losing health"] = true
L["Dynamic Datatext that changes according to class to show Ammo or Soul Shards when playing Hunter, Warrior, Rogue or Warlock"] = true
L["Enable the Dynamic Datatext"] = true
L["Expand the Talents to show the entire tree"] = true
L["Expanded Talents"] = true
L["Expand Talents to cover the full tree"] = true
L["Nameplates"] = true
L["Class Colored Nameplate Options"] = true
L["Hover"] = true
L["Change the color of the hover to be class colored"] = true
L["Border"] = true
L["Change the color of the border glow to be class bordered in nameplates"] = true
L["Target Texture"] = true
L["Change the texture of the nameplate to be a class gradient"] = true
L["Control how Nameplates behave"] = true
L["Show Friendly Nameplates but Hide Healthbar"] = true
L["Hide Friendly Nameplates inside Instances"] = true
L["Hide Friendly Nameplates everywhere"] = true
L["Wide nameplate debuffs and buffs"] = true
L["Make Buffs and Debuffs Wide on Nameplates"] = true
L["Toggle On and Off"] = true
L["Enemy Nameplate Level"] = true
L["Hide level on enemy nameplates when you are max level"] = true
L["Nameplate Power Bar"] = true
L["Enable Nameplate Power Bar"] = true
L["Enable an extra Power Bar on Nameplates for missing powers"] = true
L["Enable Autoadjusting Buffs/Debuffs"] = true
L["Enable autoadjusting the position of Buffs/Debuffs"] = true
L["Enable Autoadjusting the Vertical Position of the Power Bar"] = true
L["Power Bar will move automatically based on class/spec/druid form"] = true
L["Select the Y Offset for the Power Bar (Default 16)"] = true
L["Set Y Offset"] = true
L["Select the Horizontal Size of the Power Bar (Default 132)"] = true
L["Set Horizontal Size"] = true
L["Select the Vertical Size of the Power Bar (Default 6)"] = true
L["Set Vertical Size"] = true
L["Choose the Power Bar Texture"] = true
L["Select a Texture"] = true
L["Select the power types to be displayed:"] = true
L["Mana"] = true
L["Rage"] = true
L["Energy"] = true
L["Loot"] = true
L["Show a floating loot text"] = true
L["Choose which types of text:"] = true
L["Honor"] = true
L["Currency"] = true
L["Pets"] = true
L["Change the scale of LootText"] = true
L["Set the size of LootText"] = true
L["Reset Scale"] = true
L["Return LootText to its default scale"] = true
L["Change the strata of the Loot Text"] = true
L["Set the level that LootText will be drawn to this"] = true
L["Background"] = true
L["Low"] = true
L["Medium"] = true
L["High"] = true
L["Dialog"] = true
L["Change the Horizontal Position of LootText (Default = 0)"] = true
L["Set X offset"] = true
L["Change the Vertical Position of LootText (Default = 200)"] = true
L["Set Y offset"] = true
L["Change the font of LootText to be that the ElvUI Default Font found in General"] = true
L["Use ElvUI General Font"] = true
L["Change the font of LootText"] = true
L["Chat"] = true
L["Chat Options"] = true
L["Enable ElvUI Chat modifications"] = true
L["Add fade over time, and mouse over to left and right chat panels"] = true
L["Add mouse over to the left chat panel"] = true
L["Left Chat Mouse Over"] = true
L["Toggle the option"] = true
L["Add a fade to the left chat panel, controlled by ElvUI Chat > Text Fade > Inactivity Timer"] = true
L["Left Inactivity Fader"] = true
L["Add mouse over to the left chat panel"] = true
L["Right Chat Mouse Over"] = true
L["Add a fade to the right chat panel, controlled by ElvUI Chat > Text Fade > Inactivity Timer"] = true
L["Right Inactivity Fader"] = true
L["Combat Hide"] = true
L["Hide Left Chat in Combat"] = true
L["Hide Right Chat in Combat"] = true
L["Invert left mouse click so that chat starts faded and mouse click will make it stop fading"] = true
L["Invert Mouse Click"] = true
L["Toggle the option on"] = true
L["Stealth Vignette"] = true
L["Toggle a Stealth Effect"] = true
L["Add a vignette effect while in stealth"] = true
L["Turn the effect on"] = true
L["You can set your Weakauras to anchor to custom locations making it easier to move them"] = true
L["In order to use this feature, simply go to your Weakaura, and go to its Group options, scroll down to Position Settings and set the Anchored To Select Frame, then type either |cff82B4ffEltruismWA|r or |cff82B4ffEltruismConsumables|r to anchor the weakaura to the preset location"] = true
L["Setting "] = true
L[" or "] = true
L[" as the anchor will move them to the locations, keep in mind you might need to change the X and Y offset of the weakaura to zero"] = true
L["My WeakAuras are available here, but are not focused on one class. Consider them more like upcoming features."] = true
L["All weakauras"] = true
L["Nameplate Power Bar"] = true
L["Boss nameplate at base"] = true
L["Executes next to nameplates"] = true
L["Join the Discord if you have any questions or issues"] = true
L["Keep in mind the discord is in English"] = true
L["Changelog"] = true
L["Select a version:"] = true
L["Choose a version to see its changelog"] = true
L["Credits"] = true
L["Author"] = true
L["Credits and Thank yous"] = true
L["License"] = true
L["Support"] = true
L["New commits, basically a preview of fixes or upcoming features"] = true
L["Report issues and problems here:"] = true
L["Addon on Tukui:"] = true
L["Addon on CurseForge:"] = true
L["Custom Glow"] = true
L["Replace Blizzards Default Glow with a Custom Glow"] = true
L["Select a Type"] = true
L["Autocast"] = true
L["Pixel"] = true
L["Blizzard"] = true  -- the company not the weather effect
L["Adds a Blizzard style glow using class color"] = true
L["Glow Colors"] = true
L["Use Class Colors"] = true
L["Toggle Class Colored glows"] = true
L["Custom Color"] = true
L["Pixel Glow"] = true
L["Pixel Border"] = true
L["Enable a border for the Pixel Glow"] = true
L["Number of Pixels (Default is 9)"] = true
L["Set the number of pixels in pixel glow"] = true
L["Pixel Frequency (Default is 1)"] = true
L["Set the frequency pixel glow"] = true
L["Pixel Length (Default is 3)"] = true
L["Set the length of pixels"] = true
L["Pixel Thickness (Default is 5)"] = true
L["Set the thickness of pixels"] = true
L["Pixel Horizontal Offset (Default is 5)"] = true
L["Set the horizontal offset of pixels"] = true
L["Pixel Vertical Offset (Default is 5)"] = true
L["Set the vertical offset of pixels"] = true
L["Autocast Glow"] = true
L["Autocast Particle Groups (Default is 8)"] = true
L["Set the number of groups for autocast, for each group you get 4 particles"] = true
L["Autocast Frequency (Default is 0.8)"] = true
L["Speed for Autocast, set to negative to inverse direction of rotation"] = true
L["Autocast Scale (Default is 2)"] = true
L["Change the size of Autocast"] = true
L["Autocast Horizontal Offset (Default is 5)"] = true
L["Set the horizontal offset of autocast"] = true
L["Autocast Vertical Offset (Default is 5)"] = true
L["Set the vertical offset of autocast"] = true
L["Blizzard Glow"] = true
L["Blizzard Frequency (Default is 0.5)"] = true
L["Speed for Blizzard glow"] = true
L["Quests"] = true
L["Collapse Quests during Encounters/Boss Fights"] = true
L["Collapse Quests when the boss fight starts"] = true
L["Maps"] = true
L["Add a time to arrive below the waypoint"] = true
L["The time will be calculated based on player speed and distance"] = true
L["If the player is not moving then *** will show up since time cannot be calculated"] = true
L["If you move away from the waypoint the time will just increase"] = true
L["Add an ETA to waypoints"] = true  --translation note: eta means estimated time to arrive
L["Enable the /way and /waypoint commands"] = true  -- do not translate /way and /waypoint since the commands are not translated
L["You can type /way or /waypoint"] = true  -- do not translate /way and /waypoint since the commands are not translated
L["Use formats such as:"] = true
L["XX YY, XX.XX YY.YY, XX,XX YY,YY and XXX YYY"] = true
L["Other Formats can end up causing errors"] = true
L["Enable the /way and /waypoint commands"] = true -- do not translate /way and /waypoint since the commands are not translated
L["Astral power"] = true
L["Runic power"] = true
L["Insanity"] = true
L["Maelstrom"] = true
L["Fury"] = true
L["Focus"] = true
L["Select a type of music"] = true
L["Racial Music"] = true
L["Class Music"] = true
L["Skin Level Up, Boss Loot and Instance Entrance frames to be class colored"] = true
L["Enable the Skins"] = true
L["Expand Hunter Stables to show all pets and improve search"] = true
L["Enable the Expanded Stable"] = true
L["Expand Transmog Window to better show your character"] = true
L["Enable the Wider Transmog Window"] = true
L["Auto open the Rogue Order Hall, to avoid opening hold CTRL or SHIFT or ALT while talking to the NPC"] = true
L["Enable the Rogue Order Hall Auto Open"] = true
L["Enable Floating Reputation Changes"] = true
L["Enable the Floating Rep Text"] = true
L["Buffs have been updated for Open World"] = true
L["Buffs have been updated for Arenas"] = true
