-- DeepL esMX translation
--local L = LibStub("AceLocale-3.0"):NewLocale("ElvUI_EltreumUI", "esES")
local L = ElvUI[1].Libs.ACL:NewLocale("ElvUI", "esES")
if not L then return end

L[" and "] = "y"
L[" and import its settings"] = "e importar su configuración"
L[" as the anchor will move them to the locations keep in mind you might need to change the X and Y offset of the weakaura to zero"] = "como el ancla los moverá a las ubicaciones tenga en cuenta que podría necesitar cambiar el desplazamiento X e Y de la weakaura a cero"
L[" is not installed or enabled"] = "no está instalado o habilitado"
L[" or "] = "o"
L["1080p resolution detected setting fonts to outline mode."] = "Se ha detectado una resolución de 1080p y se ha establecido el modo de contorno de las fuentes."
L["1440p resolution detected setting fonts to outline mode."] = "Se ha detectado una resolución de 1440p y se ha configurado el modo de contorno de las fuentes."
L["4K resolution detected setting fonts to default mode."] = "Se ha detectado la resolución 4K y se ha establecido el modo de fuentes por default."
L["A.F.K"] = true
L["Abbreviates the unit name once it goes over 16 characters made by Azilroka"] = "Abrevia el nombre de la unidad cuando supera los 16 caracteres hecho por Azilroka"
L["Add a cooldown icon when trying to use skills that are on cooldown and a cooldown flash when they are ready"] = "Añadir un icono de enfriamiento cuando se intenta utilizar habilidades que están en enfriamiento y un flash de enfriamiento cuando están listos"
L["Add a fade to the left chat panel controlled by ElvUI Chat > Text Fade > Inactivity Timer"] = "Añade un desvanecimiento al panel izquierdo del chat controlado por ElvUI Chat > Desvanecimiento de texto > Temporizador de inactividad"
L["Add a fade to the right chat panel controlled by ElvUI Chat > Text Fade > Inactivity Timer"] = "Añade un desvanecimiento en el panel derecho del chat controlado por ElvUI Chat > Desvanecimiento de texto > Temporizador de inactividad"
L["Add a rings around the mouse cursor for GCD casts and combat"] = "Añadir un anillo alrededor del cursor del ratón para GCD lanzamientos y combate"
L["Add a time to arrive below the waypoint"] = "Añade una hora de llegada debajo del waypoint"
L["Add a vignette effect while in stealth"] = "Añadir un efecto de viñeta mientras se está en sigilo"
L["Add an ETA to waypoints"] = "Añadir una ETA a los waypoints"
L["Add fade over time and mouse over to left and right chat panels"] = "Añadir desvanecimiento en el tiempo y el ratón sobre los paneles de chat de la izquierda y la derecha"
L["Add GCD Cast and Combat indicator rings to the cursor"] = "Añadir anillos indicadores de GCD Cast y Combate al cursor"
L["Add mouse over to the left chat panel"] = "Añadir mouse over al panel de chat de la izquierda"
L["Addon on CurseForge:"] = "Addon en CurseForge:"
L["Addon on Tukui:"] = "Addon en Tukui:"
L["Addon Profiles"] = "Perfiles de los addons"
L["Addons"] = true
L["AddOnSkins"] = true
L["AddOnSkins profile has been set."] = "El perfil de AddOnSkins ha sido establecido."
L["Adds a Blizzard style glow using class color"] = "Añade un resplandor estilo Blizzard usando el color de la clase"
L["All Boss Buffs"] = "Todos los Buffs de los Jefes"
L["All Boss Debuffs"] = "Todos los Debuffs de los Jefes"
L["All Focus Buffs"] = "Todos los Buffs de enfoque"
L["All Focus Debuffs"] = "Todos los Debuffs de enfoque"
L["All Nameplate Buffs"] = "Todos los Buffs de las placas de identificación"
L["All Nameplate Debuffs"] = "Todos los Debuffs de las placas de identificación"
L["All Player Buffs"] = "Todos los Buffs de los jugadores"
L["All Player Debuffs"] = "Todos los Debuffs de los jugadores"
L["All Target Buffs"] = "Todos los Buffs de objetivo "
L["All Target Debuffs"] = "Todos los Debuffs de objetivo "
L["All weakauras"] = "Todas las weakauras"
L["Alternative Layout"] = "Disposición alternativa"
L["Alternative unitframe layouts"] = "Disposiciones alternativas del marco de la unidad"
L["And has many plugins to choose from"] = "Y tiene muchos plugins para elegir"
L["Area does not support waypoints"] = "La zona no admite waypoints"
L["Arenas"] = true
L["Astral power"] = "Poder astral"
L["Aura Filters"] = "Filtros Aura"
L["Author"] = "Autor"
L["Auto open the Rogue Order Hall to avoid opening hold CTRL or SHIFT or ALT while talking to the NPC"] = "Abrir automáticamente la Sala de la Orden de los Pícaros para evitar que se abra mantener CTRL o SHIFT o ALT mientras se habla con el NPC"
L["Autocast"] = true
L["Autocast Frequency (Default is 0.8)"] = "Autocast Frecuencia (El valor predeterminado es 08)"
L["Autocast Glow"] = "brillo de Autocast"
L["Autocast Horizontal Offset (Default is 5)"] = "Desplazamiento horizontal de la Autocast (El valor predeterminado es 5)"
L["Autocast Particle Groups (Default is 8)"] = "Grupos de partículas de Autocast (El valor predeterminado es 8)"
L["Autocast Scale (Default is 2)"] = "Escala de Autocast (El valor predeterminado es 2)"
L["Autocast Vertical Offset (Default is 5)"] = "Desplazamiento vertical de Autocast (El valor predeterminado es 5)"
L["Autodetect"] = "Autodetección"
L["Background"] = "Fondo"
L["BigWigs is not installed or enabled so DBM will be used"] = "BigWigs no está instalado o habilitado por lo que se utilizará DBM"
L["BigWigs profile has been set."] = "El perfil de BigWigs ha sido fijado."
L["Blizzard"] = true
L["Blizzard Frequency (Default is 0.5)"] = "Frecuencia de Blizzard (El valor predeterminado es 05)"
L["Blizzard Glow"] = "brillo de Blizzard"
L["Border"] = "Frontera"
L["Boss Mods"] = "Mods del jefe"
L["Boss nameplate at base"] = "Placa de identificación del jefe en la base"
L["BossMods Profiles"] = "Perfiles de BossMods"
L["Both DBM and BigWigs are not installed or enabled"] = "Tanto DBM como BigWigs no están instalados o habilitados"
L["Buff filters were setup"] = "Se configuraron los filtros Buff"
L["Buffs have been updated for Arenas"] = "Se han actualizado los buffs para las arenas"
L["Buffs have been updated for Open World"] = "Se han actualizado los potenciadores para el mundo abierto"
L["Cast Radius (Default: 25)"] = "Radio de proyección (Predeterminado: 25)"
L["Cast Thickness (Default: 5)"] = "Espesor de la colada (Predeterminado: 5)"
L["Change the color of the border glow to be class bordered in nameplates"] = "Cambiar el color del resplandor del borde para ser clase de borde en las placas de identificación"
L["Change the color of the hover to be class colored"] = "Cambiar el color del hover para que sea del color de la clase"
L["Change the font of LootText"] = "Cambiar la fuente de LootText"
L["Change the font of LootText to be that the ElvUI Default Font found in General"] = "Cambia la fuente de LootText para que sea la fuente por defecto de ElvUI que se encuentra en General"
L["Change the Horizontal Position of LootText (Default = 0)"] = "Cambiar la posición horizontal de LootText (Predeterminado = 0)"
L["Change the look of frames to Dark or Light mode"] = "Cambiar el aspecto de los marcos a modo oscuro o claro"
L["Change the scale of LootText"] = "Cambiar la escala de LootText"
L["Change the size of Autocast"] = "Cambiar el tamaño del Autocast"
L["Change the size of the World of Warcraft Cursor"] = "Cambiar el tamaño del Cursor de World of Warcraft"
L["Change the strata of the Loot Text"] = "Cambiar los estratos del texto del botín"
L["Change the texture of the nameplate to be a class gradient"] = "Cambiar la textura de la placa de identificación para que sea un gradiente de clase"
L["Change the Vertical Position of LootText (Default = 200)"] = "Cambiar la posición vertical de LootText (Predeterminado = 200)"
L["Changelog"] = "Registro de cambios"
L["Chat"] = true
L["Chat Options"] = "Opciones de chat"
L["Choose a different font from the preselected ones"] = "Elija una fuente diferente de las preseleccionadas"
L["Choose a type of cursor by clicking it"] = "Elija un tipo de cursor haciendo clic en él"
L["Choose a version to see its changelog"] = "Elija una versión para ver su registro de cambios"
L["Choose the Power Bar Texture"] = "Elija la textura de la barra de energía"
L["Choose this size"] = "Elija esta talla"
L["Choose which types of text:"] = "Elija qué tipos de texto:"
L["Class Colored Casts"] = "Casts de clase de color"
L["Class Colored Combat"] = "Combate de color de la clase"
L["Class Colored GCD"] = "Clase de color GCD"
L["Class Colored Nameplate Options"] = "Opciones de placas de color de la clase"
L["Class Music"] = "Música de clase"
L["Clear Details Tables"] = "Cuadros de Details claros"
L["Clear Details! Damage Meter tables to free up memory"] = "Borrar las tablas Details! Damage Meter para liberar memoria"
L["Click:"] = "Haz clic:"
L["Collapse Quests during Encounters/Boss Fights"] = "Colapsar las misiones durante los encuentros/luchas con jefes"
L["Collapse Quests when the boss fight starts"] = "Colapsar las misiones cuando se inicia la lucha contra el jefe"
L["Combat Cursor Radius (Default: 15)"] = "Radio del cursor de combate (Predeterminado: 15)"
L["Combat Cursor Thickness (Default: 5)"] = "Grosor del cursor de combate (Predeterminado: 5)"
L["Combat Hide"] = "Esconderse en combate"
L["Combat Music"] = "Música de combate"
L["Control how Nameplates behave"] = "Controla el comportamiento de las placas de identificación"
L["Copper"] = "Cobre"
L["Credits"] = "Créditos"
L["Credits and Thank yous"] = "Créditos y agradecimientos"
L["Crystalzcuhei Font has been set."] = "La fuente Crystalzcuhei ha sido fijada."
L["Currency"] = "Moneda"
L["Currently selected cursor: "] = "Cursor seleccionado actualmente:"
L["Cursor"] = true
L["Cursor Colors "] = "Colores del Cursor"
L["Custom Color"] = "Color personalizado"
L["Custom Color Cast"] = "Colocación de colores a medida"
L["Custom Color Combat"] = "Combate de colores personalizado"
L["Custom Color GCD"] = "Color personalizado GCD"
L["Custom Glow"] = "Brillo personalizado"
L["CVars"] = true
L["Dark Mode"] = "Modo oscuro"
L["DBM is not installed or enabled so BigWigs will be used"] = "DBM no está instalado o habilitado por lo que se utilizará BigWigs"
L["DBM profile has been set."] = "Se ha establecido el perfil DBM."
L["DBM uses DBM English by Calanon as a voice pack"] = "DBM utiliza DBM English de Calanon como paquete de voz"
L["Debuff filters were setup"] = "Se configuraron los filtros de debuff"
L["Defaults"] = "Predeterminados"
L["Details is an advanced combat parser"] = "Details es un analizador de combate avanzado"
L["Details profile has been set."] = "Se ha establecido el perfil de los Details."
L["Dialog"] = "Diálogo"
L["Disable in Instances"] = "Desactivar en las instancias"
L["Disable music during combat in instances"] = "Desactivar la música durante el combate en las instancias"
L["DPS/Tank layouts were created with pure dps classes in mind if you play a class with more raid cooldowns like a Shaman Druid or Paladin you might want to use the alternative layout in order to make it easier for you to use your cooldowns on the members of your group"] = "Los diseños de DPS/Tanque fueron creados con las clases de dps puras en mente si juegas una clase con más cooldowns de raid como un Chamán Druida o Paladín puede que quieras usar el diseño alternativo para que sea más fácil para ti usar tus cooldowns en los miembros de tu grupo"
L["Dynamic Cam profile has been set."] = "Se ha configurado el perfil de la Dynamic Cam."
L["Dynamic Datatext that changes according to class to show Ammo or Soul Shards when playing Hunter Warrior Rogue or Warlock"] = "Texto de datos dinámico que cambia según la clase para mostrar la munición o los fragmentos de alma cuando se juega con un cazador un guerrero un pícaro o un brujo."
L["Eltruism Ammo"] = "Eltruism Munición"
L["Eltruism Boss Buffs"] = "Eltruismo Jefe Buffs"
L["Eltruism Boss Debuffs"] = "Eltruismo Jefe Debuffs"
L["Eltruism Config"] = "Configuración del Eltruism"
L["Eltruism Focus Buffs"] = "Eltruismo enfoque Buffs"
L["Eltruism Focus Debuffs"] = "Eltruismo enfoque Debuffs"
L["Eltruism Nameplate Buffs"] = "Eltruismo placa de identificación Buffs"
L["Eltruism Nameplate Debuffs"] = "Eltruismo placa de identificación Debuffs"
L["Eltruism Player Buffs"] = "Eltruism Jugador Buffs"
L["Eltruism Player Debuffs"] = "Eltruism Jugador Debuffs"
L["Eltruism Target Buffs"] = "Eltruism Objetivo Buffs"
L["Eltruism Target Debuffs"] = "Eltruism Objetivo Debuffs"
L["Eltruism uses Kimberley as the default font"] = "Eltruism utiliza Kimberley como fuente por defecto"
L["EltruismConsumables"] = true
L["ElvUI Chat has been set."] = "ElvUI Chat ha sido fijado."
L["ElvUI Plugins"] = "Plugins de ElvUI"
L["Enable"] = "Activar"
L["Enable a border for the Pixel Glow"] = "Habilitar un borde para el brillo de Pixel"
L["Enable an extra Power Bar on Nameplates for missing powers"] = "Habilitar una barra de energía adicional en las placas de identificación para las potencias que faltan"
L["Enable Auto-adjusting Buffs/Debuffs"] = "Activar el autoajuste de los Buffs/Debuffs"
L["Enable Auto-adjusting the position of Buffs/Debuffs"] = "Activar el ajuste automático de la posición de los Buffs/Debuffs"
L["Enable Auto-adjusting the Vertical Position of the Power Bar"] = "Habilitar el ajuste automático de la posición vertical de la barra de energía"
L["Enable cooldown tracking"] = "Activar el seguimiento del enfriamiento"
L["Enable cursor rings for Casts GCD and Combat"] = "Habilitar los anillos del cursor para los Casts GCD y Combate"
L["Enable ElvUI Chat modifications"] = "Habilitar las modificaciones de ElvUI Chat"
L["Enable Floating Reputation Changes"] = "Activar los cambios de reputación flotantes"
L["Enable music during combat"] = "Activar la música durante el combate"
L["Enable Nameplate Power Bar"] = "Habilitar la barra de potencia de la placa"
L["Enable the /way and /waypoint commands"] = "Habilitar los comandos /way y /waypoint"
L["Enable the Dynamic Datatext"] = "Habilitar el texto de datos dinámico"
L["Enable the Expanded Stable"] = "Habilitar el establo ampliado"
L["Enable the Floating Rep Text"] = "Habilitar el texto flotante del representante"
L["Enable the Rogue Order Hall Auto Open"] = "Activar la apertura automática de la sala de pedidos"
L["Enable the Skins"] = "Habilitar las skins"
L["Enable the Wider Transmog Window"] = "Activar la ventana de transmutación más amplia"
L["Enemy Nameplate Level"] = "Nivel de la placa del enemigo"
L["Energy"] = "Energía"
L["Example: "] = "Ejemplo:"
L["Executes next to nameplates"] = "Se ejecuta junto a las placas de identificación"
L["Exo2 Font has been set."] = "La fuente Exo2 ha sido fijada."
L["Expand Hunter Stables to show all pets and improve search"] = "Ampliar los establos de los cazadores para mostrar todas las mascotas y mejorar la búsqueda"
L["Expand Talents to cover the full tree"] = "Ampliar los talentos para cubrir todo el árbol"
L["Expand the Talents to show the entire tree"] = "Expandir los talentos para mostrar el árbol completo"
L["Expand Transmog Window to better show your character"] = "Ampliar la ventana de transmutación para mostrar mejor tu personaje"
L["Expanded Talents"] = "Talentos ampliados"
L["FCT profile will be used"] = "Se utilizará el perfil FCT"
L["Finished"] = "Terminado"
L["Floating Combat Text profile has been set."] = "Se ha establecido el perfil del texto de combate flotante."
L["Focus"] = "Enfoque"
L["Fonts"] = "Fuentes"
L["Fonts were set to Outline due to your resolution."] = "Las fuentes se han ajustado a Outline debido a su resolución."
L["For Shadowlands import aura filters by copying the code below and going into Profiles > Import Profile."] = "Para las Shadowlands importa los filtros de aura copiando el código de abajo y yendo a Perfiles > Importar Perfil."
L["Fury"] = "Furia"
L["GCD Radius (Default: 20)"] = "Radio de GCD (Predeterminado: 20)"
L["GCD Thickness (Default: 5)"] = "Grosor del GCD (Predeterminado: 5)"
L["General CVars"] = "CVars generales"
L["General CVars have been set."] = "Se han fijado los CVares generales."
L["General Layout has been set."] = "Se ha establecido la disposición general."
L["Gladdy profile has been set."] = "El perfil de Gladdy ha sido fijado."
L["Gladius profile has been set."] = "El perfil de Gladius ha sido fijado."
L["GladiusEx profile has been set."] = "El perfil de GladiusEx ha sido establecido."
L["Glow Colors"] = "Colores de brillo"
L["Gold"] = "Oro"
L["GothamNarrow Black Font has been set."] = "GothamNarrow Black Font se ha establecido."
L["Hide Friendly Nameplates everywhere"] = "Ocultar placas de identificación amigables en todas partes"
L["Hide Friendly Nameplates inside Instances"] = "Ocultar las placas de identificación de los amigos dentro de las instancias"
L["Hide Left Chat in Combat"] = "Ocultar el chat izquierdo en el combate"
L["Hide level on enemy nameplates when you are max level"] = "Ocultar el nivel en las placas de identificación de los enemigos cuando se tiene el nivel máximo"
L["Hide Right Chat in Combat"] = "Ocultar el chat derecho en el combate"
L["High"] = "Alta"
L["Honor"] = true
L["Hover"] = true
L["Hybrid"] = "Híbrido"
L["If the player is not moving then *** will show up since time cannot be calculated"] = "Si el jugador no se mueve aparecerá *** ya que no se puede calcular el tiempo"
L["If you move away from the waypoint the time will just increase"] = "Si te alejas del waypoint el tiempo sólo aumentará"
L["Immersion profile has been set."] = "Se ha configurado el perfil de Immersion."
L["Import "] = "Importar"
L["Import DBM or Bigwigs profiles"] = "Importar perfiles de DBM o Bigwigs"
L["Import Details! profile with dual panels"] = "Importar detalles! Perfil con paneles dobles"
L["Import Dynamic Cam profile"] = "Importar el perfil de la Dynamic Cam"
L["Import profiles for NameplateSCT or ElvUI Floating Combat Text"] = "Importar perfiles para NameplateSCT o ElvUI Floating Combat Text"
L["Importance: "] = "Importancia:"
L["In order to use this feature simply go to your Weakaura and go to its Group options scroll down to Position Settings and set the Anchored To Select Frame then type either |cff82B4ffEltruismWA|r or |cff82B4ffEltruismConsumables|r to anchor the weakaura to the preset location"] = "Para utilizar esta función simplemente vaya a su Weakaura y vaya a sus opciones de Grupo desplácese hacia abajo a la Configuración de la posición y establezca el Anclado al marco de selección luego escriba |cff82B4ffEltruismWA|r o |cff82B4ffEltruismConsumables|r para anclar el weakaura a la ubicación preestablecida"
L["Insanity"] = true
L["Install"] = "Instalar"
L["Installation Complete"] = "Instalación completa"
L["Installer"] = "Instalador"
L["INVENTORY IS FULL"] = "EL INVENTARIO ESTÁ LLENO"
L["Inventory is full."] = "El inventario está lleno."
L["Invert left mouse click so that chat starts faded and mouse click will make it stop fading"] = "Invertir el clic izquierdo del ratón para que el chat comience a desvanecerse y el clic del ratón haga que deje de desvanecerse"
L["Invert Mouse Click"] = "Invertir el clic del ratón"
L["It uses less memory and is more efficient than alternatives"] = true
L["It will set these CVars:"] = "Se fijarán estas CVars:"
L["Join the Discord if you have any questions or issues"] = "Únase al Discord si tiene alguna pregunta o problema"
L["Join the Discord if you have any questions or issues (English Support)"] = "Únase al Discord si tiene alguna pregunta o problema (Soporte en inglés)"
L["Keep in mind the discord is in English"] = "Tenga en cuenta que la discordia está en inglés"
L["Kimberley Font has been set."] = "Kimberley Font ha sido fijada."
L["Layout has been set."] = "La disposición se ha establecido."
L["Layouts"] = "Disposición"
L["Left Chat Mouse Over"] = "Chat izquierdo Mouse Over"
L["Left Inactivity Fader"] = "Fader de inactividad izquierdo"
L["License"] = "Licencia"
L["Light Mode"] = "Modo de luz"
L["Loot"] = "Botín"
L["Low"] = "Bajo"
L["Maelstrom"] = true
L["Make Buffs and Debuffs Wide on Nameplates"] = "Hacer que los Buffs y Debuffs sean amplios en las placas de identificación"
L["Make sure to install "] = "Asegúrese de instalar"
L["Mana"] = true
L["Maps"] = "Mapas"
L["Media"] = true
L["Medium"] = "Medio"
L["Method Raid Tools"] = true
L["Method Raid Tools profile has been set."] = "Se ha configurado el perfil del Method Raid Tools."
L["My WeakAuras are available here but are not focused on one class. Consider them more like upcoming features."] = "Mis WeakAuras están disponibles aquí pero no se centran en una clase. Considérelas más bien como características próximas."
L["NamePlate CVars have been set."] = "Las CVars de NamePlate se han configurado."
L["Nameplate Power Bar"] = "Barra de potencia de la placa de características"
L["Nameplates"] = "Placas de identificación"
L["NameplateSCT profile has been set."] = "Se ha establecido el perfil NameplateSCT."
L["NameplateSCT profile will be used"] = "Se utilizará el perfil NameplateSCT"
L["New commits basically a preview of fixes or upcoming features"] = "Nuevos commits básicamente un avance de las correcciones o de las próximas funciones"
L["None"] = "Ninguno"
L["Number of Pixels (Default is 9)"] = "Número de píxeles (por defecto es 9)"
L["Open Eltruism Configuration Panel"] = "Abrir el panel de configuración de Eltruism"
L["Optional"] = "Opcional"
L["Or choose a custom font"] = "O elige un tipo de letra personalizado"
L["Original Layout"] = "Diseño original"
L["Other Formats can end up causing errors"] = "Otros formatos pueden acabar provocando errores"
L["Outline"] = "Contorno"
L["Party/Raid"] = true
L["Pets"] = true
L["Pixel"] = "Píxel"
L["Pixel Border"] = "Borde de píxeles"
L["Pixel Frequency (Default is 1)"] = "Frecuencia de Pixel (El valor predeterminado es 1)"
L["Pixel Glow"] = "brillo de Pixel"
L["Pixel Horizontal Offset (Default is 5)"] = "Desplazamiento horizontal de los píxeles (Predeterminado es 5)"
L["Pixel Length (Default is 3)"] = "Longitud del píxel (Predeterminado es 3)"
L["Pixel Thickness (Default is 5)"] = "Grosor del píxel (Predeterminado es 5)"
L["Pixel Vertical Offset (Default is 5)"] = "Desplazamiento vertical de píxeles (Predeterminado es 5)"
L["Play a sound when someone dies in Party or Raid"] = "Reproducir un sonido cuando alguien muere en Party o Raid"
L["Play music during combat"] = "Reproducir música durante el combate"
L["Play music while you are AFK"] = "Reproducir música mientras estás AFK"
L["Please read the instructions to avoid issues"] = "Lea las instrucciones para evitar problemas"
L["Please select the role for your character, which will create a new profile.\nThis process can take a few seconds"] = "Por favor seleccione el papel para su personaje que creará un nuevo perfil\nEste proceso puede durar unos segundos"
L["Power Bar will move automatically based on class/spec/druid form"] = "La barra de poder se moverá automáticamente en función de la clase/especie/forma de druida"
L["ProjectAzilroka"] = true
L["ProjectAzilroka profile has been set."] = "El perfil del ProyectoAzilroka ha sido establecido."
L["Questie is not installed or enabled"] = "Questie no está instalado o habilitado"
L["Questie profile has been set."] = "Se ha establecido el perfil de Questie."
L["Quests"] = "Misiones"
L["Racial Music"] = "Música racial"
L["Rage"] = "Furia"
L["Remember to swap the second window to Healing Done or Tiny Threat"] = "Acuérdate de cambiar la segunda ventana por la de Curar Hecho o Diminuta Amenaza"
L["Replace Blizzards Default Glow with a Custom Glow"] = "Reemplaza el resplandor predeterminado de Blizzard por un resplandor personalizado"
L["Report issues and problems here:"] = "Informe de las cuestiones y los problemas aquí:"
L["Requires a Reload"] = "Requiere una recarga"
L["Reset all Media"] = "Restablecer todos las Media"
L["Reset Fonts Textures Skins to Eltreum UI defaults."] = "Restablecer fuentes texturas y skins a los valores predeterminados de Eltreum UI."
L["Reset Scale"] = "Reajuste de la escala"
L["Reset to Eltruism defaults."] = "Restablecer los valores predeterminados de Eltruism."
L["Return LootText to its default scale"] = "Devuelve a LootText su escala predeterminada"
L["Right Chat Mouse Over"] = "Chat derecho Mouse Over"
L["Right Inactivity Fader"] = "Fader de inactividad derecho"
L["Roboto Font has been set."] = "Se ha fijado la fuente Roboto."
L["Runic power"] = "Poder rúnico"
L["Select a size"] = "Seleccione un tamaño"
L["Select a Sound"] = "Seleccione un sonido"
L["Select a Texture"] = "Seleccione una textura"
L["Select a Type"] = "Seleccione un tipo"
L["Select a type of music"] = "Seleccione un tipo de música"
L["Select a version:"] = "Seleccione una versión:"
L["Select the Horizontal Size of the Power Bar (Default 132)"] = "Seleccione el tamaño horizontal de la barra de energía (Predeterminado 132)"
L["Select the power types to be displayed:"] = "Seleccione los tipos de potencia que se van a mostrar:"
L["Select the Vertical Size of the Power Bar (Default 6)"] = "Select the Vertical Size of the Power Bar (Predeterminado 6)"
L["Select the Y Offset for the Power Bar (Default 16)"] = "Seleccione el desplazamiento Y de la barra de potencia (Predeterminado 16)"
L["Set Details tables to be empty"] = "Configurar las tablas de Details para que estén vacías"
L["Set filters to be Eltruism/ElvUI defaults on Boss"] = "Configurar los filtros para que sean los predeterminados de Eltruism/ElvUI en Boss"
L["Set filters to be Eltruism/ElvUI defaults on Focus"] = "Establecer los filtros por defecto de Eltruism/ElvUI en Focus"
L["Set filters to be Eltruism/ElvUI defaults on Nameplates"] = "Establecer los filtros por defecto de Eltruism/ElvUI en las placas de identificación"
L["Set filters to be Eltruism/ElvUI defaults on Player"] = "Configurar los filtros para que sean los predeterminados de Eltruism/ElvUI en Player"
L["Set filters to be Eltruism/ElvUI defaults on Target"] = "Establecer los filtros por defecto de Eltruism/ElvUI en Target"
L["Set filters to show more buffs on Boss"] = "Establecer filtros para mostrar más buffs en el Jefe"
L["Set filters to show more buffs on Focus"] = "Establecer filtros para mostrar más buffs en Focus"
L["Set filters to show more buffs on Nameplates"] = "Establecer filtros para mostrar más buffs en las placas de identificación"
L["Set filters to show more buffs on Player"] = "Establecer filtros para mostrar más buffs en el Jugador"
L["Set filters to show more buffs on Target"] = "Establecer filtros para mostrar más buffs en Target"
L["Set filters to show more debuffs on Boss"] = "Establecer filtros para mostrar más debuffs en los jefes"
L["Set filters to show more debuffs on Focus"] = "Establecer filtros para mostrar más debuffs en Focus"
L["Set filters to show more debuffs on Nameplates"] = "Establecer filtros para mostrar más debuffs en las placas de identificación"
L["Set filters to show more debuffs on Player"] = "Establecer filtros para mostrar más debuffs en el jugador"
L["Set filters to show more debuffs on Target"] = "Establecer filtros para mostrar más debuffs en el objetivo"
L["Set Horizontal Size"] = "Ajustar el tamaño horizontal"
L["Set the Font Outlines everywhere. Use Default to return to Eltruism default settings"] = "Configure los contornos de la fuente en todas partes. Usar el valor por defecto para volver a la configuración predeterminada de Eltruism"
L["Set the fonts used in Eltruism. Kimberley is the default font"] = "Establezca los tipos de letra utilizados en Eltruism. Kimberley es la fuente predeterminada"
L["Set the frequency pixel glow"] = "Ajustar la frecuencia de brillo de Pixel"
L["Set the horizontal offset of autocast"] = "Establecer el desplazamiento horizontal de la emisión automática"
L["Set the horizontal offset of pixels"] = "Establecer el desplazamiento horizontal de los píxeles"
L["Set the length of pixels"] = "Establecer la longitud de los píxeles"
L["Set the level that LootText will be drawn to this"] = "Establece el nivel en el que se dibujará el LootText"
L["Set the number of groups for autocast for each group you get 4 particles"] = "Establece el número de grupos para la autodifusión por cada grupo se obtienen 4 partículas"
L["Set the number of pixels in pixel glow"] = "Establece el número de píxeles en el brillo de los píxeles"
L["Set the radius of the cast cursor"] = "Establecer el radio del cursor de fundición"
L["Set the radius of the combat cursor"] = "Establecer el radio del cursor de combate"
L["Set the radius of the gcd cursor"] = "Establecer el radio del cursor gcd"
L["Set the size of LootText"] = "Establecer el tamaño de LootText"
L["Set the thickness of pixels"] = "Establecer el grosor de los píxeles"
L["Set the thickness of the combat cursor"] = "Establecer el grosor del cursor de combate"
L["Set the thickness of the gcd cursor"] = "Establecer el grosor del cursor gcd"
L["Set the vertical offset of autocast"] = "Establecer el desplazamiento vertical de la emisión automática"
L["Set the vertical offset of pixels"] = "Establecer el desplazamiento vertical de los píxeles"
L["Set Vertical Size"] = "Ajustar el tamaño vertical"
L["Set X offset"] = "Ajustar el desplazamiento X"
L["Set Y offset"] = "Ajustar el desplazamiento Y"
L["Set Y Offset"] = "Ajustar el desplazamiento Y"
L["Setting "] = "Configuración"
L["settings configured for "] = "ajustes configurados para"
L["Setup Aura Filters to be Eltruism/ElvUI defaults"] = "Configurar los filtros de Aura para que sean los predeterminados de Eltruism/ElvUI"
L["Setup Aura Filters to show all"] = "Configurar los filtros de Aura para mostrar todo"
L["Setup CVars"] = "Configurar CVars"
L["Setup Media"] = "Medios de comunicación de configuración"
L["Shadow and Light"] = true
L["Show a floating loot text"] = "Mostrar un texto de botín flotante"
L["Show Friendly Nameplates but Hide Healthbar"] = "Mostrar las placas de identificación amigables pero ocultar la barra de salud"
L["Shows Class Icons by Blizzard on all targets"] = "Muestra los iconos de clase de Blizzard en todos los objetivos"
L["Shows Class Icons by Blizzard only on Player targets"] = "Muestra los iconos de clase de Blizzard sólo en los objetivos de los jugadores"
L["Shows Class Icons recolored by Releaf on all targets"] = "Muestra los iconos de clase recoloreados por Releaf en todos los objetivos"
L["Shows Class Icons recolored by Releaf on Player targets"] = "Muestra los Iconos de Clase recoloreados por Releaf en los objetivos del Jugador"
L["Shows Class Icons with borders recolored by Releaf on all targets"] = "Muestra los iconos de clase con bordes recoloreados por Releaf en todos los objetivos"
L["Shows Class Icons with borders recolored by Releaf on Player targets"] = "Muestra los iconos de clase con bordes recolorados por Releaf en los objetivos del jugador"
L["Silver"] = "Plata"
L["Skin Level Up Boss Loot and Instance Entrance frames to be class colored"] = "La subida de nivel de la piel el botín de los jefes y los marcos de entrada a las instancias tendrán el color de la clase"
L["Skip Install"] = "Saltar la instalación"
L["Soul Ash"] = "Ceniza del alma"
L["Speed for Autocast set to negative to inverse direction of rotation"] = "Velocidad para la Autocast ajustada en negativo para invertir el sentido de giro"
L["Speed for Blizzard glow"] = "Velocidad para el resplandor de la Blizzard"
L["Stealth Vignette"] = "Viñeta de sigilo"
L["Support"] = "Soporte"
L["Target Texture"] = "Textura objetivo"
L["The alternative layout was made for the Eltruism DPS/Tank profile please switch to it to use it"] = "El diseño alternativo fue hecho para el perfil DPS/Tanque de Eltruismo por favor cambia a él para usarlo"
L["The Cursor will use this type as its texture"] = "El Cursor utilizará este tipo como textura"
L["The original layout was made for the Eltruism DPS/Tank profile please switch to it to use it"] = "El diseño original fue hecho para el perfil de DPS/Tanque de Eltruismo por favor cambia a él para usarlo"
L["The time will be calculated based on player speed and distance"] = "El tiempo se calculará en función de la velocidad y la distancia del jugador"
L["Thick Outline"] = "Contorno grueso"
L["This prompt will help you install "] = "Este aviso le ayudará a instalar"
L["This will set all ElvUI fonts as Exo2"] = "Esto establecerá todas las fuentes ElvUI como Exo2"
L["This will set all ElvUI fonts as Gotham"] = "Esto establecerá todas las fuentes ElvUI como Gotham"
L["This will set all ElvUI fonts as Kimberley"] = "Esto establecerá todas las fuentes ElvUI como Kimberley"
L["This will set all ElvUI fonts as Roboto"] = "Esto establecerá todas las fuentes ElvUI como Roboto"
L["This will set colors to black with class colors when losing health"] = "Esto pondrá los colores en negro con los colores de la clase cuando se pierde la salud"
L["This will set colors to class based with black backgrounds when losing health"] = "Esto hará que los colores se basen en la clase con fondos negros cuando se pierda la salud"
L["This will set fonts to Eltruism defaults recommended for 4K"] = "Esto establecerá las fuentes a los valores predeterminados de Eltruism recomendados para 4K"
L["This will set fonts to no outline"] = "Esto hará que las fuentes no tengan contorno"
L["This will set fonts to use outline recommended for 1440p and 1080p"] = "Esto establecerá las fuentes para usar el contorno recomendado para 1440p y 1080p"
L["This will set fonts to use thick outline"] = "Esto hará que las fuentes utilicen un contorno grueso"
L["Toggle a Stealth Effect"] = "Activar un efecto de sigilo"
L["Toggle Class Colored glows"] = "Alternar brilla en color por la clase"
L["Toggle the option"] = "Alternar la opción"
L["Toggle the option on"] = "Activar la opción"
L["Toggle On and Off"] = "Activar y desactivar"
L["Turn the effect on"] = "Activar el efecto"
L["Type 1"] = "Tipo 1"
L["Type 10"] = "Tipo 10"
L["Type 2"] = "Tipo 2"
L["Type 3"] = "Tipo 3"
L["Type 4"] = "Tipo 4"
L["Type 5"] = "Tipo 5"
L["Type 6"] = "Tipo 6"
L["Type 7"] = "Tipo 7"
L["Type 8"] = "Tipo 8"
L["Type 9"] = "Tipo 9"
L["Unsupported format"] = "Formato no admitido"
L["Unsupported format or Area does not support waypoints"] = "Formato no soportado o Área no soporta waypoints"
L["updated to "] = "actualizado a"
L["Use Class Colors"] = "Utilizar los colores de la clase"
L["Use Class Colors for Cast"] = "Utilizar los colores de la clase para el reparto"
L["Use Class Colors for Cursor"] = "Usar colores de clase para el cursor"
L["Use Class Colors for GCD"] = "Utilizar los colores de la clase para la DGC"
L["Use ElvUI General Font"] = "Utilizar la fuente general ElvUI"
L["Use formats such as:"] = "Utiliza formatos como:"
L["Very High"] = "Muy alto"
L["WARNING"] = "ADVERTENCIA"
L["Welcome"] = "Bienvenido"
L["Wide nameplate debuffs and buffs"] = "Amplia placa de identificación de debuffs y buffs"
L["WindTools"] = true
L["XX YY XX.XX YY.YY XXXX YYYY and XXX YYY"] = "XX YY XX.XX YY.YY XXXX YYYY e XXX YYY"
L["You can replace it with one of the following:"] = "Puedes sustituirlo por uno de los siguientes:"
L["You can right click the bottom right arrow to toggle the Details! Window"] = "Puede hacer clic con el botón derecho del ratón en la flecha inferior derecha para activar la Details! Ventana"
L["You can set your Weakauras to anchor to custom locations making it easier to move them"] = "Puedes configurar tus Weakauras para que se anclen a ubicaciones personalizadas facilitando su traslado"
L["You can support the group with your class if you select DPS/Tank then its recommended to click Alt Frames after clicking DPS/Tank"] = "Puedes apoyar al grupo con tu clase si seleccionas DPS/Tanque entonces se recomienda hacer clic en Alt Frames después de hacer clic en DPS/Tanque"
L["You can type /way or /waypoint"] = "Puedes escribir /way o /waypoint"
L["You need to be using an Eltruism profile in order to use this function"] = "Para poder utilizar esta función es necesario contar con un perfil de Eltruismo"
L["Your current settings will be lost please back them up"] = "Su configuración actual se perderá por favor haga una copia de seguridad"
L["Your custom font has been set."] = "Se ha configurado su fuente personalizada."

--missing texts from February 2022
L["Eltruism Installer"] = true
L["Launch Eltruism Installer"] = true
L["Reset Eltruism Settings"] = true
L["Launches the Eltruism install prompt"] = true
L["Resets Eltruism Settings to Eltreum's Defaults"] = true
L["Reset nameplates to Eltruism Settings"] = true
L["Reset Chat to ElvUI Settings"] = true
L["Reset layout to Eltruism DPS/Tank"] = true
L["Reset layout to Eltruism Healer"] = true
L["Skip Plugins install message"] = true
L["Details v1 - Blizzard Flat Icons"] = true
L["Details v2 - Releaf Transparent Icons"] = true
L["Details v3 - Releaf Solid Icons"] = true
L["Enable Borders"] = true
L["Change the size of the borders:"] = true
L["Actionbar Thickness"] = true
L["Unitframe Thickness"] = true
L["(All settings require a reload)"] = true
L["Action bar 1"] = true
L["Action bar 2"] = true
L["Action bar 3"] = true
L["Action bar 4"] = true
L["Action bar 5"] = true
L["Action bar 6"] = true
L["Target Border"] = true
L["Target of Target Border"] = true
L["Border X offset"] = true
L["Player Border"] = true
L["Player Castbar Border"] = true
L["Target Castbar Border"] = true
L["Target of Target Border"] = true
L["Nameplate Power Bar Border"] = true
L["Nameplate Power Bar Thickness"] = true
L["Enable Fast Loot"] = true
L["Decrease the time it takes for auto loot to work, works with TSM"] = true
L['Enable Fast Loot with Loot Quality Filter'] = true
L["Enable filtering item quality, items can still be looted by holding Shift or the mod key setup in Interface"] = true
L['Enable Fast Loot with Wishlist Filter'] = true
L["Items not on the wishlist will not be looted, items can still be looted by holding Shift or the mod key setup in Interface"] = true
L["Enable Wishlist Loot Warning"] = true
L["Show a toast if an item in the wishlist is looted"] = true
L["Enable Automatically Closing Loot Window"] = true
L["Loot Window will automatically close when using filters and the item desired is not found"] = true
L["Enable Screenshotting if an item from the wishlist is looted"] = true
L["Loot Window will automatically close when using filters and the item desired is not found"] = true
L["Minimum Loot Quality Filter"] = true
L["Poor"] = true
L["Common"] = true
L["Uncommon"] = true
L["Rare"] = true
L["Epic"] = true
L["Only items of this quality or better will be looted when using Fast Loot Filter"] = true
L["Item Wishlist (type the Item ID)"] = true
L["Items in your wishlist will display a warning when looted"] = true
L["Invalid Item, you need to add an itemID which can be found in the tooltip or in Wowhead"] = true
L["Remove item from Wishlist"] = true
L["Remove"] = true
L["Add color to some chat messages"] = true
L["Enhance Item Links in Chat"] = true
L['Enable Chat Icons'] = true
L["Enable Item Levels"] = true
L["Customize the Chat tabs"] = true
L["Dark Chat"] = true
L["Transparent Chat"] = true
L["Make more texts use ElvUI font settings"] = true
L["Such as the Zones, Mail and others"] = true
L["Skin Objective Frame (when Shadow and Light and Windtools are not loaded)"] = true
L['Enable Wowhead Button on Quest Log'] = true
L["Show a button for Wowhead quest links"] = true
L['Enable Skin'] = true
L["Skin the Objective/Quest Frame"] = true
L["Remove Blizzard's Boss Emote Frame"] = true
L["Customize the player castbar spark"] = true
L["Cursor Sizes"] = true
L["Select how auras will be displayed for Player"] = true
L["Select how auras will be displayed for Target"] = true
L["Select how auras will be displayed for Focus"] = true
L["Select how auras will be displayed for Boss"] = true
L["Select how auras will be displayed for Nameplates"] = true
L["Enable cursor only during combat"] = true
L["Cursor will only show during combat"] = true
L["Enable cooldown tracking"] = true
L["Add a cooldown icon when trying to use skills that are on cooldown, and a cooldown flash when they are ready"] = true
L["Attempt to fix Cursor Lag"] = true
L["Software cursor is how the cursor was before Battle for Azeroth, Hardware cursor is faster but will cause problems with addons that attach to it"] = true
L["Software Cursor"] = true
L["Hardware Cursor"] = true
L["Enable on Action Bars"] = true
L["Enable on Pet Bar"] = true
L["Enable on Nameplate"] = true
L["Add a glow when buffs or debuffs are expiring on nameplates"] = true
L["Adds an autocast style glow using class color"] = true
L["Adds a pixel style glow using class color"] = true
L["Preview the Glow"] = true
L["Preview"] = true
L["Preview the Glow, you will need to toggle it off and on to update the glow"] = true
L["Action Bars"] = true
L["Pet Bar"] = true
L["Nameplate Buff/Debuff"] = true
L["Customize CVars"] = true
L["Nameplate Other Bottom Inset"] = true
L["In screen % the inset from the Bottom"] = true
L["Nameplate Other Top Inset"] = true
L["In screen % the inset from the Top"] = true
L["Nameplate Target Radial Position"] = true
L["When target is off screen, position its nameplate radially around sides and bottom."] = true
L["Target Only"] = true
L["All in Combat"] = true
L["Camera Distance Max Zoom Factor"] = true
L["Maximum Camera Zoom Out"] = true
L["Hide Minimap while in Combat"] = true
L["Automatically hide the Minimap in combat"] = true
L["Dynamically toggle the mouseover of the Experience Bar"] = true
L["Shows XP bar when below max level, makes it mouseover when max level"] = true
L["Enable Entering/Leaving Combat Indicator Texts"] = true
L["Adds a +Combat and -Combat for when entering and leaving combat"] = true
L["Enable a Dark Souls death animation"] = true
L["Plays an animation when you die"] = true
L["Add Sounds to /roll when someone gets a 1 or a 100"] = true
L["Plays a sound if someone rolls 1 or 100 out 100"] = true
L["Change the Scale of the World Text"] = true
L["Such as the floating XP, floating reputation changes and others"] = true
L["Select the size of the World Text"] = true
L["Hide Talking Head"] = true
L["Prevent Blizzard's Talking Head from appearing"] = true
L["Automatically take Screenshots"] = true
L["Automatically take Screenshots such as when leveling up"] = true
L["Stealth"] = true
L["Item Deletion"] = true
L["Automatically type DELETE on the popup"] = true
L["Will not delete the item, will simply type DELETE instead you needing to type it"] = true
L["Blizzard Floating Combat Text"] = true
L["Disable Combat Text"] = true
L["Enable or disable Blizzard's default Floating Combat Text"] = true
L["Enable Resource Gains"] = true
L["Enable or disable Blizzard's default Floating Combat Text for Mana/Rage/Energy and other resouces"] = true
L["Swap Action Paging and visibility for Bar1 and Bar4"] = true
L["Enable Boss Music"] = true
L["Disable Combat Music in Instances"] = true
L["Normal Combat Music"] = true
L["Name of file inside Interface\\Addons"] = true
L["Boss Combat Music"] = true
L["Player Class Texture"] = true
L["Target Class Texture"] = true
L["Change the texture of the nameplate to be a class gradient of the player's class"] = true
L["Change the texture of the nameplate to be a class gradient of the target's class"] = true
L["Enable Automatically accepting/turning in Quests when not holding CTRL/SHIFT/ALT"] = true
L["You will automatically accept and turn in quests that do not require gold, are not weekly and are not daily"] = true
L["Accept Daily and Weekly quests"] = true
L["You will also automatically accept Daily and Weekly Quests"] = true
L["Invert CTRL/SHIFT/ALT"] = true
L["You will only accept and turn in quests if you hold CTRL/SHIFT/ALT while talking to the NPC"] = true
L["Quest Item Bar"] = true
L["Enable Quest Item Bar"] = true
L["Add a Quest Item bar, keybind can be changed in Keybinds > ElvUI Eltruism"] = true
L["Add a Quest Item bar, keybind can be changed in Key Bindings > ElvUI Eltruism"] = true
L["Quest Item Bar follows visibility settings for ElvUI Action Bar 1"] = true
L["The Quest Item Bar will appear only when ElvUI Action Bar 1 appears, following its settings"] = true
L["Quest Item Bar Button Mouse Over"] = true
L["Each Button in the Quest Item Bar will appear only if the cursor is over it"] = true
L["Quest Item Bar Button Size"] = true
L["Change the size of the button on the Quest Item Bar"] = true
L["Character Panel"] = true
L["Expand Character Art"] = true
L["Expand Character Panel"] = true
L["Add Crest to Character Panel"] = true
L["Art Alpha"] = true
L["Change the transparency of the Art"] = true
L["Add Class Icons to Character Panel"] = true
L["Enable this option"] = true
L["Use Blizzard Icons"] = true
L["Enable Blizzard Icons"] = true
L["Use Blizzard Icons colored by Releaf"] = true
L["Enable Releaf Icons"] = true
L["Add Shadows to Frames"] = true
L["Add Shadows to some frames"] = true
L["Enable General Shadows"] = true
L["Add Shadows to frames like Player, target, Chats and others"] = true
L["Other Shadows (can become CPU/Memory Intensive)"] = true
L["Nameplate Health"] = true
L["Add Shadows to Nameplate Healthbars"] = true
L["Nameplate Aura"] = true
L["Add Shadows to Nameplate Auras"] = true
L["Nameplate Portrait"] = true
L["Add Shadows to Nameplate Portraits"] = true
L["Nameplate Power"] = true
L["Add Shadows to Nameplate Powers"] = true
L["Nameplate Castbar"] = true
L["Add Shadows to Nameplate Castbars"] = true
L["Unitframe Aura"] = true
L["Add Shadows to Unitframe Auras"] = true
L["ActionBars"] = true
L["Add Shadows to Actionbars"] = true
L["Aura"] = true
L["Add Aura Shadows (Aura list next to the minimap)"] = true
L["Choose the Border Texture to be used:"] = true
L["Change the size of the borders:"] = true
L["Bar 1 X offset"] = true
L["Bar 1 Y offset"] = true
L["Bar 2 X offset"] = true
L["Bar 2 Y offset"] = true
L["Bar 3 X offset"] = true
L["Bar 3 Y offset"] = true
L["Bar 4 X offset"] = true
L["Bar 4 Y offset"] = true
L["Bar 5 X offset"] = true
L["Bar 5 Y offset"] = true
L["Bar 6 X offset"] = true
L["Bar 6 Y offset"] = true
L["How to use the Anchors"] = true
L["Open WeakAuras, go to your group Weakauras and in Group change Position Settings > Anchored To > Select Frame > EltruismWA or EltruismConsumables"] = true
L["Hide Quests during Battlegrounds and Arenas"] = true
L["Eltruism uses a 0.7 scale, but ElvUI can calculate the best scale for you using the Automatic Scale option"] = true
L["Very High (but Optional)"] = true
L['DPS\nTank'] = true
L['Healer'] = true
L['Automatic\nScale'] = true
L['Alternative\nFrames'] = true
L["Or change it later in Eltruism > Media options"] = true
L["Eltruism Modes"] = true
L["Eltruism uses Dark Mode and Transparent chat by default"] = true
L["You can switch to Light Mode and/or Dark Chat by clicking the buttons below"] = true
L["Transparent\nChat"] = true
L['Details! DPS Meter'] = true
L['Choose the type of icons Details! will use:'] = true
L['PVP/PVE Addons'] = true
L["Import GladiusEx profile for arenas, remember to disable ElvUI Arena Frames"] = true
L['GladiusEx'] = true
L["Import Questie profile, which uses the DBM radar"] = true
L["Questie"] = true
L["Import DBM or BigWigs profiles for dungeons and raids. (Uses DBM English Calanon and Bigwigs Voice)"] = true
L["Import Method Raid Tools profile with raid cooldowns and other settings"] = true
L["Import profiles for Gladdy (Gladius can be found in Eltruism settings)"] = true
L["Gladdy is not installed or enabled (You can find the Gladius profile in Eltruism Settings"] = true
L["Gladius profile can be found in Eltruism > Addons, please check it there"] = true
L["You have none of these addons installed or enabled"] = true
L["QOL Addons"] = true
L["Import a profile for Simpy's ElvUI FCT configured for Eltruism"] = true
L["Import a profile for NameplateSCT configured for Eltruism"] = true
L["NameplateSCT and ElvUI FCT are not installed or enabled"] = true
L["You have completed the installation process"] = "Ha completado el proceso de instalación"
L["Please click Finished to reload the UI"] = "Haga clic en Finalizar para recargar la interfaz de usuario"
L["Shaman Totems"] = true
L["Enable on Shaman Totems"] = true
L["Enable on Shaman Fire Totem"] = true
L["Enable on Shaman Earth Totem"] = true
L["Enable on Shaman Water Totem"] = true
L["Enable on Shaman Air Totem"] = true
L["Shaman Fire Totem"] = true
L["Shaman Earth Totem"] = true
L["Shaman Water Totem"] = true
L["Shaman Air Totem"] = true
