local L = ElvUI[1].Libs.ACL:NewLocale("ElvUI", "ptBR")
if not L then return end
-- Core
L["4K resolution detected, setting fonts to default mode."] = "Resolução 4K detectada, configurando fontes para o modo padrão"
L["1440p resolution detected, setting fonts to outline mode."] = "Resolução 1440p detectada, configurando fontes para o modo padrão"
L["1080p resolution detected, setting fonts to outline mode."] = "Resolução 1080p detectada, configurando fontes para o modo padrão"
L["Fonts were set to Outline due to your resolution."] = "Fontes foram configuradas para o modo Outline devido sua resolução"
L["EltruismConsumablesWA"] = true
--Install
L["General CVars have been set."] = "CVars gerais foram configuradas"
L["NamePlate CVars have been set."] = "CVars para placas de nomes foram configuradas"
L["AddOnSkins profile has been set."] = "Perfil de AddOnSkins foi configurado"
L["Immersion profile has been set."] = "Perfil de Immersion foi configurado"
L["BigWigs profile has been set."] = "Perfil de Bigwigs foi configurado"
L["DBM profile has been set."] = "Perfil de DBM foi configurado"
L["Details profile has been set."] = "Perfil de Details foi configurado"
L["Dynamic Cam profile has been set."] = "Perfil de Dynamic Cam foi configurado"
L["GladiusEx profile has been set."] = "Perfil de GladiusEx foi configurado"
L["Method Raid Tools profile has been set."] = "Perfil de Method Raid Tools foi configurado"
L["ProjectAzilroka profile has been set."] = "Perfil de ProjectAzilroka foi configurado"
L["Questie profile has been set."] = "Perfil de Questie foi configurado"
L["NameplateSCT profile has been set."] = "Perfil de NamelateSCT foi configurado"
L["Floating Combat Text profile has been set."] = "Perfil de Floating Combat Text foi configurado"
L["Gladius profile has been set."] = "Perfil de Gladius foi configurado"
L["Gladdy profile has been set."] = "Perfil de Gladdy foi configurado"
L["Area does not support waypoints"] = "Área não suporta rotas"
L["Unsupported format"] = "Formato não suportado"
L["Unsupported format or Area does not support waypoints"] = "Formato não suportado ou área não suporta rotas"
L["WARNING"] = "ALERTA"
L["Make sure to install "] = "Certifique-se que tenha instalado "
L["Shadow and Light"] = true
L[" and "] = " e "
L["WindTools"] = true
L["AddOnSkins"] = true
L["ProjectAzilroka"] = true
L["This prompt will help you install "] = "Este painel irá ajudá-lo a instalar "
L[" and import its settings"] = " e importar suas configurações"
L["Please read the instructions to avoid issues"] = "Por favor leia as instruções para evitar problemas"
L["Skip Install"] = "Pular Instalação"
L["Layouts"] = true
L["Please select the role for your character, which will create a new profile.\nThis process can take a few seconds"] = "Por favor selecione a função do seu personagem, o que irá criar um novo perfil.\nEste processo pode demorar alguns segundos"
L["You can support the group with your class, if you select DPS/Tank then its recommended to click Alternative Frames after clicking DPS/Tank"] = "Você pode suportar o grupo com sua classe, se você selecionar DPS/Tank é recomendado clicar em Alternative Frames"
L["Importance: "] = "Importância: "
L["Very High"] = "Muito Alta"
L["Fonts"] = "Fontes"
L["Eltruism uses Kimberley as the default font"] = "Eltruism usa Kimberley como a fonte padrão"
L["You can replace it with one of the following:"] = "Você pode substituí-la com uma das seguintes:"
L["Optional"] = "Opcional"
L["Your current settings will be lost, please back them up"] = "Suas configurações atuais serão perdidas, por favor faça um backup"
L["Import "] = "Importar "
L["Import Details! profile with dual panels"] = "Importar perfil para Detail! com dois painéis"
L["You can right click the bottom right arrow to toggle the Details! Window"] = "Você pode clicar com o botão direito na seta do canto inferior direito para mostrar/esconder o Details!"
L["Remember to swap the second window to Healing Done or Tiny Threat"] = "Lembre-se de trocar a segunda janela para Healing ou Tiny Threat"
L["Details is an advanced combat parser"] = "Details é um analisador de combate avançado"
L["It has many plugins to choose from"] = "Ele possui vários plugins que podem ser utilizados"
L["Boss Mods"] = true
L["Import DBM or Bigwigs profiles"] = "Importar perfis para DBM ou Bigwigs"
L["DBM is not installed or enabled so BigWigs will be used"] = "DBM não está instalado ou habilitado então BigWigs será utilizado"
L["BigWigs is not installed or enabled so DBM will be used"] = "BigWigs não está instalado ou habilitado então DBM será utilizado"
L["DBM uses DBM English by Calanon as a voice pack"] = "DBM utiliza o pacote de vozes DBM English por Calanon"
L["Both DBM and BigWigs are not installed or enabled"] = "Tanto o BigWigs quanto o DBM não estão instalados ou habilitados"
L["Method Raid Tools"] = true
L["Import profiles for NameplateSCT or ElvUI Floating Combat Text"] = "Importar configurações para NameplateSCT ou ElvUI Floating Combat Text"
L["FCT profile will be used"] = "Perfil para FCT será utilizado"
L["NameplateSCT profile will be used"] = "Perfil para NameplateSCT será utilizado"
L["Import "] = "Importar "
L["settings configured for "] = "configurações aplicadas para "
L[" is not installed or enabled"] = " não está instalado ou habilitado"
L["Import Dynamic Cam profile"] = "Importar configurações para Dynamic Cam"
L["Welcome"] = "Bem vindo"
L["Join the Discord if you have any questions or issues (English Support)"] = "Junte-se ao Discord se você tiver perguntas ou problemas (Suporte em Inglês)"
L["Installation Complete"] = "Instalação Completada"
L["Finished"] = "Finalizar"
L["Questie is not installed or enabled"] = "Questie não está instalado ou habilitado"
L["Arenas"] = true
L["Abbreviates the unit name once it goes over 16 characters, made by Azilroka"] = "Abrevia o nome da unidade quando possui mais de 16 caracteres, feito por Azilroka"
L["updated to "] = "actualizado para "
L["Layout has been set."] = "Layout foi aplicado."
L["General Layout has been set."] = "Layout geral foi aplicado"
L["The alternative layout was made for the Eltruism DPS/Tank profile, please switch to it to use it"] = "O layout alternativo foi feito para o perfil Eltreum DPS/Tank, por favor mude para ele para utilizá-lo"
L["The original layout was made for the Eltruism DPS/Tank profile, please switch to it to use it"] = "O layout original foi feito para o perfil Eltreum DPS/Tank, por favor mude para ele para utilizá-lo"
L["You need to be using an Eltruism profile in order to use this function"] = "Você precisa estar utilizando um perfil do Eltruism para utilizar esta função"
L["Debuff filters were setup"] = "Filtros para Penalidades foram aplicados"
L["Buff filters were setup"] = "Filtros para Bônus foram aplicados"
L["ElvUI Chat has been set."] = "Chat do ElvUI foi configurado"
-- Datatext
L["Eltruism Ammo"] = "Munição Eltruism"
L["Click:"] = "Clique:"
L["Open Eltruism Configuration Panel"] = "Abrir painel de configuração do Eltruism"
L["Eltruism Config"] = "Painel de Configuração do Eltruism"
-- Fonts
L["Your custom font has been set."] = "Sua fonte personalizada foi aplicada."
L["Kimberley Font has been set."] = "Fonte Kimberley foi aplicada."
L["Exo2 Font has been set."] = "Fonte Exo2 foi aplicada"
L["GothamNarrow Black Font has been set."] = "Fonte GothamNarrow Black Font foi aplicada."
L["Roboto Font has been set."] = "Fonte Roboto foi aplicada."
L["Crystalzcuhei Font has been set."] = "Fonte Crystalzcuhei foi aplicada"
--LootText
L["INVENTORY IS FULL"] = "O inventário está cheio."
L["Inventory is full."] = "O inventário está cheio." --is a blizzard argument for the error, if different from blizzard it will not work
L["Silver"] = "Prata" -- the coin type exactly as it is in game, or the function will not work for the location
L["Gold"] = "Ouro" -- the coin type exactly as it is in game, or the function will not work for the location
L["Copper"] = "Cobre" -- the coin type exactly as it is in game, or the function will not work for the location
L["Soul Ash"] = true -- the currency exactly as it is in game, or the function will not work for the location
--Options
L["Installer"] = "Instalador"
L["Nameplates"] = "Placas de Nome"
L["Chat"] = true
L["Clear Details! Damage Meter tables to free up memory"] = "Limpar tabelas do Details! para diminuir uso da memória"
L["Clear Details Tables"] = "Limpar tabelas do Details!"
L["Set Details tables to be empty"] = "Configura as tabelas do Details! para ficarem vazias"
L["Install"] = "Instalar"
L["A.F.K"] = true -- away from keyboard, can be longer in other languages
L["Play music while you are AFK"] = "Tocar música quando você está AFK"
L["Enable"] = "Habilitar"
L["Cursor"] = true
L["Change the size of the World of Warcraft Cursor"] = "Mude o tamanho do Cursor do World of Warcraft"
L["Select a size"] = "Selecione um tamanho"
L["Choose this size"] = "Escolha este tamanho"
L["Autodetect"] = "Autodetectar"
L["Add GCD, Cast and Combat indicator rings to the cursor"] = "Adicione incidadores para GCD, Lançamentos e Combate ao cursor"
L["Enable cooldown tracking"] = "Permitir rastreamento de regarga"
L["Add a cooldown icon when trying to use skills that are on cooldown, and a cooldown flash when they are ready"] = "Adicionar um ícone de recarga quanmdo você tenta utilizar uma habilidade que ainda está em recarga, e este símbolo irá aparecer quando a habilidade estiver pronta"
L["Enable cursor rings for Casts, GCD and Combat"] = "Habilitar anéis de cursor para Lançamentos, GCD e Combate"
L["Add a rings around the mouse cursor for GCD, casts and combat"] = "Adicionar anéis ao cursor para GCD, lançamentos e combate"
L["Choose a type of cursor by clicking it"] = "Escolha um tipo de cursor clicando nele"
L["Currently selected cursor: "] = "Cursor selecionado atualmente: "
L["Type 1"] = "Tipo 1"
L["Type 2"] = "Tipo 2"
L["Type 3"] = "Tipo 3"
L["Type 4"] = "Tipo 4"
L["Type 5"] = "Tipo 5"
L["Type 6"] = "Tipo 6"
L["Type 7"] = "Tipo 7"
L["Type 8"] = "Tipo 8"
L["Type 9"] = "Tipo 9"
L["Type 10"] = "Tipo 10"
L["The Cursor will use this type as its texture"] = "O Cursor irá utilizar este tipo como sua textura"
L["Cursor Colors "] = "Cores do Cursor"
L["Requires a Reload"] = "Requer um Reload"
L["Class Colored Casts"] = "Cor de classe para Lançamentos"
L["Use Class Colors for Cast"] = "Utilizar Cores de Classe para os Lançamentos"
L["Custom Color Cast"] = "Cor Customizada para Lançamentos"
L["Class Colored GCD"] = "Cor de Classe para GCD"
L["Use Class Colors for GCD"] = "Utilizar Cores de Classe para GCD"
L["Custom Color GCD"] = "Cor Customizada para GCD"
L["Class Colored Combat"] = "Cor de Classe para Combate"
L["Use Class Colors for Cursor"] = "Utilizar Cores de Classe para o Cursor"
L["Custom Color Combat"] = "Cor Customizada para Combate"
L["Cast Radius (Default: 25)"] = "Raio de Lançamento (Padrão: 25)"
L["Set the radius of the cast cursor"] = "Selecione o raio do cursor de lançamentos"
L["Cast Thickness (Default: 5)"] = "Espessura de Lançamentos (Padrão: 5)"
L["GCD Radius (Default: 20)"] = "Raio de GCD (Padrão: 20)"
L["Set the radius of the gcd cursor"] = "Selecione o raio do cursor de gcd"
L["GCD Thickness (Default: 5)"] = "Espessura de GCD (Padrão: 5)"
L["Set the thickness of the gcd cursor"] = "Selecione a espessura do cursor de gcd"
L["Combat Cursor Radius (Default: 15)"] = "Raio de Combate (Padrão: 15)"
L["Set the radius of the combat cursor"] = "Selecione o raio do cursor de combate"
L["Combat Cursor Thickness (Default: 5)"] = "Espessura de Combate (Padrão: 5)"
L["Set the thickness of the combat cursor"] = "Selecione a espessura do cursor de combate"
L["Aura Filters"] = "Filtros de Auras"
L["For Shadowlands, import aura filters by copying the code below and going into Profiles > Import Profile."] = "Para Shadowlands, importe filtros de auras copiando o código abaixo e indo até Perfis > Importar Perfis."
L["Setup Aura Filters to show all"] = "Configurar Filtros de Aura para mostrar tudo"
L["All Player Buffs"] = "Todos os Bônus do Jogador"
L["Set filters to show more buffs on Player"] = "Configurar filtros para mostrar mais bônus no jogador"
L["All Player Debuffs"] = "Todas as Penalidades do Jogador"
L["Set filters to show more debuffs on Player"] = "Configurar filtros apra mostrar mais penalidades no jogador"
L["All Target Debuffs"] = "Todas as Penalidades do Alvo"
L["Set filters to show more debuffs on Target"] = "Configurar filtros para mostar mais penalidades no Alvo"
L["All Target Buffs"] = "Todos os Bônus do Alvo"
L["Set filters to show more buffs on Target"] = "Configurar filtros para mostrar mais bônus no Alvo"
L["All Focus Buffs"] = "Todos os Bônus do Foco"
L["Set filters to show more buffs on Focus"] = "Configurar filtros para mostrar mais bônus no Foco"
L["All Focus Debuffs"] = "Todas as Penalidades do Foco"
L["Set filters to show more debuffs on Focus"] = "Configurar filtros para mostrar mais penalidades no Foco"
L["All Boss Buffs"] = "Todos os Bônus do Chefe"
L["Set filters to show more buffs on Boss"] = "Configurar filtros para mostrar mais bônus no Chefe"
L["All Boss Debuffs"] = "Todos as Penalidades do Chefe"
L["Set filters to show more debuffs on Boss"] = "Configurar filtros para mostrar mais penalidades no Chefe"
L["All Nameplate Buffs"] = "Todas Penalidades das Placas de Nome"
L["Set filters to show more buffs on Nameplates"] = "Configurar filtros para mostrar mais bônus nas placas de nome"
L["All Nameplate Debuffs"] = "Todas as Penalidades das Placas de Nome"
L["Set filters to show more debuffs on Nameplates"] = "Configurar filtros para mostrar mais penalidades nas placas de nome"
L["Setup Aura Filters to be Eltruism/ElvUI defaults"] = "Configurar Filtros de Aura para o padrão Eltruism/ElvUI"
L["Eltruism Player Buffs"] = "Bônus de Jogador Eltruism"
L["Set filters to be Eltruism defaults on Player"] = "Configurar filtros de jogador para os padrões Eltruism"
L["Eltruism Player Debuffs"] = "Penalidades de Jogador Eltruism"
L["Eltruism Target Debuffs"] = "Bônus de Alvo Eltruism"
L["Set filters to be Eltruism defaults on Target"] = "Configurar filtros de Alvo para os pardões Eltruism"
L["Eltruism Target Buffs"] = "Bônus de Alvo Eltruism"
L["Eltruism Focus Buffs"] = "Bônus de Foco Eltruism"
L["Set filters to be Eltruism defaults on Focus"] = "Configurar filtros de Foco para os padrões Eltruism"
L["Eltruism Focus Debuffs"] = "Penalidades de Foco Eltruism"
L["Eltruism Boss Buffs"] = "Penalidades de Chefe Eltruism"
L["Set filters to be Eltruism defaults on Boss"] = "Configurar filtros de Chefe para os padrões Eltruism"
L["Eltruism Boss Debuffs"] = "Penalidades de Chefe Eltruism"
L["Eltruism Nameplate Buffs"] = "Bônus de Placas de Nome Eltruism"
L["Set filters to be Eltruism defaults on Nameplates"] = "Configurar filtros de Placas de Nome para os padrões Eltruism"
L["Eltruism Nameplate Debuffs"] = "Penalidades de Placas de Nome Eltruism"
L["Addons"] = true
L["ElvUI Plugins"] = true
L["Reset to Eltruism defaults."] = "Resetar para os padrões Eltruism"
L["BossMods Profiles"] = "Perfis de BossMods"
L["Addon Profiles"] = "Perfis de Addon"
L["Combat Music"] = "Música de Combate"
L["Play music during combat"] = "Tocar música durante o combate"
L["Enable music during combat"] = "Habilitar música durante o combate"
L["Disable in Instances"] = "Desabilitar em Instâncias"
L["Example: "] = "Exemplo: "
L["CVars"] = true -- i dont know if this gets localized
L["Setup CVars"] = "Configurar CVars"
L["General CVars"] = "CVars Gerais"
L["It will set these CVars:"] = "Irá aplicar estas CVars:"
L["Party/Raid"] = "Grupo/Raide"
L["Play a sound when someone dies in Party or Raid"] = "Tocar um som quando alguém morre no Grupo ou Raide"
L["Select a Sound"] = "Selecione um Som"
L["Alternative unitframe layouts"] = "Layout alternativo para painéis"
L["DPS/Tank layouts were created with pure dps classes in mind, if you play a class with more raid cooldowns like a Shaman, Druid or Paladin you might want to use the alternative layout in order to make it easier for you to use your cooldowns on the members of your group"] =  "O Layout DPS/Tank foi criado pensando em classes que podem apenas causar dano, se você joga com uma classe que possui habilidades para grupo ou raide como Xamã, Druída ou Paladino você pode querer utilizr o layout alternativo para tornar a utilzação destas habilidades mais fácil"
L["Alternative Layout"] = "Layout Alternativo"
L["Original Layout"] = "Layout Original"
L["Media"] = "Mídia"
L["Setup Media"] = "Configurar Mídia"
L["Reset all Media"] = "Resetar todas as Mídias"
L["Reset Fonts, Textures, Skins to Eltreum UI defaults."] = "Resetar Fontes, Texturas e Skins para os padrões Eltruism."
L["Set the fonts used in Eltruism. Kimberley is the default font"] = "Configurar as fontes utilizadas no Eltruism. Kimberley é a fonte padrão"
L["This will set all ElvUI fonts as Kimberley"] = "Isto irá configurar todas as fontes ElvUI como Kimberley"
L["This will set all ElvUI fonts as Exo2"] = "Isto irá configurar todas as fontes ElvUI como Exo2"
L["This will set all ElvUI fonts as Gotham"] = "Isto irá configurar todas as fontes ElvUI como Gotham"
L["This will set all ElvUI fonts as Roboto"] = "Isto irá configurar todas as fontes ElvUI como Roboto"
L["Or choose a custom font"] = "Ou escolha uma fonte customizada"
L["Choose a different font from the preselected ones"] = "Escolha uma fonte diferente das pré-selecionadas"
L["Set the Font Outlines everywhere. Use Default to return to Eltruism default settings"] = "Configurar os Contornos de Todas as Fontes. Utilize o botão Padrão para retornar ao padrão de configuração Eltruism"
L["Defaults"] = "Padrão"
L["This will set fonts to Eltruism defaults, recommended for 4K"] = "Isto irá configurar as fontes para os padrões Eltruism, recomendado para 4K"
L["None"] = "Nenhum"  --as in no font outline
L["This will set fonts to no outline"] = "Isto irá configurar as fontes para nenhum contorno"
L["Outline"] = "Contorno"
L["This will set fonts to use outline, recommended for 1440p and 1080p"] = "Isto irá configurar as fontes para utilizar contornos, recomendado para 1440p e 1080p"
L["Thick Outline"] = "Contorno Grosso"
L["This will set fonts to use thick outline"] = "Isto irá configurar as fontes para utilziar contornos grossos"
L["Change the look of frames to Dark or Light mode"] = "Mude a aparência dos painéis para o modo Escuro ou Claro"
L["Dark Mode"] = "Modo Escuro"
L["This will set colors to black with class colors when losing health"] = "Isto irá configurar as cores para serem pretas, com cores de classe quando vida for perdida"
L["Light Mode"] = "Modo Claro"
L["This will set colors to class based with black backgrounds when losing health"] = "Isto írá configurar cores para utilizar cores de classe, com um fundo preto quando vida for perdida"
L["Dynamic Datatext that changes according to class to show Ammo or Soul Shards when playing Hunter, Warrior, Rogue or Warlock"] = "Texto de Informação Dinâmico que muda de acordo com sua classe para mostrar Munição ou Fragmentos de Alma quando estiver jogando como um Caçador, Guerreio, Ladrão ou Bruxo"
L["Enable the Dynamic Datatext"] = "Habilitar Texto de Informação Dinâmico"
L["Expand the Talents to show the entire tree"] = "Expandir os Talentos para mostrar a árvore inteira"
L["Expanded Talents"] = "Talentos Expandidos"
L["Expand Talents to cover the full tree"] = "Expandir os Talentos para mostrar a árvore inteira"
L["Nameplates"] = "Placas de Nome"
L["Class Colored Nameplate Options"] = "Opções de Cores de Classe para Placas de Nome"
L["Hover"] = "Fundo"
L["Change the color of the hover to be class colored"] = "Mudar a cor do fundo para ser igual a cor de classe"
L["Border"] = "Borda"
L["Change the color of the border glow to be class bordered in nameplates"] = "Mudar a cor do brilho de borda para ser igual a cor de classe em placas de nome"
L["Target Texture"] = "Textura do Alvo"
L["Change the texture of the nameplate to be a class gradient"] = "Mudar a textura da placa de nome para ser um gradiente da classe"
L["Control how Nameplates behave"] = "Controlar como as Placas de Nome se comportam"
L["Show Friendly Nameplates but Hide Healthbar"] = "Mostrar Placas de Nome amigavéis mas esconder barra de vida"
L["Hide Friendly Nameplates inside Instances"] = "Esconder Placas de Nome amigavéis dentro de Instâncias"
L["Hide Friendly Nameplates everywhere"] = "Esconder Placas de Nome amigavéis em todos os lugares"
L["Wide nameplate debuffs and buffs"] = "Achatar Penalidades e Bônus em Placa de Nomes"
L["Make Buffs and Debuffs Wide on Nameplates"] = "Mudar a aparência das Penalidades e Bônus em Placas de Nome"
L["Toggle On and Off"] = "Habilitar ou Desabilitar"
L["Enemy Nameplate Level"] = "Nível do Inimigo em Placas de Nome"
L["Hide level on enemy nameplates when you are max level"] = "Esconder nível nas placas de nome de inimigos quando você estiver no nível máximo"
L["Nameplate Power Bar"] = "Barra de Poder em Placa de Nome"
L["Enable Nameplate Power Bar"] = "Habilitar Barra de Poder em Placa de Nome"
L["Enable an extra Power Bar on Nameplates for missing powers"] = "Habilitar uma Barra de Poder extra me placas de nome par poderes que não aparecem"
L["Enable Auto-adjusting Buffs/Debuffs"] = "Habilitar auto ajuste de Bônus e Penalidade"
L["Enable Auto-adjusting the position of Buffs/Debuffs"] = "Habilitar ajuste automático da posição dos Bônus e Penalidades"
L["Enable Auto-adjusting the Vertical Position of the Power Bar"] = "Habilitar ajuste automático da posição vertical dos Bônus e Penalidades"
L["Power Bar will move automatically based on class/spec/druid form"] = "Barra de Poder irá mover automaticamente baseando na forma de druída ou classe atual"
L["Select the Y Offset for the Power Bar (Default 16)"] = "Selecione o deslocamento Y da Barra de Poder (Padrão 16)"
L["Set Y Offset"] = "Selecione o deslocamento Y"
L["Select the Horizontal Size of the Power Bar (Default 132)"] = "Selecione o tamanho horizontal da Barra de Poder (Padrão 132)"
L["Set Horizontal Size"] = "Selecione o tamanho horizontal"
L["Select the Vertical Size of the Power Bar (Default 6)"] = "Selecione o tamanho vertical da Barra de Poder (Padrão 6)"
L["Set Vertical Size"] = "Selecione o tamanho vertical"
L["Choose the Power Bar Texture"] = "Escolha a textura da Barra de Poder"
L["Select a Texture"] = "Selecione a Textura"
L["Select the power types to be displayed:"] = "Selecione os tipos de poder a serem exibidos"
L["Mana"] = true
L["Rage"] = "Raiva"
L["Energy"] = "Energia"
L["Loot"] = "Saque"
L["Show a floating loot text"] = "Mostrar um texto fluante para o texto de saque"
L["Choose which types of text:"] = "Escolha os tipos de texto:"
L["Honor"] = "Honra"
L["Currency"] = "Moedas"
L["Pets"] = "Mascotes"
L["Change the scale of LootText"] = "Mude a escala do LootText"
L["Set the size of LootText"] = "Selecione o tamanho do LootText"
L["Reset Scale"] = "Resetar a Escala"
L["Return LootText to its default scale"] = "Retornar o LootText para sua escala padrão"
L["Change the strata of the Loot Text"] = "Mudar o estrato do LootText"
L["Set the level that LootText will be drawn to this"] = "Configurar o nível no qual o LootText irá aparecer"
L["Background"] = "Fundo"
L["Low"] = "Baixo"
L["Medium"] = "Médio"
L["High"] = "Alto"
L["Dialog"] = "Diálogo"
L["Change the Horizontal Position of LootText (Default = 0)"] = "Mudar a Posição Horizontal do LootText (Pedrão = 0)"
L["Set X offset"] = "Selecione o deslocamento X"
L["Change the Vertical Position of LootText (Default = 200)"] = "Mudar a Posição Vertical do LootText(Padrão = 200)"
L["Change the font of LootText to be that the ElvUI Default Font found in General"] = "Mudar a fonte do LootText para ser igual a fonte ElvUI"
L["Use ElvUI General Font"] = "Utilizar a Fonte Geral ElvUI"
L["Change the font of LootText"] = "Mudar a fonte do LootText"
L["Chat"] = true
L["Chat Options"] = "Opções de Chat"
L["Enable ElvUI Chat modifications"] = "Habilitar modificações de Chat ElvUI"
L["Add fade over time, and mouse over to left and right chat panels"] = "Adicionar desaparecimento com o tempo e mouse passando aos paíneis de chat esquerdo e direito"
L["Add mouse over to the left chat panel"] = "Adicionar passamento de mouse ao paínel de chat esquerdo"
L["Left Chat Mouse Over"] = "Passamento de Mouse do Chat Esquerdo"
L["Toggle the option"] = "Habilitar ou Desabilitar a opção"
L["Add a fade to the left chat panel, controlled by ElvUI Chat > Text Fade > Inactivity Timer"] = true
L["Left Inactivity Fader"] = "Desaparecimento com Inatividade do Chat Esquerdo"
L["Add mouse over to the right chat panel"] = "Adicionar passamento de mouse ao paínel de chat direito"
L["Right Chat Mouse Over"] = "Passamento de Mouse do Chat Direito"
L["Add a fade to the right chat panel, controlled by ElvUI Chat > Text Fade > Inactivity Timer"] = true
L["Right Inactivity Fader"] = "Desaparecimento com Inatividade do Chat Direito"
L["Combat Hide"] = "Esconder em Combate"
L["Hide Left Chat in Combat"] = "Esconder Chat Esquerdo em Combate"
L["Hide Right Chat in Combat"] = "Esconder Chat Direito em Combate"
L["Invert left mouse click so that chat starts faded and mouse click will make it stop fading"] = "Inverter clique do botão esquerdo do mouse para que o chat começe escondido e um clique irá fazê-lo parar de esconder"
L["Invert Mouse Click"] = "Inverter Clique do Mouse"
L["Toggle the option on"] = "Habilitar a opção"
L["Stealth Vignette"] = "Vinheta da Furtividade"
L["Toggle a Stealth Effect"] = "Adicionar um efeito quando estiver Furtivo"
L["Add a vignette effect while in stealth"] = "Adicione um efeito de vinheta quando estiver em furtividade"
L["Turn the effect on"] = "Habilitar o efeito"
L["You can set your Weakauras to anchor to custom locations making it easier to move them"] = "Você pode configurar suas Weakauras para ancorar em lugares customizados o que torna elas mais fáceis de serem movidas"
L["In order to use this feature, simply go to your Weakaura, and go to its Group options, scroll down to Position Settings and set the Anchored To Select Frame, then type either |cff82B4ffEltruismWA|r or |cff82B4ffEltruismConsumablesWA|r to anchor the weakaura to the preset location"] = "Para utilizar este recurso, simplesmente vá até sua Weakaura e vá até suas opções de grupo, indo até as configurações de posição e selecione ancorar a paínel escolhido, então digite |cff82B4ffEltruismWA|r ou |cff82B4ffEltruismConsumablesWA|r para ancorar a weakaura a localização do paínel"
L["Setting "] = "Configuração"
L[" or "] = " ou "
L[" as the anchor will move them to the locations, keep in mind you might need to change the X and Y offset of the weakaura to zero"] = " como a âncora irá mover para a localização, lembre-se que você pode precisar mudar os deslocamentos X e Y da Weakaura para zero"
L["All weakauras"] = "Todas as weakauras"
L["Nameplate Power Bar"] = "Barra de Poder de Placa de Nome"
L["Boss nameplate at base"] = "Placa de Nome de Chefe na base"
L["Executes next to nameplates"] = "Executação ao lado da placa de nome"
L["Join the Discord if you have any questions or issues"] = "Junte-se ao Discord se você tiver questões ou problemas"
L["Keep in mind the discord is in English"] = "Lembre-se que o discord é em Inglês"
L["Changelog"] = "Mudanças"
L["Select a version:"] = "Selecione uma versão:"
L["Choose a version to see its changelog"] = "Escolha uma versão para visualizar as mudanças"
L["Credits"] = "Créditos"
L["Author"] = "Author"
L["Credits and Thank yous"] = "Créditos e Gratificações"
L["License"] = "Licensa"
L["Support"] = "Suporte"
L["New commits, basically a preview of fixes or upcoming features"] = "Novas mudanças, basicamente uma prévia de melhorias e novos recursos"
L["Report issues and problems here:"] = "Reporte erros e problemas aqui:"
L["Addon on Tukui:"] = "Addon no Tukui:"
L["Addon on CurseForge:"] = "Addon no CurseForge:"
L["Custom Glow"] = "Brilho Customizado"
L["Replace Blizzards Default Glow with a Custom Glow"] = "Troque o Brilho padrão da Blizzard por um customizado"
L["Select a Type"] = "Selecione um Tipo"
L["Autocast"] = true
L["Pixel"] = true
L["Blizzard"] = true  -- the company not the weather effect
L["Adds a Blizzard style glow using class color"] = "Adicione um brilho utilizando o estilo Blizzard com cores de classe"
L["Glow Colors"] = "Cores do Brilho"
L["Use Class Colors"] = "Utilizar Cores de Classe"
L["Toggle Class Colored glows"] = "Habilitar brilhos com Cores de Classe"
L["Custom Color"] = "Cor Customizada"
L["Pixel Glow"] = "Brilho Pixel"
L["Pixel Border"] = "Borda Pixel"
L["Enable a border for the Pixel Glow"] = true
L["Number of Pixels (Default is 9)"] = true
L["Set the number of pixels in pixel glow"] = true
L["Pixel Frequency (Default is 1)"] = true
L["Set the frequency pixel glow"] = true
L["Pixel Length (Default is 3)"] = true
L["Set the length of pixels"] = true
L["Pixel Thickness (Default is 5)"] = true
L["Set the thickness of pixels"] = true
L["Pixel Horizontal Offset (Default is 5)"] = true
L["Set the horizontal offset of pixels"] = true
L["Pixel Vertical Offset (Default is 5)"] = true
L["Set the vertical offset of pixels"] = true
L["Autocast Glow"] = true
L["Autocast Particle Groups (Default is 8)"] = true
L["Set the number of groups for autocast, for each group you get 4 particles"] = true
L["Autocast Frequency (Default is 0.8)"] = true
L["Speed for Autocast, set to negative to inverse direction of rotation"] = true
L["Autocast Scale (Default is 2)"] = true
L["Change the size of Autocast"] = true
L["Autocast Horizontal Offset (Default is 5)"] = true
L["Set the horizontal offset of autocast"] = true
L["Autocast Vertical Offset (Default is 5)"] = true
L["Set the vertical offset of autocast"] = true
L["Blizzard Glow"] = true
L["Blizzard Frequency (Default is 0.5)"] = true
L["Speed for Blizzard glow"] = true
L["Quests"] = true
L["Collapse Quests during Encounters/Boss Fights"] = true
L["Collapse Quests when the boss fight starts"] = true
L["Maps"] = true
L["Add a time to arrive below the waypoint"] = true
L["The time will be calculated based on player speed and distance"] = true
L["If the player is not moving then *** will show up since time cannot be calculated"] = true
L["If you move away from the waypoint the time will just increase"] = true
L["Add an ETA to waypoints"] = true  --translation note: eta means estimated time to arrive
L["Enable the /way and /waypoint commands"] = true  -- do not translate /way and /waypoint since the commands are not translated
L["You can type /way or /waypoint"] = true  -- do not translate /way and /waypoint since the commands are not translated
L["Use formats such as:"] = true
L["XX YY, XX.XX YY.YY, XX,XX YY,YY and XXX YYY"] = true
L["Other Formats can end up causing errors"] = true
L["Enable the /way and /waypoint commands"] = true -- do not translate /way and /waypoint since the commands are not translated
L["Astral power"] = true
L["Runic power"] = true
L["Insanity"] = true
L["Maelstrom"] = true
L["Fury"] = true
L["Focus"] = true
L["Select a type of music"] = true
L["Racial Music"] = true
L["Class Music"] = true
L["Skin Level Up, Boss Loot and Instance Entrance frames to be class colored"] = true
L["Enable the Skins"] = true
L["Expand Hunter Stables to show all pets and improve search"] = true
L["Enable the Expanded Stable"] = true
L["Expand Transmog Window to better show your character"] = true
L["Enable the Wider Transmog Window"] = true
L["Auto open the Rogue Order Hall, to avoid opening hold CTRL or SHIFT or ALT while talking to the NPC"] = true
L["Enable the Rogue Order Hall Auto Open"] = true
L["Enable Floating Reputation Changes"] = true
L["Enable the Floating Rep Text"] = true
L["Buffs have been updated for Open World"] = true
L["Buffs have been updated for Arenas"] = true
L["Shows Class Icons recolored by Releaf on all targets"] = true
L["Shows Class Icons recolored by Releaf on Player targets"] = true
L["Shows Class Icons by Blizzard on all targets"] = true
L["Shows Class Icons by Blizzard only on Player targets"] = true
L["Shows Class Icons with borders recolored by Releaf on all targets"] = true
L["Shows Class Icons with borders recolored by Releaf on Player targets"] = true
L["Hybrid"] = true
L["Enable a Dark Souls death animation"] = true
L["Plays an animation when you die"] = true
L["ElvUI NamePlates were setup."] = true
L["NamePlate Style Filters were set."] = true

--missing texts from February 2022
L["Eltruism Installer"] = true
L["Launch Eltruism Installer"] = true
L["Reset/Update Eltruism Settings"] = true
L["Launches the Eltruism install prompt"] = true
L["Resets/Updates Eltruism Settings to Eltreum's Defaults"] = true
L["Reset nameplates to Eltruism settings"] = true
L["Reset Chat to ElvUI Settings"] = true
L["Reset layout to Eltruism DPS/Tank"] = true
L["Reset layout to Eltruism Healer"] = true
L["Skip Plugins install message"] = true
L["Details v1 - Blizzard Flat Icons"] = true
L["Details v2 - Releaf Transparent Icons"] = true
L["Details v3 - Releaf Solid Icons"] = true
L["Enable Borders"] = true
L["Change the size of the borders:"] = true
L["Actionbar Thickness"] = true
L["Unitframe Thickness"] = true
L["(All settings require a reload)"] = true
L["Action Bar 1"] = true
L["Action Bar 2"] = true
L["Action Bar 3"] = true
L["Action Bar 4"] = true
L["Action Bar 5"] = true
L["Action Bar 6"] = true
L["Target Border"] = true
L["Target of Target Border"] = true
L["Border X offset"] = true
L["Border Y offset"] = true
L["Player Border"] = true
L["Player Castbar Border"] = true
L["Target Castbar Border"] = true
L["Nameplate Power Bar Border"] = true
L["Nameplate Power Bar Thickness"] = true
L["Enable Fast Loot"] = true
L["Decrease the time it takes for auto loot to work, works with TSM"] = true
L["Enable Fast Loot with Loot Quality Filter"] = true
L["Enable filtering item quality, items can still be looted by holding Shift or the mod key setup in Interface"] = true
L["Enable Fast Loot with Wishlist Filter"] = true
L["Items not on the wishlist will not be looted, items can still be looted by holding Shift or the mod key setup in Interface"] = true
L["Enable Wishlist Loot Warning"] = true
L["Show a toast if an item in the wishlist is looted"] = true
L["Enable Automatically Closing Loot Window"] = true
L["Loot Window will automatically close when using filters and the item desired is not found"] = true
L["Enable Screenshotting if an item from the wishlist is looted"] = true
L["Minimum Loot Quality Filter"] = true
L["Poor"] = true
L["Common"] = true
L["Uncommon"] = true
L["Rare"] = true
L["Epic"] = true
L["Only items of this quality or better will be looted when using Fast Loot Filter"] = true
L["Item Wishlist (type the Item ID)"] = true
L["Items in your wishlist will display a warning when looted"] = true
L["Invalid Item, you need to add an itemID which can be found in the tooltip or in Wowhead"] = true
L["Remove item from Wishlist"] = true
L["Remove"] = true
L["Add color to some chat messages"] = true
L["Enhance Item Links in Chat"] = true
L["Enable Chat Icons"] = true
L["Enable Item Levels"] = true
L["Customize the Chat tabs"] = true
L["Dark Chat"] = true
L["Transparent Chat"] = true
L["Make more texts use ElvUI font settings"] = true
L["Such as the Zones, Mail and others"] = true
L["Skin Objective Frame (when Shadow and Light and Windtools are not loaded)"] = true
L["Enable Wowhead Button on Quest Log"] = true
L["Show a button for Wowhead quest links"] = true
L["Enable Skin"] = true
L["Skin the Objective/Quest Frame"] = true
L["Remove Blizzard's Boss Emote Frame"] = true
L["Customize the player castbar spark"] = true
L["Cursor Sizes"] = true
L["Select how auras will be displayed for Player"] = true
L["Select how auras will be displayed for Target"] = true
L["Select how auras will be displayed for Focus"] = true
L["Select how auras will be displayed for Boss"] = true
L["Select how auras will be displayed for Nameplates"] = true
L["Enable cursor only during combat"] = true
L["Cursor will only show during combat"] = true
L["Add a cooldown icon when trying to use skills that are on cooldown, and a cooldown flash when they are ready"] = true
L["Attempt to fix Cursor Lag"] = true
L["Software cursor is how the cursor was before Battle for Azeroth, Hardware cursor is faster but will cause problems with addons that attach to it"] = true
L["Software Cursor"] = true
L["Hardware Cursor"] = true
L["Enable on Action Bars"] = true
L["Enable on Pet Bar"] = true
L["Enable on Nameplate"] = true
L["Add a glow when buffs or debuffs are expiring on nameplates"] = true
L["Adds an autocast style glow using class color"] = true
L["Adds a pixel style glow using class color"] = true
L["Preview the Glow"] = true
L["Preview"] = true
L["Preview the Glow, you will need to toggle it off and on to update the glow"] = true
L["Action Bars"] = true
L["Pet Bar"] = true
L["Nameplate Buff/Debuff"] = true
L["Customize CVars"] = true
L["Nameplate Other Bottom Inset"] = true
L["In screen % the inset from the Bottom"] = true
L["Nameplate Other Top Inset"] = true
L["In screen % the inset from the Top"] = true
L["Nameplate Target Radial Position"] = true
L["When target is off screen, position its nameplate radially around sides and bottom."] = true
L["Target Only"] = true
L["All in Combat"] = true
L["Camera Distance Max Zoom Factor"] = true
L["Maximum Camera Zoom Out"] = true
L["Hide Minimap while in Combat"] = true
L["Automatically hide the Minimap in combat"] = true
L["Dynamically toggle the mouseover of the Experience Bar"] = true
L["Shows XP bar when below max level, makes it mouseover when max level"] = true
L["Enable Entering/Leaving Combat Indicator Texts"] = true
L["Adds a +Combat and -Combat for when entering and leaving combat"] = true
L["Enable a Dark Souls death animation"] = true
L["Plays an animation when you die"] = true
L["Add Sounds to /roll when someone gets a 1 or a 100"] = true
L["Plays a sound if someone rolls 1 or 100 out 100"] = true
L["Change the Scale of the World Text"] = true
L["Such as the floating XP, floating reputation changes and others"] = true
L["Select the size of the World Text"] = true
L["Hide Talking Head"] = true
L["Prevent Blizzard's Talking Head from appearing"] = true
L["Automatically take Screenshots"] = true
L["Automatically take Screenshots such as when leveling up"] = true
L["Stealth"] = true
L["Item Deletion"] = true
L["Automatically type DELETE on the popup"] = true
L["Will not delete the item, will simply type DELETE instead you needing to type it"] = true
L["Blizzard Floating Combat Text"] = true
L["Disable Combat Text"] = true
L["Enable or disable Blizzard's default Floating Combat Text"] = true
L["Enable Resource Gains"] = true
L["Enable or disable Blizzard's default Floating Combat Text for Mana/Rage/Energy and other resouces"] = true
L["Swap Action Paging and visibility for Bar1 and Bar4"] = true
L["Enable Boss Music"] = true
L["Disable Combat Music in Instances"] = true
L["Normal Combat Music"] = true
L["Name of file inside Interface\\Addons"] = true
L["Boss Combat Music"] = true
L["Player Class Texture"] = true
L["Target Class Texture"] = true
L["Change the texture of the nameplate to be a class gradient of the player's class"] = true
L["Change the texture of the nameplate to be a class gradient of the target's class"] = true
L["Enable Automatically accepting/turning in Quests when not holding CTRL/SHIFT/ALT"] = true
L["You will automatically accept and turn in quests that do not require gold, are not weekly and are not daily"] = true
L["Accept Daily and Weekly quests"] = true
L["You will also automatically accept Daily and Weekly Quests"] = true
L["Invert CTRL/SHIFT/ALT"] = true
L["You will only accept and turn in quests if you hold CTRL/SHIFT/ALT while talking to the NPC"] = true
L["Quest Item Bar"] = true
L["Enable Quest Item Bar"] = true
L["Add a Quest Item bar, keybind can be changed in Keybinds > ElvUI Eltruism"] = true
L["Add a Quest Item bar, keybind can be changed in Key Bindings > ElvUI Eltruism"] = true
L["Quest Item Bar follows visibility settings for ElvUI Action Bar 1"] = true
L["The Quest Item Bar will appear only when ElvUI Action Bar 1 appears, following its settings"] = true
L["Quest Item Bar Button Mouse Over"] = true
L["Each Button in the Quest Item Bar will appear only if the cursor is over it"] = true
L["Quest Item Bar Button Size"] = true
L["Change the size of the button on the Quest Item Bar"] = true
L["Character Panel"] = true
L["Expand Character Art"] = true
L["Expand Character Panel"] = true
L["Add Crest to Character Panel"] = true
L["Art Alpha"] = true
L["Change the transparency of the Art"] = true
L["Add Class Icons to Character Panel"] = true
L["Enable this option"] = true
L["Use Blizzard Icons"] = true
L["Enable Blizzard Icons"] = true
L["Use Blizzard Icons colored by Releaf"] = true
L["Enable Releaf Icons"] = true
L["Add Shadows to Frames"] = true
L["Add Shadows to some frames"] = true
L["Enable General Shadows"] = true
L["Add Shadows to frames like Player, target, Chats and others"] = true
L["Other Shadows (can become CPU/Memory Intensive)"] = true
L["Nameplate Health"] = true
L["Add Shadows to Nameplate Healthbars"] = true
L["Nameplate Aura"] = true
L["Add Shadows to Nameplate Auras"] = true
L["Nameplate Portrait"] = true
L["Add Shadows to Nameplate Portraits"] = true
L["Nameplate Power"] = true
L["Add Shadows to Nameplate Powers"] = true
L["Nameplate Castbar"] = true
L["Add Shadows to Nameplate Castbars"] = true
L["Unitframe Aura"] = true
L["Add Shadows to Unitframe Auras"] = true
L["ActionBars"] = true
L["Add Shadows to Actionbars"] = true
L["Aura"] = true
L["Add Aura Shadows (Aura list next to the minimap)"] = true
L["Choose the Border Texture to be used:"] = true
L["Change the size of the borders:"] = true
L["Bar 1 X offset"] = true
L["Bar 1 Y offset"] = true
L["Bar 2 X offset"] = true
L["Bar 2 Y offset"] = true
L["Bar 3 X offset"] = true
L["Bar 3 Y offset"] = true
L["Bar 4 X offset"] = true
L["Bar 4 Y offset"] = true
L["Bar 5 X offset"] = true
L["Bar 5 Y offset"] = true
L["Bar 6 X offset"] = true
L["Bar 6 Y offset"] = true
L["How to use the Anchors"] = true
L["Open WeakAuras, go to your group Weakauras and in Group change Position Settings > Anchored To > Select Frame > EltruismWA or EltruismConsumablesWA"] = true
L["Hide Quests during Battlegrounds and Arenas"] = true
L["Eltruism uses a 0.7 scale, but ElvUI can calculate the best scale for you using the Automatic Scale option"] = true
L["Very High (but Optional)"] = true
L["DPS\nTank"] = true
L["Healer"] = true
L["Automatic\nScale"] = true
L["Alternative\nFrames"] = true
L["Or change it later in Eltruism > Media options"] = true
L["Eltruism Modes"] = true
L["Transparent\nChat"] = true
L["Details! DPS Meter"] = true
L["Choose the type of icons Details! will use:"] = true
L["PVP/PVE Addons"] = true
L["Import GladiusEx profile for arenas, remember to disable ElvUI Arena Frames"] = true
L["GladiusEx"] = true
L["Import Questie profile, which uses the DBM radar"] = true
L["Questie"] = true
L["Import DBM or BigWigs profiles for dungeons and raids. (Uses DBM English Calanon and Bigwigs Voice)"] = true
L["Import Method Raid Tools profile with raid cooldowns and other settings"] = true
L["Import profiles for Gladdy"] = true
L["Import profiles for Gladius"] = true
L["Gladdy is not installed or enabled (You can find the Gladius profile in Eltruism Settings)"] = true
L["Gladius profile can be found in Eltruism > Addons, please check it there"] = true
L["You have none of these addons installed or enabled"] = true
L["QOL Addons"] = true
L["Import a profile for Simpy's ElvUI FCT configured for Eltruism"] = true
L["Import a profile for NameplateSCT configured for Eltruism"] = true
L["NameplateSCT and ElvUI FCT are not installed or enabled"] = true
L["You have completed the installation process"] = true
L["Please click Finished to reload the UI"] = true
L["Shaman Totems"] = true
L["Enable on Shaman Totems"] = true
L["Enable on Shaman Fire Totem"] = true
L["Enable on Shaman Earth Totem"] = true
L["Enable on Shaman Water Totem"] = true
L["Enable on Shaman Air Totem"] = true
L["Shaman Fire Totem"] = true
L["Shaman Earth Totem"] = true
L["Shaman Water Totem"] = true
L["Shaman Air Totem"] = true
--didnt export earlier
L["Use Type Colors"] = true
L["Grey Background"] = true
L["Black Background"] = true
L["Show Buffs in Arena and hide them outside (will overwrite Eltruism default settings)"] = true
L["Hide Arena Frames in Arena due to Gladius/Gladdy or another addon"] = true
L["Hide Raid Unitframes in battlegrounds due to addons like Battleground Enemies"] = true
L["Hide Arena Frames in Arena due to Gladius/GladiusEX or another addon"] = true
L["Enable Combat Music"] = true
L["Disable in Battlegrounds/Arenas"] = true
L["Nameplate Power Bar"] = true
L["Nameplate Powerbar Position"] = true
L["Nameplate Powerbar Size"] = true
L["Nameplate Powerbar Position"] = true
L["Background Color"] = true
L["Skin Objective Frame"] = true
L["Enable Wowhead Button"] = true
L["Skin Profession Frame"] = true
L["Skin the Profession/Tradeskill Frame"] = true
L["Sockets and Enchants"] = true
L["Add Sockets and Enchants to the Character Panel"] = true
L["Item Levels"] = true
L["Ilvl Anchor Point"] = true
L["Choose where the Ilvl will be attach to on the items"] = true
L["Ilvl Font Outline"] = true
L["Choose the Ilvl font outline"] = true
L["Automatically swap the Character Stats to your main ones"] = true
L["Add Item Levels to the Character Panel"] = true
L["Enable a GTA death animation"] = true
L["Both Gladdy and Gladius are not installed or enabled"] = true
L["Enable for Error Frame"] = true
L["Enable for Boss Emote Frame"] = true
L["Enable for Zones, Mail and others"] = true
L["Only loads when Questie is not enabled"] = true
L["Customize Unitframe textures"] = true
L["Choose custom textures for some unitframes"] = true
L["Enable Custom Textures"] = true
L["Player Texture"] = true
L["Target of Target Texture"] = true
L["Focus Texture"] = true
L["Class Textures"] = true
L["Death Knight"] = true
L["Demon Hunter"] = true
L["Druid"] = true
L["Hunter"] = true
L["Mage"] = true
L["Monk"] = true
L["Paladin"] = true
L["Priest"] = true
L["Rogue"] = true
L["Shaman"] = true
L["Warlock"] = true
L["Warrior"] = true
L["Extra Media"] = true
L["Skip Plugins"] = true
L["!key Chat Command"] = true
L["Enable !key and !keys chat command"] = true
L["Will link your key and covenant in guild or party chat"] = true
L["Automatically screenshot when you loot an item from the wishlist"] = true
L["Collapse Quests during any combat event"] = true
L["Collapse Quests when you enter combat"] = true
L["Automatically Hide NPC Names"] = true
L["Hide NPC Names when they are too far away to have Nameplates"] = true
L["Restore Hidden Names"] = true
L["Restore Unit Names hidden by Hide NPC Names"] = true
L["This will set the background to be a grey color"] = true
L["This will set the background to be a black color"] = true
L["Set Width of the Spark (Default 3)"] = true
L["Customize Player CastBar Spark"] = true
L["Add more fonts to Shared Media"] = true
L["Enable Pixel Border"] = true
L["Enable ETA"] = true -- eta = estimated time to arrive
L["Enable Autopin"] = true
L["Automatically pin the Waypoint"] = true
L["Enable removing the Alert Frame that can show up in the middle of the screen"] = true
L["Hide Error Frame"] = true
L["Set the number of groups for autocast, for each group you get 4 particles"] = true
L["Enable Smart Classbar"] = true
L["Automatically hide the Classbar if the Target is Friendly, show if it is an enemy"] = true
L["Cursor Colors"] = true
L["Cursor Sizes "] = true
L["Make the warnings to install profiles for other plugins stop"] = true
L["Error Frame Font Size"] = true
L["Boss Emote Frame Font Size"] = true
L["Add Item Levels to the Inspect Panel"] = true
L["Backdrops"] = true
L["Backdrop Texture"] = true
L["Backdrop Alpha"] = true
L["Change the transparency of the backdrop"] = true
L["Font"] = true
L["Font Size"] = true
L["Nameplate Powerbar Font"] = true
L["Choose a font for the Nameplate Powerbar Text"] = true
L["Nameplate Powerbar Font Size"] = true
L["Shows the Leader Icon or Assist icon if the unit is Leader or Assist"] = true
L["Abbreviates the unit name once it goes over 20 characters, made by Azilroka"] = true
L["Adds a line break"] = true
L["Gradient Colors"] = true
L["Enable Gradient colors for Health"] = true
L["Enable for Group Units"] = true
L["Enable Custom Colors"] = true
L["Gradient Orientation"] = true
L["Choose the direction of the gradient"] = true
L["Gradient Texture"] = true
L["Color 1"] = true
L["Color 2"] = true
L["Toggle the Click Casting Menu"] = true
L["Instance Texts"] = true
L["Instance Text Color"] = true
L["Font Size"] = true
L["Instance text Font Size"] = true
L["Dungeon"] = true
L["The text displayed when in a normal dungeon"] = true
L["Dungeon (Heroic)"] = true
L["The text displayed when in a heroic dungeon"] = true
L["Dungeon (Timewalking)"] = true
L["The text displayed when in a timewalking dungeon"] = true
L["Dungeon (Mythic)"] = true
L["The text displayed when in a mythic dungeon"] = true
L["Dungeon (Mythic Plus)"] = true
L["The text displayed when in a mythic plus dungeon"] = true
L["Raid (Normal)"] = true
L["The text displayed when in a normal raid"] = true
L["Raid (Heroic)"] = true
L["The text displayed when in a heroic raid"] = true
L["Raid (LFR)"] = true
L["The text displayed when in a lfr raid"] = true
L["Raid (Mythic)"] = true
L["The text displayed when in a mythic raid"] = true
L["Raid (Timewalking)"] = true
L["The text displayed when in a timewalking raid"] = true
L["Guild"] = true
L["The text displayed when in a guild group"] = true
L["Eltruism uses Dark Mode by default"] = true
L["You can switch to Light Mode or Gradient Mode by clicking the buttons below"] = true
L["You can customize the textures and colors in Eltruism > Unitframes"] = true
L["Eltruism uses Transparent chat by default"] = true
L["You can switch to Dark Chat by clicking the buttons below"] = true
L["Add Sockets and Enchants to the Inspect Frame"] = true
L["Add Shadows to Raid Frames"] = true
L["Left Click:"] = true
L["Right Click:"] = true
L["Open Eltruism Installation"] = true
L["Eltruism Honor/Conquest Points"] = true
L["Dark Power Background"] = true
L["Sets Class Power backgrounds to be black"] = true
L["Change the Class Power background"] = true
L["Player Castbar Texture"] = true
L["Enable Auto-adjusting the actionbar spacing and position"] = true
L["Adjusts actionbar spacing and position based on borders being enabled or not"] = true
L["Enable Unitframe Modifications"] = true
L["Enable changing textures and gradients for ElvUI unitframes"] = true
L["Choose between custom textures or gradient mode"] = true
L["Enable Gradient"] = true
L["Apply"] = true
L["Apply the mode selected"] = true
L["Friendly NPC"] = true
L["Neutral NPC"] = true
L["Unfriendly NPC"] = true
L["Hostile NPC"] = true
L["Original Group, Raid and Raid40 layout has been set"] = true
L["Alternative Group, Raid and Raid40 layout has been set"] = true
L["Spell Haste"] = true
L["Enable for Player"] = true
L["Enable for Target"] = true
L["Enable for Target of Target"] = true
L["Enable for Focus"] = true
L["Enable for Boss"] = true
L["Enable a Custom death animation"] = true
L["Custom Death Text"] = true
L["The text displayed when you die using the custom text option"] = true
L["Feel free to explore Eltruism settings in ElvUI > Eltruism. There are lot of settings that are disabled by default."] = true
L["Show Eltruism Game Menu Button"] = true
L["Target"] = true
L["Unitframes"] = true
L["Shadows"] = true
L["Cursor Type"] = true
L["Show a Battle Resurrection Count and Cooldown Frame"] = true
L["Enables a frame that shows a cooldown and count for battle ressurections while in an instance that has them"] = true
L["Choose the Progress Bar Texture"] = true
L["Add Class Gradient Colors to Stats"] = true
L["Enable for Target Castbar"] = true
L["Enable for Arena"] = true
L["Enable for Player Castbar"] = true
L["Enable pet cooldown tracking"] = true
L["Attributes"] = true
L["Item Level"] = true
L["Specialization"] = true
L["Other Skins"] = true
L["Skin MeetingHorn"] = true
L["Add a gradient color to the Experience Bar"] = true
L["Pet Border"] = true
L["Import Capping profile for battlegrounds"] = true
L["Import BattlegroundEnemies profile for battlegrounds"] = true
L["Import WarpDeplete profile for Mythic Plus"] = true
L["WarpDeplete profile requires an import per class in order to have the correct texture"] = true
L["BattlegroundEnemies is not installed or enabled"] = true
L["Capping is not installed or enabled"] = true
L["WarpDeplete is not installed or enabled"] = true
L["Version 1"] = true
L["Version 2"] = true
L["Light Mode Texture Version"] = true
L["Nameplate Texture Version"] = true
L["Enable Gradient (Requires Dark or Light Modes)"] = true
L["Automatically Detect Classes for Player, Target, Target of Target and Focus"] = true
L["Friendly NPC"] = true
L["Neutral NPC"] = true
L["Unfriendly NPC"] = true
L["Hostile NPC"] = true
L["Use the custom texture based on it's class instead of general texture for Player, Target, Target of Target and Focus"] = true
L["Party Border"] = true
L["Raid Border"] = true
L["Focus Border"] = true
L["Aura Border X offset"] = true
L["Aura Border Y offset"] = true
L["Left Chat Border X offset"] = true
L["Left Chat Border Y offset"] = true
L["Right Chat Border X offset"] = true
L["Right Chat Border Y offset"] = true
L["Other"] = true
L["Raid40 Border"] = true
L["Enable for Target of Target of Target"] = true
L["Target of Target of Target Texture"] = true
L["Player Castbar"] = true
L["Player Castbar (Interrupted)"] = true
L["Player Castbar (Non Interruptible)"] = true
L["Enable for Player Castbar (Non Interruptible)"] = true
L["Enable for Player Castbar (Interrupted)"] = true
L["Enable Gradient colors for Player Castbar (Interrupted)"] = true
L["Target Castbar"] = true
L["Target Castbar (Non Interruptible)"] = true
L["Enable for Target Castbar (Non Interruptible)"] = true
L["Enable Gradient colors for Target Castbar (Non Interruptible)"] = true
L["Target Castbar (Interrupted)"] = true
L["Enable for Target Castbar (Interrupted)"] = true
L["Enable Gradient colors for Target Castbar (Interrupted)"] = true
L["Version 3"] = true
L["Debuff Timer"] = true
L["Time at which the glow will start"] = true
L["Group Unitframe Thickness"] = true
L["Castbar Thickness"] = true
L["Pet Thickness"] = true
L["Focus Thickness"] = true
L["Boss Thickness"] = true
L["Aura Thickness"] = true
L["Chat Thickness"] = true
L["Minimap Thickness"] = true
L["Class Colors"] = true
L["Use Class Colors instead of Custom Colors"] = true
L["NPCs use Target Castbar colors not NPC colors for their castbars"] = true
L["Shows level difference when it exists for NPCs and players, hides for players if same level"] = true
L["Shows the current Death Knight presence"] = true
L["Displays the number of the group for the first member of that group, raid sorting can break this tag making it show up on other members."] = true
L["Cooldown Sound"] = true
L["Play a Sound when attempting to use a skill that is on cooldown."] = true
L["Stance Bar Thickness"] = true
L["Stance Bar"] = true
L["Stance X offset"] = true
L["Stance Y offset"] = true
L["Shaman Totem Bar"] = true
L["Shaman Totem Thickness"] = true
L["Totem X offset"] = true
L["Totem Y offset"] = true
L["Requires Light Mode Enabled"] = true
L["Pet Action Bar"] = true
L["Pet Action Bar X offset"] = true
L["Pet Action Bar Y offset"] = true
L["Pet Action Bar Thickness"] = true
L["Background Texture Type"] = true
L["Choose between a Class, Race or Custom Background"] = true
L["Class"] = true
L["Race"] = true
L["Custom"] = true
L["Example: "] = true
L["Add Item Quality Texture"] = true
L["Focus Castbar Border"] = true
L["Displays shortvalue HP and a status symbol from Releaf for players. Usage: [eltruism:hpstatus{number,number}]"] = true
L["Displays a disconnect symbol from Releaf when unit is disconnected. Usage: [eltruism:dc{number}]"] = true
L["Displays a dead symbol from Releaf when unit is dead. Usage: [eltruism:dead{number}]"] = true
