local L = ElvUI[1].Libs.ACL:NewLocale("ElvUI", "ruRU")
if not L then return end
-- Core
L["4K resolution detected, setting fonts to default mode."] = true
L["1440p resolution detected, setting fonts to outline mode."] = true
L["1080p resolution detected, setting fonts to outline mode."] = true
L["Fonts were set to Outline due to your resolution."] = true
L["EltruismConsumablesWA"] = true
--Install
L["General CVars have been set."] = true
L["NamePlate CVars have been set."] = true
L["AddOnSkins profile has been set."] = true
L["Immersion profile has been set."] = true
L["BigWigs profile has been set."] = true
L["DBM profile has been set."] = true
L["Details profile has been set."] = true
L["Dynamic Cam profile has been set."] = true
L["GladiusEx profile has been set."] = true
L["Method Raid Tools profile has been set."] = true
L["ProjectAzilroka profile has been set."] = true
L["Questie profile has been set."] = true
L["NameplateSCT profile has been set."] = true
L["Floating Combat Text profile has been set."] = true
L["Gladius profile has been set."] = true
L["Gladdy profile has been set."] = true
L["Area does not support waypoints"] = true
L["Unsupported format"] = true
L["Unsupported format or Area does not support waypoints"] = true
L["WARNING"] = true
L["Make sure to install "] = true
L["Shadow and Light"] = true
L[" and "] = true
L["WindTools"] = true
L["AddOnSkins"] = true
L["ProjectAzilroka"] = true
L["This prompt will help you install "] = true
L[" and import its settings"] = true
L["Please read the instructions to avoid issues"] = true
L["Skip Install"] = true
L["Layouts"] = true
L["Please select the role for your character, which will create a new profile.\nThis process can take a few seconds"] = true
L["You can support the group with your class, if you select DPS/Tank then its recommended to click Alternative Frames after clicking DPS/Tank"] = true
L["Importance: "] = true
L["Very High"] = true
L["Fonts"] = true
L["Eltruism uses Kimberley as the default font"] = true
L["You can replace it with one of the following:"] = true
L["Optional"] = true
L["Your current settings will be lost, please back them up"] = true
L["Import Details! profile with dual panels"] = true
L["You can right click the bottom right arrow to toggle the Details! Window"] = true
L["Remember to swap the second window to Healing Done or Tiny Threat"] = true
L["Details is an advanced combat parser"] = true
L["It has many plugins to choose from"] = true
L["Boss Mods"] = true
L["Import DBM or Bigwigs profiles"] = true
L["DBM is not installed or enabled so BigWigs will be used"] = true
L["BigWigs is not installed or enabled so DBM will be used"] = true
L["DBM uses DBM English by Calanon as a voice pack"] = true
L["Both DBM and BigWigs are not installed or enabled"] = true
L["Method Raid Tools"] = true
L["Import profiles for NameplateSCT or ElvUI Floating Combat Text"] = true
L["FCT profile will be used"] = true
L["NameplateSCT profile will be used"] = true
L["Import "] = true
L["settings configured for "] = true
L[" is not installed or enabled"] = true
L["Import Dynamic Cam profile"] = true
L["Welcome"] = true
L["Join the Discord if you have any questions or issues (English Support)"] = true
L["Installation Complete"] = true
L["Finished"] = true
L["Questie is not installed or enabled"] = true
L["Arenas"] = true
L["Abbreviates the unit name once it goes over 16 characters, made by Azilroka"] = true
L["updated to "] = true
L["Layout has been set."] = true
L["General Layout has been set."] = true
L["The alternative layout was made for the Eltruism DPS/Tank profile, please switch to it to use it"] = true
L["The original layout was made for the Eltruism DPS/Tank profile, please switch to it to use it"] = true
L["You need to be using an Eltruism profile in order to use this function"] = true
L["Debuff filters were setup"] = true
L["Buff filters were setup"] = true
L["ElvUI Chat has been set."] = true
-- Datatext
L["Eltruism Ammo"] = true
L["Open Eltruism Configuration Panel"] = true
L["Eltruism Config"] = true
-- Fonts
L["Your custom font has been set."] = true
L["Kimberley Font has been set."] = true
L["Exo2 Font has been set."] = true
L["GothamNarrow Black Font has been set."] = true
L["Roboto Font has been set."] = true
L["Crystalzcuhei Font has been set."] = true
--LootText
L["Silver"] = true -- the coin type exactly as it is in game, or the function will not work for the location
L["Gold"] = true -- the coin type exactly as it is in game, or the function will not work for the location
L["Copper"] = true -- the coin type exactly as it is in game, or the function will not work for the location
L["Soul Ash"] = true -- the currency exactly as it is in game, or the function will not work for the location
--Options
L["Installer"] = true
L["Clear Details! Damage Meter tables to free up memory"] = true
L["Clear Details Tables"] = true
L["Set Details tables to be empty"] = true
L["Install"] = true
L["A.F.K"] = true -- away from keyboard, can be longer in other languages
L["Play music while you are AFK"] = true
L["Enable"] = true
L["Cursor"] = true
L["Change the size of the World of Warcraft Cursor"] = true
L["Select a size"] = true
L["Choose this size"] = true
L["Autodetect"] = true
L["Add GCD, Cast and Combat indicator rings to the cursor"] = true
L["Enable cooldown tracking"] = true
L["Enable cursor rings for Casts, GCD and Combat"] = true
L["Add a rings around the mouse cursor for GCD, casts and combat"] = true
L["Choose a type of cursor by clicking it"] = true
L["Currently selected cursor: "] = true
L["Type 1"] = true
L["Type 2"] = true
L["Type 3"] = true
L["Type 4"] = true
L["Type 5"] = true
L["Type 6"] = true
L["Type 7"] = true
L["Type 8"] = true
L["Type 9"] = true
L["Type 10"] = true
L["The Cursor will use this type as its texture"] = true
L["Requires a Reload"] = true
L["Class Colored Casts"] = true
L["Use Class Colors for Cast"] = true
L["Custom Color Cast"] = true
L["Class Colored GCD"] = true
L["Use Class Colors for GCD"] = true
L["Custom Color GCD"] = true
L["Class Colored Combat"] = true
L["Use Class Colors for Cursor"] = true
L["Custom Color Combat"] = true
L["Cast Radius (Default: 25)"] = true
L["Cast Thickness (Default: 5)"] = true
L["Set the radius of the cast cursor"] = true
L["GCD Radius (Default: 20)"] = true
L["Set the radius of the gcd cursor"] = true
L["GCD Thickness (Default: 5)"] = true
L["Set the thickness of the gcd cursor"] = true
L["Combat Cursor Radius (Default: 15)"] = true
L["Set the radius of the combat cursor"] = true
L["Combat Cursor Thickness (Default: 5)"] = true
L["Set the thickness of the combat cursor"] = true
L["Aura Filters"] = true
L["For Shadowlands, import aura filters by copying the code below and going into Profiles > Import Profile."] = true
L["Setup Aura Filters to show all"] = true
L["All Player Buffs"] = true
L["Set filters to show more buffs on Player"] = true
L["All Player Debuffs"] = true
L["Set filters to show more debuffs on Player"] = true
L["All Target Debuffs"] = true
L["Set filters to show more debuffs on Target"] = true
L["All Target Buffs"] = true
L["Set filters to show more buffs on Target"] = true
L["All Focus Buffs"] = true
L["Set filters to show more buffs on Focus"] = true
L["All Focus Debuffs"] = true
L["Set filters to show more debuffs on Focus"] = true
L["All Boss Buffs"] = true
L["Set filters to show more buffs on Boss"] = true
L["All Boss Debuffs"] = true
L["Set filters to show more debuffs on Boss"] = true
L["All Nameplate Buffs"] = true
L["Set filters to show more buffs on Nameplates"] = true
L["All Nameplate Debuffs"] = true
L["Set filters to show more debuffs on Nameplates"] = true
L["Setup Aura Filters to be Eltruism defaults"] = true
L["Eltruism Player Buffs"] = true
L["Set filters to be Eltruism defaults on Player"] = true
L["Eltruism Player Debuffs"] = true
L["Eltruism Target Debuffs"] = true
L["Set filters to be Eltruism defaults on Target"] = true
L["Eltruism Target Buffs"] = true
L["Eltruism Focus Buffs"] = true
L["Set filters to be Eltruism defaults on Focus"] = true
L["Eltruism Focus Debuffs"] = true
L["Eltruism Boss Buffs"] = true
L["Set filters to be Eltruism defaults on Boss"] = true
L["Eltruism Boss Debuffs"] = true
L["Eltruism Nameplate Buffs"] = true
L["Set filters to be Eltruism defaults on Nameplates"] = true
L["Eltruism Nameplate Debuffs"] = true
L["Addons"] = true
L["ElvUI Plugins"] = true
L["Reset to Eltruism defaults."] = true
L["BossMods Profiles"] = true
L["Addon Profiles"] = true
L["Combat Music"] = true
L["Play music during combat"] = true
L["Enable music during combat"] = true
L["Disable in Instances"] = true
L["CVars"] = true -- i dont know if this gets localized
L["Setup CVars"] = true
L["General CVars"] = true
L["It will set these CVars:"] = true
L["Party/Raid"] = true
L["Play a sound when someone dies in Party or Raid"] = true
L["Select a Sound"] = true
L["Alternative unitframe layouts"] = true
L["DPS/Tank layouts were created with pure dps classes in mind, if you play a class with more raid cooldowns like a Shaman, Druid or Paladin you might want to use the alternative layout in order to make it easier for you to use your cooldowns on the members of your group"] = true
L["Alternative Layout"] = true
L["Original Layout"] = true
L["Media"] = true
L["Setup Media"] = true
L["Reset all Media"] = true
L["Reset Fonts, Textures, Skins to Eltreum UI defaults."] = true
L["Set the fonts used in Eltruism. Kimberley is the default font"] = true
L["This will set all ElvUI fonts as Kimberley"] = true
L["This will set all ElvUI fonts as Exo2"] = true
L["This will set all ElvUI fonts as Gotham"] = true
L["This will set all ElvUI fonts as Roboto"] = true
L["Or choose a custom font"] = true
L["Choose a different font from the preselected ones"] = true
L["Set the Font Outlines everywhere. Use Default to return to Eltruism default settings"] = true
L["Defaults"] = true
L["This will set fonts to Eltruism defaults, recommended for 4K"] = true
L["None"] = true --as in no font outline
L["This will set fonts to no outline"] = true
L["Outline"] = true
L["This will set fonts to use outline, recommended for 1440p and 1080p"] = true
L["Thick Outline"] = true
L["This will set fonts to use thick outline"] = true
L["Change the look of frames to Dark or Light mode"] = true
L["Dark Mode"] = true
L["This will set colors to black with class colors when losing health"] = true
L["Light Mode"] = true
L["This will set colors to class based with black backgrounds when losing health"] = true
L["Dynamic Datatext that changes according to class to show Ammo or Soul Shards when playing Hunter, Warrior, Rogue or Warlock"] = true
L["Enable the Dynamic Datatext"] = true
L["Expand the Talents to show the entire tree"] = true
L["Expanded Talents"] = true
L["Expand Talents to cover the full tree"] = true
L["Nameplates"] = true
L["Class Colored Nameplate Options"] = true
L["Hover"] = true
L["Change the color of the hover to be class colored"] = true
L["Border"] = true
L["Change the color of the border glow to be class bordered in nameplates"] = true
L["Target Texture"] = true
L["Change the texture of the nameplate to be a class gradient"] = true
L["Control how Blizzard Friendly Nameplates behave"] = true
L["Show Blizzard Friendly Nameplates but Hide Healthbar"] = true
L["Hide Blizzard Friendly Nameplates inside Instances"] = true
L["Hide Blizzard Friendly Nameplates everywhere"] = true
L["Wide nameplate debuffs and buffs"] = true
L["Make Buffs and Debuffs Wide on Nameplates"] = true
L["Toggle On and Off"] = true
L["Enemy Nameplate Level"] = true
L["Hide level on enemy nameplates when you are max level"] = true
L["Enable Nameplate Power Bar"] = true
L["Enable an extra Power Bar on Nameplates for missing powers"] = true
L["Enable Auto-adjusting Buffs/Debuffs"] = true
L["Enable Auto-adjusting the position of Buffs/Debuffs"] = true
L["Enable Auto-adjusting the Vertical Position of the Power Bar"] = true
L["Power Bar will move automatically based on class/spec/druid form"] = true
L["Select the Y Offset for the Power Bar (Default 16)"] = true
L["Set Y Offset"] = true
L["Select the Horizontal Size of the Power Bar (Default 132)"] = true
L["Set Horizontal Size"] = true
L["Select the Vertical Size of the Power Bar (Default 6)"] = true
L["Set Vertical Size"] = true
L["Choose the Power Bar Texture"] = true
L["Select a Texture"] = true
L["Select the power types to be displayed:"] = true
L["Show a floating loot text"] = true
L["Choose which types of text:"] = true
L["Honor"] = true
L["Currency"] = true
L["Pets"] = true
L["Change the scale of LootText"] = true
L["Set the size of LootText"] = true
L["Reset Scale"] = true
L["Return LootText to its default scale"] = true
L["Change the strata of the Loot Text"] = true
L["Set the level that LootText will be drawn to this"] = true
L["Background"] = true
L["Low"] = true
L["Medium"] = true
L["High"] = true
L["Dialog"] = true
L["Change the Horizontal Position of LootText (Default = 0)"] = true
L["Set X offset"] = true
L["Change the Vertical Position of LootText (Default = 200)"] = true
L["Change the font of LootText to be the ElvUI Default Font found in General"] = true
L["Use ElvUI General Font"] = true
L["Change the font of LootText"] = true
L["Chat Options"] = true
L["Enable ElvUI Chat modifications"] = true
L["Add fade over time, and mouse over to left and right chat panels"] = true
L["Left Chat Mouse Over"] = true
L["Toggle the option"] = true
L["Add a fade to the left chat panel, controlled by ElvUI Chat > Text Fade > Inactivity Timer"] = true
L["Left Inactivity Fader"] = true
L["Add mouse over to the left chat panel"] = true
L["Right Chat Mouse Over"] = true
L["Add a fade to the right chat panel, controlled by ElvUI Chat > Text Fade > Inactivity Timer"] = true
L["Right Inactivity Fader"] = true
L["Combat Hide"] = true
L["Hide Left Chat in Combat"] = true
L["Hide Right Chat in Combat"] = true
L["Invert left mouse click so that chat starts faded and mouse click will make it stop fading"] = true
L["Invert Mouse Click"] = true
L["Toggle the option on"] = true
L["Stealth Vignette"] = true
L["Toggle a Stealth Effect"] = true
L["Add a vignette effect while in stealth"] = true
L["Turn the effect on"] = true
L["You can set your Weakauras to anchor to custom locations making it easier to move them"] = true
L["In order to use this feature, simply go to your Weakaura, and go to its Group options, scroll down to Position Settings and set the Anchored To Select Frame, then type either |cff82B4ffEltruismWA|r or |cff82B4ffEltruismConsumablesWA|r to anchor the weakaura to the preset location"] = true
L["Setting "] = true
L[" or "] = true
L[" as the anchor will move them to the locations, keep in mind you might need to change the X and Y offset of the weakaura to zero"] = true
L["All weakauras"] = true
L["Boss nameplate at base"] = true
L["Executes next to nameplates"] = true
L["Join the Discord if you have any questions or issues"] = true
L["Keep in mind the discord is in English"] = true
L["Changelog"] = true
L["Select a version:"] = true
L["Choose a version to see its changelog"] = true
L["Author"] = true
L["Credits and Thank yous"] = true
L["License"] = true
L["New commits, basically a preview of fixes or upcoming features"] = true
L["Report issues and problems here:"] = true
L["Addon on Tukui:"] = true
L["Addon on CurseForge:"] = true
L["Custom Glow"] = true
L["Replace Blizzards Default Glow with a Custom Glow"] = true
L["Select a Type"] = true
L["Autocast"] = true
L["Pixel"] = true
L["Blizzard"] = true -- the company not the weather effect
L["Adds a Blizzard style glow using class color"] = true
L["Glow Colors"] = true
L["Use Class Colors"] = true
L["Toggle Class Colored glows"] = true
L["Custom Color"] = true
L["Pixel Glow"] = true
L["Pixel Border"] = true
L["Enable a border for the Pixel Glow"] = true
L["Number of Pixels (Default is 9)"] = true
L["Set the number of pixels in pixel glow"] = true
L["Pixel Frequency (Default is 1)"] = true
L["Set the frequency pixel glow"] = true
L["Pixel Length (Default is 3)"] = true
L["Set the length of pixels"] = true
L["Pixel Thickness (Default is 5)"] = true
L["Set the thickness of pixels"] = true
L["Pixel Horizontal Offset (Default is 5)"] = true
L["Set the horizontal offset of pixels"] = true
L["Pixel Vertical Offset (Default is 5)"] = true
L["Set the vertical offset of pixels"] = true
L["Autocast Glow"] = true
L["Autocast Particle Groups (Default is 8)"] = true
L["Autocast Frequency (Default is 0.8)"] = true
L["Speed for Autocast, set to negative to inverse direction of rotation"] = true
L["Autocast Scale (Default is 2)"] = true
L["Change the size of Autocast"] = true
L["Autocast Horizontal Offset (Default is 5)"] = true
L["Set the horizontal offset of autocast"] = true
L["Autocast Vertical Offset (Default is 5)"] = true
L["Set the vertical offset of autocast"] = true
L["Blizzard Glow"] = true
L["Blizzard Frequency (Default is 0.5)"] = true
L["Speed for Blizzard glow"] = true
L["Collapse Quests during Encounters/Boss Fights"] = true
L["Collapse Quests when the boss fight starts"] = true
L["Maps"] = true
L["Add a time to arrive below the waypoint"] = true
L["The time will be calculated based on player speed and distance"] = true
L["Credits"] = true
L["If the player is not moving then *** will show up since time cannot be calculated"] = true
L["If you move away from the waypoint the time will just increase"] = true
L["Add an ETA to waypoints"] = true --translation note: eta means estimated time to arrive
L["Enable the /way and /waypoint commands"] = true -- do not translate /way and /waypoint since the commands are not translated
L["You can type /way or /waypoint"] = true -- do not translate /way and /waypoint since the commands are not translated
L["Use formats such as:"] = true
L["XX YY, XX.XX YY.YY, XX,XX YY,YY and XXX YYY"] = true
L["Other Formats can end up causing errors"] = true
L["Enable the /way and /waypoint commands"] = true -- do not translate /way and /waypoint since the commands are not translated
L["Select a type of music"] = true
L["Racial Music"] = true
L["Class Music"] = true
L["Skin Level Up, Boss Loot and Instance Entrance frames to be class colored"] = true
L["Enable the Skins"] = true
L["Expand Hunter Stables to show all pets and improve search"] = true
L["Enable the Expanded Stable"] = true
L["Expand Transmog Window to better show your character"] = true
L["Enable the Wider Transmog Window"] = true
L["Auto open the Rogue Order Hall, to avoid opening hold CTRL or SHIFT or ALT while talking to the NPC"] = true
L["Enable the Rogue Order Hall Auto Open"] = true
L["Enable Floating Reputation Changes"] = true
L["Enable the Floating Rep Text"] = true
L["Buffs have been updated for Open World"] = true
L["Buffs have been updated for Arenas"] = true
L["Shows Class Icons recolored by Releaf on all targets"] = true
L["Shows Class Icons recolored by Releaf on Player targets"] = true
L["Shows Class Icons by Blizzard on all targets"] = true
L["Shows Class Icons by Blizzard only on Player targets"] = true
L["Shows Class Icons with borders recolored by Releaf on all targets"] = true
L["Shows Class Icons with borders recolored by Releaf on Player targets"] = true
L["Hybrid"] = true
L["ElvUI NamePlates were setup."] = true
L["NamePlate Style Filters were set."] = true

--missing texts from February 2022
L["Eltruism Installer"] = true
L["Launch Eltruism Installer"] = true
L["Reset/Update Eltruism Settings"] = true
L["Launches the Eltruism install prompt"] = true
L["Resets/Updates Eltruism Settings to Eltreum's Defaults"] = true
L["Reset nameplates to Eltruism settings"] = true
L["Reset Chat to ElvUI Settings"] = true
L["Reset layout to Eltruism DPS/Tank"] = true
L["Reset layout to Eltruism Healer"] = true
L["Skip Plugins install message"] = true
L["Details v1 - Blizzard Flat Icons"] = true
L["Details v2 - Releaf Transparent Icons"] = true
L["Details v3 - Releaf Solid Icons"] = true
L["Enable Borders"] = true
L["Actionbar Thickness"] = true
L["Unitframe Thickness"] = true
L["(All settings require a reload)"] = true
L["Action Bar 1"] = true
L["Action Bar 2"] = true
L["Action Bar 3"] = true
L["Action Bar 4"] = true
L["Action Bar 5"] = true
L["Action Bar 6"] = true
L["Target Border"] = true
L["Target of Target Border"] = true
L["Border X offset"] = true
L["Border Y offset"] = true
L["Player Border"] = true
L["Player Castbar Border"] = true
L["Target Castbar Border"] = true
L["Nameplate Power Bar Border"] = true
L["Nameplate Power Bar Thickness"] = true
L["Enable Fast Loot"] = true
L["Decrease the time it takes for auto loot to work, works with TSM"] = true
L["Enable Fast Loot with Loot Quality Filter"] = true
L["Enable filtering item quality, items can still be looted by holding Shift or the mod key setup in Interface"] = true
L["Enable Fast Loot with Wishlist Filter"] = true
L["Items not on the wishlist will not be looted, items can still be looted by holding Shift or the mod key setup in Interface"] = true
L["Enable Wishlist Loot Warning"] = true
L["Show a toast if an item in the wishlist is looted"] = true
L["Enable Automatically Closing Loot Window"] = true
L["Loot Window will automatically close when using filters and the item desired is not found"] = true
L["Enable Screenshotting if an item from the wishlist is looted"] = true
L["Minimum Loot Quality Filter"] = true
L["Only items of this quality or better will be looted when using Fast Loot Filter"] = true
L["Item Wishlist (type the Item ID)"] = true
L["Items in your wishlist will display a warning when looted"] = true
L["Invalid Item, you need to add an itemID which can be found in the tooltip or in Wowhead"] = true
L["Remove item from Wishlist"] = true
L["Add color to some chat messages"] = true
L["Enhance Item Links in Chat"] = true
L["Enable Chat Icons"] = true
L["Enable Item Levels"] = true
L["Customize the Chat tabs"] = true
L["Dark Chat"] = true
L["Transparent Chat"] = true
L["Make more texts use ElvUI font settings"] = true
L["Such as the Zones, Mail and others"] = true
L["Skin Objective Frame (when Shadow and Light and Windtools are not loaded)"] = true
L["Enable Wowhead Button on Quest Log"] = true
L["Show a button for Wowhead quest links"] = true
L["Enable Skin"] = true
L["Skin the Objective/Quest Frame"] = true
L["Remove Blizzard's Boss Emote Frame"] = true
L["Customize the player castbar spark"] = true
L["Select how auras will be displayed for Player"] = true
L["Select how auras will be displayed for Target"] = true
L["Select how auras will be displayed for Focus"] = true
L["Select how auras will be displayed for Boss"] = true
L["Select how auras will be displayed for Nameplates"] = true
L["Enable cursor only during combat"] = true
L["Cursor will only show during combat"] = true
L["Add a cooldown icon when trying to use skills that are on cooldown, and a cooldown flash when they are ready"] = true
L["Attempt to fix Cursor Lag"] = true
L["Software cursor is how the cursor was before Battle for Azeroth, Hardware cursor is faster but will cause problems with addons that attach to it"] = true
L["Software Cursor"] = true
L["Hardware Cursor"] = true
L["Enable on Action Bars"] = true
L["Enable on Pet Bar"] = true
L["Enable on Nameplate"] = true
L["Add a glow when buffs or debuffs are expiring on nameplates"] = true
L["Adds an autocast style glow using class color"] = true
L["Adds a pixel style glow using class color"] = true
L["Preview the Glow"] = true
L["Preview the Glow, you will need to toggle it off and on to update the glow"] = true
L["Action Bars"] = true
L["Pet Bar"] = true
L["Nameplate Buff/Debuff"] = true
L["Customize CVars"] = true
L["Nameplate Other Bottom Inset"] = true
L["In screen % the inset from the Bottom"] = true
L["Nameplate Other Top Inset"] = true
L["In screen % the inset from the Top"] = true
L["Nameplate Target Radial Position"] = true
L["When target is off screen, position its nameplate radially around sides and bottom."] = true
L["Target Only"] = true
L["All in Combat"] = true
L["Camera Distance Max Zoom Factor"] = true
L["Maximum Camera Zoom Out"] = true
L["Hide Minimap while in Combat"] = true
L["Automatically hide the Minimap in combat"] = true
L["Dynamically toggle the mouseover of the Experience Bar"] = true
L["Shows XP bar when below max level, makes it mouseover when max level"] = true
L["Enable Entering/Leaving Combat Indicator Texts"] = true
L["Adds a +Combat and -Combat for when entering and leaving combat"] = true
L["Enable a Dark Souls death animation"] = true
L["Plays an animation when you die"] = true
L["Add Sounds to /roll when someone gets a 1 or a 100"] = true
L["Plays a sound if someone rolls 1 or 100 out 100"] = true
L["Change the Scale of the World Text"] = true
L["Such as the floating XP, floating reputation changes and others"] = true
L["Select the size of the World Text"] = true
L["Hide Talking Head"] = true
L["Prevent Blizzard's Talking Head from appearing"] = true
L["Automatically take Screenshots"] = true
L["Automatically take Screenshots such as when leveling up"] = true
L["Stealth"] = true
L["Item Deletion"] = true
L["Automatically type DELETE on the popup"] = true
L["Will not delete the item, will simply type DELETE instead you needing to type it"] = true
L["Blizzard Floating Combat Text"] = true
L["Disable Combat Text"] = true
L["Enable or disable Blizzard's default Floating Combat Text"] = true
L["Enable Resource Gains"] = true
L["Enable or disable Blizzard's default Floating Combat Text for Mana/Rage/Energy and other resouces"] = true
L["Swap Action Paging and visibility for Bar1 and Bar4"] = true
L["Enable Boss Music"] = true
L["Disable Combat Music in Instances"] = true
L["Normal Combat Music"] = true
L["Name of file inside Interface\\Addons"] = true
L["Boss Combat Music"] = true
L["Player Class Texture"] = true
L["Target Class Texture"] = true
L["Change the texture of the nameplate to be a class gradient of the player's class"] = true
L["Change the texture of the nameplate to be a class gradient of the target's class"] = true
L["Enable Automatically accepting/turning in Quests when not holding CTRL/SHIFT/ALT"] = true
L["You will automatically accept and turn in quests that do not require gold, are not weekly and are not daily"] = true
L["Accept Daily and Weekly quests"] = true
L["You will also automatically accept Daily and Weekly Quests"] = true
L["Invert CTRL/SHIFT/ALT"] = true
L["You will only accept and turn in quests if you hold CTRL/SHIFT/ALT while talking to the NPC"] = true
L["Quest Item Bar"] = true
L["Enable Quest Item Bar"] = true
L["Add a Quest Item bar, keybind can be changed in Keybinds > ElvUI Eltruism"] = true
L["Add a Quest Item bar, keybind can be changed in Key Bindings > ElvUI Eltruism"] = true
L["Quest Item Bar follows visibility settings for ElvUI Action Bar 1"] = true
L["The Quest Item Bar will appear only when ElvUI Action Bar 1 appears, following its settings"] = true
L["Quest Item Bar Button Mouse Over"] = true
L["Each Button in the Quest Item Bar will appear only if the cursor is over it"] = true
L["Quest Item Bar Button Size"] = true
L["Change the size of the button on the Quest Item Bar"] = true
L["Character Panel"] = true
L["Expand Character Art"] = true
L["Expand Character Panel"] = true
L["Add Crest to Character Panel"] = true
L["Art Alpha"] = true
L["Change the transparency of the Art"] = true
L["Add Class Icons to Character Panel"] = true
L["Enable this option"] = true
L["Use Blizzard Icons"] = true
L["Enable Blizzard Icons"] = true
L["Use Blizzard Icons colored by Releaf"] = true
L["Enable Releaf Icons"] = true
L["Add Shadows to Frames"] = true
L["Add Shadows to some frames"] = true
L["Enable General Shadows"] = true
L["Add Shadows to frames like Player, target, Chats and others"] = true
L["Other Shadows (can become CPU/Memory Intensive)"] = true
L["Nameplate Health"] = true
L["Add Shadows to Nameplate Healthbars"] = true
L["Nameplate Aura"] = true
L["Add Shadows to Nameplate Auras"] = true
L["Nameplate Portrait"] = true
L["Add Shadows to Nameplate Portraits"] = true
L["Nameplate Power"] = true
L["Add Shadows to Nameplate Powers"] = true
L["Nameplate Castbar"] = true
L["Add Shadows to Nameplate Castbars"] = true
L["Unitframe Aura"] = true
L["Add Shadows to Unitframe Auras"] = true
L["ActionBars"] = true
L["Add Shadows to Actionbars"] = true
L["Aura"] = true
L["Add Aura Shadows (Aura list next to the minimap)"] = true
L["Choose the Border Texture to be used:"] = true
L["Change the size of the borders:"] = true
L["Bar 1 X offset"] = true
L["Bar 1 Y offset"] = true
L["Bar 2 X offset"] = true
L["Bar 2 Y offset"] = true
L["Bar 3 X offset"] = true
L["Bar 3 Y offset"] = true
L["Bar 4 X offset"] = true
L["Bar 4 Y offset"] = true
L["Bar 5 X offset"] = true
L["Bar 5 Y offset"] = true
L["Bar 6 X offset"] = true
L["Bar 6 Y offset"] = true
L["How to use the Anchors"] = true
L["Open WeakAuras, go to your group Weakauras and in Group change Position Settings > Anchored To > Select Frame > EltruismWA or EltruismConsumablesWA"] = true
L["Hide Quests during Battlegrounds and Arenas"] = true
L["Eltruism uses a 0.7 scale, but ElvUI can calculate the best scale for you using the Automatic Scale option"] = true
L["Very High (but Optional)"] = true
L["DPS\nTank"] = true
L["Healer"] = true
L["Automatic\nScale"] = true
L["Alternative\nFrames"] = true
L["Or change it later in Eltruism > Media options"] = true
L["Eltruism Modes"] = true
L["Transparent\nChat"] = true
L["Details! DPS Meter"] = true
L["Choose the type of icons Details! will use:"] = true
L["PVP/PVE Addons"] = true
L["Import GladiusEx profile for arenas, remember to disable ElvUI Arena Frames"] = true
L["GladiusEx"] = true
L["Import Questie profile, which uses the DBM radar"] = true
L["Questie"] = true
L["Import DBM or BigWigs profiles for dungeons and raids. (Uses DBM English Calanon and Bigwigs Voice)"] = true
L["Import Method Raid Tools profile with raid cooldowns and other settings"] = true
L["Import profiles for Gladdy"] = true
L["Import profiles for Gladius"] = true
L["Gladdy is not installed or enabled (You can find the Gladius profile in Eltruism Settings)"] = true
L["Gladius profile can be found in Eltruism > Addons, please check it there"] = true
L["You have none of these addons installed or enabled"] = true
L["QOL Addons"] = true
L["Import a profile for Simpy's ElvUI FCT configured for Eltruism"] = true
L["Import a profile for NameplateSCT configured for Eltruism"] = true
L["NameplateSCT and ElvUI FCT are not installed or enabled"] = true
L["You have completed the installation process"] = true
L["Please click Finished to reload the UI"] = true
L["Shaman Totems"] = true
L["Enable on Shaman Totems"] = true
L["Enable on Shaman Fire Totem"] = true
L["Enable on Shaman Earth Totem"] = true
L["Enable on Shaman Water Totem"] = true
L["Enable on Shaman Air Totem"] = true
L["Shaman Fire Totem"] = true
L["Shaman Earth Totem"] = true
L["Shaman Water Totem"] = true
L["Shaman Air Totem"] = true
--didnt export earlier
L["Use Type Colors"] = true
L["Grey Background"] = true
L["Black Background"] = true
L["Show Buffs in Arena and hide them outside (will overwrite Eltruism default settings)"] = true
L["Hide Arena Frames in Arena due to Gladius/Gladdy or another addon"] = true
L["Hide Raid Unitframes in battlegrounds due to addons like Battleground Enemies"] = true
L["Hide Arena Frames in Arena due to Gladius/GladiusEX or another addon"] = true
L["Enable Combat Music"] = true
L["Disable in Battlegrounds/Arenas"] = true
L["Nameplate Power Bar"] = true
L["Nameplate Powerbar Size"] = true
L["Nameplate Powerbar Position"] = true
L["Background Color"] = true
L["Skin Objective Frame"] = true
L["Enable Wowhead Button"] = true
L["Skin Profession Frame"] = true
L["Skin the Profession/Tradeskill Frame"] = true
L["Sockets and Enchants"] = true
L["Add Sockets and Enchants to the Character Panel"] = true
L["Item Levels"] = true
L["Ilvl Anchor Point"] = true
L["Choose where the Ilvl will be attach to on the items"] = true
L["Ilvl Font Outline"] = true
L["Choose the Ilvl font outline"] = true
L["Automatically swap the Character Stats to your main ones"] = true
L["Add Item Levels to the Character Panel"] = true
L["Enable a GTA death animation"] = true
L["Both Gladdy and Gladius are not installed or enabled"] = true
L["Enable for Error Frame"] = true
L["Enable for Boss Emote Frame"] = true
L["Enable for Zones, Mail and others"] = true
L["Only loads when Questie is not enabled"] = true
L["Customize Unitframe textures"] = true
L["Choose custom textures for some unitframes"] = true
L["Enable Custom Textures"] = true
L["Player Texture"] = true
L["Target of Target Texture"] = true
L["Focus Texture"] = true
L["Class Textures"] = true
L["Death Knight"] = true
L["Demon Hunter"] = true
L["Druid"] = true
L["Hunter"] = true
L["Mage"] = true
L["Monk"] = true
L["Paladin"] = true
L["Priest"] = true
L["Rogue"] = true
L["Shaman"] = true
L["Warlock"] = true
L["Warrior"] = true
L["Extra Media"] = true
L["Skip Plugins"] = true
L["!key Chat Command"] = true
L["Enable !key and !keys chat command"] = true
L["Will link your key and covenant in guild or party chat"] = true
L["Automatically screenshot when you loot an item from the wishlist"] = true
L["Collapse Quests during any combat event"] = true
L["Collapse Quests when you enter combat"] = true
L["Automatically Hide NPC Names"] = true
L["Hide NPC Names when they are too far away to have Nameplates"] = true
L["Restore Hidden Names"] = true
L["Restore Unit Names hidden by Hide NPC Names"] = true
L["This will set the background to be a grey color"] = true
L["This will set the background to be a black color"] = true
L["Set Width of the Spark (Default 3)"] = true
L["Customize Player CastBar Spark"] = true
L["Add more fonts to Shared Media"] = true
L["Enable Pixel Border"] = true
L["Enable ETA"] = true -- eta = estimated time to arrive
L["Enable Autopin"] = true
L["Automatically pin the Waypoint"] = true
L["Enable removing the Alert Frame that can show up in the middle of the screen"] = true
L["Hide Error Frame"] = true
L["Set the number of groups for autocast, for each group you get 4 particles"] = true
L["Enable Smart Classbar"] = true
L["Automatically hide the Classbar if the Target is Friendly, show if it is an enemy"] = true
L["Cursor Colors"] = true
L["Cursor Colors "] = true
L["Cursor Sizes"] = true
L["Cursor Sizes "] = true
L["Make the warnings to install profiles for other plugins stop"] = true
L["Error Frame Font Size"] = true
L["Boss Emote Frame Font Size"] = true
L["Add Item Levels to the Inspect Panel"] = true
L["Backdrops"] = true
L["Backdrop Texture"] = true
L["Backdrop Alpha"] = true
L["Change the transparency of the backdrop"] = true
L["Font"] = true
L["Font Size"] = true
L["Nameplate Powerbar Font"] = true
L["Choose a font for the Nameplate Powerbar Text"] = true
L["Nameplate Powerbar Font Size"] = true
L["Nameplate Powerbar Appearance"] = true
L["Shows the Leader Icon or Assist icon if the unit is Leader or Assist"] = true
L["Abbreviates the unit name once it goes over 20 characters, made by Azilroka"] = true
L["Adds a line break"] = true
L["Enable Gradient colors for Health"] = true
L["Enable for Group Units"] = true
L["Enable Custom Colors"] = true
L["Gradient Orientation"] = true
L["Choose the direction of the gradient"] = true
L["Gradient Texture"] = true
L["Color 1"] = true
L["Color 2"] = true
L["Toggle the Click Casting Menu"] = true
L["Instance Texts"] = true
L["Instance Text Color"] = true
L["Instance text Font Size"] = true
L["Dungeon"] = true
L["The text displayed when in a normal dungeon"] = true
L["Dungeon (Heroic)"] = true
L["The text displayed when in a heroic dungeon"] = true
L["Dungeon (Timewalking)"] = true
L["The text displayed when in a timewalking dungeon"] = true
L["Dungeon (Mythic)"] = true
L["The text displayed when in a mythic dungeon"] = true
L["Dungeon (Mythic Plus)"] = true
L["The text displayed when in a mythic plus dungeon"] = true
L["Raid (Normal)"] = true
L["The text displayed when in a normal raid"] = true
L["Raid (Heroic)"] = true
L["The text displayed when in a heroic raid"] = true
L["Raid (LFR)"] = true
L["The text displayed when in a lfr raid"] = true
L["Raid (Mythic)"] = true
L["The text displayed when in a mythic raid"] = true
L["Raid (Timewalking)"] = true
L["The text displayed when in a timewalking raid"] = true
L["Guild"] = true
L["The text displayed when in a guild group"] = true
L["Eltruism uses Dark Mode by default"] = true
L["You can switch to Light Mode or Gradient Mode by clicking the buttons below"] = true
L["You can customize the textures and colors in Eltruism > Unitframes"] = true
L["Eltruism uses Transparent chat by default"] = true
L["You can switch to Dark Chat by clicking the buttons below"] = true
L["Add Sockets and Enchants to the Inspect Frame"] = true
L["Add Shadows to Raid Frames"] = true
L["Left Click:"] = true
L["Open Eltruism Installation"] = true
L["Eltruism Honor/Conquest Points"] = true
L["Dark Power Background"] = true
L["Sets Class Power backgrounds to be black"] = true
L["Change the Class Power background"] = true
L["Player Castbar Texture"] = true
L["Enable Auto-adjusting the actionbar spacing and position"] = true
L["Adjusts actionbar spacing and position based on borders being enabled or not"] = true
L["Enable Unitframe Modifications"] = true
L["Enable changing textures and gradients for ElvUI unitframes"] = true
L["Choose between custom textures or gradient mode"] = true
L["Enable Gradient"] = true
L["Apply"] = true
L["Apply the mode selected"] = true
L["Friendly NPC"] = true
L["Neutral NPC"] = true
L["Unfriendly NPC"] = true
L["Hostile NPC"] = true
L["Original Group, Raid and Raid40 layout has been set"] = true
L["Alternative Group, Raid and Raid40 layout has been set"] = true
L["Spell Haste"] = true
L["Enable for Player"] = true
L["Enable for Target"] = true
L["Enable for Target of Target"] = true
L["Enable for Focus"] = true
L["Enable for Boss"] = true
L["Enable a Custom death animation"] = true
L["Custom Death Text"] = true
L["The text displayed when you die using the custom text option"] = true
L["Feel free to explore Eltruism settings in ElvUI > Eltruism.\nThere are lot of settings that are disabled by default."] = true
L["Show Eltruism Game Menu Button"] = true
L["Unitframes"] = true
L["Shadows"] = true
L["Cursor Type"] = true
L["Show a Battle Resurrection Count and Cooldown Frame"] = true
L["Enables a frame that shows a cooldown and count for battle resurrections while in an instance that has them"] = true
L["Choose the Progress Bar Texture"] = true
L["Add Class Gradient Colors to Stats"] = true
L["Enable for Target Castbar"] = true
L["Enable for Arena"] = true
L["Enable for Player Castbar"] = true
L["Enable pet cooldown tracking"] = true
L["Attributes"] = true
L["Item Level"] = true
L["Specialization"] = true
L["Other Skins"] = true
L["Skin MeetingHorn"] = true
L["Add a gradient color to the Experience Bar"] = true
L["Pet Border"] = true
L["Import Capping profile for battlegrounds"] = true
L["Import BattlegroundEnemies profile for battlegrounds"] = true
L["Import WarpDeplete profile for Mythic Plus"] = true
L["WarpDeplete profile requires an import per class in order to have the correct texture"] = true
L["BattlegroundEnemies is not installed or enabled"] = true
L["Capping is not installed or enabled"] = true
L["WarpDeplete is not installed or enabled"] = true
L["Version 1"] = true
L["Version 2"] = true
L["Light Mode Texture Version"] = true
L["Nameplate Texture Version"] = true
L["Enable Gradient (Requires Dark or Light Modes)"] = true
L["Automatically Detect Classes for Player, Target, Target of Target and Focus"] = true
L["Use the custom texture based on it's class instead of general texture for Player, Target, Target of Target and Focus"] = true
L["Party Border"] = true
L["Raid Border"] = true
L["Focus Border"] = true
L["Aura Border X offset"] = true
L["Aura Border Y offset"] = true
L["Left Chat Border X offset"] = true
L["Left Chat Border Y offset"] = true
L["Right Chat Border X offset"] = true
L["Right Chat Border Y offset"] = true
L["Other"] = true
L["Raid40 Border"] = true
L["Enable for Target of Target of Target"] = true
L["Target of Target of Target Texture"] = true
L["Player Castbar"] = true
L["Player Castbar (Interrupted)"] = true
L["Player Castbar (Non Interruptible)"] = true
L["Enable for Player Castbar (Interrupted)"] = true
L["Enable for Target Castbar (Interrupted)"] = true
L["Enable for Player Castbar (Non Interruptible)"] = true
L["Enable for Target Castbar (Non Interruptible)"] = true
L["Enable Gradient colors for Player Castbar"] = true
L["Enable Gradient colors for Target Castbar"] = true
L["Enable Gradient colors for Player Castbar (Interrupted)"] = true
L["Enable Gradient colors for Target Castbar (Interrupted)"] = true
L["Enable Gradient colors for Player Castbar (Non Interruptible)"] = true
L["Enable Gradient colors for Target Castbar (Non Interruptible)"] = true
L["Target Castbar"] = true
L["Target Castbar (Interrupted)"] = true
L["Target Castbar (Non Interruptible)"] = true
L["Version 3"] = true
L["Debuff Timer"] = true
L["Time at which the glow will start"] = true
L["Group Unitframe Thickness"] = true
L["Castbar Thickness"] = true
L["Pet Thickness"] = true
L["Focus Thickness"] = true
L["Boss Thickness"] = true
L["Aura Thickness"] = true
L["Chat Thickness"] = true
L["Minimap Thickness"] = true
L["Class Colors"] = true
L["Use Class Colors instead of Custom Colors"] = true
L["NPCs use Target Castbar colors not NPC colors for their castbars"] = true
L["Shows level difference when it exists for NPCs and players, hides for players if same level"] = true
L["Shows the current Death Knight presence"] = true
L["Displays the number of the group for the first member of that group, raid sorting can break this tag making it show up on other members."] = true
L["Cooldown Sound"] = true
L["Play a Sound when attempting to use a skill that is on cooldown."] = true
L["Stance Bar Thickness"] = true
L["Stance Bar"] = true
L["Stance X offset"] = true
L["Stance Y offset"] = true
L["Shaman Totem Bar"] = true
L["Shaman Totem Thickness"] = true
L["Totem X offset"] = true
L["Totem Y offset"] = true
L["Requires Light Mode Enabled"] = true
L["Pet Action Bar"] = true
L["Pet Action Bar X offset"] = true
L["Pet Action Bar Y offset"] = true
L["Pet Action Bar Thickness"] = true
L["Background Texture Type"] = true
L["Choose between a Class, Race or Custom Background"] = true
L["Example: "] = true
L["Add Item Quality Texture"] = true
L["Focus Castbar Border"] = true
L["Displays a disconnect symbol from Releaf when unit is disconnected. Usage: [eltruism:dc{number}]"] = true
L["Displays a dead symbol from Releaf when unit is dead. Usage: [eltruism:dead{number}]"] = true
L["Returns class color only for players"] = true
L["Displays an icon when the unit is in combat, uses player icon"] = true
L["Add a Vignette over the Character Art"] = true
L["Vignette Alpha"] = true
L["Change the transparency of the Vignette"] = true
L["Character Panel Scale"] = true
L["Change the size of the Character Panel"] = true
L["Hide Actionbar Button Press"] = true
L["Spark Texture"] = true
L["Addon on Wago:"] = true
L["Plays a voiced emote when you have low mana as a healer. Usage: [eltruism:lowmana{5}] as an example of 5%"] = true
L["Plays a voiced emote when you have low health. Usage: [eltruism:lowhealth{1}] as an example of 1%"] = true
L["Displays HP - % and a status symbol from Releaf for players. Usage: [eltruism:hpstatus{number,number}]"] = true
L["Displays shortvalue HP and a status symbol from Releaf for players. Usage: [eltruism:hpstatusnopc{number,number}]"] = true
L["Gradient Colors"] = true
L["Customize Colors"] = true
L["Colors"] = true
L["Enable Gradient Nameplates"] = true
L["Nameplate Custom Color"] = true
L["Enable Custom Colors for Nameplates"] = true
L["Unitframe Custom Color"] = true
L["Enable Custom Colors for Unitframes"] = true
L["Tapped NPC"] = true
L["Nameplate Colors"] = true
L["Good Threat"] = true
L["Bad Threat"] = true
L["Good Threat Transition"] = true
L["Bad Threat Transition"] = true
L["Off Tank"] = true
L["Off Tank Good Threat Transition"] = true
L["Off Tank Bad Threat Transition"] = true
L["Enable Gradient colors for Nameplates. |cffFF0000WARNING:|r This will overwrite some default ElvUI NP settings, if you dont want this, please disable this feature."] = true
L["Limit Max Distance"] = true
L["Text Color"] = true
L["Max Distance"] = true
L["Unitframe Fill Orientation"] = true
L["Horizontal"] = true
L["Vertical"] = true
L["Custom Health Height"] = true
L["Enable Custom Health Heights"] = true
L["Changes Nameplate Health Height depending on conditions"] = true
L["Use ElvUI Health Heights"] = true
L["Use ElvUI Nameplate Health Heights when targeted or in combat"] = true
L["Out of Combat/Not Targeted"] = true
L["Choose the Health Height for Nameplates not in combat or not targeted"] = true
L["In Combat/Targeted"] = true
L["Choose the Health Height for Nameplates that are in combat or targeted"] = true
L["Target Model"] = true
L["Enable Target Model"] = true
L["Shows the target's model on the target nameplate"] = true
L["Use ElvUI Damage Font"] = true
L["Enable Playing a Sound if an item from the wishlist is looted"] = true
L["Effect"] = true
L["Rested Nameplates"] = true
L["Decrease Nameplate Overlap when Resting"] = true
L["Target Portrait Fix"] = true
L["Automatically rotate Target Portrait"] = true
L["Detects target's species and uses it to fix the rotation of the Target's 3D Portrait"] = true
L["Hide Cooldown Swipe"] = true
L["Hide Cooldown Swipe on Buffs and Debuffs"] = true
L[" was detected. To prevent issues some settings were changed."] = true
L["Invalid Model, you need to add a Model ID/Path"] = true
L["Models"] = true
L["Castbar Models"] = true
L["Add an Effect"] = true
L["Unitframe Models"] = true
L["Enable Models/Effects"] = true
L["Enable adding models as effects on unitframes"] = true
L["Enable adding models as effects on Castbars"] = true
L["Model Types"] = true
L["Choose between Class Based Models or a Custom Model"] = true
L["Choose between a Default Model or a Custom Model"] = true
L["Type the Model ID, such as 165575"]= true
L["Type the Model Path, such as spells/arcanebreath.m2"]= true
L["Type the Model ID, such as 165821"] = true
L["Type the Model Path, such as spells/corruption_impactdot_med_base.m2"] = true
L["Health Bars"] = true
L["Transparency in Light Mode"] = true
L["Transparency in Dark Mode"] = true
L["Desaturation"] = true
L[" This can be a very demanding feature, it's not recommended to use models for performance."] = true
L["Combat Text Addons"] = true
L["Details Profiles"] = true
L["Camera Field of View"] = true
L["This allows you to zoom out further with the camera to increase the field of view."] = true
L["Replace role icons with Eltruism role icons"] = true
L["Model Alpha"] = true
L["Desaturate"] = true
L["Custom Class Colors"] = true
L["Unitframe Colors"] = true
L["Cooldown"] = true
L["Enable Cooldown Pulse"] = true
L["Show a Skill Pulse when its cooldown is ending"] = true
L["Show Spell Name"] = true
L["Displays a Text with the name of the spell"] = true
L["Fade In Time"] = true
L["Time it takes for the icon to fade in"] = true
L["Fade Out Time"] = true
L["Time it takes for the icon to fade out"] = true
L["Alpha"] = true
L["Transparency of the Icon"] = true
L["Animation Scale"] = true
L["Animation will scale to this size"] = true
L["Icon Size"] = true
L["Size of the Icon"] = true
L["Hold Time"] = true
L["How long the Icon will appear"] = true
L["Minimum Cooldown Length"] = true
L["Cooldowns must be longer than this to show up"] = true
L["Ignored Spells, use a comma to separate spells"] = true
L["List of spells ignored, use a comma to separate spells"] = true
L["Hide Backdrop"] = true
L["Sets the Backdrop as Transparent/Hidden"] = true
L["Light Mode Alpha"] = true
L["Dark Mode Alpha"] = true
L["Add Class Gradient Colors to Other Texts"] = true
L["Add Class Gradient Colors to Text"] = true
L["Add Class Colors to Text"] = true
L["Cursor Position"] = true
L["Color Modifier Keys"] = true
L["Add Class Color to Modifier Keys like ALT and CTRL on the ActionBars"] = true
L["Hide Debuffs on Non Targeted Nameplates, show when Targeted"] = true
L["Hide Debuffs on Non Target"] = true
L["Database Check"] = true
L["Run Database Check"] = true
L["Perform a Database Check if you are updating from a very old version as some settings have changed places and the Database Check will convert them"] = true
L["WeakAuras Action Bar"] = true
L["Move ActionBars and Power to be similar to WeakAuras"] = true
L["Overwrites some profile settings to move ActionBars, Unitframes and Powers to look similar to a WeakAura. |cffFF0000WARNING:|r This will overwrite some of your profile settings"] = true
L["Eltruism database was converted.\n|cff82B4ffThe Following profiles were updated:|r\n%s\n\n|cff82B4ffPrivate settings were updated for the following private profiles:|r\n%s\n\n|cff82B4ffIf you have any issues please report in Discord or open a ticket.|r\n|cffff0000A Reload is necessary to save this conversion and fix variables|r"] = true
L["Datatext Hiding"] = true
L["Hide Right Chat Datatext out of Combat"] = true
L["Hide Left Chat Datatext out of Combat"] = true
L["Play a Sound when receiving mail"] = true
L["Text to Speech"] = true
L["Text to Speech announcement"] = true
L["Text to Speech Config"] = true
L["Enable AMD FSR even if not scaling"] = true
L["Forces AMD's FSR to sharpen image even if you aren't running a lower resolution"] = true
L["Add a gradient color to the Honor Bar"] = true
L["Add a gradient color to the Reputation Bar"] = true
L["Add a gradient color to the Alt Power Bar"] = true
L["Character Model Zoom"] = true
L["Character Model X Offset"] = true
L["Character Model Y Offset"] = true
L["Character Model"] = true
L["Ilvl Font X Offset"] = true
L["Ilvl Font Y Offset"] = true
L["Enable Eltruism Icons"] = true
L["Enable Custom Icons"] = true
L["Tank"] = true
L["DPS"] = true
L["Gradient Power Orientation"] = true
L["Enable Gradient Power"] = true
L["Enable Gradient Power Colors"] = true
L["Enable Custom Gradient Power"] = true
L["Enable Custom Gradient Power Colors"] = true
L["Reset/Add Eltruism Datatext Panel"] = true
L["Change the ElvUI background"] = true
L["Supporters"] = true
L["Translators"] = true
L["Power Colors"] = true
L["Enable Shadows"] = true
L["Line"] = true
L["Line Texture"] = true
L["Line Width"] = true
L["Line Height"] = true
L["Button Size"] = true
L["Text"] = true
L["This is the second color on the Experience Bar, the first can be found in ElvUI Databars section"] = true
L["This is how much the color will gain or lose this value"] = true
L["Power Bar Models"] = true
L["NPC Castbars (Interruptible)"] = true
L["Color by Reaction"] = true
L["Use Custom Font"] = true
L["Red"] = true
L["Green"] = true
L["Blue"] = true
L["Enable Information Panel on Top"] = true
L["Sets Information panel to be on Top instead of Bottom of the unitframe"] = true
L["Add Item Set Colors"] = true
L["Enable Custom Set Colors"] = true
L["Enable Comparing Equipped and Bag Ilvl"] = true
L["Bad Color"] = true
L["Medium Color"] = true
L["Good Color"] = true
L["Use this button to restore names should you have disabled the Hide NPC Names option"] = true
L["Gradient Power Backdrop"] = true
L["Change how much the Gradient Power Backdrop will Fade"] = true
L["Use ElvUI Unitframe Texture"] = true
L["Uses ElvUI Unitframe Statusbar texture instead"] = true
L["Restore All Blizzard Combat Text"] = true
L["Abbreviates the unit name once it goes over 10 characters"] = true
L["Focus Target Border"] = true
L["Raid1 Border"] = true
L["Raid2 Border"] = true
L["Raid3 Border"] = true
L["Enable on All Unitframes"] = true
L["Class Colored Cooldowns"] = true
L["Sets Cooldowns to be Class Colored"] = true
L["Hide Blizzard Frames"] = true
L["Hide the Red Error Text"] = true
L["Hide Zone Text"] = true
L["Hide the text that appears when changing zones"] = true
L["Hide Alert Frame"] = true
L["Hide the Alert Frame that appears when looting a rare item or earning an achievement"] = true
L["Hide Boss Banner Frame"] = true
L["Hide the boss banner that appears when killing a raid boss or completing a Mythic+ dungeon"] = true
L["Enable on System Messages"] = true
L["Enable on Chat Messages"] = true
L["Adjust Auras Position"] = true
L["Automatically move auras to the Top Right when minimap is hidden"] = true
L["Enable for Focus Target"] = true
L["Skin PallyPower"] = true
L["Enable on Unitframes"] = true
L["Add a glow when Unitframes have a debuff"] = true
L["Enable Gradient Aurabars"] = true
L["Shadow Size"] = true
L["Skin BigWigs"] = true
L["Skin Details"] = true
L["Replace Texture"] = true
L["Replace Details Bar Texture"] = true
L["Enable Automatically Confirming Bind on Pickup"] = true
L["Loot Window will automatically confirm looting Bind on Pickup items"] = true
L["Minimap Cardinal Directions"] = true
L["Enable Cardinal Directions"] = true
L["Add North, East, South, West to Minimap"] = true
L["Cardinal Text Offset"] = true
L["You have another Nameplate Addon installed and loaded, and many nameplate features will not work with it"] = true
L["Reset Nameplate Style Filters"] = true
L["Enable adding more functions to ElvUI Chat"] = true
L["Shows the current stance"] = true
L["Item Level on Tooltip"] = true
L["Shows Item Level on Tooltips"] = true
L["Enable Automatic Combat Log"] = true
L["Quest Detail Scale"] = true
L["Flight Frame Scale"] = true
L["Donators"] = true
L["Gradient Archeology Digsite Bar"] = true
L["Text X offset"] = true
L["Text Y offset"] = true
L["Add Shadows to BigWigs Bars"] = true
L["Add Shadows to the Minimap"] = true
L["Add Shadows to the Chat Frames"] = true
L["Debuff Aura Border X offset"] = true
L["Debuff Aura Border Y offset"] = true
L["Unitframe Auras"] = true
L["Enable Unitframe Auras"] = true
L["Unitframe Aura Border X offset"] = true
L["Unitframe Aura Border Y offset"] = true
L["Unitframes Debuff Aura Border X offset"] = true
L["Unitframes Debuff Aura Border Y offset"] = true
L["Add gradient to Details Bars"] = true
L["Add Gradient to BigWigs Bars"] = true
L["Only items of this quality or better will be displayed"] = true
L["Objective Frame Anchor"] = true
L["Reactivate the ElvUI Objective Frame Anchor and Mover"] = true
L["Reset/Update ElvUI Settings"] = true
L["Resets/Updates ElvUI Settings to Eltreum's Defaults"] = true
L["Settings for ElvUI were updated."] = true
L["Displays unit name in gradient class color or reaction color"] = true
L["Displays unit name in gradient class color or reaction color, shortens over 16 characters"] = true
L["Empowering Color"] = true
L["Automatically offset Player/Target Portrait"] = true
L["Detects player and target's species and uses it to fix the offset of the 3D Portrait"] = true
L["Font has been set."] = true --name of font shows up before "Font", example: "Arial Font has been set."
L["Will link your key in guild or party chat"] = true --updated to remove the covenant reference
L["Pet Texture"] = true
L["Shuffle"] = true
L["Randomize Music Order"] = true
L["Shuffle List"] = true
L["Split files with a comma, such as: file1.mp3,file2.mp3"] = true
L["Enable World Map Scaling"] = true
L["World Map Scale"] = true
L["Adjust the position of the text on Buffs/Debuffs"] = true
L["Adjust Aura Position"] = true
L["Boss Banner Frame Scale"] = true
L["Boss Texture"] = true
L["Disable Class Textures"] = true
L["Use only textures sets for specific frames and not class specific textures"] = true
L["Classification"] = true
L["Custom Icons"] = true
L["Enable replacing Elite/Rare Icons"] = true
L["Adds different Rare/Elite Icons"] = true
L["Elite Color"] = true
L["Elite Icon"] = true
L["Rare Color"] = true
L["Rare Icon"] = true
L["Boss Color"] = true
L["Boss Icon"] = true
L["Rare Elite"] = true
L["Rare Elite Color"] = true
L["Rare Elite Icon"] = true
L["Difficulty Specific Colors"] = true
L["Use different colors per Difficulty"] = true
L["Requires ElvUI Nameplate Elite Icon"] = true
L["Hide Left Chat in Boss Encounters"] = true
L["Hide Right Chat in Boss Encounters"] = true
L["Right Click:"] = true
L["Toggle Details"] = true
L["Skin BugSack"] = true
L["Skin Clique"] = true
L["Embed"] = true
L["Simple Right Chat Embed"] = true
L["Hide Out of Combat"] = true
L["Out of Combat Delay"] = true
L["Skin Immersion"] = true
L["Skin RareScanner"] = true
L["Skin SimulationCraft"] = true
L["Skin WarpDeplete"] = true
L["Your World of Warcraft version is not expected to be compatible with Eltruism, please update Eltruism or you might run into issues.\n|cffFF0000(You are likely having errors right now!)|r"] = true
L["Install, Reinstall or Update various parts of Eltruism"] = true
L["Enhance the AFK screen"] = true
L["Install or update other Addon profiles"] = true
L["Choose to show all debuffs/buffs or use default Filters"] = true
L["Add Borders to frames and customize them"] = true
L["Enhance Chat Functionality"] = true
L["Play custom music during fights and boss fights"] = true
L["Show a pulsing cooldown and let it speak the spell name"] = true
L["Attach Rings to the Cursor that will show Castbars, GCDs and can also show the cooldown of skills you attempt to use"] = true
L["Fully customize how action bars glow and add glows to debuffs on unitframes"] = true
L["Customize Blizzard's Hidden Settings"] = true
L["Customize Gradient Colors"] = true
L["Add a scrolling loot text that will show items that you loot, filter which items you can loot, enable fast looting and create your own item wishlist"] = true
L["Add a time to arrive to waypoints, cardinal directions and more"] = true
L["Add cardinal directions, change map scale and more"] = true
L["Change Fonts, Font Outlines and Action Paging"] = true
L["Various miscellaneous features such as death animations, stealth texture, mail sound, /roll sounds and more"] = true
L["Enhance ElvUI Nameplates with options for gradient, size, textures, models, behavior and more"] = true
L["Play sounds when party members die, show resurrection timers and change instance texts"] = true
L["Automate Quests and Gossip, add a Quest Item Bar, hide Quests during Boss fights and more"] = true
L["Add several skins to World of Warcraft, such as Quests, Character Frame, Shadows, other Addons, Role Icons and more"] = true
L["Add Gradient, Custom Textures, Models, change fill orientation and more"] = true
L["Learn how to use the WeakAuras anchors to attach WeakAuras and use ElvUI's movers to move them"] = true
L["Join the Discord for faster support and to report any issues you might encounter"] = true
L["Credits and Licenses"] = true
L["Direct links to GitHub, CurseForge, Wago and Tukui"] = true
L["Your World of Warcraft version is older than Eltruism, you might run into issues!"] = true
L["Eltruism Settings"] = true
L["ElvUI Settings"] = true
L["Reset Nameplates"] = true
L["Reinstall DPS Layout"] = true
L["Reinstall Healer Layout"] = true
L["Reinstall Eltruism Datatext"] = true
L["Reinstall"] = true
L["Boss Music"] = true
L["Fade"] = true
L["Text Types"] = true
L["Time to Arrive"] = true
L["Chat Command"] = true
L["Cardinal Directions"] = true
L["Flight Frame"] = true
L["Aura Text"] = true
L["Friendly Nameplates"] = true
L["Appearance"] = true
L["Model"] = true
L["Item Quality"] = true
L["Stats"] = true
L["Panel"] = true
L["Class Icons"] = true
L["Sockets/Enchants/Ilvl"] = true
L["Armory"] = true
L["Archeology"] = true
L["Other AddOns"] = true
L["Power Bar"] = true
L["Graphics"] = true
L["Icons"] = true
L["Miscellaneous"] = true
L["Gradient Nameplate\nHealth/CastBar/Threat"] = true
L["Gradient Nameplate Health"] = true
L["Custom Role Icons"] = true
L["Role Icons"] = true
L["Cooldown Pulse\n(Includes TTS)"] = true
L["Cooldown Pulse"] = true
L["Waypoints"] = true
L["Autopin, Time to Arrive"] = true
L["Autopin"] = true
L["Cast Bar Custom Spark/Texture"] = true
L["Combat Alert"] = true
L["Unitframe/Chat Role Icons"] = true
L["Unitframe Role Icons"] = true
L["Keystone\n!key command/Autoinsert"] = true
L["Keystone Autoinsert"] = true
L["Chat Role Icons"] = true
L["Quests Skin"] = true
L["Chat Loot Icons"] = true
L["Gradient Zone/Mail/Quest Text"] = true
L["Zone Text"] = true
L["Mail Text"] = true
L["Custom Power Models"] = true
L["Power Models"] = true
L["Custom Gradient Details"] = true
L["Gradient Details"] = true
L["Gradient BigWigs"] = true
L["BigWigs Queue Timer"] = true
L["Map Scale"] = true
L["Fast Loot"] = true
L["Auto Type Delete"] = true
L["Quest Autoaccept"] = true
L["Chat Loot Item Level"] = true
L["Emphasize"] = true
L["Normal"] = true
L["MAP_SEARCHER_TOOLTIP_TITLE"] = "RareScanner searcher" -- from rarescanner locales
L["Add Shadows to the Unitframes"] = true
L["Add Shadows to Tooltips"] = true
L["Add Shadows to general Blizzard/ElvUI frames"] = true
L["Nameplate Occluded Alpha"] = true
L["Alpha of Nameplates out of Sight"] = true
L["Force ElvUI Chat Toggles"] = true
L["Enable Always Forcing ElvUI Chat Toggles On"] = true
L["Enable on Aura Bars"] = true
L["Leader Icons"] = true
L["Replace Leader icons with Eltruism leader icons"] = true
L["Assist Icons"] = true
L["Replace Raid Assist icons with Eltruism Raid Assist icons"] = true
L["Master Looter Icons"] = true
L["Replace Master Looter icons with Eltruism Master Looter icons"] = true
L["Displays a dead symbol when unit is dead. Can be customized in Eltruism > Media"] = true
L["Displays a disconnect symbol when unit is disconnected. Can be customized in Eltruism > Media"] = true
L["Displays HP - % and a status symbol. Can be customized in Eltruism > Media"] = true
L["Displays shortvalue HP and a status symbol for players. Can be customized in Eltruism > Media"] = true
L["Tags"] = true
L["Customize Tags"] = true
L["Customize Health Status Icons"] = true
L["Disconnected"] = true
L["Customize the Dead Icons"] = true
L["Customize the Disconnected Icons"] = true
L["Dynamic Render Scale"] = true
L["Lowers render scale if GPU bound to hit Target FPS."] = true
L["Note this feature is in BETA.\nKnown issues:\n - May cause hitching.\n - May behave poorly with vsync on."] = true
L["Dynamic Render Scale Minimum"] = true
L["Lowest Render Scale used"] = true
L["Other CVars"] = true
L["Smart Classbar"] = true
L["Health Height"] = true
L["Auto Accept"] = true
L["Skin ElvUI"] = true
L["Add a texture to ElvUI Backgrounds"] = true
L["Reset Style Filters"] = true
L["Nameplate Global Scale"] = true
L["Global Scaling of nameplates after selected, min, and max scale"] = true
L["Soft Target Interact"] = true
L["Enable Soft Target Interactions"] = true
L["Skin BagSync"] = true
L["Skin Hekili"] = true
L["Skin OmniCD"] = true
L["Add Class Icons in Chat messages"] = true
L["Player names in chat will have a class icon next to their name"] = true
L["Enable Showing Author, Donator and MVP Chat Icons"] = true
L["Author, MVP and Donator Icons"] = true
L["Enable Gradient Tooltips"] = true
L["Add Gradient to Names"] = true
L["Player names in chat will have a class gradient"] = true
L["Enable on Buttons"] = true
L["Double Click:"] = true
L["Minimal Buffs"] = true
L["Minimal Debuffs"] = true
L["Select how auras will be displayed for Party"] = true
L["Set filters to show more buffs on Party"] = true
L["Set filters to show more debuffs on Party"] = true
L["Set filters to be Eltruism defaults on Party"] = true
L["All Party Buffs"] = true
L["All Party Debuffs"] = true
L["Eltruism Party Buffs"] = true
L["Eltruism Party Debuffs"] = true
L["Select how auras will be displayed for Raid"] = true
L["Set filters to show more buffs on Raid"] = true
L["Set filters to show more debuffs on Raid"] = true
L["Set filters to be Eltruism defaults on Raid"] = true
L["All Raid Buffs"] = true
L["All Raid Debuffs"] = true
L["Eltruism Raid Buffs"] = true
L["Eltruism Raid Debuffs"] = true
L["Minimal"] = true
L["Select how auras will be displayed for Aura Bars"] = true
L["Gradient Item Color Offsets"] = true
L["Left Offset"] = true
L["Right Offset"] = true
L["Customize the Ghost Icons"] = true
L["Displays percentage health with status icons"] = true
L["Enable Gradient Glow"] = true
L["Reverse Target"] = true
L["Reverse Target Gradient Health"] = true
L["Skin Cell"] = true
L["Gradient Health Loss"] = true
L["Gradient Name"] = true
L["Add gradient to Names"] = true
L["Select which type of teleports to use on double click"] = true
L["Disable DPS Icons"] = true
L["Shows the current presence with color"] = true
L["Stats Font Size"] = true
L["Character Name Font Size"] = true
L["Toggle ElvUI Anchors"] = true
L["Toggle Edit Mode"] = true
L["Proc Glow"] = true
L["Start Animation"] = true
L["Speed for Proc Glow"] = true
L["Horizontal Offset"] = true
L["Vertical Offset"] = true
L["Set the horizontal offset"] = true
L["Set the vertical offset"] = true
L["Enable for Pet"] = true
L["Enable Gradient colors for Pet"] = true
L["Class Color Texture with Eltruism Datatext"] = true
L["Displays unit name in caps while being class color or reaction color, shortens over 16 characters but can be changed with {arg}"] = true
L["NPC Textures"] = true
L["Frames"] = true
L["Skin"] = true
L["Shows the current stance of the player"] = true
L["Replace ElvUI Rest Icon with Blizzard's Animated one"] = true
L["Edge"] = true
L["Choose the texture type"] = true
L["Type"] = true
L["Portrait Skin"] = true
L["Enable Portrait Skin"] = true
L["Eltruism Hearthstones/Teleports"] = true
L["Classes"] = true
L["Enable Custom Font"] = true
L["Change Texture Color"] = true
L["Play a sound when you Die in Hardcore"] = true
L["Enable Animation and Sound when Guild Member Dies"] = true
L["Enable Ace3 Skin"] = true
L["Button Hover Texture"] = true
L["Button Hover"] = true
L["Button Disabled"] = true
L["Text Selected"] = true
L["Text Enabled"] = true
L["Default Gradient Colors"] = true
L["Gradient Mode"] = true
L["Mail Animation"] = true
L["Enable Mail Animation"] = true
L["Play a Blizzard animation when receiving mail or when new mail exists"] = true
L["Enable Gradient Backdrop"] = true
L["Skin Auctionator"] = true
L["Gradient Backdrop Fade"] = true
L["Change how much the Gradient Backdrop will Fade"] = true
L["Skin Blizzard Raid Frames"] = true
L["Adds Gradient, Custom Textures, Shadows, Font and Role Icons to Blizzard Raid Frames"] = true
L["Add Other Stats"] = true
L["Display stats such as Speed and Mana Regen"] = true
L["Add Spec Icons to the Group Finder Listing"] = true
L["Font Shadow"] = true
L["Add Dungeon Score to Group Finder Listing"] = true
L["Country Style"] = true
L["Flag"] = true
L["Add Class Icons to the Group Finder Listing"] = true
L["Map not found"] = true
L["Hide Auras"] = true
L["Hide Auras on Nameplates that are not in Combat"] = true
L["Pause and Desaturate Portrait if Dead"] = true
L["Change Combat Indicators to be class based"] = true
L["Show Pet Spells"] = true
L["Health Alpha"] = true
L["Change the transparency of the health"] = true
L["Make Mage and Warlock use their original Class Colors"] = true
