local L = ElvUI[1].Libs.ACL:NewLocale("ElvUI", "ruRU")
if not L then return end

L[" and "] = true
L[" and import its settings"] = true
L[" as the anchor will move them to the locations, keep in mind you might need to change the X and Y offset of the weakaura to zero"] = true
L[" is not installed or enabled"] = true
L[" or "] = true
L[" This can be a very demanding feature, it's not recommended to use models for performance."] = true
L[" was detected. To prevent issues some settings were changed."] = true
L["!key Chat Command"] = true
L["(All settings require a reload)"] = true
L["1080p resolution detected, setting fonts to outline mode."] = true
L["1440p resolution detected, setting fonts to outline mode."] = true
L["4K resolution detected, setting fonts to default mode."] = true
L["A.F.K"] = true
L["Abbreviates the unit name once it goes over 10 characters"] = true
L["Abbreviates the unit name once it goes over 16 characters, made by Azilroka"] = true
L["Abbreviates the unit name once it goes over 20 characters, made by Azilroka"] = true
L["Accept Daily and Weekly quests"] = true
L["Action Bar 1"] = true
L["Action Bar 2"] = true
L["Action Bar 3"] = true
L["Action Bar 4"] = true
L["Action Bar 5"] = true
L["Action Bar 6"] = true
L["Action Bars"] = true
L["Actionbar Thickness"] = true
L["ActionBars"] = true
L["Add a cooldown icon when trying to use skills that are on cooldown, and a cooldown flash when they are ready"] = true
L["Add a fade to the left chat panel, controlled by ElvUI Chat > Text Fade > Inactivity Timer"] = true
L["Add a fade to the right chat panel, controlled by ElvUI Chat > Text Fade > Inactivity Timer"] = true
L["Add a glow when buffs or debuffs are expiring on nameplates"] = true
L["Add a glow when Unitframes have a debuff"] = true
L["Add a gradient color to the Alt Power Bar"] = true
L["Add a gradient color to the Experience Bar"] = true
L["Add a gradient color to the Honor Bar"] = true
L["Add a gradient color to the Reputation Bar"] = true
L["Add a Level Up toast"] = true
L["Add a Quest Item bar, keybind can be changed in Key Bindings > ElvUI Eltruism"] = true
L["Add a Quest Item bar, keybind can be changed in Keybinds > ElvUI Eltruism"] = true
L["Add a rings around the mouse cursor for GCD, casts and combat"] = true
L["Add a scrolling loot text that will show items that you loot, filter which items you can loot, enable fast looting and create your own item wishlist"] = true
L["Add a texture to ElvUI Backgrounds"] = true
L["Add a time to arrive below the waypoint"] = true
L["Add a time to arrive to waypoints, cardinal directions and more"] = true
L["Add a vignette effect always"] = true
L["Add a vignette effect while in stealth"] = true
L["Add a Vignette over the Character Art"] = true
L["Add an Effect"] = true
L["Add an ETA to waypoints"] = true
L["Add Aura Shadows (Aura list next to the minimap)"] = true
L["Add Borders to frames and customize them"] = true
L["Add cardinal directions, change map scale and more"] = true
L["Add Class Color to Modifier Keys like ALT and CTRL on the ActionBars"] = true
L["Add Class Colors to Text"] = true
L["Add Class Gradient Colors to Other Texts"] = true
L["Add Class Gradient Colors to Stats"] = true
L["Add Class Gradient Colors to Text"] = true
L["Add Class Icons in Chat messages"] = true
L["Add Class Icons to Character Panel"] = true
L["Add Class Icons to the Group Finder Listing"] = true
L["Add color to some chat messages"] = true
L["Add Crest to Character Panel"] = true
L["Add debuffs to the Style Filter to make Nameplates with expiring Debuffs show full alpha and scale"] = true
L["Add Dungeon Score to Group Finder Listing"] = true
L["Add fade over time, and mouse over to left and right chat panels"] = true
L["Add GCD, Cast and Combat indicator rings to the cursor"] = true
L["Add Gradient to BigWigs Bars"] = true
L["Add gradient to Details Bars"] = true
L["Add Gradient to Names"] = true
L["Add Gradient, Custom Textures, Models, change fill orientation and more"] = true
L["Add gradients to Unitframes and Nameplates"] = true
L["Add Item Levels to the Character Panel"] = true
L["Add Item Levels to the Inspect Panel"] = true
L["Add Item Quality Texture"] = true
L["Add Item Set Colors"] = true
L["Add more fonts to Shared Media"] = true
L["Add mouse over to the left chat panel"] = true
L["Add mouse over to the right chat panel"] = true
L["Add North, East, South, West to Minimap"] = true
L["Add Other Stats"] = true
L["Add Profession Buttons to Bags"] = true
L["Add several skins to World of Warcraft, such as Quests, Character Frame, Shadows, other Addons, Role Icons and more"] = true
L["Add Shadows to Actionbars"] = true
L["Add Shadows to BigWigs Bars"] = true
L["Add Shadows to frames like Player, target, Chats and others"] = true
L["Add Shadows to Frames"] = true
L["Add Shadows to general Blizzard/ElvUI frames"] = true
L["Add Shadows to Nameplate Auras"] = true
L["Add Shadows to Nameplate Castbars"] = true
L["Add Shadows to Nameplate Healthbars"] = true
L["Add Shadows to Nameplate Portraits"] = true
L["Add Shadows to Nameplate Powers"] = true
L["Add Shadows to Raid Frames"] = true
L["Add Shadows to some frames"] = true
L["Add Shadows to the Chat Frames"] = true
L["Add Shadows to the Minimap"] = true
L["Add Shadows to the Unitframes"] = true
L["Add Shadows to Tooltips"] = true
L["Add Shadows to Unitframe Auras"] = true
L["Add Sockets and Enchants to the Character Panel"] = true
L["Add Sockets and Enchants to the Inspect Frame"] = true
L["Add Sounds to /roll when someone gets a 1 or a 100"] = true
L["Add Spec Icons to the Group Finder Listing"] = true
L["Addon on CurseForge:"] = true
L["Addon on Tukui:"] = true
L["Addon on Wago:"] = true
L["Addon Profiles"] = true
L["AddOns that do the same thing can cause issues, to prevent errors you should pick between them below. Choose what you prefer!"] = true
L["Addons"] = true
L["AddOnSkins profile has been set."] = true
L["AddOnSkins"] = true
L["Adds a +Combat and -Combat for when entering and leaving combat"] = true
L["Adds a Blizzard style glow using class color"] = true
L["Adds a line break"] = true
L["Adds a pixel style glow using class color"] = true
L["Adds an autocast style glow using class color"] = true
L["Adds different Rare/Elite Icons"] = true
L["Adds Gradient, Custom Textures, Shadows, Font and Role Icons to Blizzard Raid Frames"] = true
L["Adjust Aura Position"] = true
L["Adjust Auras Position"] = true
L["Adjust the position of the text on Buffs/Debuffs"] = true
L["Adjusts actionbar spacing and position based on borders being enabled or not"] = true
L["All Boss Buffs"] = true
L["All Boss Debuffs"] = true
L["All Focus Buffs"] = true
L["All Focus Debuffs"] = true
L["All in Combat"] = true
L["All Nameplate Buffs"] = true
L["All Nameplate Debuffs"] = true
L["All Party Buffs"] = true
L["All Party Debuffs"] = true
L["All Player Buffs"] = true
L["All Player Debuffs"] = true
L["All Raid Buffs"] = true
L["All Raid Debuffs"] = true
L["All Target Buffs"] = true
L["All Target Debuffs"] = true
L["Allowed Spells, use a comma to separate spells"] = true
L["Alpha of Nameplates out of Sight"] = true
L["Alpha"] = true
L["Alternative Group, Raid and Raid40 layout has been set"] = true
L["Alternative Layout"] = true
L["Alternative unitframe layouts"] = true
L["Alternative\nFrames"] = true
L["Animation Scale"] = true
L["Animation will scale to this size"] = true
L["Appearance"] = true
L["Apply the mode selected"] = true
L["Apply"] = true
L["Archeology"] = true
L["Area does not support waypoints"] = true
L["Arenas"] = true
L["Armory"] = true
L["Art Alpha"] = true
L["Assist Icons"] = true
L["Attach Rings to the Cursor that will show Castbars, GCDs and can also show the cooldown of skills you attempt to use"] = true
L["Attempt to fix Cursor Lag"] = true
L["Attributes"] = true
L["Aura Border X offset"] = true
L["Aura Border Y offset"] = true
L["Aura Filters"] = true
L["Aura Text"] = true
L["Aura Thickness"] = true
L["Aura"] = true
L["Author"] = true
L["Author, MVP and Donator Icons"] = true
L["Auto Accept"] = true
L["Auto color Border"] = true
L["Auto color Glow"] = true
L["Auto open the Rogue Order Hall, to avoid opening hold CTRL or SHIFT or ALT while talking to the NPC"] = true
L["Auto Type Delete"] = true
L["Autocast Frequency (Default is 0.8)"] = true
L["Autocast Glow"] = true
L["Autocast Horizontal Offset (Default is 5)"] = true
L["Autocast Particle Groups (Default is 8)"] = true
L["Autocast Scale (Default is 2)"] = true
L["Autocast Vertical Offset (Default is 5)"] = true
L["Autocast"] = true
L["Autodetect"] = true
L["Automate Quests and Gossip, add a Quest Item Bar, hide Quests during Boss fights and more"] = true
L["Automatically Detect Classes for Player, Target, Target of Target and Focus"] = true
L["Automatically Hide NPC Names"] = true
L["Automatically hide the Classbar if the Target is Friendly, show if it is an enemy"] = true
L["Automatically hide the Minimap in combat"] = true
L["Automatically move auras to the Top Right when minimap is hidden"] = true
L["Automatically offset Player/Target Portrait"] = true
L["Automatically pin the Waypoint"] = true
L["Automatically rotate Target Portrait"] = true
L["Automatically screenshot when you loot an item from the wishlist"] = true
L["Automatically swap the Character Stats to your main ones"] = true
L["Automatically take Screenshots such as when leveling up"] = true
L["Automatically take Screenshots"] = true
L["Automatically type DELETE on the popup"] = true
L["Automatic\nScale"] = true
L["Autopin"] = true
L["Autopin, Time to Arrive"] = true
L["Backdrop Alpha"] = true
L["Backdrop Texture"] = true
L["Backdrops"] = true
L["Background Color"] = true
L["Background Texture Type"] = true
L["Background"] = true
L["Bad Color"] = true
L["Bad Threat Transition"] = true
L["Bad Threat"] = true
L["Bar 1 X offset"] = true
L["Bar 1 Y offset"] = true
L["Bar 2 X offset"] = true
L["Bar 2 Y offset"] = true
L["Bar 3 X offset"] = true
L["Bar 3 Y offset"] = true
L["Bar 4 X offset"] = true
L["Bar 4 Y offset"] = true
L["Bar 5 X offset"] = true
L["Bar 5 Y offset"] = true
L["Bar 6 X offset"] = true
L["Bar 6 Y offset"] = true
L["BattlegroundEnemies is not installed or enabled"] = true
L["BattleGroundEnemies is not loaded"] = true
L["BattleGroundEnemies profile has been set."] = true
L["BigWigs is not installed or enabled so DBM will be used"] = true
L["BigWigs profile has been set."] = true
L["BigWigs Queue Timer"] = true
L["Black Background"] = true
L["Blizzard Buff Frame"] = true
L["Blizzard Floating Combat Text"] = true
L["Blizzard Frequency (Default is 0.5)"] = true
L["Blizzard Glow"] = true
L["Blizzard"] = true
L["Blue"] = true
L["Border X offset"] = true
L["Border Y offset"] = true
L["Border"] = true
L["Boss Banner Frame Scale"] = true
L["Boss Border"] = true
L["Boss Color"] = true
L["Boss Combat Music"] = true
L["Boss Emote Frame Font Size"] = true
L["Boss Icon"] = true
L["Boss Mods"] = true
L["Boss Music"] = true
L["Boss Texture"] = true
L["Boss Thickness"] = true
L["BossMods Profiles"] = true
L["Both DBM and BigWigs are not installed or enabled"] = true
L["Both Gladdy and Gladius are not installed or enabled"] = true
L["Buff filters were setup"] = true
L["Buffs have been updated for Arenas"] = true
L["Buffs have been updated for Open World"] = true
L["Button Disabled"] = true
L["Button Hover Texture"] = true
L["Button Hover"] = true
L["Button Size"] = true
L["Camera Distance Max Zoom Factor"] = true
L["Camera Field of View"] = true
L["Capping is not installed or enabled"] = true
L["Capping is not loaded"] = true
L["Capping profile has been set."] = true
L["Cardinal Directions"] = true
L["Cardinal Text Offset"] = true
L["Cast Bar Custom Spark/Texture"] = true
L["Cast Radius (Default: 25)"] = true
L["Cast Thickness (Default: 5)"] = true
L["Castbar Models"] = true
L["Castbar Shield"] = true
L["Castbar Spark"] = true
L["Castbar Thickness"] = true
L["Change Combat Indicators to be class based"] = true
L["Change Fonts, Font Outlines and Action Paging"] = true
L["Change how much the Gradient Backdrop will Fade"] = true
L["Change how much the Gradient Power Backdrop will Fade"] = true
L["Change Texture Color"] = true
L["Change the Class Power background"] = true
L["Change the color of the border glow to be class bordered in nameplates"] = true
L["Change the color of the hover to be class colored"] = true
L["Change the ElvUI background"] = true
L["Change the font of LootText to be the ElvUI Default Font found in General"] = true
L["Change the font of LootText"] = true
L["Change the Horizontal Position of LootText (Default = 0)"] = true
L["Change the Ilvl font size"] = true
L["Change the look of frames to Dark or Light mode"] = true
L["Change the scale of LootText"] = true
L["Change the Scale of the World Text"] = true
L["Change the size of Autocast"] = true
L["Change the size of the borders:"] = true
L["Change the size of the button on the Quest Item Bar"] = true
L["Change the size of the Character Panel"] = true
L["Change the size of the World of Warcraft Cursor"] = true
L["Change the strata of the Loot Text"] = true
L["Change the texture of the nameplate to be a class gradient of the player's class"] = true
L["Change the texture of the nameplate to be a class gradient of the target's class"] = true
L["Change the texture of the nameplate to be a class gradient"] = true
L["Change the transparency of the Art"] = true
L["Change the transparency of the backdrop"] = true
L["Change the transparency of the health"] = true
L["Change the transparency of the Vignette"] = true
L["Change the Vertical Position of LootText (Default = 200)"] = true
L["Changelog"] = true
L["Changes Nameplate Health Height depending on conditions"] = true
L["Character Model X Offset"] = true
L["Character Model Y Offset"] = true
L["Character Model Zoom"] = true
L["Character Model"] = true
L["Character Name Font Size"] = true
L["Character Panel Scale"] = true
L["Character Panel"] = true
L["Character"] = true
L["Chat Command"] = true
L["Chat Loot Icons"] = true
L["Chat Loot Item Level"] = true
L["Chat Options"] = true
L["Chat Role Icons"] = true
L["Chat Thickness"] = true
L["Check what has changed in the current version of Eltruism"] = true
L["Choose a different font from the preselected ones"] = true
L["Choose a font for the Nameplate Powerbar Text"] = true
L["Choose a Sound from SharedMedia files"] = true
L["Choose a type of cursor by clicking it"] = true
L["Choose a version to see its changelog"] = true
L["Choose between a Class, Race or Custom Background"] = true
L["Choose between a Default Model or a Custom Model"] = true
L["Choose between Class Based Models or a Custom Model"] = true
L["Choose between custom textures or gradient mode"] = true
L["Choose custom textures for some unitframes"] = true
L["Choose the Border Texture to be used:"] = true
L["Choose the direction of the gradient"] = true
L["Choose the Health Height for Nameplates not in combat or not targeted"] = true
L["Choose the Health Height for Nameplates that are in combat or targeted"] = true
L["Choose the Ilvl font outline"] = true
L["Choose the Power Bar Texture"] = true
L["Choose the Progress Bar Texture"] = true
L["Choose the texture type"] = true
L["Choose the type of icons Details! will use:"] = true
L["Choose this size"] = true
L["Choose to show all debuffs/buffs or use default Filters"] = true
L["Choose where the Ilvl will be attach to on the items"] = true
L["Choose which types of text:"] = true
L["Circle"] = true
L["Class Color Texture with Eltruism Datatext"] = true
L["Class Colored Casts"] = true
L["Class Colored Combat"] = true
L["Class Colored Cooldowns"] = true
L["Class Colored GCD"] = true
L["Class Colored Nameplate Options"] = true
L["Class Colors"] = true
L["Class Icons"] = true
L["Class Music"] = true
L["Class Textures"] = true
L["Classes"] = true
L["Classification"] = true
L["Clear Details Tables"] = true
L["Clear Details! Damage Meter tables to free up memory"] = true
L["Collapse Quests during any combat event"] = true
L["Collapse Quests during Encounters/Boss Fights"] = true
L["Collapse Quests when the boss fight starts"] = true
L["Collapse Quests when you enter combat"] = true
L["Color 1"] = true
L["Color 2"] = true
L["Color by Reaction"] = true
L["Color Modifier Keys"] = true
L["Colors NPC name according to their difficulty compared to the player"] = true
L["Colors"] = true
L["Combat Alert"] = true
L["Combat Cursor Radius (Default: 15)"] = true
L["Combat Cursor Thickness (Default: 5)"] = true
L["Combat Hide"] = true
L["Combat Music"] = true
L["Combat Text Addons"] = true
L["Combat Text"] = true
L["Compatibility Check"] = true
L["Complete"] = true
L["Control how Blizzard Friendly Nameplates behave"] = true
L["Cooldown Pulse"] = true
L["Cooldown Pulse\n(Includes TTS)"] = true
L["Cooldown Sound"] = true
L["Cooldown"] = true
L["Cooldowns must be longer than this to show up"] = true
L["Cooldowns must be shorter than this to show up"] = true
L["Country Style"] = true
L["Credits and Licenses"] = true
L["Credits and Thank yous"] = true
L["Credits"] = true
L["Currency"] = true
L["Currently selected cursor: "] = true
L["Cursor Colors"] = true
L["Cursor Position"] = true
L["Cursor Sizes"] = true
L["Cursor Type"] = true
L["Cursor will only show during combat"] = true
L["Cursor"] = true
L["Custom Class Colors"] = true
L["Custom Color Cast"] = true
L["Custom Color Combat"] = true
L["Custom Color GCD"] = true
L["Custom Color"] = true
L["Custom Death Text"] = true
L["Custom Glow"] = true
L["Custom Gradient Details"] = true
L["Custom Health Height"] = true
L["Custom Icons"] = true
L["Custom Power Models"] = true
L["Custom Role Icons"] = true
L["Customize Blizzard's Hidden Settings"] = true
L["Customize Colors"] = true
L["Customize CVars"] = true
L["Customize Gradient Colors"] = true
L["Customize Health Status Icons"] = true
L["Customize Player CastBar Spark"] = true
L["Customize Tags"] = true
L["Customize the Chat tabs"] = true
L["Customize the Dead Icons"] = true
L["Customize the Disconnected Icons"] = true
L["Customize the Ghost Icons"] = true
L["Customize the player castbar spark"] = true
L["Customize Unitframe textures"] = true
L["CVars"] = true
L["Dark Chat"] = true
L["Dark Mode Alpha"] = true
L["Dark Mode"] = true
L["Dark Power Background"] = true
L["Database Check"] = true
L["Datatext Hiding"] = true
L["DBM is not installed or enabled so BigWigs will be used"] = true
L["DBM profile has been set."] = true
L["DBM uses DBM English by Calanon as a voice pack"] = true
L["Death Knight"] = true
L["Debuff Aura Border X offset"] = true
L["Debuff Aura Border Y offset"] = true
L["Debuff filters were setup"] = true
L["Debuff Timer"] = true
L["Decrease Nameplate Overlap when Resting"] = true
L["Decrease the time it takes for auto loot to work, works with TSM"] = true
L["Default Gradient Colors"] = true
L["Defaults"] = true
L["Demon Hunter"] = true
L["Desaturate"] = true
L["Desaturation"] = true
L["Details is an advanced combat parser"] = true
L["Details profile has been set."] = true
L["Details profile using Blizzard icons has been set."] = true
L["Details Profiles"] = true
L["Details v1 - Blizzard Flat Icons"] = true
L["Details v2 - Releaf Transparent Icons"] = true
L["Details v3 - Releaf Solid Icons"] = true
L["Details! DPS Meter"] = true
L["Detects player and target's species and uses it to fix the offset of the 3D Portrait"] = true
L["Detects target's species and uses it to fix the rotation of the Target's 3D Portrait"] = true
L["Dialog"] = true
L["Difficulty Specific Colors"] = true
L["Direct links to GitHub, CurseForge, Wago and Tukui"] = true
L["Disable Class Textures"] = true
L["Disable Combat Music in Instances"] = true
L["Disable Combat Text"] = true
L["Disable DPS Icons"] = true
L["Disable in Battlegrounds/Arenas"] = true
L["Disable in Instances"] = true
L["Disable music during combat in instances"] = true
L["Disabling a number of functions in ElvUI and Eltruism to optimize performance"] = true
L["Disconnected"] = true
L["Display stats such as Speed and Mana Regen"] = true
L["Displays a dead symbol from Releaf when unit is dead. Usage: [eltruism:dead{number}]"] = true
L["Displays a dead symbol when unit is dead. Can be customized in Eltruism > Media"] = true
L["Displays a disconnect symbol from Releaf when unit is disconnected. Usage: [eltruism:dc{number}]"] = true
L["Displays a disconnect symbol when unit is disconnected. Can be customized in Eltruism > Media"] = true
L["Displays a Text with the name of the spell"] = true
L["Displays an icon when the unit is in combat, uses player icon"] = true
L["Displays current health percentage and health lost in shortvalue"] = true
L["Displays Details nickname in class color or reaction color if Details is loaded"] = true
L["Displays health lost in shortvalue and current health percentage"] = true
L["Displays HP - % and a status symbol from Releaf for players. Usage: [eltruism:hpstatus{number,number}]"] = true
L["Displays HP - % and a status symbol. Can be customized in Eltruism > Media"] = true
L["Displays HP and a status symbol from Releaf for players"] = true
L["Displays name and title"] = true
L["Displays NPC title in gradient with brackets"] = true
L["Displays NPC title in gradient"] = true
L["Displays percentage health with status icons"] = true
L["Displays shortvalue HP and a status symbol for players. Can be customized in Eltruism > Media"] = true
L["Displays shortvalue HP and a status symbol from Releaf for players. Usage: [eltruism:hpstatusnopc{number,number}]"] = true
L["Displays the current target of the unit, accepts length args"] = true
L["Displays the guild name with brackets in gradient"] = true
L["Displays the name of the unit with abbreviation, accepts length args"] = true
L["Displays the number of the group for the first member of that group, raid sorting can break this tag making it show up on other members."] = true
L["Displays the number of the group for the first member of that group, \nraid sorting can break this tag making it show up on other members."] = true
L["Displays unit name in caps while being class color or reaction color, shortens over 16 characters but can be changed with {arg}"] = true
L["Displays unit name in gradient class color or reaction color"] = true
L["Displays unit name in gradient class color or reaction color, shortens over 16 characters"] = true
L["Donators"] = true
L["Double Click:"] = true
L["DPS"] = true
L["DPS/Tank Layout has been set."] = true
L["DPS/Tank layouts were created with pure dps classes in mind, if you play a class with more raid cooldowns like a Shaman, Druid or Paladin you might want to use the alternative layout in order to make it easier for you to use your cooldowns on the members of your group"] = true
L["DPS\nTank"] = true
L["Druid"] = true
L["Dungeon (Heroic)"] = true
L["Dungeon (Mythic Plus)"] = true
L["Dungeon (Mythic)"] = true
L["Dungeon (Timewalking)"] = true
L["Dungeon"] = true
L["Dynamic Cam profile has been set."] = true
L["Dynamic Datatext that changes according to class to show Ammo or Soul Shards when playing Hunter, Warrior, Rogue or Warlock"] = true
L["Dynamic Render Scale Minimum"] = true
L["Dynamic Render Scale"] = true
L["Dynamically toggle the mouseover of the Experience Bar"] = true
L["Each Button in the Quest Item Bar will appear only if the cursor is over it"] = true
L["Edge"] = true
L["Effect"] = true
L["Elite Color"] = true
L["Elite Icon"] = true
L["Eltruism Ammo"] = true
L["Eltruism Boss Buffs"] = true
L["Eltruism Boss Debuffs"] = true
L["Eltruism Config"] = true
L["Eltruism database was converted.\n|cff82B4ffThe Following profiles were updated:|r\n%s\n\n|cff82B4ffPrivate settings were updated for the following private profiles:|r\n%s\n\n|cff82B4ffIf you have any issues please report in Discord or open a ticket.|r\n|cffff0000A Reload is necessary to save this conversion and fix variables|r"] = true
L["Eltruism Focus Buffs"] = true
L["Eltruism Focus Debuffs"] = true
L["Eltruism Hearthstones/Teleports"] = true
L["Eltruism Honor/Conquest Points"] = true
L["Eltruism Installer"] = true
L["Eltruism Modes"] = true
L["Eltruism Nameplate Buffs"] = true
L["Eltruism Nameplate Debuffs"] = true
L["Eltruism Party Buffs"] = true
L["Eltruism Party Debuffs"] = true
L["Eltruism Player Buffs"] = true
L["Eltruism Player Debuffs"] = true
L["Eltruism Raid Buffs"] = true
L["Eltruism Raid Debuffs"] = true
L["Eltruism Settings"] = true
L["Eltruism Target Buffs"] = true
L["Eltruism Target Debuffs"] = true
L["Eltruism uses a 0.7 scale, but ElvUI can calculate the best scale for you using the Automatic Scale option"] = true
L["Eltruism uses Dark Mode by default"] = true
L["Eltruism uses Kimberley as the default font"] = true
L["Eltruism uses Transparent chat by default"] = true
L["EltruismConsumablesWA"] = true
L["ElvUI Chat has been set."] = true
L["ElvUI NamePlates were setup."] = true
L["ElvUI Plugins"] = true
L["ElvUI Settings"] = true
L["Embed"] = true
L["Emphasize"] = true
L["Empowering Color"] = true
L["Enable !key and !keys chat command"] = true
L["Enable a border for the Pixel Glow"] = true
L["Enable a Custom death animation"] = true
L["Enable a Dark Souls death animation"] = true
L["Enable a GTA death animation"] = true
L["Enable a start animation"] = true
L["Enable a toast showing up when you level up"] = true
L["Enable Ace3 Skin"] = true
L["Enable adding models as effects on Castbars"] = true
L["Enable adding models as effects on unitframes"] = true
L["Enable adding more functions to ElvUI Chat"] = true
L["Enable Always Forcing ElvUI Chat Toggles On"] = true
L["Enable AMD FSR even if not scaling"] = true
L["Enable an extra Power Bar on Nameplates for missing powers"] = true
L["Enable Animation and Sound when Guild Member Dies"] = true
L["Enable Auto-adjusting Buffs/Debuffs"] = true
L["Enable Auto-adjusting the actionbar spacing and position"] = true
L["Enable Auto-adjusting the position of Buffs/Debuffs"] = true
L["Enable Auto-adjusting the Vertical Position of the Power Bar"] = true
L["Enable Automatic Combat Log"] = true
L["Enable Automatically accepting/turning in Quests when not holding CTRL/SHIFT/ALT"] = true
L["Enable Automatically Closing Loot Window"] = true
L["Enable Automatically Confirming Bind on Pickup"] = true
L["Enable Autopin"] = true
L["Enable Blizzard Icons"] = true
L["Enable Borders"] = true
L["Enable Boss Music"] = true
L["Enable Cardinal Directions"] = true
L["Enable changing textures and gradients for ElvUI unitframes"] = true
L["Enable Chat Icons"] = true
L["Enable Combat Music"] = true
L["Enable Comparing Equipped and Bag Ilvl"] = true
L["Enable Cooldown Pulse"] = true
L["Enable cooldown tracking"] = true
L["Enable cursor only during combat"] = true
L["Enable cursor rings for Casts, GCD and Combat"] = true
L["Enable Custom Colors for Nameplates"] = true
L["Enable Custom Colors for Unitframes"] = true
L["Enable Custom Colors"] = true
L["Enable Custom Font"] = true
L["Enable Custom Gradient Power Colors"] = true
L["Enable Custom Gradient Power"] = true
L["Enable Custom Health Heights"] = true
L["Enable Custom Icons"] = true
L["Enable Custom Set Colors"] = true
L["Enable Custom Textures"] = true
L["Enable Eltruism Icons"] = true
L["Enable ElvUI Chat modifications"] = true
L["Enable Entering/Leaving Combat Indicator Texts"] = true
L["Enable ETA"] = true
L["Enable Fast Loot with Loot Quality Filter"] = true
L["Enable Fast Loot with Wishlist Filter"] = true
L["Enable Fast Loot"] = true
L["Enable filtering item quality, items can still be looted by holding Shift or the mod key setup in Interface"] = true
L["Enable Floating Reputation Changes"] = true
L["Enable for Arena"] = true
L["Enable for Boss Emote Frame"] = true
L["Enable for Boss"] = true
L["Enable for Error Frame"] = true
L["Enable for Focus Target"] = true
L["Enable for Focus"] = true
L["Enable for Group Units"] = true
L["Enable for Pet"] = true
L["Enable for Player Castbar (Interrupted)"] = true
L["Enable for Player Castbar (Non Interruptible)"] = true
L["Enable for Player Castbar"] = true
L["Enable for Player"] = true
L["Enable for Target Castbar (Interrupted)"] = true
L["Enable for Target Castbar (Non Interruptible)"] = true
L["Enable for Target Castbar"] = true
L["Enable for Target of Target of Target"] = true
L["Enable for Target of Target"] = true
L["Enable for Target"] = true
L["Enable for Zones, Mail and others"] = true
L["Enable General Shadows"] = true
L["Enable Gradient (Requires Dark or Light Modes)"] = true
L["Enable Gradient Aurabars"] = true
L["Enable Gradient Backdrop"] = true
L["Enable Gradient Class Bar"] = true
L["Enable Gradient colors for Health"] = true
L["Enable Gradient colors for Nameplates. |cffFF0000WARNING:|r This will overwrite some default ElvUI NP settings, if you dont want this, please disable this feature."] = true
L["Enable Gradient colors for Pet"] = true
L["Enable Gradient colors for Player Castbar (Interrupted)"] = true
L["Enable Gradient colors for Player Castbar (Non Interruptible)"] = true
L["Enable Gradient colors for Player Castbar"] = true
L["Enable Gradient colors for Target Castbar (Interrupted)"] = true
L["Enable Gradient colors for Target Castbar (Non Interruptible)"] = true
L["Enable Gradient colors for Target Castbar"] = true
L["Enable Gradient Glow"] = true
L["Enable Gradient Nameplates"] = true
L["Enable Gradient Power Colors"] = true
L["Enable Gradient Power"] = true
L["Enable Gradient Tooltips"] = true
L["Enable Gradient"] = true
L["Enable ignoring Spells"] = true
L["Enable Information Panel on Top"] = true
L["Enable Item Levels"] = true
L["Enable Mail Animation"] = true
L["Enable Models/Effects"] = true
L["Enable music during combat"] = true
L["Enable Nameplate Power Bar"] = true
L["Enable on Action Bars"] = true
L["Enable on All Unitframes"] = true
L["Enable on Aura Bars"] = true
L["Enable on Buttons"] = true
L["Enable on Chat Messages"] = true
L["Enable on Nameplate"] = true
L["Enable on Pet Bar"] = true
L["Enable on Shaman Air Totem"] = true
L["Enable on Shaman Earth Totem"] = true
L["Enable on Shaman Fire Totem"] = true
L["Enable on Shaman Totems"] = true
L["Enable on Shaman Water Totem"] = true
L["Enable on System Messages"] = true
L["Enable on Unitframes"] = true
L["Enable only for listed Spells"] = true
L["Enable or disable Blizzard's default Floating Combat Text for Mana/Rage/Energy and other resouces"] = true
L["Enable or disable Blizzard's default Floating Combat Text"] = true
L["Enable pet cooldown tracking"] = true
L["Enable Pixel Border"] = true
L["Enable Playing a Sound if an item from the wishlist is looted"] = true
L["Enable Portrait Skin"] = true
L["Enable Quest Item Bar"] = true
L["Enable Releaf Icons"] = true
L["Enable removing the Alert Frame that can show up in the middle of the screen"] = true
L["Enable replacing Elite/Rare Icons"] = true
L["Enable Resource Gains"] = true
L["Enable Screenshotting if an item from the wishlist is looted"] = true
L["Enable Shadows"] = true
L["Enable Showing Author, Donator and MVP Chat Icons"] = true
L["Enable Skin"] = true
L["Enable Smart Classbar"] = true
L["Enable Soft Target Interactions"] = true
L["Enable Target Model"] = true
L["Enable the /way and /waypoint commands"] = true
L["Enable the Dynamic Datatext"] = true
L["Enable the Expanded Stable"] = true
L["Enable the Floating Rep Text"] = true
L["Enable the Rogue Order Hall Auto Open"] = true
L["Enable the Skins"] = true
L["Enable the Wider Transmog Window"] = true
L["Enable this option"] = true
L["Enable Unitframe Auras"] = true
L["Enable Unitframe Modifications"] = true
L["Enable Wishlist Loot Warning"] = true
L["Enable World Map Scaling"] = true
L["Enable Wowhead Button on Quest Log"] = true
L["Enable Wowhead Button"] = true
L["Enable"] = true
L["Enables a frame that shows a cooldown and count for battle resurrections while in an instance that has them"] = true
L["Enemy Nameplate Level"] = true
L["Enhance Chat Functionality"] = true
L["Enhance ElvUI Nameplates with options for gradient, size, textures, models, behavior and more"] = true
L["Enhance Item Links in Chat"] = true
L["Enhance the AFK screen"] = true
L["Error Frame Font Size"] = true
L["Example: "] = true
L["Expand Character Art"] = true
L["Expand Character Panel"] = true
L["Expand Hunter Stables to show all pets and improve search"] = true
L["Expand Talents to cover the full tree"] = true
L["Expand the Talents to show the entire tree"] = true
L["Expand Transmog Window to better show your character"] = true
L["Expanded Talents"] = true
L["Extra Media"] = true
L["Fade In Time"] = true
L["Fade Out Time"] = true
L["Fade"] = true
L["Fast Loot"] = true
L["FCT profile will be used"] = true
L["Feel free to explore Eltruism settings in ElvUI > Eltruism.\nThere are lot of settings that are disabled by default."] = true
L["Fill Orientation"] = true
L["Finished"] = true
L["Flag"] = true
L["Flags"] = true
L["Flight Frame Scale"] = true
L["Flight Frame"] = true
L["Floating Combat Text profile has been set."] = true
L["Focus Border"] = true
L["Focus Castbar Border"] = true
L["Focus Target Border"] = true
L["Focus Texture"] = true
L["Focus Thickness"] = true
L["Font has been set."] = true
L["Font Shadow"] = true
L["Fonts were set to Outline due to your resolution."] = true
L["Fonts"] = true
L["For Shadowlands, import aura filters by copying the code below and going into Profiles > Import Profile."] = true
L["Force ElvUI Chat Toggles"] = true
L["Forces AMD's FSR to sharpen image even if you aren't running a lower resolution"] = true
L["Frames"] = true
L["Friendly Nameplates"] = true
L["Friendly NPC"] = true
L["Fully customize how action bars glow and add glows to debuffs on unitframes"] = true
L["GCD Radius (Default: 20)"] = true
L["GCD Thickness (Default: 5)"] = true
L["General CVars have been set."] = true
L["General CVars"] = true
L["General Layout has been set."] = true
L["Gladdy and Gladius are not installed or enabled"] = true
L["Gladdy is not installed or enabled (You can find the Gladius profile in Eltruism Settings)"] = true
L["Gladdy profile has been set."] = true
L["Gladius profile can be found in Eltruism > Addons, please check it there"] = true
L["Gladius profile has been set."] = true
L["GladiusEx profile has been set."] = true
L["GladiusEx"] = true
L["Global Scaling of nameplates after selected, min, and max scale"] = true
L["Glow Colors"] = true
L["Good Color"] = true
L["Good Threat Transition"] = true
L["Good Threat"] = true
L["Gradient Archeology Digsite Bar"] = true
L["Gradient Backdrop Fade"] = true
L["Gradient BigWigs"] = true
L["Gradient Colors"] = true
L["Gradient Details Names"] = true
L["Gradient Details"] = true
L["Gradient Health Loss"] = true
L["Gradient Item Color Offsets"] = true
L["Gradient Mode"] = true
L["Gradient Name"] = true
L["Gradient Nameplate Health"] = true
L["Gradient Nameplate\nHealth/CastBar/Threat"] = true
L["Gradient Orientation"] = true
L["Gradient Power Backdrop"] = true
L["Gradient Power Orientation"] = true
L["Gradient Power"] = true
L["Gradient Texture"] = true
L["Gradient Zone/Mail/Quest Text"] = true
L["Gradient"] = true
L["Graphics"] = true
L["Green"] = true
L["Grey Background"] = true
L["Group Unitframe Thickness"] = true
L["Guild"] = true
L["Hardware Cursor"] = true
L["Healer Layout has been set."] = true
L["Healer"] = true
L["Health Alpha"] = true
L["Health Bars"] = true
L["Health Height"] = true
L["Hide Actionbar Button Press"] = true
L["Hide Alert Frame"] = true
L["Hide Arena Frames in Arena due to Gladius/Gladdy or another addon"] = true
L["Hide Arena Frames in Arena due to Gladius/GladiusEX or another addon"] = true
L["Hide Auras on Nameplates that are not in Combat"] = true
L["Hide Auras"] = true
L["Hide Backdrop"] = true
L["Hide Blizzard Frames"] = true
L["Hide Blizzard Friendly Nameplates everywhere"] = true
L["Hide Blizzard Friendly Nameplates inside Instances"] = true
L["Hide Boss Banner Frame"] = true
L["Hide Cooldown Swipe on Buffs and Debuffs"] = true
L["Hide Cooldown Swipe"] = true
L["Hide Debuffs on Non Target"] = true
L["Hide Debuffs on Non Targeted Nameplates, show when Targeted"] = true
L["Hide Error Frame"] = true
L["Hide Event Toaster Frame"] = true
L["Hide Left Chat Datatext out of Combat"] = true
L["Hide Left Chat in Boss Encounters"] = true
L["Hide Left Chat in Combat"] = true
L["Hide level on enemy nameplates when you are max level"] = true
L["Hide Minimap while in Combat"] = true
L["Hide NPC Names when they are too far away to have Nameplates"] = true
L["Hide Out of Combat"] = true
L["Hide Quests during Battlegrounds and Arenas"] = true
L["Hide Raid Unitframes in battlegrounds due to addons like Battleground Enemies"] = true
L["Hide Right Chat Datatext out of Combat"] = true
L["Hide Right Chat in Boss Encounters"] = true
L["Hide Right Chat in Combat"] = true
L["Hide Talking Head"] = true
L["Hide the Alert Frame that appears when looting a rare item or earning an achievement"] = true
L["Hide the boss banner that appears when killing a raid boss or completing a Mythic+ dungeon"] = true
L["Hide the Red Error Text"] = true
L["Hide the text that appears when changing zones"] = true
L["Hide the toaster frame, such as when you level up"] = true
L["Hide Zone Text"] = true
L["High"] = true
L["Hold Time"] = true
L["Honor"] = true
L["Horizontal Offset"] = true
L["Horizontal"] = true
L["Hostile NPC"] = true
L["Hover"] = true
L["How long the Icon will appear"] = true
L["How to use the Anchors"] = true
L["Hunter"] = true
L["Hybrid"] = true
L["Icon Size"] = true
L["Icons"] = true
L["If the player is not moving then *** will show up since time cannot be calculated"] = true
L["If you move away from the waypoint the time will just increase"] = true
L["Ignored Spells, use a comma to separate spells"] = true
L["Ilvl Anchor Point"] = true
L["Ilvl Font Outline"] = true
L["Ilvl Font Size"] = true
L["Ilvl Font X Offset"] = true
L["Ilvl Font Y Offset"] = true
L["Immersion profile has been set."] = true
L["Import "] = true
L["Import a profile for NameplateSCT configured for Eltruism"] = true
L["Import a profile for Simpy's ElvUI FCT configured for Eltruism"] = true
L["Import BattlegroundEnemies profile for battlegrounds"] = true
L["Import Capping profile for battlegrounds"] = true
L["Import DBM or BigWigs profiles for dungeons and raids. (Uses DBM English Calanon and Bigwigs Voice)"] = true
L["Import DBM or Bigwigs profiles"] = true
L["Import Details! profile with dual panels"] = true
L["Import Dynamic Cam profile"] = true
L["Import GladiusEx profile for arenas, remember to disable ElvUI Arena Frames"] = true
L["Import Method Raid Tools profile with raid cooldowns and other settings"] = true
L["Import OmniCD profile"] = true
L["Import profiles for Gladdy (Gladius can be found in Eltruism settings)"] = true
L["Import profiles for Gladdy"] = true
L["Import profiles for Gladius"] = true
L["Import profiles for NameplateSCT or ElvUI Floating Combat Text"] = true
L["Import Questie profile, which uses the DBM radar"] = true
L["Import WarpDeplete profile for Mythic Plus"] = true
L["Importance: "] = true
L["In Combat/Targeted"] = true
L["In order to use this feature, simply go to your Weakaura, and go to its Group options, scroll down to Position Settings and set the Anchored To Select Frame, then type either |cff82B4ffEltruismWA|r or |cff82B4ffEltruismConsumablesWA|r to anchor the weakaura to the preset location"] = true
L["In screen % the inset from the Bottom"] = true
L["In screen % the inset from the Top"] = true
L["Install or update other Addon profiles"] = true
L["Install, Reinstall or Update various parts of Eltruism"] = true
L["Installation Complete"] = true
L["Installer"] = true
L["Instance Text Color"] = true
L["Instance text Font Size"] = true
L["Instance Texts"] = true
L["Invalid Item, you need to add an itemID which can be found in the tooltip or in Wowhead"] = true
L["Invalid Model, you need to add a Model ID/Path"] = true
L["Invert CTRL/SHIFT/ALT"] = true
L["Invert left mouse click so that chat starts faded and mouse click will make it stop fading"] = true
L["Invert Mouse Click"] = true
L["It has many plugins to choose from"] = true
L["It will set these CVars:"] = true
L["Item Deletion"] = true
L["Item Level on Tooltip"] = true
L["Item Level"] = true
L["Item Levels"] = true
L["Item Quality"] = true
L["Item Wishlist (type the Item ID)"] = true
L["Items in your wishlist will display a warning when looted"] = true
L["Items not on the wishlist will not be looted, items can still be looted by holding Shift or the mod key setup in Interface"] = true
L["Join the Discord for faster support and to report any issues you might encounter"] = true
L["Join the Discord if you have any questions or issues (English Support)"] = true
L["Join the Discord if you have any questions or issues"] = true
L["Keep in mind the discord is in English"] = true
L["Keystone Autoinsert"] = true
L["Keystone\n!key command/Autoinsert"] = true
L["Launch Eltruism Installer"] = true
L["Launches the Eltruism install prompt"] = true
L["Layout has been set."] = true
L["Layouts"] = true
L["Leader Icons"] = true
L["Learn how to use the WeakAuras anchors to attach WeakAuras and use ElvUI's movers to move them"] = true
L["Left Chat Border X offset"] = true
L["Left Chat Border Y offset"] = true
L["Left Chat Mouse Over"] = true
L["Left Click:"] = true
L["Left Inactivity Fader"] = true
L["Left Offset"] = true
L["License"] = true
L["Light Mode Alpha"] = true
L["Light Mode Texture Version"] = true
L["Light Mode"] = true
L["Limit Max Distance"] = true
L["Line Height"] = true
L["Line Texture"] = true
L["Line Width"] = true
L["Line"] = true
L["List of spells allowed, use a comma to separate spells"] = true
L["List of spells ignored, use a comma to separate spells"] = true
L["Loot Window will automatically close when using filters and the item desired is not found"] = true
L["Loot Window will automatically confirm looting Bind on Pickup items"] = true
L["Low"] = true
L["Lowers render scale if GPU bound to hit Target FPS."] = true
L["Lowest Render Scale used"] = true
L["Mage"] = true
L["Mail Animation"] = true
L["Mail Text"] = true
L["Make Buffs and Debuffs Wide on Nameplates"] = true
L["Make Mage and Warlock use their original Class Colors"] = true
L["Make more texts use ElvUI font settings"] = true
L["Make Shamans Blue instead of Pink"] = true
L["Make sure to install "] = true
L["Make the warnings to install profiles for other plugins stop"] = true
L["Manage Debuff Style Filter"] = true
L["Map not found"] = true
L["Map Scale"] = true
L["Maps"] = true
L["MAP_SEARCHER_TOOLTIP_TITLE"] = true
L["Master Looter Icons"] = true
L["Max Distance"] = true
L["Maximum Camera Zoom Out"] = true
L["Maximum Cooldown Length"] = true
L["Media"] = true
L["Medium Color"] = true
L["Medium"] = true
L["Method Raid Tools profile has been set."] = true
L["Method Raid Tools"] = true
L["Minimal Buffs"] = true
L["Minimal Debuffs"] = true
L["Minimal"] = true
L["Minimap Cardinal Directions"] = true
L["Minimap Thickness"] = true
L["Minimum Cooldown Length"] = true
L["Minimum Loot Quality Filter"] = true
L["Misc"] = true
L["Miscellaneous"] = true
L["Model Alpha"] = true
L["Model Rotation"] = true
L["Model Types"] = true
L["Model"] = true
L["Models"] = true
L["Monk"] = true
L["Move ActionBars and Power to be similar to WeakAuras"] = true
L["Name of file inside Interface\\Addons"] = true
L["Nameplate Aura"] = true
L["Nameplate Buff/Debuff"] = true
L["Nameplate Castbar"] = true
L["Nameplate Colors"] = true
L["Nameplate Custom Color"] = true
L["NamePlate CVars have been set."] = true
L["Nameplate Global Scale"] = true
L["Nameplate Health"] = true
L["Nameplate Occluded Alpha"] = true
L["Nameplate Other Bottom Inset"] = true
L["Nameplate Other Top Inset"] = true
L["Nameplate Portrait"] = true
L["Nameplate Power Bar Border"] = true
L["Nameplate Power Bar Thickness"] = true
L["Nameplate Power Bar"] = true
L["Nameplate Power"] = true
L["Nameplate Powerbar Appearance"] = true
L["Nameplate Powerbar Font Size"] = true
L["Nameplate Powerbar Font"] = true
L["Nameplate Powerbar Position"] = true
L["Nameplate Powerbar Size"] = true
L["NamePlate Style Filters were set."] = true
L["Nameplate Target Radial Position"] = true
L["Nameplate Texture Version"] = true
L["NameplateSCT and ElvUI FCT are not installed or enabled"] = true
L["NameplateSCT profile has been set."] = true
L["NameplateSCT profile will be used"] = true
L["Neutral NPC"] = true
L["No quest selected"] = true
L["None"] = true
L["Normal Combat Music"] = true
L["Normal"] = true
L["Note this feature is in BETA.\nKnown issues:\n - May cause hitching.\n - May behave poorly with vsync on."] = true
L["NPC Castbars (Interruptible)"] = true
L["NPC Textures"] = true
L["NPCs use Target Castbar colors not NPC colors for their castbars"] = true
L["Number of Pixels (Default is 9)"] = true
L["Objective Frame Anchor"] = true
L["Objective Tracker"] = true
L["Off Tank Bad Threat Transition"] = true
L["Off Tank Good Threat Transition"] = true
L["Off Tank"] = true
L["OmniCD is not installed or enabled"] = true
L["OmniCD profile has been set."] = true
L["Only items of this quality or better will be displayed"] = true
L["Only items of this quality or better will be looted when using Fast Loot Filter"] = true
L["Only loads when Questie is not enabled"] = true
L["Open Eltruism Configuration Panel"] = true
L["Open Eltruism Installation"] = true
L["Open WeakAuras, go to your group Weakauras and in Group change Position Settings > Anchored To > Select Frame > EltruismWA or EltruismConsumablesWA"] = true
L["Optional"] = true
L["Or change it later in Eltruism > Media options"] = true
L["Or choose a custom font"] = true
L["Original Group, Raid and Raid40 layout has been set"] = true
L["Original Layout"] = true
L["Other AddOns"] = true
L["Other CVars"] = true
L["Other Formats can end up causing errors"] = true
L["Other Shadows (can become CPU/Memory Intensive)"] = true
L["Other Skins"] = true
L["Other"] = true
L["Out of Combat Delay"] = true
L["Out of Combat/Not Targeted"] = true
L["Outline"] = true
L["Overwrites some profile settings to move ActionBars, Unitframes and Powers to look more similar to a WeakAura. |cffFF0000WARNING:|r This will overwrite some of your profile settings with no way to restore"] = true
L["Overwrites some profile settings to move ActionBars, Unitframes and Powers to look similar to a WeakAura. |cffFF0000WARNING:|r This will overwrite some of your profile settings"] = true
L["Paladin"] = true
L["Panel"] = true
L["Party Border"] = true
L["Party/Raid"] = true
L["Path to file"] = true
L["Pause and Desaturate Portrait if Dead"] = true
L["Perform a Database Check if you are updating from a very old version as some settings have changed places and the Database Check will convert them"] = true
L["Pet Action Bar Thickness"] = true
L["Pet Action Bar X offset"] = true
L["Pet Action Bar Y offset"] = true
L["Pet Action Bar"] = true
L["Pet Bar"] = true
L["Pet Border"] = true
L["Pet Texture"] = true
L["Pet Thickness"] = true
L["Pets"] = true
L["Pixel Border"] = true
L["Pixel Frequency (Default is 1)"] = true
L["Pixel Glow"] = true
L["Pixel Horizontal Offset (Default is 5)"] = true
L["Pixel Length (Default is 3)"] = true
L["Pixel Thickness (Default is 5)"] = true
L["Pixel Vertical Offset (Default is 5)"] = true
L["Pixel"] = true
L["Play a Blizzard animation when receiving mail or when new mail exists"] = true
L["Play a Sound when attempting to use a skill that is on cooldown."] = true
L["Play a Sound when receiving mail"] = true
L["Play a sound when someone dies in Party or Raid"] = true
L["Play a sound when you Die in Hardcore"] = true
L["Play custom music during fights and boss fights"] = true
L["Play music during combat"] = true
L["Play music while you are AFK"] = true
L["Play sounds when party members die, show resurrection timers and change instance texts"] = true
L["Player Border"] = true
L["Player Castbar (Interrupted)"] = true
L["Player Castbar (Non Interruptible)"] = true
L["Player Castbar Border"] = true
L["Player Castbar Texture"] = true
L["Player Castbar"] = true
L["Player Class Texture"] = true
L["Player names in chat will have a class gradient"] = true
L["Player names in chat will have a class icon next to their name"] = true
L["Player Texture"] = true
L["Plays a sound if someone rolls 1 or 100 out 100"] = true
L["Plays a voiced emote when you have low health. Usage: [eltruism:lowhealth{1}] as an example of 1%"] = true
L["Plays a voiced emote when you have low mana as a healer. Usage: [eltruism:lowmana{5}] as an example of 5%"] = true
L["Plays an animation when you die"] = true
L["Please click Finished to reload the UI"] = true
L["Please read the instructions to avoid issues"] = true
L["Please select the role for your character, which will create a new profile.\nThis process can take a few seconds"] = true
L["Portrait Skin"] = true
L["Power Bar Models"] = true
L["Power Bar will move automatically based on class/spec/druid form"] = true
L["Power Bar"] = true
L["Power Colors"] = true
L["Power Models"] = true
L["Prevent Blizzard's Talking Head from appearing"] = true
L["Preview the Glow"] = true
L["Preview the Glow, you will need to toggle it off and on to update the glow"] = true
L["Priest"] = true
L["Proc Glow"] = true
L["ProjectAzilroka profile has been set."] = true
L["ProjectAzilroka"] = true
L["PVP/PVE Addons"] = true
L["QOL Addons"] = true
L["Quest Autoaccept"] = true
L["Quest Detail Scale"] = true
L["Quest Item Bar Button Mouse Over"] = true
L["Quest Item Bar Button Size"] = true
L["Quest Item Bar follows visibility settings for ElvUI Action Bar 1"] = true
L["Quest Item Bar"] = true
L["Questie is not installed or enabled"] = true
L["Questie profile has been set."] = true
L["Questie"] = true
L["Quests Skin"] = true
L["Racial Music"] = true
L["Raid (Heroic)"] = true
L["Raid (LFR)"] = true
L["Raid (Mythic)"] = true
L["Raid (Normal)"] = true
L["Raid (Timewalking)"] = true
L["Raid Border"] = true
L["Raid1 Border"] = true
L["Raid2 Border"] = true
L["Raid3 Border"] = true
L["Raid40 Border"] = true
L["Randomize Music Order"] = true
L["Rare Color"] = true
L["Rare Elite Color"] = true
L["Rare Elite Icon"] = true
L["Rare Elite"] = true
L["Rare Icon"] = true
L["Reactivate the ElvUI Objective Frame Anchor and Mover"] = true
L["Ready"] = true
L["Red"] = true
L["Reinstall DPS Layout"] = true
L["Reinstall Eltruism Datatext"] = true
L["Reinstall Healer Layout"] = true
L["Reinstall"] = true
L["Remember to swap the second window to Healing Done or Tiny Threat"] = true
L["Remove Blizzard's Boss Emote Frame"] = true
L["Remove item from Wishlist"] = true
L["Replace Blizzards Default Glow with a Custom Glow"] = true
L["Replace Details Bar Texture"] = true
L["Replace ElvUI Rest Icon with Blizzard's Animated one"] = true
L["Replace Leader icons with Eltruism leader icons"] = true
L["Replace Master Looter icons with Eltruism Master Looter icons"] = true
L["Replace Raid Assist icons with Eltruism Raid Assist icons"] = true
L["Replace role icons with Eltruism role icons"] = true
L["Replace Texture"] = true
L["Report issues and problems here:"] = true
L["Requires a Reload"] = true
L["Requires ElvUI Nameplate Elite Icon"] = true
L["Requires Light Mode Enabled"] = true
L["Reset all Media"] = true
L["Reset Chat to ElvUI Settings"] = true
L["Reset Fonts, Textures, Skins to Eltreum UI defaults."] = true
L["Reset layout to Eltruism DPS/Tank"] = true
L["Reset layout to Eltruism Healer"] = true
L["Reset Nameplate Style Filters"] = true
L["Reset nameplates to Eltruism settings"] = true
L["Reset Nameplates"] = true
L["Reset Scale"] = true
L["Reset Style Filters"] = true
L["Reset to Eltruism defaults."] = true
L["Reset/Add Eltruism Datatext Panel"] = true
L["Reset/Update Eltruism Settings"] = true
L["Reset/Update ElvUI Settings"] = true
L["Resets/Updates Eltruism Settings to Eltreum's Defaults"] = true
L["Resets/Updates ElvUI Settings to Eltreum's Defaults"] = true
L["Rested Nameplates"] = true
L["Restore All Blizzard Combat Text"] = true
L["Restore Hidden Names"] = true
L["Restore Unit Names hidden by Hide NPC Names"] = true
L["Restore Unit Names Hidden during install"] = true
L["Return LootText to its default scale"] = true
L["Returns class color only for players"] = true
L["Reverse Gradient"] = true
L["Reverse Target Gradient Health"] = true
L["Reverse Target"] = true
L["Right Chat Border X offset"] = true
L["Right Chat Border Y offset"] = true
L["Right Chat Mouse Over"] = true
L["Right Click:"] = true
L["Right Inactivity Fader"] = true
L["Right Offset"] = true
L["Rogue"] = true
L["Role Icons"] = true
L["Run Database Check"] = true
L["Select a size"] = true
L["Select a Sound"] = true
L["Select a Texture"] = true
L["Select a type of music"] = true
L["Select a Type"] = true
L["Select a version:"] = true
L["Select how auras will be displayed for Aura Bars"] = true
L["Select how auras will be displayed for Boss"] = true
L["Select how auras will be displayed for Focus"] = true
L["Select how auras will be displayed for Nameplates"] = true
L["Select how auras will be displayed for Party"] = true
L["Select how auras will be displayed for Player"] = true
L["Select how auras will be displayed for Raid"] = true
L["Select how auras will be displayed for Target"] = true
L["Select the Horizontal Size of the Power Bar (Default 132)"] = true
L["Select the power types to be displayed:"] = true
L["Select the size of the World Text"] = true
L["Select the Vertical Size of the Power Bar (Default 6)"] = true
L["Select the Y Offset for the Power Bar (Default 16)"] = true
L["Select which type of teleports to use on double click"] = true
L["Set Details tables to be empty"] = true
L["Set filters to be Eltruism defaults on Boss"] = true
L["Set filters to be Eltruism defaults on Focus"] = true
L["Set filters to be Eltruism defaults on Nameplates"] = true
L["Set filters to be Eltruism defaults on Party"] = true
L["Set filters to be Eltruism defaults on Player"] = true
L["Set filters to be Eltruism defaults on Raid"] = true
L["Set filters to be Eltruism defaults on Target"] = true
L["Set filters to show more buffs on Boss"] = true
L["Set filters to show more buffs on Focus"] = true
L["Set filters to show more buffs on Nameplates"] = true
L["Set filters to show more buffs on Party"] = true
L["Set filters to show more buffs on Player"] = true
L["Set filters to show more buffs on Raid"] = true
L["Set filters to show more buffs on Target"] = true
L["Set filters to show more debuffs on Boss"] = true
L["Set filters to show more debuffs on Focus"] = true
L["Set filters to show more debuffs on Nameplates"] = true
L["Set filters to show more debuffs on Party"] = true
L["Set filters to show more debuffs on Player"] = true
L["Set filters to show more debuffs on Raid"] = true
L["Set filters to show more debuffs on Target"] = true
L["Set Horizontal Size"] = true
L["Set the Font Outlines everywhere. Use Default to return to Eltruism default settings"] = true
L["Set the fonts used in Eltruism. Kimberley is the default font"] = true
L["Set the frequency pixel glow"] = true
L["Set the horizontal offset of autocast"] = true
L["Set the horizontal offset of pixels"] = true
L["Set the horizontal offset"] = true
L["Set the length of pixels"] = true
L["Set the level that LootText will be drawn to this"] = true
L["Set the number of groups for autocast, for each group you get 4 particles"] = true
L["Set the number of pixels in pixel glow"] = true
L["Set the radius of the cast cursor"] = true
L["Set the radius of the combat cursor"] = true
L["Set the radius of the gcd cursor"] = true
L["Set the size of LootText"] = true
L["Set the thickness of pixels"] = true
L["Set the thickness of the combat cursor"] = true
L["Set the thickness of the gcd cursor"] = true
L["Set the vertical offset of autocast"] = true
L["Set the vertical offset of pixels"] = true
L["Set the vertical offset"] = true
L["Set Vertical Size"] = true
L["Set Width of the Spark (Default 3)"] = true
L["Set X Offset"] = true
L["Set Y Offset"] = true
L["Sets Class Power backgrounds to be black"] = true
L["Sets Cooldowns to be Class Colored"] = true
L["Sets Information panel to be on Top instead of Bottom of the unitframe"] = true
L["Sets the Backdrop as Transparent/Hidden"] = true
L["Setting "] = true
L["settings configured for "] = true
L["Settings for ElvUI were updated."] = true
L["Setup Aura Filters to be Eltruism defaults"] = true
L["Setup Aura Filters to show all"] = true
L["Setup CVars"] = true
L["Setup Media"] = true
L["Shadow and Light"] = true
L["Shadow Size"] = true
L["Shadows"] = true
L["Shaman Air Totem"] = true
L["Shaman Earth Totem"] = true
L["Shaman Fire Totem"] = true
L["Shaman Totem Bar"] = true
L["Shaman Totem Thickness"] = true
L["Shaman Totems"] = true
L["Shaman Water Totem"] = true
L["Shaman"] = true
L["Show a Battle Resurrection Count and Cooldown Frame"] = true
L["Show a button for Wowhead quest links"] = true
L["Show a floating loot text"] = true
L["Show a pulsing cooldown and let it speak the spell name"] = true
L["Show a Skill Pulse when its cooldown is ending"] = true
L["Show a toast if an item in the wishlist is looted"] = true
L["Show Blizzard Friendly Nameplates but Hide Healthbar"] = true
L["Show Buffs in Arena and hide them outside (will overwrite Eltruism default settings)"] = true
L["Show Eltruism Game Menu Button"] = true
L["Show Pet Spells"] = true
L["Show Spell Name"] = true
L["Shows an Icon for the classification of the unit"] = true
L["Shows Class Icons by Blizzard on all targets"] = true
L["Shows Class Icons by Blizzard only on Player targets"] = true
L["Shows Class Icons recolored by Releaf on all targets"] = true
L["Shows Class Icons recolored by Releaf on Player targets"] = true
L["Shows Class Icons with borders recolored by Releaf on all targets"] = true
L["Shows Class Icons with borders recolored by Releaf on Player targets"] = true
L["Shows Flipped Class Icons by Blizzard on all targets"] = true
L["Shows Flipped Class Icons by Blizzard only on Player targets"] = true
L["Shows Flipped Class Icons recolored by Releaf on all targets"] = true
L["Shows Flipped Class Icons recolored by Releaf on Player targets"] = true
L["Shows Flipped Class Icons with borders recolored by Releaf on all targets"] = true
L["Shows Flipped Class Icons with borders recolored by Releaf on Player targets"] = true
L["Shows Item Level on Tooltips"] = true
L["Shows level difference when it exists for NPCs and players, hides for players if same level"] = true
L["Shows mana if the unit is a healer"] = true
L["Shows raid target marker"] = true
L["Shows Target of Spellcast, does not work for Mouseover casts"] = true
L["Shows Target of Spellcast, does not work for Mouseover casts. Includes a Target > indicator"] = true
L["Shows the current Death Knight presence"] = true
L["Shows the current presence with color"] = true
L["Shows the current stance of the player"] = true
L["Shows the current stance"] = true
L["Shows the Leader Icon as an Emoji Crown"] = true
L["Shows the Leader Icon or Assist icon if the unit is Leader or Assist"] = true
L["Shows the target's model on the target nameplate"] = true
L["Shows the Unit Level, or a skull if the level is too high"] = true
L["Shows XP bar when below max level, makes it mouseover when max level"] = true
L["Shuffle List"] = true
L["Shuffle"] = true
L["Simple Right Chat Embed"] = true
L["Size of the Icon"] = true
L["Skin Auctionator"] = true
L["Skin BagSync"] = true
L["Skin BigWigs"] = true
L["Skin Blizzard Raid Frames"] = true
L["Skin BugSack"] = true
L["Skin Cell"] = true
L["Skin Clique"] = true
L["Skin Details"] = true
L["Skin ElvUI"] = true
L["Skin Hekili"] = true
L["Skin Immersion"] = true
L["Skin Level Up, Boss Loot and Instance Entrance frames to be class colored"] = true
L["Skin MeetingHorn"] = true
L["Skin Objective Frame (when Shadow and Light and Windtools are not loaded)"] = true
L["Skin Objective Frame"] = true
L["Skin OmniCD"] = true
L["Skin PallyPower"] = true
L["Skin Profession Frame"] = true
L["Skin RareScanner"] = true
L["Skin SimulationCraft"] = true
L["Skin the Objective/Quest Frame"] = true
L["Skin the Profession/Tradeskill Frame"] = true
L["Skin WarpDeplete"] = true
L["Skin"] = true
L["Skip Install"] = true
L["Skip Plugins install message"] = true
L["Skip Plugins"] = true
L["Smart Classbar"] = true
L["Sockets and Enchants"] = true
L["Sockets/Enchants/Ilvl"] = true
L["Soft Target Interact"] = true
L["Software cursor is how the cursor was before Battle for Azeroth, Hardware cursor is faster but will cause problems with addons that attach to it"] = true
L["Software Cursor"] = true
L["Spark Texture"] = true
L["Specialization"] = true
L["Speed for Autocast, set to negative to inverse direction of rotation"] = true
L["Speed for Blizzard glow"] = true
L["Speed for Proc Glow"] = true
L["Spell Haste"] = true
L["Split files with a comma, such as: file1.mp3,file2.mp3"] = true
L["Stance Bar Thickness"] = true
L["Stance Bar"] = true
L["Stance X offset"] = true
L["Stance Y offset"] = true
L["Start Animation"] = true
L["Stats Font Size"] = true
L["Stats"] = true
L["Stealth Vignette"] = true
L["Stealth"] = true
L["Strata"] = true
L["Such as the floating XP, floating reputation changes and others"] = true
L["Such as the Zones, Mail and others"] = true
L["Supporters"] = true
L["Swap Action Paging and visibility for Bar1 and Bar4"] = true
L["Tags"] = true
L["Tapped NPC"] = true
L["Target Border"] = true
L["Target Castbar (Interrupted)"] = true
L["Target Castbar (Non Interruptible)"] = true
L["Target Castbar Border"] = true
L["Target Castbar"] = true
L["Target Class Texture"] = true
L["Target Model"] = true
L["Target of Target Border"] = true
L["Target of Target of Target Texture"] = true
L["Target of Target Texture"] = true
L["Target Only"] = true
L["Target Portrait Fix"] = true
L["Target Texture"] = true
L["Text Color"] = true
L["Text Enabled"] = true
L["Text Selected"] = true
L["Text to Speech announcement"] = true
L["Text to Speech Config"] = true
L["Text to Speech"] = true
L["Text Types"] = true
L["Text X offset"] = true
L["Text Y offset"] = true
L["The alternative layout was made for the Eltruism DPS/Tank profile, please switch to it to use it"] = true
L["The Cursor will use this type as its texture"] = true
L["The original layout was made for the Eltruism DPS/Tank profile, please switch to it to use it"] = true
L["The Quest Item Bar will appear only when ElvUI Action Bar 1 appears, following its settings"] = true
L["The text displayed when in a guild group"] = true
L["The text displayed when in a heroic dungeon"] = true
L["The text displayed when in a heroic raid"] = true
L["The text displayed when in a lfr raid"] = true
L["The text displayed when in a mythic dungeon"] = true
L["The text displayed when in a mythic plus dungeon"] = true
L["The text displayed when in a mythic raid"] = true
L["The text displayed when in a normal dungeon"] = true
L["The text displayed when in a normal raid"] = true
L["The text displayed when in a timewalking dungeon"] = true
L["The text displayed when in a timewalking raid"] = true
L["The text displayed when you die using the custom text option"] = true
L["The time will be calculated based on player speed and distance"] = true
L["Thick Outline"] = true
L["This allows you to zoom out further with the camera to increase the field of view."] = true
L["This is how much the color will gain or lose this value"] = true
L["This is the second color on the Experience Bar, the first can be found in ElvUI Databars section"] = true
L["This prompt will help you install "] = true
L["This will set all ElvUI fonts as Exo2"] = true
L["This will set all ElvUI fonts as Gotham"] = true
L["This will set all ElvUI fonts as Kimberley"] = true
L["This will set all ElvUI fonts as Roboto"] = true
L["This will set colors to black with class colors when losing health"] = true
L["This will set colors to class based with black backgrounds when losing health"] = true
L["This will set fonts to Eltruism defaults, recommended for 4K"] = true
L["This will set fonts to no outline"] = true
L["This will set fonts to use outline, recommended for 1440p and 1080p"] = true
L["This will set fonts to use thick outline"] = true
L["This will set the background to be a black color"] = true
L["This will set the background to be a grey color"] = true
L["Time at which the glow will start"] = true
L["Time it takes for the icon to fade in"] = true
L["Time it takes for the icon to fade out"] = true
L["Time to Arrive"] = true
L["Toggle a Stealth Effect"] = true
L["Toggle Class Colored glows"] = true
L["Toggle Details"] = true
L["Toggle Edit Mode"] = true
L["Toggle ElvUI Anchors"] = true
L["Toggle On and Off"] = true
L["Toggle the Click Casting Menu"] = true
L["Toggle the option on"] = true
L["Toggle the option"] = true
L["Toggle Totem to use it's own Type Colors"] = true
L["Tooltip\nGradient Name and Health"] = true
L["Totem X offset"] = true
L["Totem Y offset"] = true
L["Translators"] = true
L["Transparency in Dark Mode"] = true
L["Transparency in Light Mode"] = true
L["Transparency of the Icon"] = true
L["Transparent Chat"] = true
L["Transparent\nChat"] = true
L["Tree Group Button"] = true
L["Turn the effect on"] = true
L["Type 1"] = true
L["Type 10"] = true
L["Type 2"] = true
L["Type 3"] = true
L["Type 4"] = true
L["Type 5"] = true
L["Type 6"] = true
L["Type 7"] = true
L["Type 8"] = true
L["Type 9"] = true
L["Type the Model ID, such as 165575"] = true
L["Type the Model ID, such as 165821"] = true
L["Type the Model Path, such as spells/arcanebreath.m2"]= true
L["Type the Model Path, such as spells/corruption_impactdot_med_base.m2"] = true
L["Type"] = true
L["Unfriendly NPC"] = true
L["Unitframe Aura Border X offset"] = true
L["Unitframe Aura Border Y offset"] = true
L["Unitframe Aura"] = true
L["Unitframe Auras"] = true
L["Unitframe Colors"] = true
L["Unitframe Custom Color"] = true
L["Unitframe Fill Orientation"] = true
L["Unitframe Models"] = true
L["Unitframe Role Icons"] = true
L["Unitframe Thickness"] = true
L["Unitframe/Chat Role Icons"] = true
L["Unitframes Debuff Aura Border X offset"] = true
L["Unitframes Debuff Aura Border Y offset"] = true
L["Unitframes"] = true
L["Unsupported format or Area does not support waypoints"] = true
L["Unsupported format"] = true
L["updated to "] = true
L["Use Blizzard Icons colored by Releaf"] = true
L["Use Blizzard Icons"] = true
L["Use Class Colors for Cast"] = true
L["Use Class Colors for Cursor"] = true
L["Use Class Colors for GCD"] = true
L["Use Class Colors instead of Custom Colors"] = true
L["Use Class Colors"] = true
L["Use Custom Font"] = true
L["Use different colors per Difficulty"] = true
L["Use ElvUI Damage Font"] = true
L["Use ElvUI General Font"] = true
L["Use ElvUI Health Heights"] = true
L["Use ElvUI Nameplate Health Heights when targeted or in combat"] = true
L["Use ElvUI Unitframe Texture"] = true
L["Use formats such as:"] = true
L["Use only textures sets for specific frames and not class specific textures"] = true
L["Use the custom texture based on it's class instead of general texture for Player, Target, Target of Target and Focus"] = true
L["Use this button to restore names should you have disabled the Hide NPC Names option"] = true
L["Use this button to restore names"] = true
L["Use Type Colors"] = true
L["Uses ElvUI Unitframe Statusbar texture instead"] = true
L["Various miscellaneous features such as death animations, stealth texture, mail sound, /roll sounds and more"] = true
L["Version 1"] = true
L["Version 2"] = true
L["Version 3"] = true
L["Vertical Offset"] = true
L["Vertical"] = true
L["Very High (but Optional)"] = true
L["Very High"] = true
L["Vignette Alpha"] = true
L["Vignette"] = true
L["Warlock"] = true
L["WARNING"] = true
L["WarpDeplete is not installed or enabled"] = true
L["WarpDeplete is not loaded"] = true
L["WarpDeplete profile has been set."] = true
L["WarpDeplete profile requires an import per class in order to have the correct texture"] = true
L["Warrior"] = true
L["Waypoints"] = true
L["WeakAuras Action Bar"] = true
L["Welcome"] = true
L["When target is off screen, position its nameplate radially around sides and bottom."] = true
L["Wide nameplate debuffs and buffs"] = true
L["Will link your key and covenant in guild or party chat"] = true
L["Will link your key in guild or party chat"] = true
L["Will not delete the item, will simply type DELETE instead you needing to type it"] = true
L["WindTools"] = true
L["World Map Scale"] = true
L["XX YY, XX.XX YY.YY, XX,XX YY,YY and XXX YYY"] = true
L["You can customize the textures and colors in Eltruism > Unitframes"] = true
L["You can replace it with one of the following:"] = true
L["You can right click the bottom right arrow to toggle the Details! Window"] = true
L["You can set your Weakauras to anchor to custom locations making it easier to move them"] = true
L["You can support the group with your class, if you select DPS/Tank then its recommended to click Alternative Frames after clicking DPS/Tank"] = true
L["You can switch to Dark Chat by clicking the buttons below"] = true
L["You can switch to Light Mode or Gradient Mode by clicking the buttons below"] = true
L["You can type /way or /waypoint"] = true
L["You have another Nameplate Addon installed and loaded, and many nameplate features will not work with it"] = true
L["You have completed the installation process"] = true
L["You have none of these addons installed or enabled"] = true
L["You need to be using an Eltruism profile in order to use this function"] = true
L["You will also automatically accept Daily and Weekly Quests"] = true
L["You will automatically accept and turn in quests that do not require gold, are not weekly and are not daily"] = true
L["You will only accept and turn in quests if you hold CTRL/SHIFT/ALT while talking to the NPC"] = true
L["Your current settings will be lost, please back them up"] = true
L["Your custom font has been set."] = true
L["Your ElvUI version is higher than expected for Eltruism, please update Eltruism or you might run into issues.\n|cffFF0000(You are likely having errors right now!)|r"] = true
L["Your ElvUI version is out of date, please update to avoid issues!"] = true
L["Your World of Warcraft version is higher than expected for Eltruism, please update Eltruism or you might run into issues.\n|cffFF0000(You are likely having errors right now!)|r"] = true
L["Your World of Warcraft version is not expected to be compatible with Eltruism, please update Eltruism or you might run into issues.\n|cffFF0000(You are likely having errors right now!)|r"] = true
L["Your World of Warcraft version is older than Eltruism, you might run into issues!"] = true
L["Zone Text"] = true
L["|cffff0000Private Servers are unsupported!"] = true
--lines after reordering
L["Displays % - HP and a status symbol. Can be customized in Eltruism > Media"] = true
L["Frequently Asked Questions"] = true
L["How do I disable the chat hide?"] = true
L["If you are coming from a version before 2.3.0 then check ElvUI > Shadow and Light > Chat > Set Hide to None\nOtherwise, check Eltruism > Chat"] = true
L["After the Chat fades I still see some icons"] = true
L["This is a Blizzard bug that was found a long time ago"] = true
L["My chat hides when my mouse leaves it"] = true
L["Disable Mouse over in Eltruism > Chat"] = true
L["My chat hides after a few seconds"] = true
L["Disable Inactivity/Fader in Eltruism > Chat"] = true
L["My action bars and unitframes keep disappearing!"] = true
L["ElvUI > ActionBars > Player Bars > on each Bar disable Inherit Global Fade\nElvUI > Unitframes > Type of Unit > Unit > Fader, disable the fader"] = true
L["My Details! window disappears after combat!"] = true
L["If you have AddOnSkins then go to ElvUI > AddOnSkins > Embed Settings > Turn off Out of Combat (Hide)\nIf details is showing up on top of the trade chat, try going to AddOnSkins > Embed Settings and making sure that its hiding the Trade/Loot chat, you can also right click the > arrow in order to toggle the details embed.\nIf you do not have AddOnSkins then go to Eltruism > Skins > Addons > Details > Embed > Hide out of Combat, you can also change the amount of time it takes for it to hide.\nIn either AddOnSkins or Eltruism embeds you can also Right Click the Chat Toggle (the Arrow [ > ] on the bottom right) to Toggle the Visibility\nA shortcut to disabling the combat hide is /eltruism detailshide"] = true
L["Music keeps playing when AFK"] = true
L["Disable the AFK music in Eltruism > AFK in order to stop the music from playing"] = true
L["How do I make bar 1 my action paging bar instead of bar 4?"] = true
L["You can swap them out in Eltruism > Media, or by using the command /eltruism paging, make sure to reload"] = true
L["How can I get Blizzard's floating Mana/Energy/Rage/Other combat text back?"] = true
L["Go to ElvUI > Eltruism > Misc > Blizzard Combat Text and uncheck Disable Combat Text and Check Enable Resource Gains, then reload"] = true
L["My Loot Rolls are missing!"] = true
L["You have enabled Hide Alert Frame, disable that setting to restore the Alert Frame/Loot Rolls"] = true
L["Where is my floating combat text?"] = true
L["It's possible you installed NameplateSCT/FCT and removed it so the floating combat text was not enabled back\nYou can go into Eltruism > CVars > Other CVars > Restore All Combat Text to restore them"] = true
L["My nameplates flash once an enemy is below 20% Health!"] = true
L["That is due to the EltreumExecute filter, you can disable it in:\nElvUI > Nameplates > Style Filter > (from the dropdown) EltreumExecute > Triggers > Uncheck Enable"] = true
L["Header Font Size"] = true
L["Hide Dash"] = true
L["Hide Completion Checkmark"] = true
L["My Unitframes and/or ActionBars keep reverting positions!"] = true
L["If your actionbars or other frames are moving or resetting after a reload,\ncheck ElvUI > Eltruism > Borders for the Auto Adjust option.\n\nThis option is enabled when you enable Borders, it will not enable otherwise.\n\nAuto Adjust moves frames to a set position due to how borders need\ndifferent settings per layout and need to be changed so that borders don't overlap.\nDisable this option to stop the automatic changes.\n\nYou can also use the /eltruism autoadjust command to toggle it off"] = true
L["How do I remove the lines/skin on all the frames?"] = true
L["If you want to disable the ElvUI skin that adds textures to ElvUI you can go into\n\nEltruism > Skins > Addons > ElvUI\n\nWhere you can disable it or change its color, transparency and texture.\nYou can also type /eltruism elvuiskin to disable it "] = true
L["Disable the worldPreloadNonCritical CVar, doing so can improve loading times."] = true
L["If you find the %s option has issues, alert me via Discord or GitHub issue."] = true
L["Choose the option you would like to enable"] = true
L["Model Inside Health"] = true
L["Model will be set inside health instead of over whole frame"] = true
L["Circle Minimap"] = true
L["Databars Thickness"] = true
L["Alternative Power Thickness"] = true
L["Adjust Position of Item Level Text"] = true
L["Focus Power Border"] = true
L["The text displayed when in a delve"] = true
L["The text displayed when in a quest instance"] = true
L["Thin Aura Bars"] = true
L["Exported Gradient Data:"] = true
L["Import Gradient Data"] = true
L["Reinstall Thin Layout"] = true
L["Reset layout to Eltruism Thin"] = true
L["Reverse Focus"] = true
L["Reverse Focus Gradient Health"] = true
L["Hide Quests during Mythic Plus"] = true
L["Add Character Race Icons"] = true
L["Enable Character Race Icons"] = true
L["Disable Combat Conditions"] = true
L["Disables the in combat and out of combat conditions, keeping only the target/non-target function"] = true
