-- English localization
local L = ElvUI[1].Libs.ACL:NewLocale("ElvUI", "ruRU", true, true)
if not L then return end
-- Core
L["4K resolution detected, setting fonts to default mode."] = true
L["1440p resolution detected, setting fonts to outline mode."] = true
L["1080p resolution detected, setting fonts to outline mode."] = true
L["Fonts were set to Outline due to your resolution."] = true
L["EltruismConsumables"] = true
--Install
L["General CVars have been set."] = true
L["NamePlate CVars have been set."] = true
L["AddOnSkins profile has been set."] = true
L["Immersion profile has been set."] = true
L["BigWigs profile has been set."] = true
L["DBM profile has been set."] = true
L["Details profile has been set."] = true
L["Dynamic Cam profile has been set."] = true
L["GladiusEx profile has been set."] = true
L["Exorsus Raid Tools profile has been set."] = true
L["ProjectAzilroka profile has been set."] = true
L["Questie profile has been set."] = true
L["NameplateSCT profile has been set."] = true
L["Floating Combat Text profile has been set."] = true
L["Gladius profile has been set."] = true
L["Gladdy profile has been set."] = true
L["Area does not support waypoints"] = true
L["Unsupported format"] = true
L["Unsupported format or Area does not support waypoints"] = true
L["WARNING"] = true
L["Make sure to install "] = true
L["Shadow and Light"] = true
L[" and "] = true
L["WindTools"] = true
L[" before starting this installation process"] = true
L["Curse doesn't allow selective dependencies for addons when it comes to World of Warcraft versions"] = true
L[" are required for Retail but not Classic that's why you are seeing this screen"] = true
L["Download them before continuing"] = true
L[" before starting this installation process"] = true
L["AddOnSkins"] = true
L["ProjectAzilroka"] = true
L["This prompt will help you install "] = true
L[" and import its settings"] = true
L["Please read the instructions to avoid issues"] = true
L["Skip Install"] = true
L["Layouts"] = true
L["Please select the role for your character, which will create a new profile"] = true
L["This process can take a few seconds"] = true
L["You can support the group with your class, if you select DPS/Tank then its recommended to click Alt Frames after clicking DPS/Tank"] = true
L["Importance: "] = true
L["Very High"] = true
L["Fonts"] = true
L["Eltruism uses Kimberley as the default font"] = true
L["You can replace it with one of the following:"] = true
L["Optional"] = true
L["Import GladiusEx profile, remember to disable ElvUI Arena Frames"] = true
L["You will need to change the profile in /gex profile options"] = true
L["Your current settings will be lost, please back them up"] = true
L["Import "] = true
L["WARNING"] = true
L["GladiusEx adds many features not available on Elvui Arena frames"] = true
L["Such as diminishing cooldowns, enemy cast tracker, cooldown tracker"] = true
L["Import Details! profile with dual panels"] = true
L["You can right click the bottom right arrow to toggle the Details! Window"] = true
L["Remember to swap the second window to Healing Done or Tiny Threat"] = true
L["Make sure to run Details! install before importing"] = true
L["Details is an advanced combat parser"] = true
L["It uses less memory and is more efficient than alternatives"] = true
L["And has many plugins to choose from"] = true
L["Boss Mods"] = true
L["Import DBM or Bigwigs profiles"] = true
L["These profiles are setup with DBM English Calanon and Bigwigs Voice"] = true
L["Your current settings will be lost with overwrite, please back them up"] = true
L["DBM is not installed or enabled so BigWigs will be used"] = true
L["BigWigs uses BigWigs voice in its profile"] = true
L["BigWigs is not installed or enabled so DBM will be used"] = true
L["DBM uses DBM English by Calanon as a voice pack"] = true
L["Both DBM and BigWigs are not installed or enabled"] = true
L["No boss mods found"] = true
L["Boss mods are highly recommended for modern encounters"] = true
L["Exorsus Raid Tools"] = true
L["Import EXRT profile with raid cooldowns and other settings"] = true
L["You will need to swap to this profile in ExRT"] = true
L["Overwrite"] = true
L["Copy"] = true
L["ExRT is a suite of tools for raiding"] = true
L["Includes tracking raid cooldowns and creating notes"] = true
L["Alongside attendance and other features"] = true
L["Combat Text"] = true
L["Import profiles for NameplateSCT or ElvUI Floating Combat Text"] = true
L["FCT profile will be used"] = true
L["NameplateSCT profile will be used"] = true
L["Combat text addons enhance the default Blizzard Combat Text"] = true
L["NameplateSCT and FCT make the combat text float from the nameplate/frame"] = true
L["And add effects to them with minimal memory usage"] = true
L["Import "] = true
L["settings configured for "] = true
L[" is not installed or enabled"] = true
L["NameplateSCT and FCT are not installed or enabled"] = true
L["Immersion is an addon that changes the quest dialog with npcs"] = true
L["It transforms them into a talking head with dialog options on the side"] = true
L["Including the ability to press number keys to select an option"] = true
L["Import Dynamic Cam profile"] = true
L["You might need to swap profiles in DynamicCam settings"] = true
L["DynamicCam is addon that modifies the behavior of the camera"] = true
L["The profile uses some effects while questing"] = true
L["But in instances the effects are disabled"] = true
L["Welcome"] = true
L["Join the Discord if you have any questions or issues (English Support)"] = true
L["Installation Complete"] = true
L["You have completed the installation process, please click Finished to reload the UI"] = true
L["Finished"] = true
L["Import Questie profile"] = true
L["You will need to reload and wait for questie to rebuild the database"] = true
L["Questie is not installed or enabled"] = true
L["Questie is an addon that modifies the objective tracker"] = true
L["As such Questie adds a lot of features to it not available by default"] = true
L["Including TomTom support"] = true
L["Arenas"] = true
L["Import profiles for Gladius or Gladdy"] = true
L["You might need to swap profiles to Eltreum in their settings"] = true
L["Gladius is not installed or enabled"] = true
L["Gladdy profile will be used"] = true
L["Gladdy is not installed or enabled"] = true
L["Gladius profile will be used"] = true
L["Gladdy and Gladius are not installed or enabled"] = true
L["Arena unitframes enhance the default Blizzard unitframes"] = true
L["Giving them additional features like DR tracking, trinket tracking, buffs and cooldowns"] = true
L["Being used by players for many years since 2008"] = true
L["NamePlates have been setup."] = true
L["NamePlate Style Filters have been setup."] = true
L["Abbreviates the unit name once it goes over 16 characters, made by Azilroka"] = true
L["Shows Class Icons by Blizzard on all targets"] = true
L["Shows Class Icons by Blizzard only on Player targets"] = true
L["updated to "] = true
L["Layout has been set."] = true
L["The alternative layout was made for the Eltruism DPS/Tank profile, please switch to it to use it"] = true
L["The original layout was made for the Eltruism DPS/Tank profile, please switch to it to use it"] = true
L["You need to be using an Eltruism profile in order to use this function"] = true
L["Debuff filters were setup"] = true
L["Buff filters were setup"] = true
L["ElvUI Chat has been Set"] = true
-- Datatext
L["Eltruism Ammo"] = true
-- Fonts
L["Your custom font has been set."] = true
L["Kimberley Font has been set."] = true
L["Exo2 Font has been set."] = true
L["GothamNarrow Black Font has been set."] = true
L["Roboto Font has been set."] = true
--LootText
L["INVENTORY IS FULL"] = true
L["Inventory is full."] = true --is a blizzard argument for the error, if different from blizzard it will not work
L["Silver"] = true -- the coin type exactly as it is in game, or the function will not work for the location
L["Gold"] = true -- the coin type exactly as it is in game, or the function will not work for the location
L["Copper"] = true -- the coin type exactly as it is in game, or the function will not work for the location
L["Soul Ash"] = true -- the currency exactly as it is in game, or the function will not work for the location
--Options
L["Installer"] = true
L["Reinstall the plugin to reset settings"] = true
L["Install"] = true
L["Reset nameplates to Eltruism settings"] = true
L["A.F.K"] = true -- away from keyboard, can be longer in other languages
L["Play music while you are AFK"] = true
L["Enable"] = true
L["Cursor"] = true
L["Change the size of the World of Warcraft Cursor"] = true
L["Select a size"] = true
L["Choose this size"] = true
L["Autodetect"] = true
L["Add a gcd and cast ring to the cursor"] = true
L["Enable cursor rings for Casts, GCD and Combat"] = true
L["Add a rings around the mouse cursor for GCD, casts and combat"] = true
L["Choose a type of cursor by clicking it"] = true
L["Currently selected cursor: "] = true
L["Type 1"] = true
L["Type 2"] = true
L["Type 3"] = true
L["Type 4"] = true
L["Type 5"] = true
L["Type 6"] = true
L["Type 7"] = true
L["Type 8"] = true
L["Type 9"] = true
L["Type 10"] = true
L["The Cursor will use this type as its texture"] = true
L["Cursor Colors "] = true
L["Requires a Reload"] = true
L["Class Colored Casts"] = true
L["Use Class Colors for Cast"] = true
L["Custom Color Cast"] = true
L["Class Colored GCD"] = true
L["Use Class Colors for GCD"] = true
L["Custom Color GCD"] = true
L["Class Colored Combat"] = true
L["Use Class Colors for Cursor"] = true
L["Custom Color Combat"] = true
L["Cast Radius (Default: 25)"] = true
L["Set the radius of the cast cursor"] = true
L["Cast Thickness (Default: 5)"] = true
L["Set the radius of the cast cursor"] = true
L["GCD Radius (Default: 20)"] = true
L["Set the radius of the gcd cursor"] = true
L["GCD Thickness (Default: 5)"] = true
L["Set the thickness of the gcd cursor"] = true
L["Combat Cursor Radius (Default: 15)"] = true
L["Set the radius of the combat cursor"] = true
L["Combat Cursor Thickness (Default: 5)"] = true
L["Set the thickness of the combat cursor"] = true
L["Aura Filters"] = true
L["For Shadowlands, import aura filters by copying the code below and going into Profiles > Import Profile."] = true
L["Setup Aura Filters to show all"] = true
L["All Player Buffs"] = true
L["Set filters to show more buffs on Player"] = true
L["All Player Debuffs"] = true
L["Set filters to show more debuffs on Player"] = true
L["All Target Debuffs"] = true
L["Set filters to show more debuffs on Target"] = true
L["All Target Buffs"] = true
L["Set filters to show more buffs on Target"] = true
L["All Focus Buffs"] = true
L["Set filters to show more buffs on Focus"] = true
L["All Focus Debuffs"] = true
L["Set filters to show more debuffs on Focus"] = true
L["All Boss Buffs"] = true
L["Set filters to show more buffs on Boss"] = true
L["All Boss Debuffs"] = true
L["Set filters to show more debuffs on Bosss"] = true
L["All Nameplate Buffs"] = true
L["Set filters to show more buffs on Nameplates"] = true
L["All Nameplate Debuffs"] = true
L["Set filters to show more debuffs on Nameplates"] = true
L["Setup Aura Filters to be Eltruism/ElvUI defaults"] = true
L["Eltruism Player Buffs"] = true
L["Set filters to be Eltruism/ElvUI defaults on Player"] = true
L["Eltruism Player Debuffs"] = true
L["Eltruism Target Debuffs"] = true
L["Set filters to be Eltruism/ElvUI defaults on Target"] = true
L["Eltruism Target Buffs"] = true
L["Eltruism Focus Buffs"] = true
L["Set filters to be Eltruism/ElvUI defaults on Focus"] = true
L["Eltruism Focus Debuffs"] = true
L["Eltruism Boss Buffs"] = true
L["Set filters to be Eltruism/ElvUI defaults on Boss"] = true
L["Eltruism Boss Debuffs"] = true
L["Eltruism Nameplate Buffs"] = true
L["Set filters to be Eltruism/ElvUI defaults on Nameplates"] = true
L["Eltruism Nameplate Debuffs"] = true
L["Addons"] = true
L["ElvUI Plugins"] = true
L["Reset to Eltruism defaults."] = true
L["BossMods Profiles"] = true
L["Addon Profiles"] = true
L["Combat Music"] = true
L["Play music during combat"] = true
L["Enable music during combat"] = true
L["Disable in Instances"] = true
L["Disable music during combat in instances"] = true
L["Path to file"] = true
L["Example: "] = true
L["CVars"] = true -- i dont know if this gets localized
L["Setup CVars"] = true
L["General CVars"] = true
L["It will set these CVars:"] = true
L["Party/Raid"] = true
L["Play a sound when someone dies in Party or Raid"] = true
L["Select a Sound"] = true
L["Alternative unitframe layouts"] = true
L["DPS/Tank layouts were created with pure dps classes in mind, if you play a class with more raid cooldowns like a Shaman, Druid or Paladin you might want to use the alternative layout in order to make it easier for you to use your cooldowns on the members of your group"] = true
L["Alternative Layout"] = true
L["Original Layout"] = true
L["Media"] = true
L["Setup Media"] = true
L["Reset all Media"] = true
L["Reset Fonts, Textures, Skins to Eltreum UI defaults."] = true
L["Set the fonts used in Eltruism. Kimberley is the default font"] = true
L["This will set all ElvUI fonts as Kimberley"] = true
L["This will set all ElvUI fonts as Exo2"] = true
L["This will set all ElvUI fonts as Gotham"] = true
L["This will set all ElvUI fonts as Roboto"] = true
L["Or choose a custom font"] = true
L["Choose a different font from the preselected ones"] = true
L["Set the Font Outlines everywhere. Use Default to return to Eltruism default settings"] = true
L["Defaults"] = true
L["This will set fonts to Eltruism defaults, recommended for 4K"] = true
L["None"] = true  --as in no font outline
L["This will set fonts to no outline"] = true
L["Outline"] = true
L["This will set fonts to use outline, recommended for 1440p and 1080p"] = true
L["Thick Outline"] = true
L["This will set fonts to use thick outline"] = true
L["Change the look of frames to Dark or Light mode"] = true
L["Dark Mode"] = true
L["This will set colors to black with class colors when losing health"] = true
L["Light Mode"] = true
L["This will set colors to class based with black backgrounds when losing health"] = true
L["Dynamic Datatext that changes according to class to show Ammo or Soul Shards when playing Hunter, Warrior, Rogue or Warlock"] = true
L["Enable the Dynamic Datatext"] = true
L["Expand the Talents to show the entire tree"] = true
L["Expanded Talents"] = true
L["Expand Talents to cover the full tree"] = true
L["Nameplates"] = true
L["Class Colored Nameplate Options"] = true
L["Hover"] = true
L["Change the color of the hover to be class colored"] = true
L["Border"] = true
L["Change the color of the border glow to be class bordered in nameplates"] = true
L["Target Texture"] = true
L["Change the texture of the nameplate to be a class gradient"] = true
L["Control how Nameplates behave"] = true
L["Show Friendly Nameplates but Hide Healthbar"] = true
L["Hide Friendly Nameplates inside Instances"] = true
L["Hide Friendly Nameplates everywhere"] = true
L["Wide nameplate debuffs and buffs"] = true
L["Make Buffs and Debuffs Wide on Nameplates"] = true
L["Toogle On and Off"] = true
L["Enemy Nameplate Level"] = true
L["Hide level on enemy nameplates when you are max level"] = true
L["Nameplate Power Bar"] = true
L["Enable Nameplate Power Bar"] = true
L["Enable an extra Power Bar on Nameplates for missing powers"] = true
L["Enable Autoadjusting Buffs/Debuffs"] = true
L["Enable autoadjusting the position of Buffs/Debuffs"] = true
L["Enable Autoadjusting the Vertical Position of the Power Bar"] = true
L["Power Bar will move automatically based on class/spec/druid form"] = true
L["Select the Y Offset for the Power Bar (Default 16)"] = true
L["Set Y Offset"] = true
L["Select the Horizontal Size of the Power Bar (Default 132)"] = true
L["Set Horizontal Size"] = true
L["Select the Vertical Size of the Power Bar (Default 6)"] = true
L["Set Vertical Size"] = true
L["Choose the Power Bar Texture"] = true
L["Select a Texture"] = true
L["Select the power types to be displayed:"] = true
L["Mana"] = true
L["Rage"] = true
L["Energy"] = true
L["Loot"] = true
L["Show a floating loot text"] = true
L["Choose which types of text:"] = true
L["Honor"] = true
L["Currency"] = true
L["Pets"] = true
L["Change the scale of LootText"] = true
L["Set the size of LootText"] = true
L["Reset Scale"] = true
L["Return LootText to its default scale"] = true
L["Change the strata of the Loot Text"] = true
L["Set the level that LootText will be drawn to this"] = true
L["Background"] = true
L["Low"] = true
L["Medium"] = true
L["High"] = true
L["Dialog"] = true
L["Change the Horizontal Position of LootText (Default = 0)"] = true
L["Set X offset"] = true
L["Change the Vertical Position of LootText (Default = 200)"] = true
L["Set Y offset"] = true
L["Change the font of LootText to be that the ElvUI Default Font found in General"] = true
L["Use ElvUI General Font"] = true
L["Change the font of LootText"] = true
L["Chat"] = true
L["Chat Options"] = true
L["Enable ElvUI Chat modifications"] = true
L["Add fade over time, and mouse over to left and right chat panels"] = true
L["Add mouse over to the left chat panel"] = true
L["Left Chat Mouse Over"] = true
L["Toggle the option"] = true
L["Add a fade to the left chat panel, controlled by ElvUI Chat > Text Fade > Inactivity Timer"] = true
L["Left Inactivity Fader"] = true
L["Add mouse over to the left chat panel"] = true
L["Right Chat Mouse Over"] = true
L["Add a fade to the right chat panel, controlled by ElvUI Chat > Text Fade > Inactivity Timer"] = true
L["Right Inactivity Fader"] = true
L["Combat Hide"] = true
L["Hide Left Chat in Combat"] = true
L["Hide Right Chat in Combat"] = true
L["Invert left mouse click so that chat starts faded and mouse click will make it stop fading"] = true
L["Invert Mouse Click"] = true
L["Toggle the option on"] = true
L["Stealth Vignette"] = true
L["Toggle a Stealth Effect"] = true
L["Add a vignette effect while in stealth"] = true
L["Turn the effect on"] = true
L["You can set your Weakauras to anchor to custom locations making it easier to move them"] = true
L["In order to use this feature, simply go to your Weakaura, and go to its Group options, scroll down to Position Settings and set the Anchored To Select Frame, then type either |cff82B4ffEltruismWA|r or |cff82B4ffEltruismConsumables|r to anchor the weakaura to the preset location"] = true
L["Setting "] = true
L[" or "] = true
L[" as the anchor will move them to the locations, keep in mind you might need to change the X and Y offset of the weakaura to zero"] = true
L["My WeakAuras are available here, but are not focused on one class. Consider them more like upcoming features."] = true
L["All weakauras"] = true
L["Nameplate Power Bar"] = true
L["Boss nameplate at base"] = true
L["Executes next to nameplates"] = true
L["Join the Discord if you have any questions or issues"] = true
L["Keep in mind the discord is in English"] = true
L["Changelog"] = true
L["Select a version:"] = true
L["Choose a version to see its changelog"] = true
L["Credits"] = true
L["Author"] = true
L["Credits and Thank yous"] = true
L["License"] = true
L["Support"] = true
L["New commits, basically a preview of fixes or upcoming features"] = true
L["Report issues and problems here:"] = true
L["Addon on Tukui:"] = true
L["Addon on CurseForge:"] = true
L["Custom Glow"] = true
L["Replace Blizzards Default Glow with a Custom Glow"] = true
L["Select a Type"] = true
L["Autocast"] = true
L["Pixel"] = true
L["Blizzard"] = true  -- the company not the weather effect
L["Adds a Blizzard style glow using class color"] = true
L["Glow Colors"] = true
L["Use Class Colors"] = true
L["Toggle Class Colored glows"] = true
L["Custom Color"] = true
L["Pixel Glow"] = true
L["Pixel Border"] = true
L["Enable a border for the Pixel Glow"] = true
L["Number of Pixels (Default is 9)"] = true
L["Set the number of pixels in pixel glow"] = true
L["Pixel Frequency (Default is 1)"] = true
L["Set the frequency pixel glow"] = true
L["Pixel Length (Default is 3)"] = true
L["Set the length of pixels"] = true
L["Pixel Thickness (Default is 5)"] = true
L["Set the thickness of pixels"] = true
L["Pixel Horizontal Offset (Default is 5)"] = true
L["Set the horizontal offset of pixels"] = true
L["Pixel Vertical Offset (Default is 5)"] = true
L["Set the vertical offset of pixels"] = true
L["Autocast Glow"] = true
L["Autocast Particle Groups (Default is 8)"] = true
L["Set the number of groups for autocast, for each group you get 4 particles"] = true
L["Autocast Frequency (Default is 0.8)"] = true
L["Speed for Autocast, set to negative to inverse direction of rotation"] = true
L["Autocast Scale (Default is 2)"] = true
L["Change the size of Autocast"] = true
L["Autocast Horizontal Offset (Default is 5)"] = true
L["Set the horizontal offset of autocast"] = true
L["Autocast Vertical Offset (Default is 5)"] = true
L["Set the vertical offset of autocast"] = true
L["Blizzard Glow"] = true
L["Blizzard Frequency (Default is 0.5)"] = true
L["Speed for Blizzard glow"] = true
L["Quests"] = true
L["Collapse Quests during Encounters/Boss Fights"] = true
L["Collapse Quests when the boss fight starts"] = true
L["Maps"] = true
L["Add a time to arrive below the waypoint"] = true
L["The time will be calculated based on player speed and distance"] = true
L["If the player is not moving then *** will show up since time cannot be calculated"] = true
L["If you move away from the waypoint the time will just increase"] = true
L["Add an ETA to waypoints"] = true  --translation note: eta means estimated time to arrive
L["Enable the /way and /waypoint commands"] = true  -- do not translate /way and /waypoint since the commands are not translated
L["You can type /way or /waypoint"] = true  -- do not translate /way and /waypoint since the commands are not translated
L["Use formats such as:"] = true
L["XX YY, XX.XX YY.YY, XX,XX YY,YY and XXX YYY"] = true
L["Other Formats can end up causing errors"] = true
L["Enable the /way and /waypoint commands"] = true -- do not translate /way and /waypoint since the commands are not translated
L["Astral power"] = true
L["Runic power"] = true
L["Insanity"] = true
L["Maelstrom"] = true
L["Fury"] = true
L["Focus"] = true
L["Select a type of music"] = true
L["Racial Music"] = true
L["Class Music"] = true
L["Skin Level Up, Boss Loot and Instance Entrance frames to be class colored"] = true
L["Enable the Skins"] = true
L["Expand Hunter Stables to show all pets and improve search"] = true
L["Enable the Expanded Stable"] = true
L["Expand Transmog Window to better show your character"] = true
L["Enable the Wider Transmog Window"] = true
L["Auto open the Rogue Order Hall, to avoid opening hold CTRL or SHIFT or ALT while talking to the NPC"] = true
L["Enable the Rogue Order Hall Auto Open"] = true
L["Enable Floating Reputation Changes"] = true
L["Enable the Floating Rep Text"] = true
L["Buffs have been updated for Open World"] = true
L["Buffs have been updated for Arenas"] = true
