local LSM = LibStub("LibSharedMedia-3.0")

if LSM == nil then return end

-- Fonts
LSM:Register('font', "Kimberley", [[Interface\AddOns\ElvUI_EltreumUI\Media\Fonts\Kimberley.otf]])
LSM:Register("font", "OptimusPrinceps", [[Interface\Addons\ElvUI_EltreumUI\Media\Fonts\OptimusPrinceps.ttf]])
LSM:Register("font", "GothamNarrow Black", [[Interface\Addons\ElvUI_EltreumUI\Media\Fonts\GothamNarrow Black.ttf]])
LSM:Register("font", "GothamXNarrow Black", [[Interface\Addons\ElvUI_EltreumUI\Media\Fonts\GothamXNarrow Black.ttf]])
LSM:Register("font", "GothamXNarrow Ultra", [[Interface\Addons\ElvUI_EltreumUI\Media\Fonts\GothamXNarrow Ultra.ttf]])
LSM:Register("font", "Exo2 Extra Bold", [[Interface\Addons\ElvUI_EltreumUI\Media\Fonts\Exo2-ExtraBold.otf]])
LSM:Register("font", "Candara", [[Interface\Addons\ElvUI_EltreumUI\Media\Fonts\Candara.ttf]])
LSM:Register("font", "JosefinSans-Regular", [[Interface\Addons\ElvUI_EltreumUI\Media\Fonts\JosefinSans-Regular.ttf]])
LSM:Register("font", "JosefinSans-Medium", [[Interface\Addons\ElvUI_EltreumUI\Media\Fonts\JosefinSans-Medium.ttf]])
LSM:Register("font", "JosefinSans-SemiBold", [[Interface\Addons\ElvUI_EltreumUI\Media\Fonts\JosefinSans-SemiBold.ttf]])
LSM:Register("font", "JosefinSans-Bold", [[Interface\Addons\ElvUI_EltreumUI\Media\Fonts\JosefinSans-Bold.ttf]])
LSM:Register("font", "Pricedown", [[Interface\Addons\ElvUI_EltreumUI\Media\Fonts\pricedown.ttf]])

-- Sound
LSM:Register("sound", "You_Died", [[Interface\Addons\ElvUI_EltreumUI\Media\Sound\You_Died.ogg]])
LSM:Register("sound", "Todd Horward - It just works", [[Interface\Addons\ElvUI_EltreumUI\Media\Sound\Itjustworks.mp3]])
LSM:Register("sound", "Todd Horward - Again it just works", [[Interface\Addons\ElvUI_EltreumUI\Media\Sound\Todd-Again-it-just-works.mp3]])
LSM:Register("sound", "Will Smith - Ah ahaha", [[Interface\Addons\ElvUI_EltreumUI\Media\Sound\WillSmith-Ahaha.mp3]])
LSM:Register("sound", "Will Smith - Rewind", [[Interface\Addons\ElvUI_EltreumUI\Media\Sound\WillSmith-Rewind-Long.mp3]])
LSM:Register("sound", "Will Smith - That's Hot", [[Interface\Addons\ElvUI_EltreumUI\Media\Sound\WillSmith-Thats-hot.mp3]])
LSM:Register("sound", "bruh", [[Interface\Addons\ElvUI_EltreumUI\Media\Sound\bruh.mp3]])
LSM:Register("sound", "Oof", [[Interface\Addons\ElvUI_EltreumUI\Media\Sound\oof.mp3]])
LSM:Register("sound", "This is no time for caution", [[Interface\Addons\ElvUI_EltreumUI\Media\Sound\caution.mp3]])
LSM:Register("sound", "Its not Possible", [[Interface\Addons\ElvUI_EltreumUI\Media\Sound\necessary.mp3]])
LSM:Register("sound", "All of this just works", [[Interface\Addons\ElvUI_EltreumUI\Media\Sound\error.mp3]])
LSM:Register("sound", "We are too late", [[Interface\Addons\ElvUI_EltreumUI\Media\Sound\Weretoolate.mp3]])
LSM:Register("sound", "Shame", [[Interface\Addons\ElvUI_EltreumUI\Media\Sound\shame.mp3]])
LSM:Register("sound", "Queen Azshara - What a shame", [[Interface\Addons\ElvUI_EltreumUI\Media\Sound\QueenAzsharaWhatAShame.ogg]])
LSM:Register("sound", "Queen Azshara - How disappointing", [[Interface\Addons\ElvUI_EltreumUI\Media\Sound\QueenAzsharaDissapointing.ogg]])
LSM:Register("sound", "! - Metal Gear Solid", [[Interface\Addons\ElvUI_EltreumUI\Media\Sound\metalgear.ogg]])
LSM:Register("sound", "Wow", [[Interface\Addons\ElvUI_EltreumUI\Media\Sound\wow.mp3]])
LSM:Register("sound", "GTA - Wasted", [[Interface\Addons\ElvUI_EltreumUI\Media\Sound\wasted.mp3]])
LSM:Register("sound", "Mario Game Over", [[Interface\Addons\ElvUI_EltreumUI\Media\Sound\mariodeath.mp3]])

-- Statusbar
LSM:Register("statusbar", "Eltreum-bottom", [[Interface\Addons\ElvUI_EltreumUI\Media\Statusbar\Eltreum-bottom.tga]])
LSM:Register("statusbar", "Eltreum-left", [[Interface\Addons\ElvUI_EltreumUI\Media\Statusbar\Eltreum-left.tga]])
LSM:Register("statusbar", "Eltreum-right", [[Interface\Addons\ElvUI_EltreumUI\Media\Statusbar\Eltreum-right.tga]])
LSM:Register("statusbar", "Eltreum-top", [[Interface\Addons\ElvUI_EltreumUI\Media\Statusbar\Eltreum-top.tga]])
LSM:Register("statusbar", "Eltreum1pixel", [[Interface\Addons\ElvUI_EltreumUI\Media\Statusbar\Eltreum1pixel.tga]])
LSM:Register("statusbar", "Eltreum2pixel", [[Interface\Addons\ElvUI_EltreumUI\Media\Statusbar\Eltreum2pixel.tga]])
LSM:Register("statusbar", "Eltreum3pixel", [[Interface\Addons\ElvUI_EltreumUI\Media\Statusbar\Eltreum3pixel.tga]])
LSM:Register("statusbar", "Eltreum4pixel", [[Interface\Addons\ElvUI_EltreumUI\Media\Statusbar\Eltreum4pixel.tga]])
LSM:Register("statusbar", "Eltreum5pixel", [[Interface\Addons\ElvUI_EltreumUI\Media\Statusbar\Eltreum5pixel.tga]])
LSM:Register("statusbar", "Eltreum6pixel", [[Interface\Addons\ElvUI_EltreumUI\Media\Statusbar\Eltreum6pixel.tga]])
LSM:Register("statusbar", "Eltreum7pixel", [[Interface\Addons\ElvUI_EltreumUI\Media\Statusbar\Eltreum7pixel.tga]])
LSM:Register("statusbar", "Eltreum8pixel", [[Interface\Addons\ElvUI_EltreumUI\Media\Statusbar\Eltreum8pixel.tga]])
LSM:Register("statusbar", "Eltreum9pixel", [[Interface\Addons\ElvUI_EltreumUI\Media\Statusbar\Eltreum9pixel.tga]])
LSM:Register("statusbar", "Eltreum10pixel", [[Interface\Addons\ElvUI_EltreumUI\Media\Statusbar\Eltreum10pixel.tga]])
LSM:Register("statusbar", "Eltreum-Blank", [[Interface\Addons\ElvUI_EltreumUI\Media\Statusbar\Eltreum-Blank.tga]])
LSM:Register("statusbar", "Eltreum-Elvui-Norm", [[Interface\Addons\ElvUI_EltreumUI\Media\Statusbar\Eltreum-Elvui-Norm.tga]])

-- Background
LSM:Register("background", "Eltreum-StealthOverlay", [[Interface\Addons\ElvUI_EltreumUI\Media\Textures\StealthOverlay.tga]])
LSM:Register("background", "Details-FlatClassIcons", [[Interface\Addons\ElvUI_EltreumUI\Media\Textures\wow_flat_class_icons.tga]])