local classIconsReleaf = {
	["32"] ={
		["WARRIOR"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\32\\WarriorReleaf.tga:0:0:0:0|t",
		["PALADIN"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\32\\PaladinReleaf.tga:0:0:0:0|t",
		["HUNTER"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\32\\HunterReleaf.tga:0:0:0:0|t",
		["ROGUE"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\32\\RogueReleaf.tga:0:0:0:0|t",
		["PRIEST"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\32\\PriestReleaf.tga:0:0:0:0|t",
		["DEATHKNIGHT"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\32\\DeathKnightReleaf.tga:0:0:0:0|t",
		["SHAMAN"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\32\\ShamanReleaf.tga:0:0:0:0|t",
		["MAGE"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\32\\MageReleaf.tga:0:0:0:0|t",
		["WARLOCK"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\32\\WarlockReleaf.tga:0:0:0:0|t",
		["MONK"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\32\\MonkReleaf.tga:0:0:0:0|t",
		["DRUID"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\32\\DruidReleaf.tga:0:0:0:0|t",
		["DEMONHUNTER"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\32\\DemonHunterReleaf.tga:0:0:0:0|t",
		["EVOKER"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\32\\EvokerReleaf.tga:0:0:0:0|t",
	},
	["64"] ={
		["WARRIOR"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\64\\WarriorReleaf.tga:0:0:0:0|t",
		["PALADIN"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\64\\PaladinReleaf.tga:0:0:0:0|t",
		["HUNTER"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\64\\HunterReleaf.tga:0:0:0:0|t",
		["ROGUE"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\64\\RogueReleaf.tga:0:0:0:0|t",
		["PRIEST"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\64\\PriestReleaf.tga:0:0:0:0|t",
		["DEATHKNIGHT"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\64\\DeathKnightReleaf.tga:0:0:0:0|t",
		["SHAMAN"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\64\\ShamanReleaf.tga:0:0:0:0|t",
		["MAGE"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\64\\MageReleaf.tga:0:0:0:0|t",
		["WARLOCK"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\64\\WarlockReleaf.tga:0:0:0:0|t",
		["MONK"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\64\\MonkReleaf.tga:0:0:0:0|t",
		["DRUID"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\64\\DruidReleaf.tga:0:0:0:0|t",
		["DEMONHUNTER"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\64\\DemonHunterReleaf.tga:0:0:0:0|t",
		["EVOKER"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\64\\EvokerReleaf.tga:0:0:0:0|t",
	},
	["128"] ={
		["WARRIOR"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\128\\WarriorReleaf.tga:0:0:0:0|t",
		["PALADIN"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\128\\PaladinReleaf.tga:0:0:0:0|t",
		["HUNTER"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\128\\HunterReleaf.tga:0:0:0:0|t",
		["ROGUE"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\128\\RogueReleaf.tga:0:0:0:0|t",
		["PRIEST"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\128\\PriestReleaf.tga:0:0:0:0|t",
		["DEATHKNIGHT"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\128\\DeathKnightReleaf.tga:0:0:0:0|t",
		["SHAMAN"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\128\\ShamanReleaf.tga:0:0:0:0|t",
		["MAGE"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\128\\MageReleaf.tga:0:0:0:0|t",
		["WARLOCK"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\128\\WarlockReleaf.tga:0:0:0:0|t",
		["MONK"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\128\\MonkReleaf.tga:0:0:0:0|t",
		["DRUID"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\128\\DruidReleaf.tga:0:0:0:0|t",
		["DEMONHUNTER"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\128\\DemonHunterReleaf.tga:0:0:0:0|t",
		["EVOKER"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\128\\EvokerReleaf.tga:0:0:0:0|t",
	},
}
local classIconsBlizzard = {
	["32"] ={
		["WARRIOR"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\32\\Warrior.tga:0:0:0:0|t",
		["PALADIN"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\32\\Paladin.tga:0:0:0:0|t",
		["HUNTER"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\32\\Hunter.tga:0:0:0:0|t",
		["ROGUE"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\32\\Rogue.tga:0:0:0:0|t",
		["PRIEST"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\32\\Priest.tga:0:0:0:0|t",
		["DEATHKNIGHT"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\32\\DeathKnight.tga:0:0:0:0|t",
		["SHAMAN"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\32\\Shaman.tga:0:0:0:0|t",
		["MAGE"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\32\\Mage.tga:0:0:0:0|t",
		["WARLOCK"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\32\\Warlock.tga:0:0:0:0|t",
		["MONK"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\32\\Monk.tga:0:0:0:0|t",
		["DRUID"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\32\\Druid.tga:0:0:0:0|t",
		["DEMONHUNTER"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\32\\DemonHunter.tga:0:0:0:0|t",
		["EVOKER"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\32\\Evoker.tga:0:0:0:0|t",
	},
	["64"] ={
		["WARRIOR"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\64\\Warrior.tga:0:0:0:0|t",
		["PALADIN"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\64\\Paladin.tga:0:0:0:0|t",
		["HUNTER"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\64\\Hunter.tga:0:0:0:0|t",
		["ROGUE"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\64\\Rogue.tga:0:0:0:0|t",
		["PRIEST"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\64\\Priest.tga:0:0:0:0|t",
		["DEATHKNIGHT"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\64\\DeathKnight.tga:0:0:0:0|t",
		["SHAMAN"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\64\\Shaman.tga:0:0:0:0|t",
		["MAGE"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\64\\Mage.tga:0:0:0:0|t",
		["WARLOCK"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\64\\Warlock.tga:0:0:0:0|t",
		["MONK"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\64\\Monk.tga:0:0:0:0|t",
		["DRUID"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\64\\Druid.tga:0:0:0:0|t",
		["DEMONHUNTER"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\64\\DemonHunter.tga:0:0:0:0|t",
		["EVOKER"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\64\\Evoker.tga:0:0:0:0|t",
	},
	["128"] ={
		["WARRIOR"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\128\\Warrior.tga:0:0:0:0|t",
		["PALADIN"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\128\\Paladin.tga:0:0:0:0|t",
		["HUNTER"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\128\\Hunter.tga:0:0:0:0|t",
		["ROGUE"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\128\\Rogue.tga:0:0:0:0|t",
		["PRIEST"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\128\\Priest.tga:0:0:0:0|t",
		["DEATHKNIGHT"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\128\\DeathKnight.tga:0:0:0:0|t",
		["SHAMAN"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\128\\Shaman.tga:0:0:0:0|t",
		["MAGE"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\128\\Mage.tga:0:0:0:0|t",
		["WARLOCK"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\128\\Warlock.tga:0:0:0:0|t",
		["MONK"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\128\\Monk.tga:0:0:0:0|t",
		["DRUID"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\128\\Druid.tga:0:0:0:0|t",
		["DEMONHUNTER"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\128\\DemonHunter.tga:0:0:0:0|t",
		["EVOKER"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\128\\Evoker.tga:0:0:0:0|t",
	},
}
local classIconsBorder = {
	["32"] = {
		["WARRIOR"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\32\\WarriorIconReleaf.tga:0:0:0:0|t",
		["PALADIN"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\32\\PaladinIconReleaf.tga:0:0:0:0|t",
		["HUNTER"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\32\\HunterIconReleaf.tga:0:0:0:0|t",
		["ROGUE"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\32\\RogueIconReleaf.tga:0:0:0:0|t",
		["PRIEST"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\32\\PriestIconReleaf.tga:0:0:0:0|t",
		["DEATHKNIGHT"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\32\\DeathKnightIconReleaf.tga:0:0:0:0|t",
		["SHAMAN"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\32\\ShamanIconReleaf.tga:0:0:0:0|t",
		["MAGE"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\32\\MageIconReleaf.tga:0:0:0:0|t",
		["WARLOCK"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\32\\WarlockIconReleaf.tga:0:0:0:0|t",
		["MONK"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\32\\MonkIconReleaf.tga:0:0:0:0|t",
		["DRUID"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\32\\DruidIconReleaf.tga:0:0:0:0|t",
		["DEMONHUNTER"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\32\\DemonHunterIconReleaf.tga:0:0:0:0|t",
		["EVOKER"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\32\\EvokerIconReleaf.tga:0:0:0:0|t",
	},
	["64"] = {
		["WARRIOR"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\64\\WarriorIconReleaf.tga:0:0:0:0|t",
		["PALADIN"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\64\\PaladinIconReleaf.tga:0:0:0:0|t",
		["HUNTER"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\64\\HunterIconReleaf.tga:0:0:0:0|t",
		["ROGUE"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\64\\RogueIconReleaf.tga:0:0:0:0|t",
		["PRIEST"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\64\\PriestIconReleaf.tga:0:0:0:0|t",
		["DEATHKNIGHT"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\64\\DeathKnightIconReleaf.tga:0:0:0:0|t",
		["SHAMAN"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\64\\ShamanIconReleaf.tga:0:0:0:0|t",
		["MAGE"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\64\\MageIconReleaf.tga:0:0:0:0|t",
		["WARLOCK"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\64\\WarlockIconReleaf.tga:0:0:0:0|t",
		["MONK"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\64\\MonkIconReleaf.tga:0:0:0:0|t",
		["DRUID"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\64\\DruidIconReleaf.tga:0:0:0:0|t",
		["DEMONHUNTER"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\64\\DemonHunterIconReleaf.tga:0:0:0:0|t",
		["EVOKER"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\64\\EvokerIconReleaf.tga:0:0:0:0|t",
	},
	["128"] = {
		["WARRIOR"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\128\\WarriorIconReleaf.tga:0:0:0:0|t",
		["PALADIN"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\128\\PaladinIconReleaf.tga:0:0:0:0|t",
		["HUNTER"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\128\\HunterIconReleaf.tga:0:0:0:0|t",
		["ROGUE"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\128\\RogueIconReleaf.tga:0:0:0:0|t",
		["PRIEST"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\128\\PriestIconReleaf.tga:0:0:0:0|t",
		["DEATHKNIGHT"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\128\\DeathKnightIconReleaf.tga:0:0:0:0|t",
		["SHAMAN"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\128\\ShamanIconReleaf.tga:0:0:0:0|t",
		["MAGE"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\128\\MageIconReleaf.tga:0:0:0:0|t",
		["WARLOCK"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\128\\WarlockIconReleaf.tga:0:0:0:0|t",
		["MONK"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\128\\MonkIconReleaf.tga:0:0:0:0|t",
		["DRUID"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\128\\DruidIconReleaf.tga:0:0:0:0|t",
		["DEMONHUNTER"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\128\\DemonHunterIconReleaf.tga:0:0:0:0|t",
		["EVOKER"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\128\\EvokerIconReleaf.tga:0:0:0:0|t",
	},
}
local classIconsShadow = {
	["32"] = {
		["WARRIOR"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\32\\WarriorShadow.tga:0:0:0:0|t",
		["PALADIN"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\32\\PaladinShadow.tga:0:0:0:0|t",
		["HUNTER"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\32\\HunterShadow.tga:0:0:0:0|t",
		["ROGUE"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\32\\RogueShadow.tga:0:0:0:0|t",
		["PRIEST"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\32\\PriestShadow.tga:0:0:0:0|t",
		["DEATHKNIGHT"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\32\\DeathKnightShadow.tga:0:0:0:0|t",
		["SHAMAN"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\32\\ShamanShadow.tga:0:0:0:0|t",
		["MAGE"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\32\\MageShadow.tga:0:0:0:0|t",
		["WARLOCK"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\32\\WarlockShadow.tga:0:0:0:0|t",
		["MONK"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\32\\MonkShadow.tga:0:0:0:0|t",
		["DRUID"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\32\\DruidShadow.tga:0:0:0:0|t",
		["DEMONHUNTER"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\32\\DemonHunterShadow.tga:0:0:0:0|t",
		["EVOKER"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\32\\EvokerShadow.tga:0:0:0:0|t",
	},
	["64"] = {
		["WARRIOR"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\64\\WarriorShadow.tga:0:0:0:0|t",
		["PALADIN"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\64\\PaladinShadow.tga:0:0:0:0|t",
		["HUNTER"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\64\\HunterShadow.tga:0:0:0:0|t",
		["ROGUE"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\64\\RogueShadow.tga:0:0:0:0|t",
		["PRIEST"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\64\\PriestShadow.tga:0:0:0:0|t",
		["DEATHKNIGHT"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\64\\DeathKnightShadow.tga:0:0:0:0|t",
		["SHAMAN"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\64\\ShamanShadow.tga:0:0:0:0|t",
		["MAGE"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\64\\MageShadow.tga:0:0:0:0|t",
		["WARLOCK"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\64\\WarlockShadow.tga:0:0:0:0|t",
		["MONK"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\64\\MonkShadow.tga:0:0:0:0|t",
		["DRUID"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\64\\DruidShadow.tga:0:0:0:0|t",
		["DEMONHUNTER"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\64\\DemonHunterShadow.tga:0:0:0:0|t",
		["EVOKER"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\64\\EvokerShadow.tga:0:0:0:0|t",
	},
	["128"] = {
		["WARRIOR"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\128\\WarriorShadow.tga:0:0:0:0|t",
		["PALADIN"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\128\\PaladinShadow.tga:0:0:0:0|t",
		["HUNTER"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\128\\HunterShadow.tga:0:0:0:0|t",
		["ROGUE"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\128\\RogueShadow.tga:0:0:0:0|t",
		["PRIEST"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\128\\PriestShadow.tga:0:0:0:0|t",
		["DEATHKNIGHT"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\128\\DeathKnightShadow.tga:0:0:0:0|t",
		["SHAMAN"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\128\\ShamanShadow.tga:0:0:0:0|t",
		["MAGE"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\128\\MageShadow.tga:0:0:0:0|t",
		["WARLOCK"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\128\\WarlockShadow.tga:0:0:0:0|t",
		["MONK"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\128\\MonkShadow.tga:0:0:0:0|t",
		["DRUID"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\128\\DruidShadow.tga:0:0:0:0|t",
		["DEMONHUNTER"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\128\\DemonHunterShadow.tga:0:0:0:0|t",
		["EVOKER"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\128\\EvokerShadow.tga:0:0:0:0|t",
	},
}
local classIconsOutline = {
	["32"] = {
		["WARRIOR"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\32\\Warrior1.tga:0:0:0:0|t",
		["PALADIN"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\32\\Paladin1.tga:0:0:0:0|t",
		["HUNTER"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\32\\Hunter1.tga:0:0:0:0|t",
		["ROGUE"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\32\\Rogue1.tga:0:0:0:0|t",
		["PRIEST"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\32\\Priest1.tga:0:0:0:0|t",
		["DEATHKNIGHT"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\32\\DeathKnight1.tga:0:0:0:0|t",
		["SHAMAN"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\32\\Shaman1.tga:0:0:0:0|t",
		["MAGE"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\32\\Mage1.tga:0:0:0:0|t",
		["WARLOCK"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\32\\Warlock1.tga:0:0:0:0|t",
		["MONK"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\32\\Monk1.tga:0:0:0:0|t",
		["DRUID"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\32\\Druid1.tga:0:0:0:0|t",
		["DEMONHUNTER"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\32\\DemonHunter1.tga:0:0:0:0|t",
		["EVOKER"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\32\\Evoker1.tga:0:0:0:0|t",
	},
	["64"] = {
		["WARRIOR"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\64\\Warrior1.tga:0:0:0:0|t",
		["PALADIN"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\64\\Paladin1.tga:0:0:0:0|t",
		["HUNTER"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\64\\Hunter1.tga:0:0:0:0|t",
		["ROGUE"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\64\\Rogue1.tga:0:0:0:0|t",
		["PRIEST"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\64\\Priest1.tga:0:0:0:0|t",
		["DEATHKNIGHT"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\64\\DeathKnight1.tga:0:0:0:0|t",
		["SHAMAN"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\64\\Shaman1.tga:0:0:0:0|t",
		["MAGE"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\64\\Mage1.tga:0:0:0:0|t",
		["WARLOCK"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\64\\Warlock1.tga:0:0:0:0|t",
		["MONK"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\64\\Monk1.tga:0:0:0:0|t",
		["DRUID"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\64\\Druid1.tga:0:0:0:0|t",
		["DEMONHUNTER"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\64\\DemonHunter1.tga:0:0:0:0|t",
		["EVOKER"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\64\\Evoker1.tga:0:0:0:0|t",
	},
	["128"] = {
		["WARRIOR"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\128\\Warrior1.tga:0:0:0:0|t",
		["PALADIN"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\128\\Paladin1.tga:0:0:0:0|t",
		["HUNTER"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\128\\Hunter1.tga:0:0:0:0|t",
		["ROGUE"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\128\\Rogue1.tga:0:0:0:0|t",
		["PRIEST"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\128\\Priest1.tga:0:0:0:0|t",
		["DEATHKNIGHT"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\128\\DeathKnight1.tga:0:0:0:0|t",
		["SHAMAN"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\128\\Shaman1.tga:0:0:0:0|t",
		["MAGE"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\128\\Mage1.tga:0:0:0:0|t",
		["WARLOCK"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\128\\Warlock1.tga:0:0:0:0|t",
		["MONK"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\128\\Monk1.tga:0:0:0:0|t",
		["DRUID"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\128\\Druid1.tga:0:0:0:0|t",
		["DEMONHUNTER"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\128\\DemonHunter1.tga:0:0:0:0|t",
		["EVOKER"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\128\\Evoker1.tga:0:0:0:0|t",
	},
}
local OriginalIcons = {
	["32"] = {
		["WARRIOR"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\32\\WarriorOriginal.tga:0:0:0:0|t",
		["PALADIN"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\32\\PaladinOriginal.tga:0:0:0:0|t",
		["HUNTER"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\32\\HunterOriginal.tga:0:0:0:0|t",
		["ROGUE"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\32\\RogueOriginal.tga:0:0:0:0|t",
		["PRIEST"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\32\\PriestOriginal.tga:0:0:0:0|t",
		["DEATHKNIGHT"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\32\\DeathKnightOriginal.tga:0:0:0:0|t",
		["SHAMAN"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\32\\ShamanOriginal.tga:0:0:0:0|t",
		["MAGE"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\32\\MageOriginal.tga:0:0:0:0|t",
		["WARLOCK"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\32\\WarlockOriginal.tga:0:0:0:0|t",
		["MONK"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\32\\MonkOriginal.tga:0:0:0:0|t",
		["DRUID"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\32\\DruidOriginal.tga:0:0:0:0|t",
		["DEMONHUNTER"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\32\\DemonHunterOriginal.tga:0:0:0:0|t",
		["EVOKER"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\32\\EvokerOriginal.tga:0:0:0:0|t",
	},
	["64"] = {
		["WARRIOR"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\64\\WarriorOriginal.tga:0:0:0:0|t",
		["PALADIN"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\64\\PaladinOriginal.tga:0:0:0:0|t",
		["HUNTER"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\64\\HunterOriginal.tga:0:0:0:0|t",
		["ROGUE"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\64\\RogueOriginal.tga:0:0:0:0|t",
		["PRIEST"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\64\\PriestOriginal.tga:0:0:0:0|t",
		["DEATHKNIGHT"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\64\\DeathKnightOriginal.tga:0:0:0:0|t",
		["SHAMAN"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\64\\ShamanOriginal.tga:0:0:0:0|t",
		["MAGE"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\64\\MageOriginal.tga:0:0:0:0|t",
		["WARLOCK"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\64\\WarlockOriginal.tga:0:0:0:0|t",
		["MONK"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\64\\MonkOriginal.tga:0:0:0:0|t",
		["DRUID"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\64\\DruidOriginal.tga:0:0:0:0|t",
		["DEMONHUNTER"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\64\\DemonHunterOriginal.tga:0:0:0:0|t",
		["EVOKER"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\64\\EvokerOriginal.tga:0:0:0:0|t",
	},
	["128"] = {
		["WARRIOR"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\128\\WarriorOriginal.tga:0:0:0:0|t",
		["PALADIN"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\128\\PaladinOriginal.tga:0:0:0:0|t",
		["HUNTER"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\128\\HunterOriginal.tga:0:0:0:0|t",
		["ROGUE"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\128\\RogueOriginal.tga:0:0:0:0|t",
		["PRIEST"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\128\\PriestOriginal.tga:0:0:0:0|t",
		["DEATHKNIGHT"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\128\\DeathKnightOriginal.tga:0:0:0:0|t",
		["SHAMAN"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\128\\ShamanOriginal.tga:0:0:0:0|t",
		["MAGE"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\128\\MageOriginal.tga:0:0:0:0|t",
		["WARLOCK"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\128\\WarlockOriginal.tga:0:0:0:0|t",
		["MONK"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\128\\MonkOriginal.tga:0:0:0:0|t",
		["DRUID"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\128\\DruidOriginal.tga:0:0:0:0|t",
		["DEMONHUNTER"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\128\\DemonHunterOriginal.tga:0:0:0:0|t",
		["EVOKER"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\128\\EvokerOriginal.tga:0:0:0:0|t",
	},
}
local classSymbols = {
	["WARRIOR"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\ClassSymbols\\Warrior.tga:0:0:0:0|t",
	["PALADIN"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\ClassSymbols\\Paladin.tga:0:0:0:0|t",
	["HUNTER"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\ClassSymbols\\Hunter.tga:0:0:0:0|t",
	["ROGUE"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\ClassSymbols\\Rogue.tga:0:0:0:0|t",
	["PRIEST"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\ClassSymbols\\Priest.tga:0:0:0:0|t",
	["DEATHKNIGHT"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\ClassSymbols\\DeathKnight.tga:0:0:0:0|t",
	["SHAMAN"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\ClassSymbols\\Shaman.tga:0:0:0:0|t",
	["MAGE"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\ClassSymbols\\Mage.tga:0:0:0:0|t",
	["WARLOCK"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\ClassSymbols\\Warlock.tga:0:0:0:0|t",
	["MONK"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\ClassSymbols\\Monk.tga:0:0:0:0|t",
	["DRUID"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\ClassSymbols\\Druid.tga:0:0:0:0|t",
	["DEMONHUNTER"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\ClassSymbols\\DemonHunter.tga:0:0:0:0|t",
	["EVOKER"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\ClassSymbols\\Evoker.tga:0:0:0:0|t",
}
local reverseclassIconsReleaf = {
	["32"] = {
		["WARRIOR"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\32\\WarriorReleaf.tga:0:0:0:0:64:64:64:0:0:64|t",
		["PALADIN"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\32\\PaladinReleaf.tga:0:0:0:0:64:64:64:0:0:64|t",
		["HUNTER"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\32\\HunterReleaf.tga:0:0:0:0:64:64:64:0:0:64|t",
		["ROGUE"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\32\\RogueReleaf.tga:0:0:0:0:64:64:64:0:0:64|t",
		["PRIEST"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\32\\PriestReleaf.tga:0:0:0:0:64:64:64:0:0:64|t",
		["DEATHKNIGHT"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\32\\DeathKnightReleaf.tga:0:0:0:0:64:64:64:0:0:64|t",
		["SHAMAN"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\32\\ShamanReleaf.tga:0:0:0:0:64:64:64:0:0:64|t",
		["MAGE"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\32\\MageReleaf.tga:0:0:0:0:64:64:64:0:0:64|t",
		["WARLOCK"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\32\\WarlockReleaf.tga:0:0:0:0:64:64:64:0:0:64|t",
		["MONK"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\32\\MonkReleaf.tga:0:0:0:0:64:64:64:0:0:64|t",
		["DRUID"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\32\\DruidReleaf.tga:0:0:0:0:64:64:64:0:0:64|t",
		["DEMONHUNTER"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\32\\DemonHunterReleaf.tga:0:0:0:0:64:64:64:0:0:64|t",
		["EVOKER"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\32\\EvokerReleaf.tga:0:0:0:0:64:64:64:0:0:64|t",
	},
	["64"] = {
		["WARRIOR"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\64\\WarriorReleaf.tga:0:0:0:0:64:64:64:0:0:64|t",
		["PALADIN"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\64\\PaladinReleaf.tga:0:0:0:0:64:64:64:0:0:64|t",
		["HUNTER"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\64\\HunterReleaf.tga:0:0:0:0:64:64:64:0:0:64|t",
		["ROGUE"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\64\\RogueReleaf.tga:0:0:0:0:64:64:64:0:0:64|t",
		["PRIEST"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\64\\PriestReleaf.tga:0:0:0:0:64:64:64:0:0:64|t",
		["DEATHKNIGHT"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\64\\DeathKnightReleaf.tga:0:0:0:0:64:64:64:0:0:64|t",
		["SHAMAN"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\64\\ShamanReleaf.tga:0:0:0:0:64:64:64:0:0:64|t",
		["MAGE"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\64\\MageReleaf.tga:0:0:0:0:64:64:64:0:0:64|t",
		["WARLOCK"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\64\\WarlockReleaf.tga:0:0:0:0:64:64:64:0:0:64|t",
		["MONK"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\64\\MonkReleaf.tga:0:0:0:0:64:64:64:0:0:64|t",
		["DRUID"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\64\\DruidReleaf.tga:0:0:0:0:64:64:64:0:0:64|t",
		["DEMONHUNTER"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\64\\DemonHunterReleaf.tga:0:0:0:0:64:64:64:0:0:64|t",
		["EVOKER"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\64\\EvokerReleaf.tga:0:0:0:0:64:64:64:0:0:64|t",
	},
	["128"] = {
		["WARRIOR"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\128\\WarriorReleaf.tga:0:0:0:0:64:64:64:0:0:64|t",
		["PALADIN"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\128\\PaladinReleaf.tga:0:0:0:0:64:64:64:0:0:64|t",
		["HUNTER"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\128\\HunterReleaf.tga:0:0:0:0:64:64:64:0:0:64|t",
		["ROGUE"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\128\\RogueReleaf.tga:0:0:0:0:64:64:64:0:0:64|t",
		["PRIEST"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\128\\PriestReleaf.tga:0:0:0:0:64:64:64:0:0:64|t",
		["DEATHKNIGHT"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\128\\DeathKnightReleaf.tga:0:0:0:0:64:64:64:0:0:64|t",
		["SHAMAN"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\128\\ShamanReleaf.tga:0:0:0:0:64:64:64:0:0:64|t",
		["MAGE"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\128\\MageReleaf.tga:0:0:0:0:64:64:64:0:0:64|t",
		["WARLOCK"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\128\\WarlockReleaf.tga:0:0:0:0:64:64:64:0:0:64|t",
		["MONK"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\128\\MonkReleaf.tga:0:0:0:0:64:64:64:0:0:64|t",
		["DRUID"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\128\\DruidReleaf.tga:0:0:0:0:64:64:64:0:0:64|t",
		["DEMONHUNTER"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\128\\DemonHunterReleaf.tga:0:0:0:0:64:64:64:0:0:64|t",
		["EVOKER"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\128\\EvokerReleaf.tga:0:0:0:0:64:64:64:0:0:64|t",
	},
}
local reverseclassIconsBlizzard = {
	["32"] = {
		["WARRIOR"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\32\\Warrior.tga:0:0:0:0:64:64:64:0:0:64|t",
		["PALADIN"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\32\\Paladin.tga:0:0:0:0:64:64:64:0:0:64|t",
		["HUNTER"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\32\\Hunter.tga:0:0:0:0:64:64:64:0:0:64|t",
		["ROGUE"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\32\\Rogue.tga:0:0:0:0:64:64:64:0:0:64|t",
		["PRIEST"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\32\\Priest.tga:0:0:0:0:64:64:64:0:0:64|t",
		["DEATHKNIGHT"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\32\\DeathKnight.tga:0:0:0:0:64:64:64:0:0:64|t",
		["SHAMAN"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\32\\Shaman.tga:0:0:0:0:64:64:64:0:0:64|t",
		["MAGE"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\32\\Mage.tga:0:0:0:0:64:64:64:0:0:64|t",
		["WARLOCK"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\32\\Warlock.tga:0:0:0:0:64:64:64:0:0:64|t",
		["MONK"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\32\\Monk.tga:0:0:0:0:64:64:64:0:0:64|t",
		["DRUID"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\32\\Druid.tga:0:0:0:0:64:64:64:0:0:64|t",
		["DEMONHUNTER"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\32\\DemonHunter.tga:0:0:0:0:64:64:64:0:0:64|t",
		["EVOKER"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\32\\Evoker.tga:0:0:0:0:64:64:64:0:0:64|t",
	},
	["64"] = {
		["WARRIOR"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\64\\Warrior.tga:0:0:0:0:64:64:64:0:0:64|t",
		["PALADIN"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\64\\Paladin.tga:0:0:0:0:64:64:64:0:0:64|t",
		["HUNTER"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\64\\Hunter.tga:0:0:0:0:64:64:64:0:0:64|t",
		["ROGUE"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\64\\Rogue.tga:0:0:0:0:64:64:64:0:0:64|t",
		["PRIEST"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\64\\Priest.tga:0:0:0:0:64:64:64:0:0:64|t",
		["DEATHKNIGHT"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\64\\DeathKnight.tga:0:0:0:0:64:64:64:0:0:64|t",
		["SHAMAN"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\64\\Shaman.tga:0:0:0:0:64:64:64:0:0:64|t",
		["MAGE"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\64\\Mage.tga:0:0:0:0:64:64:64:0:0:64|t",
		["WARLOCK"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\64\\Warlock.tga:0:0:0:0:64:64:64:0:0:64|t",
		["MONK"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\64\\Monk.tga:0:0:0:0:64:64:64:0:0:64|t",
		["DRUID"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\64\\Druid.tga:0:0:0:0:64:64:64:0:0:64|t",
		["DEMONHUNTER"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\64\\DemonHunter.tga:0:0:0:0:64:64:64:0:0:64|t",
		["EVOKER"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\64\\Evoker.tga:0:0:0:0:64:64:64:0:0:64|t",
	},
	["128"] = {
		["WARRIOR"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\128\\Warrior.tga:0:0:0:0:64:64:64:0:0:64|t",
		["PALADIN"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\128\\Paladin.tga:0:0:0:0:64:64:64:0:0:64|t",
		["HUNTER"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\128\\Hunter.tga:0:0:0:0:64:64:64:0:0:64|t",
		["ROGUE"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\128\\Rogue.tga:0:0:0:0:64:64:64:0:0:64|t",
		["PRIEST"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\128\\Priest.tga:0:0:0:0:64:64:64:0:0:64|t",
		["DEATHKNIGHT"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\128\\DeathKnight.tga:0:0:0:0:64:64:64:0:0:64|t",
		["SHAMAN"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\128\\Shaman.tga:0:0:0:0:64:64:64:0:0:64|t",
		["MAGE"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\128\\Mage.tga:0:0:0:0:64:64:64:0:0:64|t",
		["WARLOCK"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\128\\Warlock.tga:0:0:0:0:64:64:64:0:0:64|t",
		["MONK"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\128\\Monk.tga:0:0:0:0:64:64:64:0:0:64|t",
		["DRUID"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\128\\Druid.tga:0:0:0:0:64:64:64:0:0:64|t",
		["DEMONHUNTER"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\128\\DemonHunter.tga:0:0:0:0:64:64:64:0:0:64|t",
		["EVOKER"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\128\\Evoker.tga:0:0:0:0:64:64:64:0:0:64|t",
	},
}
local reverseclassIconsBorder = {
	["32"] = {
		["WARRIOR"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\32\\WarriorIconReleaf.tga:0:0:0:0:64:64:64:0:0:64|t",
		["PALADIN"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\32\\PaladinIconReleaf.tga:0:0:0:0:64:64:64:0:0:64|t",
		["HUNTER"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\32\\HunterIconReleaf.tga:0:0:0:0:64:64:64:0:0:64|t",
		["ROGUE"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\32\\RogueIconReleaf.tga:0:0:0:0:64:64:64:0:0:64|t",
		["PRIEST"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\32\\PriestIconReleaf.tga:0:0:0:0:64:64:64:0:0:64|t",
		["DEATHKNIGHT"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\32\\DeathKnightIconReleaf.tga:0:0:0:0:64:64:64:0:0:64|t",
		["SHAMAN"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\32\\ShamanIconReleaf.tga:0:0:0:0:64:64:64:0:0:64|t",
		["MAGE"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\32\\MageIconReleaf.tga:0:0:0:0:64:64:64:0:0:64|t",
		["WARLOCK"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\32\\WarlockIconReleaf.tga:0:0:0:0:64:64:64:0:0:64|t",
		["MONK"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\32\\MonkIconReleaf.tga:0:0:0:0:64:64:64:0:0:64|t",
		["DRUID"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\32\\DruidIconReleaf.tga:0:0:0:0:64:64:64:0:0:64|t",
		["DEMONHUNTER"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\32\\DemonHunterIconReleaf.tga:0:0:0:0:64:64:64:0:0:64|t",
		["EVOKER"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\32\\EvokerIconReleaf.tga:0:0:0:0:64:64:64:0:0:64|t",
	},
	["64"] = {
		["WARRIOR"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\64\\WarriorIconReleaf.tga:0:0:0:0:64:64:64:0:0:64|t",
		["PALADIN"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\64\\PaladinIconReleaf.tga:0:0:0:0:64:64:64:0:0:64|t",
		["HUNTER"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\64\\HunterIconReleaf.tga:0:0:0:0:64:64:64:0:0:64|t",
		["ROGUE"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\64\\RogueIconReleaf.tga:0:0:0:0:64:64:64:0:0:64|t",
		["PRIEST"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\64\\PriestIconReleaf.tga:0:0:0:0:64:64:64:0:0:64|t",
		["DEATHKNIGHT"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\64\\DeathKnightIconReleaf.tga:0:0:0:0:64:64:64:0:0:64|t",
		["SHAMAN"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\64\\ShamanIconReleaf.tga:0:0:0:0:64:64:64:0:0:64|t",
		["MAGE"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\64\\MageIconReleaf.tga:0:0:0:0:64:64:64:0:0:64|t",
		["WARLOCK"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\64\\WarlockIconReleaf.tga:0:0:0:0:64:64:64:0:0:64|t",
		["MONK"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\64\\MonkIconReleaf.tga:0:0:0:0:64:64:64:0:0:64|t",
		["DRUID"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\64\\DruidIconReleaf.tga:0:0:0:0:64:64:64:0:0:64|t",
		["DEMONHUNTER"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\64\\DemonHunterIconReleaf.tga:0:0:0:0:64:64:64:0:0:64|t",
		["EVOKER"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\64\\EvokerIconReleaf.tga:0:0:0:0:64:64:64:0:0:64|t",
	},
	["128"] = {
		["WARRIOR"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\128\\WarriorIconReleaf.tga:0:0:0:0:64:64:64:0:0:64|t",
		["PALADIN"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\128\\PaladinIconReleaf.tga:0:0:0:0:64:64:64:0:0:64|t",
		["HUNTER"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\128\\HunterIconReleaf.tga:0:0:0:0:64:64:64:0:0:64|t",
		["ROGUE"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\128\\RogueIconReleaf.tga:0:0:0:0:64:64:64:0:0:64|t",
		["PRIEST"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\128\\PriestIconReleaf.tga:0:0:0:0:64:64:64:0:0:64|t",
		["DEATHKNIGHT"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\128\\DeathKnightIconReleaf.tga:0:0:0:0:64:64:64:0:0:64|t",
		["SHAMAN"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\128\\ShamanIconReleaf.tga:0:0:0:0:64:64:64:0:0:64|t",
		["MAGE"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\128\\MageIconReleaf.tga:0:0:0:0:64:64:64:0:0:64|t",
		["WARLOCK"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\128\\WarlockIconReleaf.tga:0:0:0:0:64:64:64:0:0:64|t",
		["MONK"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\128\\MonkIconReleaf.tga:0:0:0:0:64:64:64:0:0:64|t",
		["DRUID"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\128\\DruidIconReleaf.tga:0:0:0:0:64:64:64:0:0:64|t",
		["DEMONHUNTER"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\128\\DemonHunterIconReleaf.tga:0:0:0:0:64:64:64:0:0:64|t",
		["EVOKER"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\128\\EvokerIconReleaf.tga:0:0:0:0:64:64:64:0:0:64|t",
	},
}
local reverseclassIconsShadow = {
	["32"] = {
		["WARRIOR"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\32\\WarriorShadow.tga:0:0:0:0:64:64:64:0:0:64|t",
		["PALADIN"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\32\\PaladinShadow.tga:0:0:0:0:64:64:64:0:0:64|t",
		["HUNTER"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\32\\HunterShadow.tga:0:0:0:0:64:64:64:0:0:64|t",
		["ROGUE"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\32\\RogueShadow.tga:0:0:0:0:64:64:64:0:0:64|t",
		["PRIEST"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\32\\PriestShadow.tga:0:0:0:0:64:64:64:0:0:64|t",
		["DEATHKNIGHT"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\32\\DeathKnightShadow.tga:0:0:0:0:64:64:64:0:0:64|t",
		["SHAMAN"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\32\\ShamanShadow.tga:0:0:0:0:64:64:64:0:0:64|t",
		["MAGE"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\32\\MageShadow.tga:0:0:0:0:64:64:64:0:0:64|t",
		["WARLOCK"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\32\\WarlockShadow.tga:0:0:0:0:64:64:64:0:0:64|t",
		["MONK"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\32\\MonkShadow.tga:0:0:0:0:64:64:64:0:0:64|t",
		["DRUID"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\32\\DruidShadow.tga:0:0:0:0:64:64:64:0:0:64|t",
		["DEMONHUNTER"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\32\\DemonHunterShadow.tga:0:0:0:0:64:64:64:0:0:64|t",
		["EVOKER"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\32\\EvokerShadow.tga:0:0:0:0:64:64:64:0:0:64|t",
	},
	["64"] = {
		["WARRIOR"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\64\\WarriorShadow.tga:0:0:0:0:64:64:64:0:0:64|t",
		["PALADIN"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\64\\PaladinShadow.tga:0:0:0:0:64:64:64:0:0:64|t",
		["HUNTER"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\64\\HunterShadow.tga:0:0:0:0:64:64:64:0:0:64|t",
		["ROGUE"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\64\\RogueShadow.tga:0:0:0:0:64:64:64:0:0:64|t",
		["PRIEST"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\64\\PriestShadow.tga:0:0:0:0:64:64:64:0:0:64|t",
		["DEATHKNIGHT"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\64\\DeathKnightShadow.tga:0:0:0:0:64:64:64:0:0:64|t",
		["SHAMAN"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\64\\ShamanShadow.tga:0:0:0:0:64:64:64:0:0:64|t",
		["MAGE"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\64\\MageShadow.tga:0:0:0:0:64:64:64:0:0:64|t",
		["WARLOCK"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\64\\WarlockShadow.tga:0:0:0:0:64:64:64:0:0:64|t",
		["MONK"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\64\\MonkShadow.tga:0:0:0:0:64:64:64:0:0:64|t",
		["DRUID"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\64\\DruidShadow.tga:0:0:0:0:64:64:64:0:0:64|t",
		["DEMONHUNTER"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\64\\DemonHunterShadow.tga:0:0:0:0:64:64:64:0:0:64|t",
		["EVOKER"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\64\\EvokerShadow.tga:0:0:0:0:64:64:64:0:0:64|t",
	},
	["128"] = {
		["WARRIOR"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\128\\WarriorShadow.tga:0:0:0:0:64:64:64:0:0:64|t",
		["PALADIN"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\128\\PaladinShadow.tga:0:0:0:0:64:64:64:0:0:64|t",
		["HUNTER"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\128\\HunterShadow.tga:0:0:0:0:64:64:64:0:0:64|t",
		["ROGUE"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\128\\RogueShadow.tga:0:0:0:0:64:64:64:0:0:64|t",
		["PRIEST"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\128\\PriestShadow.tga:0:0:0:0:64:64:64:0:0:64|t",
		["DEATHKNIGHT"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\128\\DeathKnightShadow.tga:0:0:0:0:64:64:64:0:0:64|t",
		["SHAMAN"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\128\\ShamanShadow.tga:0:0:0:0:64:64:64:0:0:64|t",
		["MAGE"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\128\\MageShadow.tga:0:0:0:0:64:64:64:0:0:64|t",
		["WARLOCK"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\128\\WarlockShadow.tga:0:0:0:0:64:64:64:0:0:64|t",
		["MONK"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\128\\MonkShadow.tga:0:0:0:0:64:64:64:0:0:64|t",
		["DRUID"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\128\\DruidShadow.tga:0:0:0:0:64:64:64:0:0:64|t",
		["DEMONHUNTER"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\128\\DemonHunterShadow.tga:0:0:0:0:64:64:64:0:0:64|t",
		["EVOKER"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\128\\EvokerShadow.tga:0:0:0:0:64:64:64:0:0:64|t",
	},
}
local reverseclassIconsOutline = {
	["32"] = {
		["WARRIOR"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\32\\Warrior1.tga:0:0:0:0:64:64:64:0:0:64|t",
		["PALADIN"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\32\\Paladin1.tga:0:0:0:0:64:64:64:0:0:64|t",
		["HUNTER"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\32\\Hunter1.tga:0:0:0:0:64:64:64:0:0:64|t",
		["ROGUE"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\32\\Rogue1.tga:0:0:0:0:64:64:64:0:0:64|t",
		["PRIEST"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\32\\Priest1.tga:0:0:0:0:64:64:64:0:0:64|t",
		["DEATHKNIGHT"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\32\\DeathKnight1.tga:0:0:0:0:64:64:64:0:0:64|t",
		["SHAMAN"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\32\\Shaman1.tga:0:0:0:0:64:64:64:0:0:64|t",
		["MAGE"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\32\\Mage1.tga:0:0:0:0:64:64:64:0:0:64|t",
		["WARLOCK"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\32\\Warlock1.tga:0:0:0:0:64:64:64:0:0:64|t",
		["MONK"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\32\\Monk1.tga:0:0:0:0:64:64:64:0:0:64|t",
		["DRUID"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\32\\Druid1.tga:0:0:0:0:64:64:64:0:0:64|t",
		["DEMONHUNTER"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\32\\DemonHunter1.tga:0:0:0:0:64:64:64:0:0:64|t",
		["EVOKER"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\32\\Evoker1.tga:0:0:0:0:64:64:64:0:0:64|t",
	},
	["64"] = {
		["WARRIOR"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\64\\Warrior1.tga:0:0:0:0:64:64:64:0:0:64|t",
		["PALADIN"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\64\\Paladin1.tga:0:0:0:0:64:64:64:0:0:64|t",
		["HUNTER"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\64\\Hunter1.tga:0:0:0:0:64:64:64:0:0:64|t",
		["ROGUE"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\64\\Rogue1.tga:0:0:0:0:64:64:64:0:0:64|t",
		["PRIEST"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\64\\Priest1.tga:0:0:0:0:64:64:64:0:0:64|t",
		["DEATHKNIGHT"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\64\\DeathKnight1.tga:0:0:0:0:64:64:64:0:0:64|t",
		["SHAMAN"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\64\\Shaman1.tga:0:0:0:0:64:64:64:0:0:64|t",
		["MAGE"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\64\\Mage1.tga:0:0:0:0:64:64:64:0:0:64|t",
		["WARLOCK"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\64\\Warlock1.tga:0:0:0:0:64:64:64:0:0:64|t",
		["MONK"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\64\\Monk1.tga:0:0:0:0:64:64:64:0:0:64|t",
		["DRUID"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\64\\Druid1.tga:0:0:0:0:64:64:64:0:0:64|t",
		["DEMONHUNTER"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\64\\DemonHunter1.tga:0:0:0:0:64:64:64:0:0:64|t",
		["EVOKER"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\64\\Evoker1.tga:0:0:0:0:64:64:64:0:0:64|t",
	},
	["128"] = {
		["WARRIOR"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\128\\Warrior1.tga:0:0:0:0:64:64:64:0:0:64|t",
		["PALADIN"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\128\\Paladin1.tga:0:0:0:0:64:64:64:0:0:64|t",
		["HUNTER"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\128\\Hunter1.tga:0:0:0:0:64:64:64:0:0:64|t",
		["ROGUE"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\128\\Rogue1.tga:0:0:0:0:64:64:64:0:0:64|t",
		["PRIEST"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\128\\Priest1.tga:0:0:0:0:64:64:64:0:0:64|t",
		["DEATHKNIGHT"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\128\\DeathKnight1.tga:0:0:0:0:64:64:64:0:0:64|t",
		["SHAMAN"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\128\\Shaman1.tga:0:0:0:0:64:64:64:0:0:64|t",
		["MAGE"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\128\\Mage1.tga:0:0:0:0:64:64:64:0:0:64|t",
		["WARLOCK"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\128\\Warlock1.tga:0:0:0:0:64:64:64:0:0:64|t",
		["MONK"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\128\\Monk1.tga:0:0:0:0:64:64:64:0:0:64|t",
		["DRUID"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\128\\Druid1.tga:0:0:0:0:64:64:64:0:0:64|t",
		["DEMONHUNTER"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\128\\DemonHunter1.tga:0:0:0:0:64:64:64:0:0:64|t",
		["EVOKER"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\128\\Evoker1.tga:0:0:0:0:64:64:64:0:0:64|t",
	},
}
local reverseOriginalIcons = {
	["32"] = {
		["WARRIOR"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\32\\WarriorOriginal.tga:0:0:0:0:64:64:64:0:0:64|t",
		["PALADIN"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\32\\PaladinOriginal.tga:0:0:0:0:64:64:64:0:0:64|t",
		["HUNTER"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\32\\HunterOriginal.tga:0:0:0:0:64:64:64:0:0:64|t",
		["ROGUE"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\32\\RogueOriginal.tga:0:0:0:0:64:64:64:0:0:64|t",
		["PRIEST"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\32\\PriestOriginal.tga:0:0:0:0:64:64:64:0:0:64|t",
		["DEATHKNIGHT"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\32\\DeathKnightOriginal.tga:0:0:0:0:64:64:64:0:0:64|t",
		["SHAMAN"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\32\\ShamanOriginal.tga:0:0:0:0:64:64:64:0:0:64|t",
		["MAGE"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\32\\MageOriginal.tga:0:0:0:0:64:64:64:0:0:64|t",
		["WARLOCK"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\32\\WarlockOriginal.tga:0:0:0:0:64:64:64:0:0:64|t",
		["MONK"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\32\\MonkOriginal.tga:0:0:0:0:64:64:64:0:0:64|t",
		["DRUID"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\32\\DruidOriginal.tga:0:0:0:0:64:64:64:0:0:64|t",
		["DEMONHUNTER"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\32\\DemonHunterOriginal.tga:0:0:0:0:64:64:64:0:0:64|t",
		["EVOKER"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\32\\EvokerOriginal.tga:0:0:0:0:64:64:64:0:0:64|t",
	},
	["64"] = {
		["WARRIOR"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\64\\WarriorOriginal.tga:0:0:0:0:64:64:64:0:0:64|t",
		["PALADIN"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\64\\PaladinOriginal.tga:0:0:0:0:64:64:64:0:0:64|t",
		["HUNTER"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\64\\HunterOriginal.tga:0:0:0:0:64:64:64:0:0:64|t",
		["ROGUE"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\64\\RogueOriginal.tga:0:0:0:0:64:64:64:0:0:64|t",
		["PRIEST"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\64\\PriestOriginal.tga:0:0:0:0:64:64:64:0:0:64|t",
		["DEATHKNIGHT"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\64\\DeathKnightOriginal.tga:0:0:0:0:64:64:64:0:0:64|t",
		["SHAMAN"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\64\\ShamanOriginal.tga:0:0:0:0:64:64:64:0:0:64|t",
		["MAGE"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\64\\MageOriginal.tga:0:0:0:0:64:64:64:0:0:64|t",
		["WARLOCK"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\64\\WarlockOriginal.tga:0:0:0:0:64:64:64:0:0:64|t",
		["MONK"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\64\\MonkOriginal.tga:0:0:0:0:64:64:64:0:0:64|t",
		["DRUID"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\64\\DruidOriginal.tga:0:0:0:0:64:64:64:0:0:64|t",
		["DEMONHUNTER"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\64\\DemonHunterOriginal.tga:0:0:0:0:64:64:64:0:0:64|t",
		["EVOKER"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\64\\EvokerOriginal.tga:0:0:0:0:64:64:64:0:0:64|t",
	},
	["128"] = {
		["WARRIOR"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\128\\WarriorOriginal.tga:0:0:0:0:64:64:64:0:0:64|t",
		["PALADIN"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\128\\PaladinOriginal.tga:0:0:0:0:64:64:64:0:0:64|t",
		["HUNTER"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\128\\HunterOriginal.tga:0:0:0:0:64:64:64:0:0:64|t",
		["ROGUE"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\128\\RogueOriginal.tga:0:0:0:0:64:64:64:0:0:64|t",
		["PRIEST"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\128\\PriestOriginal.tga:0:0:0:0:64:64:64:0:0:64|t",
		["DEATHKNIGHT"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\128\\DeathKnightOriginal.tga:0:0:0:0:64:64:64:0:0:64|t",
		["SHAMAN"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\128\\ShamanOriginal.tga:0:0:0:0:64:64:64:0:0:64|t",
		["MAGE"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\128\\MageOriginal.tga:0:0:0:0:64:64:64:0:0:64|t",
		["WARLOCK"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\128\\WarlockOriginal.tga:0:0:0:0:64:64:64:0:0:64|t",
		["MONK"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\128\\MonkOriginal.tga:0:0:0:0:64:64:64:0:0:64|t",
		["DRUID"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\128\\DruidOriginal.tga:0:0:0:0:64:64:64:0:0:64|t",
		["DEMONHUNTER"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\128\\DemonHunterOriginal.tga:0:0:0:0:64:64:64:0:0:64|t",
		["EVOKER"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\128\\EvokerOriginal.tga:0:0:0:0:64:64:64:0:0:64|t",
	},
}
local gradient = {
	["32"] = {
		["WARRIOR"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\32\\WarriorGradient.tga:0:0:0:0|t",
		["PALADIN"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\32\\PaladinGradient.tga:0:0:0:0|t",
		["HUNTER"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\32\\HunterGradient.tga:0:0:0:0|t",
		["ROGUE"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\32\\RogueGradient.tga:0:0:0:0|t",
		["PRIEST"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\32\\PriestGradient.tga:0:0:0:0|t",
		["DEATHKNIGHT"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\32\\DeathKnightGradient.tga:0:0:0:0|t",
		["SHAMAN"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\32\\ShamanGradient.tga:0:0:0:0|t",
		["MAGE"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\32\\MageGradient.tga:0:0:0:0|t",
		["WARLOCK"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\32\\WarlockGradient.tga:0:0:0:0|t",
		["MONK"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\32\\MonkGradient.tga:0:0:0:0|t",
		["DRUID"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\32\\DruidGradient.tga:0:0:0:0|t",
		["DEMONHUNTER"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\32\\DemonHunterGradient.tga:0:0:0:0|t",
		["EVOKER"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\32\\EvokerGradient.tga:0:0:0:0|t",
	},
	["64"] = {
		["WARRIOR"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\64\\WarriorGradient.tga:0:0:0:0|t",
		["PALADIN"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\64\\PaladinGradient.tga:0:0:0:0|t",
		["HUNTER"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\64\\HunterGradient.tga:0:0:0:0|t",
		["ROGUE"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\64\\RogueGradient.tga:0:0:0:0|t",
		["PRIEST"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\64\\PriestGradient.tga:0:0:0:0|t",
		["DEATHKNIGHT"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\64\\DeathKnightGradient.tga:0:0:0:0|t",
		["SHAMAN"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\64\\ShamanGradient.tga:0:0:0:0|t",
		["MAGE"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\64\\MageGradient.tga:0:0:0:0|t",
		["WARLOCK"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\64\\WarlockGradient.tga:0:0:0:0|t",
		["MONK"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\64\\MonkGradient.tga:0:0:0:0|t",
		["DRUID"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\64\\DruidGradient.tga:0:0:0:0|t",
		["DEMONHUNTER"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\64\\DemonHunterGradient.tga:0:0:0:0|t",
		["EVOKER"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\64\\EvokerGradient.tga:0:0:0:0|t",
	},
	["128"] = {
		["WARRIOR"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\128\\WarriorGradient.tga:0:0:0:0|t",
		["PALADIN"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\128\\PaladinGradient.tga:0:0:0:0|t",
		["HUNTER"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\128\\HunterGradient.tga:0:0:0:0|t",
		["ROGUE"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\128\\RogueGradient.tga:0:0:0:0|t",
		["PRIEST"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\128\\PriestGradient.tga:0:0:0:0|t",
		["DEATHKNIGHT"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\128\\DeathKnightGradient.tga:0:0:0:0|t",
		["SHAMAN"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\128\\ShamanGradient.tga:0:0:0:0|t",
		["MAGE"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\128\\MageGradient.tga:0:0:0:0|t",
		["WARLOCK"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\128\\WarlockGradient.tga:0:0:0:0|t",
		["MONK"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\128\\MonkGradient.tga:0:0:0:0|t",
		["DRUID"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\128\\DruidGradient.tga:0:0:0:0|t",
		["DEMONHUNTER"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\128\\DemonHunterGradient.tga:0:0:0:0|t",
		["EVOKER"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\128\\EvokerGradient.tga:0:0:0:0|t",
	},
}
local gradientReverse = {
	["32"] = {
		["WARRIOR"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\32\\WarriorGradient.tga:0:0:0:0:64:64:64:0:0:64|t",
		["PALADIN"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\32\\PaladinGradient.tga:0:0:0:0:64:64:64:0:0:64|t",
		["HUNTER"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\32\\HunterGradient.tga:0:0:0:0:64:64:64:0:0:64|t",
		["ROGUE"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\32\\RogueGradient.tga:0:0:0:0:64:64:64:0:0:64|t",
		["PRIEST"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\32\\PriestGradient.tga:0:0:0:0:64:64:64:0:0:64|t",
		["DEATHKNIGHT"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\32\\DeathKnightGradient.tga:0:0:0:0:64:64:64:0:0:64|t",
		["SHAMAN"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\32\\ShamanGradient.tga:0:0:0:0:64:64:64:0:0:64|t",
		["MAGE"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\32\\MageGradient.tga:0:0:0:0:64:64:64:0:0:64|t",
		["WARLOCK"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\32\\WarlockGradient.tga:0:0:0:0:64:64:64:0:0:64|t",
		["MONK"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\32\\MonkGradient.tga:0:0:0:0:64:64:64:0:0:64|t",
		["DRUID"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\32\\DruidGradient.tga:0:0:0:0:64:64:64:0:0:64|t",
		["DEMONHUNTER"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\32\\DemonHunterGradient.tga:0:0:0:0:64:64:64:0:0:64|t",
		["EVOKER"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\32\\EvokerGradient.tga:0:0:0:0:64:64:64:0:0:64|t",
	},
	["64"] = {
		["WARRIOR"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\64\\WarriorGradient.tga:0:0:0:0:64:64:64:0:0:64|t",
		["PALADIN"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\64\\PaladinGradient.tga:0:0:0:0:64:64:64:0:0:64|t",
		["HUNTER"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\64\\HunterGradient.tga:0:0:0:0:64:64:64:0:0:64|t",
		["ROGUE"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\64\\RogueGradient.tga:0:0:0:0:64:64:64:0:0:64|t",
		["PRIEST"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\64\\PriestGradient.tga:0:0:0:0:64:64:64:0:0:64|t",
		["DEATHKNIGHT"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\64\\DeathKnightGradient.tga:0:0:0:0:64:64:64:0:0:64|t",
		["SHAMAN"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\64\\ShamanGradient.tga:0:0:0:0:64:64:64:0:0:64|t",
		["MAGE"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\64\\MageGradient.tga:0:0:0:0:64:64:64:0:0:64|t",
		["WARLOCK"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\64\\WarlockGradient.tga:0:0:0:0:64:64:64:0:0:64|t",
		["MONK"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\64\\MonkGradient.tga:0:0:0:0:64:64:64:0:0:64|t",
		["DRUID"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\64\\DruidGradient.tga:0:0:0:0:64:64:64:0:0:64|t",
		["DEMONHUNTER"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\64\\DemonHunterGradient.tga:0:0:0:0:64:64:64:0:0:64|t",
		["EVOKER"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\64\\EvokerGradient.tga:0:0:0:0:64:64:64:0:0:64|t",
	},
	["128"] = {
		["WARRIOR"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\128\\WarriorGradient.tga:0:0:0:0:64:64:64:0:0:64|t",
		["PALADIN"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\128\\PaladinGradient.tga:0:0:0:0:64:64:64:0:0:64|t",
		["HUNTER"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\128\\HunterGradient.tga:0:0:0:0:64:64:64:0:0:64|t",
		["ROGUE"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\128\\RogueGradient.tga:0:0:0:0:64:64:64:0:0:64|t",
		["PRIEST"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\128\\PriestGradient.tga:0:0:0:0:64:64:64:0:0:64|t",
		["DEATHKNIGHT"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\128\\DeathKnightGradient.tga:0:0:0:0:64:64:64:0:0:64|t",
		["SHAMAN"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\128\\ShamanGradient.tga:0:0:0:0:64:64:64:0:0:64|t",
		["MAGE"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\128\\MageGradient.tga:0:0:0:0:64:64:64:0:0:64|t",
		["WARLOCK"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\128\\WarlockGradient.tga:0:0:0:0:64:64:64:0:0:64|t",
		["MONK"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\128\\MonkGradient.tga:0:0:0:0:64:64:64:0:0:64|t",
		["DRUID"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\128\\DruidGradient.tga:0:0:0:0:64:64:64:0:0:64|t",
		["DEMONHUNTER"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\128\\DemonHunterGradient.tga:0:0:0:0:64:64:64:0:0:64|t",
		["EVOKER"] = "|TInterface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\Classes\\128\\EvokerGradient.tga:0:0:0:0:64:64:64:0:0:64|t",
	},
}

--return icons for other functions
function ElvUI_EltreumUI:GetClassIcons(icon,unitclass,invert,resolution)
	if not invert then
		if icon == "RELEAF" then
			return classIconsReleaf[resolution][unitclass]
		elseif icon == "OUTLINE" then
			return classIconsOutline[resolution][unitclass]
		elseif icon == "BLIZZARD" then
			return classIconsBlizzard[resolution][unitclass]
		elseif icon == "BORDER" then
			return classIconsBorder[resolution][unitclass]
		elseif icon == "SHADOW" then
			return classIconsShadow[resolution][unitclass]
		elseif icon == "ORIGINAL" then
			return OriginalIcons[resolution][unitclass]
		elseif icon == "GRADIENT" then
			return gradient[resolution][unitclass]
		elseif icon == "SYMBOLS" then
			return classSymbols[unitclass]
		end
	else
		if icon == "RELEAF" then
			return reverseclassIconsReleaf[resolution][unitclass]
		elseif icon == "OUTLINE" then
			return reverseclassIconsOutline[resolution][unitclass]
		elseif icon == "BLIZZARD" then
			return reverseclassIconsBlizzard[resolution][unitclass]
		elseif icon == "BORDER" then
			return reverseclassIconsBorder[resolution][unitclass]
		elseif icon == "SHADOW" then
			return reverseclassIconsShadow[resolution][unitclass]
		elseif icon == "ORIGINAL" then
			return reverseOriginalIcons[resolution][unitclass]
		elseif icon == "GRADIENT" then
			return gradientReverse[resolution][unitclass]
		elseif icon == "SYMBOLS" then
			return classSymbols[unitclass]
		end
	end
end
