local ElvUI_EltreumUI, E, L, V, P, G = unpack(select(2, ...))
local _G = _G


local darksouls = CreateFrame("FRAME", nil, WorldFrame)
local x = GetScreenWidth()
local y = GetScreenHeight()
darksouls:SetSize(1920,1080)
local darksoulstex = darksouls:CreateTexture()
darksoulstex:SetTexture(186185)
darksoulstex:SetVertexColor(0, 0, 0)
darksoulstex:SetAlpha(0.72)
--darksoulstex:SetTexture("Interface\\Addons\\ElvUI_EltreumUI\\Media\\Textures\\StealthOverlay.tga")
darksoulstex:SetAllPoints(darksouls)
darksouls:SetPoint("Center", UIParent)
darksouls.Text = darksouls:CreateFontString(nil, "OVERLAY", "GameFontNormal")
darksouls.Text:SetJustifyH("CENTER")
darksouls.Text:SetJustifyV("MIDDLE")
darksouls.Text:SetPoint("CENTER", UIParent, "CENTER", 0, 0)
darksouls.Text:SetTextColor(1, 0.1803921568627451, 0.196078431372549, 0.5)
local fontsize = 240
darksouls.Text:SetFont("Interface\\Addons\\ElvUI_EltreumUI\\Media\\Fonts\\OptimusPrinceps.TTF", fontsize, "OUTLINE")
darksouls.Text:SetParent(darksouls)
darksouls.Text:SetText("YOU DIED")
--darksouls.Text:SetAllPoints(self)
darksouls:Hide()
darksouls.scaler = darksouls.Text:CreateAnimationGroup()
--darksouls:RegisterEvent("PLAYER_DEAD")

local scaleOut = darksouls.scaler:CreateAnimation("Scale")
scaleOut:SetOrder(1)
scaleOut:SetDuration(5)
scaleOut:SetStartDelay(0.1)
scaleOut:SetSmoothing("OUT")
scaleOut:SetFromScale(1, 1)
scaleOut:SetToScale(2, 2)
--scaleOut:SetChildKey(darksouls.Text)
--scaleOut:SetOrigin(darksouls.Text:GetCenter(), 0, 0)
local moveOut = darksouls.scaler:CreateAnimation("Translation")
moveOut:SetOrder(1)
moveOut:SetDuration(5)
moveOut:SetSmoothing("OUT")
moveOut:SetStartDelay(0.1)
moveOut:SetOffset(-fontsize, -fontsize/4)

darksouls:RegisterEvent("PLAYER_STARTED_MOVING")
darksouls:SetScript("OnEvent", function()
	UIParent:Hide()
	PlaySoundFile("Interface\\AddOns\\ElvUI_EltreumUI\\Media\\sound\\You_Died.ogg" , "Master")
	UIFrameFadeIn(darksouls, 1, 0, 1)
	darksouls.scaler:Play()
	C_Timer.After(4, function() UIFrameFadeOut(darksouls, 1, 1, 0) end)
	C_Timer.After(5, function() UIParent:Show() end)
end)
