local E, L, V, P, G = unpack(ElvUI)

-- Eltreum UI Profile DB
P.ElvUI_EltreumUI = {

	dev = false,
	deepLwarning = true,
	autoupdate = false,
	encountercheck = false,
	disabledmodels = false,

	chat = {
		enable = false,
		leftmouseover = false,
		rightmouseover = false,
		leftfader = false,
		rightfader = false,
		leftcombathide = false,
		leftbosshide = false,
		rightcombathide = false,
		rightbosshide = false,
		invertclick = false,
		colorsysmsg = false,
		classcolorchat = false,
		classcolorchatcustom = false,
		rollsound = false,
		looticons = false,
		itemlevels = false,
		chattoggles = true,
		chaticonenable = true,
		chatgradient = false,
		chaticontype = "GRADIENT",
		chatraceicon = false,
		AuthorMVPDonatorIcons = true,
	},

	cvars = {
		nameplateOtherBottomInset = 0.02,
		nameplateOtherTopInset = 0.1,
		nameplateOccludedAlphaMult = 0,
		cameraFOV = 90,
		cameraDistanceMaxZoomFactor = E.Retail and 2.6 or 4,
		nameplateTargetRadialPosition = 1,
		dynamicrenderscalemin = 0.33, --default value
		--for retail
		showInGameNavigation = 1,
		--for tbc/classic
		clampTargetNameplateToScreen = 1,
		autohidenpcname = false,
		combatlog = false,
	},

	skins = {
		elvui = {
			SetTemplate = false,
			unitframes = true,
			nameplates = true,
			button = true,
			color = {
				classcolor = false,
				r = 0.12,
				g = 0.12,
				b = 0.12,
				a = 1,
			},
			texture = "Eltreum-Tile01",
		},
		ace3 = {
			enable = false,
			texture = "ElvUI Norm1",
			fadetime = 0.3,
			tab = {
				TextEnabled = {
					r = 0.27,
					g = 0.50,
					b = 0.70,
					classcolor = true,
				},
				TextSelected = {
					r = 1,
					g = 1,
					b = 1,
					classcolor = false,
				},
			},
			button = {
				hovercolor = {
					r = 0.07,
					g = 0.30,
					b = 0.50,
					a = 1,
					classcolor = true,
				},
				disabled = {
					r = 0.07,
					g = 0.30,
					b = 0.50,
					a = 1,
					classcolor = true,
				},
			},
		},
		levelbossinstance = false,
		widertransmog = false,
		--expandedstable = false,
		characterpanelscale = 1,
		classiconsoncharacterpanel = false,
		classiconsstyle = "RELEAF",
		classicarmory = false,
		classicarmoryautostats = false,
		classicarmoryeltruismstats = true,
		charactermodelcam = {
			zoomretail = -0.2,
			xretail = 0.8,
			yretail = 0,
			zoomclassic = -0.2,
			xclassic = 0,
			yclassic = -0.1,
		},
		ilvls = false,
		ilvlsinspect = true,
		sockets = false,
		socketsinspect = false,
		ilvlanchor = "CENTER",
		ilvlanchorx = 0,
		ilvlanchory = 0,
		ilvlfontsize = 16,
		ilvlfontweight = "THICKOUTLINE",
		expandarmorybg = false,
		itemsetenable = true,
		itemsetcustomcolor = false,
		itemsetcolor = {
			--r = 0.784,
			--g = 0.635,
			--b = 0.784,
			r = 0,
			g = 1,
			b = 1,
		},
		ilvltextcolordifferenceenable = true,
		ilvltextcolordifferencecustom = false,
		ilvltextcolordifference = {
			badR = 1,
			badG = 0,
			badB = 0,
			mediumR = 1,
			mediumG = 1,
			mediumB = 0,
			goodR = 0,
			goodG = 1,
			goodB = 1,
		},
		ilvltextchangepoint = true,
		itemquality = false,
		characterskingradients = false,
		armorybgtype = "CLASS",
		armoryfontsize = 11,
		armorynamefontsize = 17,
		armoryvignette = true,
		armoryvignettealpha = 1,
		expandarmorybgalpha = 0.3,
		expandarmorycrest = false,
		armorycrestversion = 1,
		statcolors = false,
		bossemote = false,
		quests = false,
		queststatusbartexture = "ElvUI Norm1",
		questswowhead = false,
		questsettings = {
			texture = "Eltreum-Blank",
			sizex = 250,
			sizey = 3,
			lineshadow = true,
			customcolor = false,
			customr = 0.27,
			customg = 0.50,
			customb = 0.70,
			customcolortitle = false,
			customrtitle = 0.27,
			customgtitle = 0.50,
			custombtitle = 0.70,
			fontSize = 12,
			fontSizeHeader = 18,
			linebuttonsize = 28,
			linecustomcolor = false,
			linecustomcolor1r = 0.27,
			linecustomcolor1g = 0.50,
			linecustomcolor1b = 0.70,
			linecustomcolor2r = 0.2,
			linecustomcolor2g = 0.7,
			linecustomcolor2b = 1,
			questScale = 1,
			objectiveFrameHeight = 900,
			hideDash = false,
			hideCheck = false,
		},
		professions = false,
		colormodkey = false,
		classcolorcooldowns = false,
		zones = false,
		shadow = {
			enable = false,
			length = 3,
			customcolor = false,
			classcolor = false,
			r = 0.27,
			g = 0.50,
			b = 0.70,
			a = 1,
			raid = true,
			aura = false,
			ufaura = false,
			actionbars = false,
			nameplates = false, --healthbars
			npauras = false,
			npportraits = false,
			nppower = false,
			npcastbar = false,
			minimap = true,
			chat = true,
			bigwigs = true,
			unitframes = true,
			blizzard = true,
			tooltip = true,
			datatexts = true,
		},

		meetinghorn = false,
		pallypower = false,
		bigwigs = false,
		bigwigscustomcolor = false,
		bigwigscustomnormalr1 = 0.11,
		bigwigscustomnormalg1 = 0.30,
		bigwigscustomnormalb1 = 0.6,
		bigwigscustomnormalr2 = 0.71,
		bigwigscustomnormalg2 = 0.90,
		bigwigscustomnormalb2 = 1,
		bigwigscustomemphasizedr1 = 0.31,
		bigwigscustomemphasizedg1 = 0,
		bigwigscustomemphasizedb1 = 0,
		bigwigscustomemphasizedr2 = 0.91,
		bigwigscustomemphasizedg2 = 0.23,
		bigwigscustomemphasizedb2 = 0.23,
		details = false,
		detailsgradientname = true,
		detailsgradientnameshadow = false,
		detailstextureoverwrite = true,
		detailsembed = false,
		detailsembedooc = false,
		detailsembedhidden = true,
		detailsdelay = 1,
		detailsmode = "LIGHT",
		bugsack = false,
		clique = false,
		immersion = false,
		rarescanner = false,
		simulationcraft = false,
		warpdeplete = false,
		bagsync = false,
		hekili = false,
		omnicd = false,
		cell = false,
		cellhealthloss = false,
		dbm = false,
		auctionator = false,
		weakaurasoptions = false,

		hideABkeypress = false,
		tbctalents = false,
		expandedtalentscale = 1,
		stealtheffect = false,
		screenvignette = false,
		screenvignettealpha = 1,
		blizzframes = {
			hideerrorframe = false,
			raidbossframe = true,
			raidbossframefontsize = 14,
			hidealert = false,
			hidezone = false,
			hideboss = false,
			hideeventoaster = false,
			bossScale = 1,
		},
		instances = {
			enable = false,
			fontsize = 12,
			r = 0.90,
			g = 0.72,
			b = 0,
			redoffset = -0.2,
			greenoffset = -0.2,
			blueoffset = -0.2,

			classcolor = true,
			gradient = true,
			difficultycolors = true,
			DungeonNormal = "N.Dungeon",
			DungeonNormalColor = {
				r = 0.90,
				g = 0.72,
				b = 0,
			},
			DungeonHeroic = "H.Dungeon",
			DungeonHeroicColor = {
				r = 0.90,
				g = 0.72,
				b = 0,
			},
			Raid = "Raid",
			RaidColor = {
				r = 0.90,
				g = 0.72,
				b = 0,
			},
			Raid10 = "Raid (10)",
			Raid10Color = {
				r = 0.90,
				g = 0.72,
				b = 0,
			},
			Raid25 = "Raid (25)",
			Raid25Color = {
				r = 0.90,
				g = 0.72,
				b = 0,
			},
			MythicRaid = "Mythic Raid",
			MythicRaidColor = {
				r = 0.90,
				g = 0.72,
				b = 0,
			},
			RaidHeroic = "Heroic Raid",
			RaidHeroicColor = {
				r = 0.90,
				g = 0.72,
				b = 0,
			},
			Raid10Heroic = "Heroic Raid (10)",
			Raid10HeroicColor = {
				r = 0.90,
				g = 0.72,
				b = 0,
			},
			Raid25Heroic = "Heroic Raid (25)",
			Raid25HeroicColor = {
				r = 0.90,
				g = 0.72,
				b = 0,
			},
			RaidLFR = "LFR",
			RaidLFRColor = {
				r = 0.90,
				g = 0.72,
				b = 0,
			},
			DungeonMythic = "Mythic 0",
			DungeonMythicColor = {
				r = 0.90,
				g = 0.72,
				b = 0,
			},
			DungeonMythicPlus = "Mythic+",
			DungeonMythicPlusColor = {
				r = 0.90,
				g = 0.72,
				b = 0,
			},
			DungeonTimewalker = "TW.Dungeon",
			DungeonTimewalkerColor = {
				r = 0.90,
				g = 0.72,
				b = 0,
			},
			RaidTimewalker = "TW.Raid",
			RaidTimewalkerColor = {
				r = 0.90,
				g = 0.72,
				b = 0,
			},
			guild = "Guild",
			guildColor = {
				r = 0.90,
				g = 0.72,
				b = 0,
			},
			delve = "Delve",
			delveColor = {
				r = 0.90,
				g = 0.72,
				b = 0,
			},
			quest = "Quest",
			questColor = {
				r = 0.90,
				g = 0.72,
				b = 0,
			},
		},
		groupfinderSpecIcons = true,
		groupfinderSpecIconsType = "SPEC",
		groupfinderDungeonScore = true,
		groupfinderIconStyle = "TEXT",
		hidetalkinghead = false,
		playerdeath = false,
		playerdeathgta = false,
		playerdeathhardcore = true,
		--guildmemberdeathhardcore = true,
		playerdeathcustom = false,
		playerdeathcustomtext = "YOU DIED",
		doom = {
			enable = false,
			pet = true,
			fadeInTime = 0.3,
			fadeOutTime = 0.7,
			maxAlpha = 0.7,
			animScale = 1.5,
			iconSize = 75,
			holdTime = 0,
			showSpellName = false,
			graceperiod = 10,
			gracelimit = 0,
			tts = false,
			ttsvoice = nil,
			ttsvolume = 100,
			allowing = false,
			ignoring = true,
		},
		ilvltooltip = true,
		gradienttooltip = true,
		gradienttooltipoffset1 = -0.2,
		gradienttooltipoffset2 = 0.2,
		professionscale = 1,
		oldclasscolors = false,
		classicblueshaman = true,
	},

	cursors = {
		cursor = {
			enable = false,
			ring = 'Interface\\addons\\ElvUI_EltreumUI\\Media\\Textures\\Cursor\\ring3.tga',
			size = '-1',
			cooldown = false,
			cooldownsound = false,
			cooldownfile = "! - Metal Gear Solid",
			petcooldown = false,
			cooldownoffsetx = 0,
			cooldownoffsety = 0,
			fixlag = 1,
			combat = true,
		},
		cursorcast = {
			radius = 25,
			sublayer = 1,
			thickness = 5,
			classcolor = true,
			gradient = false,
			r = 0.27,
			g = 0.50,
			b = 0.70,
			a = 1,
		},
		cursorgcd = {
			radius = 20,
			sublayer = 0,
			thickness = 5,
			classcolor = false,
			r = 1,
			g = 1,
			b = 1,
			a = 1,
		},
		cursorcursor = {
			radius = 15,
			sublayer = 0,
			thickness = 5,
			combat = true,
			classcolor = false,
			r = 0.5,
			g = 0.5,
			b = 0.5,
			a = 1,
		},
	},

	nameplates = {
		nameplateOptions = {
			ClassColorGlow = false,
			ClassBorderNameplate = false,
			nameplatetexture = false,
			classbarautohide = false,
			targetclasstexture = false,
			enableHealthHeight = false,
			outofcombatHeight = 4,
			incombatHeight = 14,
			useelvuinpheight = false,
			targetmodel = false,
			CamDistanceScale = 2,
			ViewTranslationx = 0,
			ViewTranslationy = 0,
			Rotation = 0,
			modelalpha = 0.5,
			desaturation = 0,
			paused = false,
			restedoverlap = false,
			hideSwipe = false,
			hidedebuffsnontarget = false,
			hideaurasnoncombat = false,
			npglow = false,
		},
		nptextureversion = "V1",
		nameplatelevel = false,
		nameplatepower = {
			autoadjustposition = false,
			modeleffect = false,
			gradient = false,
			sizex = 131.8,
			sizey = 6,
			posy = 16,
			texture = "Eltreum-Elvui-Norm",
			font = "Kimberley",
			fontsize = 10,
			r = 0,
			g = 0,
			b = 0,
			a = 0.7,
		},
		friendlynameplatetoggle = {
			disablefriendly = false,
			friendlynames = false,
			hidefriendly = false,
		},
		auras = {
			enable = false,
			xOffset = 0,
			yOffset = 5,
		},
		classification = {
			enable = false,
			icontypeelite = "TYPE6",
			icontyperare = "TYPE10",
			icontyperareelite = "TYPE10",
			icontypeboss = "TYPE20",

			eliteR = 1,
			eliteG = 0.70,
			eliteB = 0,
			bossR = 1,
			bossG = 1,
			bossB = 1,
			rareR = 0.95,
			rareG = 1,
			rareB = 0,
			rareeliteR = 1,
			rareeliteG = 0.70,
			rareeliteB = 0,

			customelite = "",
			customboss = "",
			customrare = "",
			customrareelite = "",
		}
	},

	glow = {
		enable = false,
		enablepet = false,
		enabletotem = false,
		enableUFs = false,
		blizzard = false,
		pixel = false,
		autocast = false,
		procglow = false,
		gradient = false,

		totemtypecolor = true,
		totem1 = true,
		totem2 = true,
		totem3 = true,
		totem4 = true,

		colorclass = true,
		colorclasspet = true,
		colorclassnp = true,

		numberdebuff = 4,

		numberpixel = 9,
		frequencypixel = 1,
		lengthpixel = 3,
		thicknesspixel = 5,
		pixelxOffset = 5,
		pixelyOffset = 5,
		borderpixel = false,

		numberauto = 8,
		frequencyauto = 0.8,
		autoscale = 2,
		autoxOffset = 5,
		autoyOffset = 5,

		frequencyblizz = 0.5,

		glowcustomcolor = {
			r = 0.27,
			g = 0.50,
			b = 0.70,
		},
		glowcustomcolorpet = {
			r = 0.27,
			g = 0.50,
			b = 0.70,
		},
		glowcustomcolornp = {
			r = 0.27,
			g = 0.50,
			b = 0.70,
		},
		glowtotem1customcolor = {
			r = 0.78,
			g = 0.43,
			b = 0.30,
		},
		glowtotem2customcolor = {
			r = 0.43,
			g = 0.65,
			b = 0.33,
		},
		glowtotem3customcolor = {
			r = 0.39,
			g = 0.68,
			b = 0.80,
		},
		glowtotem4customcolor = {
			r = 0.62,
			g = 0.38,
			b = 0.94,
		},
		proc = {
			duration = 1,
			startAnim = true,
			frameLevel = 8,
			xOffset = 3,
			yOffset = 3,
		},
	},

	waypoints = {
		waypointetasetting = {
			enable = false,
			autopin = false,
			limitmaxdistance = false,
			distance = 700,
			classcolortext = false,
			textcolorR = 1,
			textcolorG = 1,
			textcolorB = 1,
			color = {
				enable = false,
				classcolor = true,
				r = 0.27,
				g = 0.50,
				b = 0.70,
			}
		},
		waytext = {
			enable = false,
		},
	},

	quests = {
		enable = false,
		rogueopen = false,
		arena = false,
		combatenable = false,
		autoaccept = false,
		acceptdaily = false,
		autoacceptinvert = false,
		questitems = false,
		questitemsbar1 = false,
		questitemsize = 36,
		questitemsizey = 36,
		showkeybind = true,
		questitemspacing = 2,
		questorientation = "HORIZONTAL",
		questitemsfade = false,
		anchor = true,
		mythicplus = false,
	},

	loot = {
		loottext = {
			quality = "0",
			enable = false,
			honor = true,
			currency = true,
			skill = false,
			pet = true,
			scale = 0.65,
			strata = "BACKGROUND",
			xOffset = 0,
			yOffset = 200,
			fontsetting = true,
			fontsettingdmg = false,
			fontLSMenable = false,
			fontLSM = "Kimberley",
			fontsize = 24,
			combatindicator = false,
			combatindicatorcustom = {
				enable = false,
				enter = "+COMBAT",
				entercolor = {
					r = 1,
					g = 0,
					b = 0,
				},
				leave = "-COMBAT",
				leavecolor = {
					r = 1,
					g = 1,
					b = 1,
				},
			},
		},
		fastloot = false,
		fastlootfilter = false,
		fastlootquality = '0',
		lootwishlistwarning = false,
		lootwishlistfilter = false,
		lootwishlistscreenshot = false,
		lootwishlistsoundenable = false,
		lootwishlistsound = "Warcraft 3 - Rokhan Be Happy",
		lootautoclose = false,
		confirmbop = false,
	},

	borders = {
		borders = false,
		texture = "Eltreum-Border-1",
		borderautoadjust = false,

		bordertest = false,

		classcolor = true,

		auraborder = true,
		aurasizex = 54,
		aurasizey = 54,
		debuffaurasizex = 54,
		debuffaurasizey = 54,
		aurastrata = "MEDIUM",
		auralevel = 4,

		auraborderuf = true,
		ufbuffsizex = 54,
		ufbuffsizey = 48,
		ufdebuffsizex = 53,
		ufdebuffsizey = 48,
		auraufstrata = "MEDIUM",
		aurauflevel = 4,
		ufaurasize = 13,

		chatborder = true,
		leftchatborderx = 432,
		leftchatbordery = 224,
		leftchatstrata = "MEDIUM",
		leftchatlevel = 3,
		rightchatborderx = 432,
		rightchatbordery = 224,
		rightchatstrata = "MEDIUM",
		rightchatlevel = 3,

		partyborders = true,
		partysizex = 222,
		partysizey = 98,
		partystrata = "LOW",
		partylevel = 20,

		--raid1
		raidborders = true,
		raidsizey = 65,
		raidsizex = 140,
		raidstrata = "MEDIUM",
		raidlevel = 3,

		raid2borders = true,
		raid2sizey = 65,
		raid2sizex = 140,
		raid2strata = "MEDIUM",
		raid2level = 3,

		--raid3
		raid40borders = true,
		raid40sizey = 63,
		raid40sizex = 140,
		raid40strata = "MEDIUM",
		raid40level = 3,

		playertargetsize = 20,
		playertargetcastsize = 20,
		petsize = 20,
		groupsize = 14,
		focussize = 20,
		bosssize = 20,
		minimapsize = 15,
		chatsize = 13,
		aurasize = 13,
		baredgesize = 13,

		powerbarborder = true,
		powerbarsize = 4,
		xpowerbar = 138.8,
		ypowerbar = 12,
		powerbarstrata = "MEDIUM",
		powerbarlevel = 3,

		minimapborder = true,
		minimapsizex = 226,
		minimapsizey = 247,
		minimapstrata = "MEDIUM",
		minimaplevel = 2,

		petborder = true,
		petsizex = 192,
		petsizey = 66,
		petstrata = "LOW",
		petlevel = 20,

		playerborder = true,
		xplayer = 302,
		yplayer = 75,
		playerstrata = "LOW",
		playerlevel = 20,

		playercastborder = true,
		xplayercast = 272,
		yplayercast = 58,
		playercaststrata = "MEDIUM",
		playercastlevel = 20,

		targetborder = true,
		xtarget = 302.8,
		ytarget = 75,
		targetstrata = "LOW",
		targetlevel = 20,

		targetcastborder = true,
		xcasttarget = 272,
		ycasttarget = 58,
		targetcaststrata = "MEDIUM",
		targetcastlevel = 20,

		targettargetborder = true,
		xtargettarget = 132.8,
		ytargettarget = 75,
		targettargetstrata = "LOW",
		targettargetlevel = 20,

		focusborder = true,
		xfocus = 224,
		yfocus = 72,
		focusstrata = "LOW",
		focuslevel = 20,

		focuspowerborder = true,
		xfocuspower = 210,
		yfocuspower = 46,
		focuspowerstrata = "MEDIUM",
		focuspowerlevel = 20,

		focuscastborder = true,
		xcastfocus = 365,
		ycastfocus = 62,
		focuscaststrata = "MEDIUM",
		focuscastlevel = 20,

		focustargetborder = true,
		xfocustarget = 223,
		yfocustarget = 58,
		focustargetstrata = "LOW",
		focustargetlevel = 3,

		bossborder = true,
		xboss = 250,
		yboss = 87,
		bossstrata = "MEDIUM",
		bosslevel = 3,

		bar1borders = true,
		bar1xborder = 65,
		bar1yborder = 56,
		bar1strata = "LOW",
		bar1level = 3,

		bar2borders = true,
		bar2xborder = 56,
		bar2yborder = 50,
		bar2strata = "LOW",
		bar2level = 3,

		bar3borders = true,
		bar3xborder = 56,
		bar3yborder = 50,
		bar3strata = "LOW",
		bar3level = 3,

		bar4borders = true,
		bar4xborder = 56,
		bar4yborder = 50,
		bar4strata = "LOW",
		bar4level = 3,

		bar5borders = true,
		bar5xborder = 56,
		bar5yborder = 50,
		bar5strata = "LOW",
		bar5level = 3,

		bar6borders = true,
		bar6xborder = 52,
		bar6yborder = 44,
		bar6strata = "LOW",
		bar6level = 3,

		totembar = true,
		totemxborder = 51,
		totemyborder = 51,
		totemedgesize = 13,
		totemstrata = "LOW",
		totemlevel = 3,

		stanceborders = true,
		stancexborder = 49,
		stanceyborder = 42,
		stanceedgesize = 13,
		stancestrata = "LOW",
		stancelevel = 3,

		petactionborders = true,
		petactionxborder = 49,
		petactionyborder = 44,
		petactionedgesize = 13,
		petabstrata = "LOW",
		petablevel = 3,

		alternativeclassbar = true,
		alternativeclassbarxborder = 208,
		alternativeclassbaryborder = 42,
		alternativeclassbarstrata = "MEDIUM",
		alternativeclassbarlevel = 3,

		staggerclassbar = true,
		staggerclassbarxborder = 211,
		staggerclassbaryborder = 41,
		staggerclassbarstrata = "MEDIUM",
		staggerclassbarlevel = 3,

		comboclassbar = true,
		combosizex = 71, --65
		combosizey = 44, --44
		combostrata = "MEDIUM",
		combolevel = 3,

		playerpower = true,
		playerpowersizex = 165, --65
		playerpowersizey = 47, --44
		playerpowerstrata = "MEDIUM",
		playerpowerlevel = 3,

		targetpower = true,
		targetpowersizex = 165,
		targetpowersizey = 47,
		targetpowerstrata = "MEDIUM",
		targetpowerlevel = 3,

		targettargetpower = true,
		targettargetpowersizex = 123,
		targettargetpowersizey = 47,
		targettargetpowerstrata = "MEDIUM",
		targettargetpowerlevel = 3,

		databarsize = 15,

		experiencebar = true,
		experiencebarsizex = 522,
		experiencebarsizey = 37,
		experiencebarstrata = "HIGH",
		experiencebarlevel = 3,

		reputationbar = true,
		reputationbarsizex = 522,
		reputationbarsizey = 37,
		reputationbarstrata = "HIGH",
		reputationbarlevel = 3,

		threatbar = true,
		threatbarsizex = 473,
		threatbarsizey = 44,
		threatbarstrata = "HIGH",
		threatbarlevel = 3,

		altpowerbar = true,
		altpowerbarsizex = 283,
		altpowerbarsizey = 52,
		altpowerbarsize = 20,
		altpowerbarstrata = "HIGH",
		altpowerbarlevel = 3,

		tankassistborders = true,
		tankassistsizex = 150,
		tankassistsizey = 58,
		tankassistsize = 20,
		tankassiststrata = "HIGH",
		tankassistlevel = 3,

		tooltipborders = true,
		tooltipsizex = 32.1,
		tooltipsizey = 32.1,
		tooltipsize = 20,
		tooltipstrata = "TOOLTIP",
		tooltiplevel = 50,

		bordercolors = {
			r = 0.27,
			g = 0.50,
			b = 0.70,
			a = 1,
		},
	},

	unitframes = {
		thinmode = false,
		thinmodeaurabars = false,
		UFmodifications = true,
		UForientation = "HORIZONTAL",
		lightmode = false,
		uftextureversion = "V1",
		alternativegroups = false,
		darkmode = false,
		--modetexture = false,
		darkpowercolor = false,
		blizzardresticon = true,
		blizzardresticonclasscolor = false,
		blizzardresticongradient = true,
		portrait = {
			enable = false,
			shadow = true,
			gradient = true,
			player = {
				enable = true,
				style = "SYMBOLS",
				type = "BLIZZARD",
				size = 92,
				position = {
					align = "LEFT",
					x = -42,
					y = 18,
				},
				custom = false,
				edge = true,
				rare = false,
				scale = -0.15,
				customcircle = false,
				reversegradient = false,
				defaultgradient = false,
				customcolor = false,
				color = {
					r = 0.27,
					g = 0.50,
					b = 0.70,
				},
				background = true,
				backgroundcolor = {
					r = 0.07,
					g = 0.07,
					b = 0.07,
				},
			},
			pet = {
				enable = true,
				style = "SYMBOLS",
				type = "BLIZZARD",
				size = 92,
				position = {
					align = "LEFT",
					x = -42,
					y = 18,
				},
				custom = false,
				edge = true,
				rare = false,
				scale = -0.15,
				customcircle = false,
				reversegradient = false,
				defaultgradient = false,
				customcolor = false,
				color = {
					r = 0.27,
					g = 0.50,
					b = 0.70,
				},
				background = true,
				backgroundcolor = {
					r = 0.07,
					g = 0.07,
					b = 0.07,
				},
			},
			target = {
				enable = true,
				style = "SYMBOLS",
				type = "BLIZZARD",
				size = 92,
				position = {
					align = "RIGHT",
					x = 42,
					y = 18,
				},
				custom = false,
				edge = true,
				rare = false,
				scale = -0.15,
				customcircle = false,
				reversegradient = true,
				defaultgradient = false,
				customcolor = false,
				color = {
					r = 0.27,
					g = 0.50,
					b = 0.70,
				},
				background = true,
				backgroundcolor = {
					r = 0.07,
					g = 0.07,
					b = 0.07,
				},
			},
			party = {
				enable = true,
				style = "SYMBOLS",
				type = "BLIZZARD",
				size = 92,
				position = {
					align = "LEFT",
					x = -42,
					y = 1,
				},
				custom = false,
				edge = true,
				rare = false,
				scale = -0.15,
				customcircle = false,
				reversegradient = false,
				defaultgradient = false,
				customcolor = false,
				color = {
					r = 0.27,
					g = 0.50,
					b = 0.70,
				},
				background = true,
				backgroundcolor = {
					r = 0.07,
					g = 0.07,
					b = 0.07,
				},
			},
			targettarget = {
				enable = true,
				style = "SYMBOLS",
				type = "BLIZZARD",
				size = 92,
				position = {
					align = "RIGHT",
					x = 42,
					y = 18,
				},
				custom = false,
				edge = true,
				rare = false,
				scale = -0.15,
				customcircle = false,
				reversegradient = true,
				defaultgradient = false,
				customcolor = false,
				color = {
					r = 0.27,
					g = 0.50,
					b = 0.70,
				},
				background = true,
				backgroundcolor = {
					r = 0.07,
					g = 0.07,
					b = 0.07,
				},
			},
			focus = {
				enable = true,
				style = "SYMBOLS",
				type = "BLIZZARD",
				size = 88,
				position = {
					align = "LEFT",
					x = -40,
					y = 19,
				},
				custom = false,
				edge = true,
				rare = false,
				scale = -0.15,
				customcircle = false,
				reversegradient = false,
				defaultgradient = false,
				customcolor = false,
				color = {
					r = 0.27,
					g = 0.50,
					b = 0.70,
				},
				background = true,
				backgroundcolor = {
					r = 0.07,
					g = 0.07,
					b = 0.07,
				},
			},
			focustarget = {
				enable = true,
				style = "SYMBOLS",
				type = "BLIZZARD",
				size = 57,
				position = {
					align = "LEFT",
					x = -30,
					y = 11,
				},
				custom = false,
				edge = true,
				rare = false,
				scale = -0.15,
				customcircle = false,
				reversegradient = false,
				defaultgradient = false,
				customcolor = false,
				color = {
					r = 0.27,
					g = 0.50,
					b = 0.70,
				},
				background = true,
				backgroundcolor = {
					r = 0.07,
					g = 0.07,
					b = 0.07,
				},
			},
		},
		infopanelontop = false,
		infopanelontopallframes = false,
		greybackground = false,
		gradientmode = {
			enable = false,
			orientation = "HORIZONTAL",
			orientationpower = "HORIZONTAL",
			texture = "Eltreum-Blank",
			useUFtexture = false,
			customcolor = false,

			bgfade = 0.05,

			classcolorplayercastbar = false,
			classcolortargetcastbar = false,

			enableaurabars = false,
			enablebackdrop = false,

			gradientXP = false,
			gradientXPdirection = "HORIZONTAL",
			gradientXPcolors ={
				r = 0.8,
				g = 0.4,
				b = 1,
			},
			gradientReputation = false,
			gradientReputationcolors = {
				r = 0,
				g = 0,
				b = 0.4,
			},
			gradientHonor = false,
			gradientHonorcolors = {
				r = -0.2,
				g = -0.4,
				b = -0.4,
			},
			gradientAltPower = false,
			gradientAltPowercolors = {
				r = -0.2,
				g = -0.2,
				b = -0.2,
			},

			enableplayer = true,
			enabletarget = true,
			reversetarget = true,
			reversefocus = false,
			enabletargettarget = true,
			enabletargettargettarget = true,
			enablefocus = true,
			enablefocustarget = true,
			enableboss = true,
			enablearena = true,
			enablegroupunits = true,
			usedeadbackdrop = false,
			classcolorbackdrop = false,

			--extra for new function
			enablepet = true,
			enableplayercastbar = false,
			enableplayercastbarnoninterruptible = false,
			enableplayercastbarinterrupted = false,

			playercastbarR1 = 0,
			playercastbarR2 = 0.67,
			playercastbarG1 = 0.6,
			playercastbarG2 = 0.94,
			playercastbarB1 = 1,
			playercastbarB2 = 1,

			playercastbarR1noninterruptible = 1,
			playercastbarR2noninterruptible = 1,
			playercastbarB1noninterruptible = 0,
			playercastbarB2noninterruptible = 0.290,
			playercastbarG1noninterruptible = 0.349,
			playercastbarG2noninterruptible = 0.196,

			playercastbarR1noninterruptiblecustom = 1,
			playercastbarR2noninterruptiblecustom = 1,
			playercastbarB1noninterruptiblecustom = 0,
			playercastbarB2noninterruptiblecustom = 0.290,
			playercastbarG1noninterruptiblecustom = 0.349,
			playercastbarG2noninterruptiblecustom = 0.196,

			playercastbarR1interrupted = 0.6,
			playercastbarR2interrupted = 0.2,
			playercastbarB1interrupted = 0.6,
			playercastbarB2interrupted = 0.2,
			playercastbarG1interrupted = 0.6,
			playercastbarG2interrupted = 0.2,

			playercastbarR1interruptedcustom = 0.6,
			playercastbarR2interruptedcustom = 0.2,
			playercastbarB1interruptedcustom = 0.6,
			playercastbarB2interruptedcustom = 0.2,
			playercastbarG1interruptedcustom = 0.6,
			playercastbarG2interruptedcustom = 0.2,

			enabletargetcastbar = false,
			enabletargetcastbarnoninterruptible = false,
			enabletargetcastbarinterrupted = false,

			targetcastbarR1 = 0,
			targetcastbarR2 = 0.67,
			targetcastbarG1 = 0.6,
			targetcastbarG2 = 0.94,
			targetcastbarB1 = 1,
			targetcastbarB2 = 1,

			targetcastbarR1custom = 0,
			targetcastbarR2custom = 0.67,
			targetcastbarG1custom = 0.6,
			targetcastbarG2custom = 0.94,
			targetcastbarB1custom = 1,
			targetcastbarB2custom = 1,

			targetcastbarR1noninterruptible = 1,
			targetcastbarR2noninterruptible = 1,
			targetcastbarB1noninterruptible = 0,
			targetcastbarB2noninterruptible = 0.290,
			targetcastbarG1noninterruptible = 0.349,
			targetcastbarG2noninterruptible = 0.196,

			targetcastbarR1noninterruptiblecustom = 1,
			targetcastbarR2noninterruptiblecustom = 1,
			targetcastbarB1noninterruptiblecustom = 0,
			targetcastbarB2noninterruptiblecustom = 0.290,
			targetcastbarG1noninterruptiblecustom = 0.349,
			targetcastbarG2noninterruptiblecustom = 0.196,

			targetcastbarR1interrupted = 0.6,
			targetcastbarR2interrupted = 0.2,
			targetcastbarB1interrupted = 0.6,
			targetcastbarB2interrupted = 0.2,
			targetcastbarG1interrupted = 0.6,
			targetcastbarG2interrupted = 0.2,

			targetcastbarR1interruptedcustom = 0.6,
			targetcastbarR2interruptedcustom = 0.2,
			targetcastbarB1interruptedcustom = 0.6,
			targetcastbarB2interruptedcustom = 0.2,
			targetcastbarG1interruptedcustom = 0.6,
			targetcastbarG2interruptedcustom = 0.2,

			targetcastbarreactioninterruptable = false,

			targetcastbarR1interruptable = 1,
			targetcastbarR2interruptable = 1,
			targetcastbarB1interruptable = 0,
			targetcastbarB2interruptable = 0,
			targetcastbarG1interruptable = 0.81,
			targetcastbarG2interruptable = 0.59,

			targetcastbarR1interruptablecustom = 1,
			targetcastbarR2interruptablecustom = 1,
			targetcastbarB1interruptablecustom = 0,
			targetcastbarB2interruptablecustom = 0,
			targetcastbarG1interruptablecustom = 0.81,
			targetcastbarG2interruptablecustom = 0.59,

			druidcustomcolorR1 = 1,
			druidcustomcolorR2 = 1,
			druidcustomcolorG1 = 0.239,
			druidcustomcolorG2 = 0.486,
			druidcustomcolorB1 = 0.007,
			druidcustomcolorB2 = 0.039,

			huntercustomcolorR1 = 0.403,
			huntercustomcolorR2 = 0.670,
			huntercustomcolorG1 = 0.537,
			huntercustomcolorG2 = 0.929,
			huntercustomcolorB1 = 0.223,
			huntercustomcolorB2 = 0.309,

			paladincustomcolorR1 = 1,
			paladincustomcolorR2 = 0.956,
			paladincustomcolorG1 = 0.266,
			paladincustomcolorG2 = 0.549,
			paladincustomcolorB1 = 0.537,
			paladincustomcolorB2 = 0.729,

			magecustomcolorR1 = 0,
			magecustomcolorR2 = 0.490,
			magecustomcolorG1 = 0.333,
			magecustomcolorG2 = 0.870,
			magecustomcolorB1 = 0.537,
			magecustomcolorB2 = 1,

			roguecustomcolorR1 = 1,
			roguecustomcolorR2 = 1,
			roguecustomcolorG1 = 0.686,
			roguecustomcolorG2 = 0.831,
			roguecustomcolorB1 = 0,
			roguecustomcolorB2 = 0.254,

			priestcustomcolorR1 = 0.356,
			priestcustomcolorR2 = 0.988,
			priestcustomcolorG1 = 0.356,
			priestcustomcolorG2 = 0.988,
			priestcustomcolorB1 = 0.356,
			priestcustomcolorB2 = 0.988,

			deathknightcustomcolorR1 = 0.498,
			deathknightcustomcolorR2 = 1,
			deathknightcustomcolorG1 = 0.074,
			deathknightcustomcolorG2 = 0.184,
			deathknightcustomcolorB1 = 0.149,
			deathknightcustomcolorB2 = 0.239,

			demonhuntercustomcolorR1 = 0.364,
			demonhuntercustomcolorR2 = 0.745,
			demonhuntercustomcolorG1 = 0.137,
			demonhuntercustomcolorG2 = 0.192,
			demonhuntercustomcolorB1 = 0.572,
			demonhuntercustomcolorB2 = 1,

			shamancustomcolorR1 = 0,
			shamancustomcolorR2 = 0,
			shamancustomcolorG1 = 0.258,
			shamancustomcolorG2 = 0.439,
			shamancustomcolorB1 = 0.509,
			shamancustomcolorB2 = 0.870,

			warlockcustomcolorR1 = 0.262,
			warlockcustomcolorR2 = 0.662,
			warlockcustomcolorG1 = 0.266,
			warlockcustomcolorG2 = 0.392,
			warlockcustomcolorB1 = 0.466,
			warlockcustomcolorB2 = 0.784,

			warriorcustomcolorR1 = 0.427,
			warriorcustomcolorR2 = 0.564,
			warriorcustomcolorG1 = 0.137,
			warriorcustomcolorG2 = 0.431,
			warriorcustomcolorB1 = 0.090,
			warriorcustomcolorB2 = 0.247,

			monkcustomcolorR1 = 0.015,
			monkcustomcolorR2 = 0,
			monkcustomcolorG1 = 0.607,
			monkcustomcolorG2 = 1,
			monkcustomcolorB1 = 0.368,
			monkcustomcolorB2 = 0.588,

			evokercustomcolorR1 = 0.196,
			evokercustomcolorR2 = 0.2,
			evokercustomcolorG1 = 0.466,
			evokercustomcolorG2 = 0.576,
			evokercustomcolorB1 = 0.537,
			evokercustomcolorB2 = 0.498,

			npcfriendlyR1 = 0.309,
			npcfriendlyR2 = 0.341,
			npcfriendlyG1 = 0.850,
			npcfriendlyG2 = 0.627,
			npcfriendlyB1 = 0.2,
			npcfriendlyB2 = 0.407,

			npcneutralR1 = 0.815,
			npcneutralG1 = 1,
			npcneutralB1 = 0,
			npcneutralR2 = 1,
			npcneutralG2 = 0.858,
			npcneutralB2 = 0.207,

			npcunfriendlyR1 = 0.843,
			npcunfriendlyG1 = 0.301,
			npcunfriendlyB1 = 0,
			npcunfriendlyR2 = 0.831,
			npcunfriendlyG2 = 0.458,
			npcunfriendlyB2 = 0,

			npchostileR1 = 1,
			npchostileR2 = 1,
			npchostileG1 = 0.090,
			npchostileG2 = 0,
			npchostileB1 = 0,
			npchostileB2 = 0.549,

			--threat stuff for np
			npenable = false,
			nporientation = "VERTICAL",
			npcustomcolor = false,

			stylefilterr = -0.4,
			stylefilterg = -0.4,
			stylefilterb = -0.4,

			goodthreatR1 = 0.278,
			goodthreatR2 = 0.952,
			goodthreatG1 = 1,
			goodthreatG2 = 0.999,
			goodthreatB1 = 0,
			goodthreatB2 = 0,

			badthreatR1 = 1,
			badthreatR2 = 0.823,
			badthreatG1 = 0.176,
			badthreatG2 = 0,
			badthreatB1 = 0.176,
			badthreatB2 = 0.349,

			goodthreattransitionR1 = 1,
			goodthreattransitionR2 = 1,
			goodthreattransitionG1 = 0.996,
			goodthreattransitionG2 = 0.733,
			goodthreattransitionB1 = 0.2,
			goodthreattransitionB2 = 0,

			badthreattransitionR1 = 1,
			badthreattransitionR2 = 1,
			badthreattransitionG1 = 0.392,
			badthreattransitionG2 = 0.984,
			badthreattransitionB1 = 0.2,
			badthreattransitionB2 = 0,

			offtankR1 = 0.729,
			offtankR2 = 0.341,
			offtankG1 = 0.2,
			offtankG2 = 0,
			offtankB1 = 1,
			offtankB2 = 1,

			badthreattransitionofftankR1 = 0.709,
			badthreattransitionofftankG1 = 0.431,
			badthreattransitionofftankB1 = 0.270,
			badthreattransitionofftankR2 = 0.901,
			badthreattransitionofftankG2 = 0.152,
			badthreattransitionofftankB2 = 0,

			goodthreattransitionofftankR1 = 0.309,
			goodthreattransitionofftankR2 = 0,
			goodthreattransitionofftankG1 = 0.450,
			goodthreattransitionofftankG2 = 1,
			goodthreattransitionofftankB1 = 0.631,
			goodthreattransitionofftankB2 = 0.709,

			tappedR1 = 1,
			tappedG1 = 1,
			tappedB1 = 1,
			tappedR2 = 0,
			tappedG2 = 0,
			tappedB2 = 0,

			enablepower = false,
			enablepowercustom = false,
			enableclassbar = false,

			manaR1 = 0.49,
			manaG1 = 0.71,
			manaB1 = 1,
			manaR2 = 0.29,
			manaG2 = 0.26,
			manaB2 = 1,

			rageR1 = 1,
			rageG1 = 0.32,
			rageB1 = 0.32,
			rageR2 = 1,
			rageG2 = 0,
			rageB2 = 0.13,

			focusR1 = 1,
			focusG1 = 0.50,
			focusB1 = 0.25,
			focusR2 = 0.71,
			focusG2 = 0.22,
			focusB2 = 0.07,

			energyR1 = 1,
			energyG1 = 0.97,
			energyB1 = 0.54,
			energyR2 = 1,
			energyG2 = 0.70,
			energyB2 = 0.07,

			runicpowerR1 = 0,
			runicpowerG1 = 0.82,
			runicpowerB1 = 1,
			runicpowerR2 = 0,
			runicpowerG2 = 0.40,
			runicpowerB2 = 1,

			lunarpowerR1 = 0.30,
			lunarpowerG1 = 0.52,
			lunarpowerB1 = 0.90,
			lunarpowerR2 = 0.12,
			lunarpowerG2 = 0.36,
			lunarpowerB2 = 0.90,

			altpowerR1 = 0.20,
			altpowerG1 = 0.40,
			altpowerB1 = 0.8,
			altpowerR2 = 0.25,
			altpowerG2 = 0.51,
			altpowerB2 = 1,

			maelstromR1 = 0,
			maelstromG1 = 0.50,
			maelstromB1 = 1,
			maelstromR2 = 0,
			maelstromG2 = 0.11,
			maelstromB2 = 1,

			insanityR1 = 0.50,
			insanityG1 = 0.25,
			insanityB1 = 1,
			insanityR2 = 0.70,
			insanityG2 = 0,
			insanityB2 = 1,

			furyR1 = 0.79,
			furyG1 = 0.26,
			furyB1 = 1,
			furyR2 = 1,
			furyG2 = 0,
			furyB2 = 0.95,

			painR1 = 1,
			painG1 = 0.61,
			painB1 = 0,
			painR2 = 1,
			painG2 = 0.30,
			painB2 = 0,

			backdropR1 = 0,
			backdropG1 = 0,
			backdropB1 = 0,
			backdropR2 = 0.19,
			backdropG2 = 0.19,
			backdropB2 = 0.19,
		},
		ufcustomtexture = {
			enable = false,
			classdetect = false,
			noclasstexture = false,
			castbartexture = "Eltreum-Blank",
			backdroptexture = "Eltreum-Blank",
			backdropalpha = 1,
			healthalpha = 0.7,
			backdrophidden = false,
			targettexture = "Eltreum-Blank",
			playertexture = "Eltreum-Blank",
			targettargettexture = "Eltreum-Blank",
			pettexture = "Eltreum-Blank",
			targettargettargettexture = "Eltreum-Blank",
			bosstexture = "Eltreum-Blank",

			focustexture = "Eltreum-Blank",
			deathknighttexture = "Eltreum-Class-DeathKnightV2",
			demonhuntertexture = "Eltreum-Class-DemonHunterV2",
			evokertexture = "Eltreum-Class-EvokerV2",
			druidtexture = "Eltreum-Class-DruidV2",
			huntertexture = "Eltreum-Class-HunterV2",
			magetexture = "Eltreum-Class-MageV2",
			monktexture = "Eltreum-Class-MonkV2",
			paladintexture = "Eltreum-Class-PaladinV2",
			priesttexture = "Eltreum-Class-PriestV2",
			roguetexture = "Eltreum-Class-RogueV2",
			shamantexture = "Eltreum-Class-ShamanV2",
			warlocktexture = "Eltreum-Class-WarlockV2",
			warriortexture = "Eltreum-Class-WarriorV2",
			npcfriendly = "Eltreum-Class-HunterV2",
			npcneutral = "Eltreum-Class-RogueV2",
			npcunfriendly = "Eltreum-Class-DruidV2",
			npchostile = "Eltreum-Class-DeathKnightV2",
			tappedtexture = "Eltreum-TappedV2",
			raidtexture = "Eltreum-Blank",
			partytexture = "Eltreum-Blank",
			arenatexture = "Eltreum-Blank",

			enableHealComm = true,
		},
		sparkcustomcolor ={
			enable = false,
			enableaurabars = false,
			texture = 'Eltreum-Blank',
			--texture = 'Eltreum-Fade',
			r = 0.80,
			g = 0.80,
			b = 0.10,
			a = 1,
			empoweringr = 0,
			empoweringg = 1,
			empoweringb = 1,
			--width = 20,
			width = 3,
		},
		models = {
			castbar = false,
			unitframe = false,
			insideHP = false,
			ufalpha = 0.3,
			ufalphadark = 0.5,
			ufdesaturation = 0,
			modeltype = "CLASS",
			custommodel = 165575,
			custommodelclassic = "spells/arcanebreath.m2",
			modeltypecast = "DEFAULT",
			custommodelcast = 165821,
			custommodelclassiccast = "spells/corruption_impactdot_med_base.m2",
			powerbar = false,
			modeltypepower = "DEFAULT",
			custommodelpower = 1715069,
			custommodelclassicpower = "spells/arcanepower_state_chest.m2",
		},
		arenabuffs = false,
		bgunitframes = false,
		arenaunitframes = false,
		portraitfix = false,
		portraitfixoffset = true,
		portraitdead = true,
		blizzardraidframes = true,
		classcombaticons = false,
	},

	otherstuff = {
		eltruismroleicons = false,
		eltruismroleiconscustom = false,
		eltruismroleiconscustomtank = "",
		eltruismroleiconscustomhealer = "",
		eltruismroleiconscustomdps = "",
		roleiconstype = 'ELTRUISM',
		eltruismroleiconsdisabledps = false,

		eltruismleadericons = false,
		leadericonstype = "1",
		eltruismleadericonscustom = "",

		eltruismassisticons = false,
		assisticonstype = "1",
		eltruismassisticonscustom = "",

		eltruismlootericons = false,
		lootericonstype = "1",
		eltruismlootericonscustom = "",

		hpstatusdeadicon = "5",
		hpstatusdcicon = "2",
		deadtagicon = "5",
		ghosttagicon = "1",
		dctagicon = "2",

		gamemenu = false,
		afklogo = true,
		afklogoeltruism = true,
		mailsoundenable = false,
		mailsoundtype = "sharedmedia",
		mailsoundttstext = "You've got mail",
		mailsound = "Interface-10",
		mailsoundttsvoice = nil,
		mailsoundttsvoicevolume = 100,
		mailAnimation = true,
		worldtextscale = 1,
		screenshot = false,
		blizzcombattext = false,
		blizzcombatmana = false,
		mapcombathide = false,
		mapcombathideadjustaura = true,
		worldmapscale = true,
		worldmapscalevalue = 1,
		rightdatatextcombatshow = false,
		leftdatatextcombatshow = false,
		dynamicxpbar = false,
		delete = false,
		mpluskeys = false,
		ABlikeWA = false,
		bres = false,
		dynamicdatatext = false,
		--floatingrep = false,
		partyraiddeath = {
			enable = false,
			bgdisable = false,
			playerdeathsound = "bruh",
		},
		afkmusic = {
			enable = false,
			racial = true,
			playerclass = false,
		},
		fonts = {
			playerfont = "Kimberley"
		},
		minimapcardinaldirections = {
			enable = false,
			colors = {
				classcolor = true,
				r = 1,
				g = 1,
				b = 1,
			},
			offset = 23,
			fontsize = 12,
			rotate = false,
			circle = false,
		},
		archeology = {
			archeologyfontsize = 12,
			archeologyfontoffsetx = 0,
			archeologyfontoffsety = 0,
			r1 = 0.70,
			g1 = 0.20,
			b1 = 0,
			r2 = 0.85,
			g2 = 0.3,
			b2 = 0.3,
			sizex = 188,
			sizey = 9,
		},
		taxiscale = 1,
		bagscale = 1,
		bankscale = 1,
		lootscale = 1,
		mirrorscale = 1,
		mirrorx = 200,
		mirrory = 18,
		colorbg = false,
		musicshuffle = false,
		datatextteleport = "Hearthstone",
		datatextteleporttype = "ITEM",
		datatextclasscolorbar = true,
		datatextclasscolorbaralpha = 0.5,
		datatextclasscolor = {
			custom = false,
			r = 0.27,
			g = 0.50,
			b = 0.70,
		},
		bagProfessionIcons = false,
	},
}
