local ElvUI_EltreumUI, E, L, V, P, G = unpack(select(2, ...))

-- Floating Combat Text profile setup
function ElvUI_EltreumUI:GetFCTProfile()
	ElvFCT = {
		["nameplates"] = {
			["enable"] = true,
			["frames"] = {
				["Player"] = {
					["fontSize"] = 16,
					["iconX"] = -5,
					["enable"] = true,
					["prefix"] = "",
					["advanced"] = {
						["OffsetY"] = 20,
					},
					["showIcon"] = true,
					["mode"] = "LS",
					["cycleColors"] = false,
					["showHots"] = true,
					["alternateIcon"] = true,
					["font"] = "Kimberley",
					["spellY"] = 20,
					["critFontSize"] = 32,
					["shakeDuration"] = 0.4,
					["numberStyle"] = "BLIZZARD",
					["critFont"] = "Kimberley",
					["followSize"] = true,
					["textShake"] = false,
				},
				["EnemyNPC"] = {
					["enable"] = true,
					["advanced"] = {
						["OffsetY"] = 100,
					},
					["followSize"] = true,
					["textShake"] = false,
					["isTarget"] = false,
					["fontSize"] = 16,
					["cycleColors"] = false,
					["prefix"] = "",
					["font"] = "Kimberley",
					["showDots"] = true,
					["critFontSize"] = 60,
					["shakeDuration"] = 0.4,
					["numberStyle"] = "BLIZZARD",
					["spellY"] = 100,
					["critFont"] = "Kimberley",
				},
				["FriendlyPlayer"] = {
					["enable"] = true,
					["advanced"] = {
						["OffsetY"] = 20,
					},
					["isTarget"] = false,
					["fontSize"] = 16,
					["cycleColors"] = false,
					["showHots"] = true,
					["prefix"] = "",
					["font"] = "Kimberley",
					["critFontSize"] = 32,
					["shakeDuration"] = 0.4,
					["numberStyle"] = "BLIZZARD",
					["spellY"] = 20,
					["critFont"] = "Kimberley",
					["followSize"] = true,
					["textShake"] = false,
				},
				["EnemyPlayer"] = {
					["enable"] = true,
					["advanced"] = {
						["OffsetY"] = 100,
					},
					["followSize"] = true,
					["textShake"] = false,
					["isTarget"] = false,
					["fontSize"] = 16,
					["cycleColors"] = false,
					["prefix"] = "",
					["font"] = "Kimberley",
					["showDots"] = true,
					["critFontSize"] = 60,
					["shakeDuration"] = 0.4,
					["numberStyle"] = "BLIZZARD",
					["spellY"] = 100,
					["critFont"] = "Kimberley",
				},
				["FriendlyNPC"] = {
					["enable"] = true,
					["advanced"] = {
						["OffsetY"] = 20,
					},
					["isTarget"] = false,
					["fontSize"] = 16,
					["cycleColors"] = false,
					["showHots"] = true,
					["prefix"] = "",
					["font"] = "Kimberley",
					["critFontSize"] = 32,
					["shakeDuration"] = 0.4,
					["numberStyle"] = "BLIZZARD",
					["spellY"] = 20,
					["critFont"] = "Kimberley",
					["followSize"] = true,
					["textShake"] = false,
				},
			},
		},
		["unitframes"] = {
			["enable"] = true,
			["frames"] = {
				["Tank"] = {
					["enable"] = false,
					["prefix"] = "",
					["advanced"] = {
						["OffsetX"] = 0,
						["OffsetY"] = 0,
					},
					["fontSize"] = 16,
					["showIcon"] = true,
					["cycleColors"] = false,
					["isPlayer"] = false,
					["showHots"] = true,
					["showDots"] = true,
					["showName"] = false,
					["spellY"] = 0,
					["showPet"] = false,
					["critFontSize"] = 32,
					["shakeDuration"] = 0.4,
					["font"] = "Kimberley",
					["critFont"] = "Kimberley",
					["followSize"] = true,
					["textShake"] = false,
				},
				["Boss"] = {
					["enable"] = false,
					["prefix"] = "",
					["advanced"] = {
						["OffsetX"] = 0,
						["OffsetY"] = 0,
					},
					["fontSize"] = 16,
					["showIcon"] = true,
					["cycleColors"] = false,
					["isPlayer"] = false,
					["showHots"] = true,
					["showDots"] = true,
					["showName"] = false,
					["spellY"] = 0,
					["showPet"] = false,
					["critFontSize"] = 32,
					["shakeDuration"] = 0.4,
					["font"] = "Kimberley",
					["critFont"] = "Kimberley",
					["followSize"] = true,
					["textShake"] = false,
				},
				["Focus"] = {
					["enable"] = false,
					["prefix"] = "",
					["advanced"] = {
						["OffsetX"] = 0,
						["OffsetY"] = 0,
					},
					["fontSize"] = 16,
					["showIcon"] = true,
					["cycleColors"] = false,
					["isPlayer"] = false,
					["showHots"] = true,
					["showDots"] = true,
					["showName"] = false,
					["spellY"] = 0,
					["showPet"] = false,
					["critFontSize"] = 32,
					["shakeDuration"] = 0.4,
					["font"] = "Kimberley",
					["critFont"] = "Kimberley",
					["followSize"] = true,
					["textShake"] = false,
				},
				["Target"] = {
					["enable"] = true,
					["prefix"] = "",
					["advanced"] = {
						["OffsetX"] = 0,
						["OffsetY"] = 0,
					},
					["fontSize"] = 16,
					["showIcon"] = true,
					["cycleColors"] = false,
					["isPlayer"] = false,
					["showHots"] = true,
					["showDots"] = true,
					["showName"] = false,
					["spellY"] = 0,
					["showPet"] = false,
					["critFontSize"] = 32,
					["shakeDuration"] = 0.4,
					["font"] = "Kimberley",
					["critFont"] = "Kimberley",
					["followSize"] = true,
					["textShake"] = false,
				},
				["FocusTarget"] = {
					["enable"] = false,
					["prefix"] = "",
					["advanced"] = {
						["OffsetX"] = 0,
						["OffsetY"] = 0,
					},
					["fontSize"] = 16,
					["showIcon"] = true,
					["cycleColors"] = false,
					["isPlayer"] = false,
					["showHots"] = true,
					["showDots"] = true,
					["showName"] = false,
					["spellY"] = 0,
					["showPet"] = false,
					["critFontSize"] = 32,
					["shakeDuration"] = 0.4,
					["font"] = "Kimberley",
					["critFont"] = "Kimberley",
					["followSize"] = true,
					["textShake"] = false,
				},
				["PetTarget"] = {
					["enable"] = false,
					["prefix"] = "",
					["advanced"] = {
						["OffsetX"] = 0,
						["OffsetY"] = 0,
					},
					["fontSize"] = 16,
					["showIcon"] = true,
					["cycleColors"] = false,
					["isPlayer"] = false,
					["showHots"] = true,
					["showDots"] = true,
					["showName"] = false,
					["spellY"] = 0,
					["showPet"] = false,
					["critFontSize"] = 32,
					["shakeDuration"] = 0.4,
					["font"] = "Kimberley",
					["critFont"] = "Kimberley",
					["followSize"] = true,
					["textShake"] = false,
				},
				["TargetTargetTarget"] = {
					["enable"] = true,
					["prefix"] = "",
					["advanced"] = {
						["OffsetX"] = 0,
						["OffsetY"] = 0,
					},
					["fontSize"] = 16,
					["showIcon"] = true,
					["cycleColors"] = false,
					["isPlayer"] = false,
					["showHots"] = true,
					["showDots"] = true,
					["showName"] = false,
					["spellY"] = 0,
					["showPet"] = false,
					["critFontSize"] = 32,
					["shakeDuration"] = 0.4,
					["font"] = "Kimberley",
					["critFont"] = "Kimberley",
					["followSize"] = true,
					["textShake"] = false,
				},
				["Pet"] = {
					["enable"] = true,
					["prefix"] = "",
					["advanced"] = {
						["OffsetX"] = 0,
						["OffsetY"] = 0,
					},
					["fontSize"] = 16,
					["showIcon"] = true,
					["cycleColors"] = false,
					["isPlayer"] = false,
					["showHots"] = true,
					["showDots"] = true,
					["showName"] = false,
					["spellY"] = 0,
					["showPet"] = false,
					["critFontSize"] = 32,
					["shakeDuration"] = 0.4,
					["font"] = "Kimberley",
					["critFont"] = "Kimberley",
					["followSize"] = true,
					["textShake"] = false,
				},
				["Raid2"] = {
					["enable"] = true,
					["prefix"] = "",
					["advanced"] = {
						["OffsetX"] = 0,
						["OffsetY"] = 0,
					},
					["fontSize"] = 16,
					["showIcon"] = true,
					["cycleColors"] = false,
					["isPlayer"] = false,
					["showHots"] = true,
					["showDots"] = true,
					["showName"] = false,
					["spellY"] = 0,
					["showPet"] = false,
					["critFontSize"] = 32,
					["shakeDuration"] = 0.4,
					["font"] = "Kimberley",
					["critFont"] = "Kimberley",
					["followSize"] = true,
					["textShake"] = false,
				},
				["Raid3"] = {
					["enable"] = true,
					["prefix"] = "",
					["advanced"] = {
						["OffsetX"] = 0,
						["OffsetY"] = 0,
					},
					["fontSize"] = 16,
					["showIcon"] = true,
					["cycleColors"] = false,
					["isPlayer"] = false,
					["showHots"] = true,
					["showDots"] = true,
					["showName"] = false,
					["spellY"] = 0,
					["showPet"] = false,
					["critFontSize"] = 32,
					["shakeDuration"] = 0.4,
					["font"] = "Kimberley",
					["critFont"] = "Kimberley",
					["followSize"] = true,
					["textShake"] = false,
				},
				["Player"] = {
					["enable"] = true,
					["prefix"] = "",
					["advanced"] = {
						["OffsetX"] = 0,
						["OffsetY"] = 0,
					},
					["fontSize"] = 16,
					["showIcon"] = true,
					["cycleColors"] = false,
					["isPlayer"] = false,
					["showHots"] = true,
					["showDots"] = true,
					["showName"] = false,
					["spellY"] = 0,
					["showPet"] = false,
					["critFontSize"] = 32,
					["shakeDuration"] = 0.4,
					["font"] = "Kimberley",
					["critFont"] = "Kimberley",
					["followSize"] = true,
					["textShake"] = false,
				},
				["Raid1"] = {
					["enable"] = true,
					["prefix"] = "",
					["advanced"] = {
						["OffsetX"] = 0,
						["OffsetY"] = 0,
					},
					["fontSize"] = 16,
					["showIcon"] = true,
					["cycleColors"] = false,
					["isPlayer"] = false,
					["showHots"] = true,
					["showDots"] = true,
					["showName"] = false,
					["spellY"] = 0,
					["showPet"] = false,
					["critFontSize"] = 32,
					["shakeDuration"] = 0.4,
					["font"] = "Kimberley",
					["critFont"] = "Kimberley",
					["followSize"] = true,
					["textShake"] = false,
				},
				["Party"] = {
					["enable"] = true,
					["prefix"] = "",
					["advanced"] = {
						["OffsetX"] = 0,
						["OffsetY"] = 0,
					},
					["fontSize"] = 16,
					["showIcon"] = true,
					["cycleColors"] = false,
					["isPlayer"] = false,
					["showHots"] = true,
					["showDots"] = true,
					["showName"] = false,
					["spellY"] = 0,
					["showPet"] = false,
					["critFontSize"] = 32,
					["shakeDuration"] = 0.4,
					["font"] = "Kimberley",
					["critFont"] = "Kimberley",
					["followSize"] = true,
					["textShake"] = false,
				},
				["TargetTarget"] = {
					["enable"] = true,
					["prefix"] = "",
					["advanced"] = {
						["OffsetX"] = 0,
						["OffsetY"] = 0,
					},
					["fontSize"] = 16,
					["showIcon"] = true,
					["cycleColors"] = false,
					["isPlayer"] = false,
					["showHots"] = true,
					["showDots"] = true,
					["showName"] = false,
					["spellY"] = 0,
					["showPet"] = false,
					["critFontSize"] = 32,
					["shakeDuration"] = 0.4,
					["font"] = "Kimberley",
					["critFont"] = "Kimberley",
					["followSize"] = true,
					["textShake"] = false,
				},
				["Arena"] = {
					["enable"] = false,
					["prefix"] = "",
					["advanced"] = {
						["OffsetX"] = 0,
						["OffsetY"] = 0,
					},
					["fontSize"] = 16,
					["showIcon"] = true,
					["cycleColors"] = false,
					["isPlayer"] = false,
					["showHots"] = true,
					["showDots"] = true,
					["showName"] = false,
					["spellY"] = 0,
					["showPet"] = false,
					["critFontSize"] = 32,
					["shakeDuration"] = 0.4,
					["font"] = "Kimberley",
					["critFont"] = "Kimberley",
					["followSize"] = true,
					["textShake"] = false,
				},
				["Assist"] = {
					["enable"] = false,
					["prefix"] = "",
					["advanced"] = {
						["OffsetX"] = 0,
						["OffsetY"] = 0,
					},
					["fontSize"] = 16,
					["showIcon"] = true,
					["cycleColors"] = false,
					["isPlayer"] = false,
					["showHots"] = true,
					["showDots"] = true,
					["showName"] = false,
					["spellY"] = 0,
					["showPet"] = false,
					["critFontSize"] = 32,
					["shakeDuration"] = 0.4,
					["font"] = "Kimberley",
					["critFont"] = "Kimberley",
					["followSize"] = true,
					["textShake"] = false,
				},
				["RaidPet"] = {
					["enable"] = false,
					["prefix"] = "",
					["advanced"] = {
						["OffsetX"] = 0,
						["OffsetY"] = 0,
					},
					["fontSize"] = 16,
					["showIcon"] = true,
					["cycleColors"] = false,
					["isPlayer"] = false,
					["showHots"] = true,
					["showDots"] = true,
					["showName"] = false,
					["spellY"] = 0,
					["showPet"] = false,
					["critFontSize"] = 32,
					["shakeDuration"] = 0.4,
					["font"] = "Kimberley",
					["critFont"] = "Kimberley",
					["followSize"] = true,
					["textShake"] = false,
				},
			},
		},
		["colors"] = {
			["Ranged"] = {
				["b"] = 0,
				["g"] = 1,
				["r"] = 1,
			},
			["Physical"] = {
				["b"] = 0,
				["g"] = 1,
				["r"] = 1,
			},
			[4] = {
				["g"] = 0.5019607843137255,
			},
			[8] = {
				["b"] = 0.3019607843137255,
				["r"] = 0.3019607843137255,
			},
			[16] = {
				["r"] = 0.5019607843137255,
			},
			[32] = {
				["b"] = 0.596078431372549,
				["g"] = 0.1725490196078431,
				["r"] = 0.4117647058823529,
			},
			["Prefix"] = {
				["b"] = 0,
				["g"] = 0,
				["r"] = 1,
			},
			[64] = {
				["b"] = 1,
				["g"] = 0.5019607843137255,
			},
			[2] = {
				["b"] = 0.5019607843137255,
				["g"] = 0.9019607843137255,
			},
		},
	}
end
