local ElvUI_EltreumUI, E, L, V, P, G = unpack(select(2, ...))

-- Gladdy profile setup
function ElvUI_EltreumUI:GetGladdyProfile()
	if IsAddOnLoaded("Gladdy") then
		if GladdyXZ.profiles.Eltreum then
			--local key = {[E.mynameRealm] = "Eltreum"}
			--table.insert(GladdyXZ.profileKeys, key)
			table.insert(GladdyXZ.profileKeys, E.mynameRealm)
			GladdyXZ["profileKeys"][E.mynameRealm] = "Eltreum"
		else
			GladdyXZ = {
				["profileKeys"] = {
					[E.mynameRealm] = "Eltreum",
				},
				["profiles"] = {
					["Eltreum"] = {
						["buffsBuffsIconPadding"] = 0,
						["shadowsightTimerRelPoint1"] = "TOP",
						["castBarXOffset"] = -26,
						["castBarBgColor"] = {
							["a"] = 0.7000000178813934,
						},
						["drFontScale"] = 0.9,
						["buffsBuffsCooldownGrowDirection"] = "LEFT",
						["npTremorFont"] = "Kimberley",
						["ciYOffset"] = -3.99993896484375,
						["castBarFont"] = "Kimberley",
						["petHealthBarTexture"] = "Eltreum-Elvui-Norm",
						["healthTextLeftOutline"] = true,
						["cooldownYOffset"] = 26,
						["drIconPadding"] = 0,
						["powerBarHeight"] = 16,
						["auraIconZoomed"] = true,
						["racialWidthFactor"] = 1,
						["castBarFrameStrata"] = "HIGH",
						["petPortraitBorderStyle"] = "Interface\\AddOns\\Gladdy\\Images\\Border_Gloss",
						["rangeCheckClassIcon"] = true,
						["castBarIconZoomed"] = true,
						["healthActual"] = true,
						["healthBarBgColor"] = {
							["a"] = 0.7000000178813934,
						},
						["castBarWidth"] = 246,
						["drLevelTextFont"] = "Kimberley",
						["locked"] = true,
						["auraFont"] = "Kimberley",
						["y"] = 590.2987875546933,
						["x"] = 1039.027789922649,
						["bottomMargin"] = 50.99993896484375,
						["trinketFont"] = "Kimberley",
						["trinketFontScale"] = 1.3,
						["auraBuffBorderColor"] = {
							["r"] = 0.6666666666666666,
							["g"] = 0.6666666666666666,
							["b"] = 0.6666666666666666,
						},
						["petHeight"] = 19,
						["ciXOffset"] = 99.9998779296875,
						["powerTextLeftOutline"] = true,
						["buffsCooldownGrowDirection"] = "LEFT",
						["powerBarBgColor"] = {
							["a"] = 0.3500000238418579,
							["r"] = 0.8,
							["g"] = 0.8,
							["b"] = 0.8,
						},
						["castBarIconStyle"] = "Interface\\AddOns\\Gladdy\\Images\\Border_squared_blp",
						["healthTextRightOutline"] = true,
						["showMover"] = false,
						["castBarColor"] = {
							["g"] = 0.8980392156862745,
							["b"] = 0.4274509803921568,
						},
						["leaderBorder"] = false,
						["cooldownIconZoomed"] = true,
						["cooldownCooldownAlpha"] = 0.9,
						["healthBarHeight"] = 30,
						["petHealthBarBorderSize"] = 6,
						["racialXOffset"] = 267,
						["classIconSpecIcon"] = true,
						["powerBarBorderSize"] = 1,
						["petWidth"] = 100,
						["cooldownSize"] = 26,
						["petHealthBarFont"] = "Kimberley",
						["drGrowDirection"] = "LEFT",
						["trinketXOffset"] = 220,
						["trinketSize"] = 47,
						["shadowsightTimerX"] = 0,
						["rangeCheckOorFactor"] = 3,
						["buffsCooldownAlpha"] = 0.9,
						["buffsBorderColor"] = {
							["r"] = 0.6666666666666666,
							["g"] = 0.6666666666666666,
							["b"] = 0.6666666666666666,
						},
						["shadowsightTimerRelPoint2"] = "TOP",
						["npTotemColors"] = {
							["totem8177"] = {
								["color"] = {
									["g"] = 0,
									["b"] = 0,
								},
							},
							["totem2484"] = {
								["color"] = {
									["b"] = 0,
									["g"] = 0,
									["r"] = 0,
								},
							},
							["totem8512"] = {
								["color"] = {
									["b"] = 0,
									["r"] = 0,
								},
							},
							["totem16190"] = {
								["color"] = {
									["b"] = 0,
									["g"] = 0,
									["r"] = 0,
								},
							},
							["totem8143"] = {
								["color"] = {
									["b"] = 0,
									["g"] = 0,
									["r"] = 0,
								},
							},
						},
						["rangeCheckTrinket"] = true,
						["castBarYOffset"] = -47,
						["racialSize"] = 47,
						["buffsBuffsIconSize"] = 23,
						["classIconXOffset"] = -48,
						["powerTextRightOutline"] = true,
						["powerPercentage"] = true,
						["newLayout"] = true,
						["totemPulseBarBorderSize"] = 2,
						["drXOffset"] = -79,
						["buffsBuffsIconZoomed"] = true,
						["racialBorderStyle"] = "Interface\\AddOns\\Gladdy\\Images\\Border_squared_blp",
						["auraBorderStyle"] = "Interface\\AddOns\\Gladdy\\Images\\Border_squared_blp",
						["announcements"] = {
							["trinketReady"] = true,
							["spec"] = false,
						},
						["racialFont"] = "Kimberley",
						["totemPulseBarBorderStyle"] = "1 Pixel",
						["buffsYOffset"] = -31,
						["healthBarBorderSize"] = 1,
						["npTotemPlatesBorderStyle"] = "Interface\\AddOns\\Gladdy\\Images\\Border_squared_blp",
						["shadowsightTimerLocked"] = true,
						["totemPulseBarTexture"] = "ElvUI Norm1",
						["racialIconZoomed"] = true,
						["auraCooldownAlpha"] = 0.9,
						["petHealthBarBorderStyle"] = "None",
						["barWidth"] = 220,
						["cooldownMaxIconsPerLine"] = 14,
						["buffsFont"] = "Kimberley",
						["buffsBuffsYOffset"] = -50,
						["cooldownBorderStyle"] = "Interface\\AddOns\\Gladdy\\Images\\Border_squared_blp",
						["castBarTexture"] = "ElvUI Norm1",
						["classIconWidthFactor"] = 1,
						["petXOffset"] = -18,
						["castBarIconSize"] = 20,
						["drFont"] = "Kimberley",
						["classIconZoomed"] = true,
						["healthBarFont"] = "Kimberley",
						["buffsFontScale"] = 0.7000000000000001,
						["petEnabled"] = false,
						["powerBarBorderStyle"] = "1 Pixel",
						["castBarBorderSize"] = 2,
						["trinketCooldownAlpha"] = 0.9,
						["drBorderColor"] = {
							["r"] = 0.6666666666666666,
							["g"] = 0.6666666666666666,
							["b"] = 0.6666666666666666,
						},
						["buffsIconSize"] = 19,
						["classIconSize"] = 48,
						["drCooldownAlpha"] = 0.9,
						["racialCooldownAlpha"] = 0.9,
						["buffsShowAuraDebuffs"] = true,
						["healthBarTexture"] = "ElvUI Norm1",
						["castBarBorderStyle"] = "1 Pixel",
						["drBorderStyle"] = "Interface\\AddOns\\Gladdy\\Images\\Border_squared_blp",
						["auraDebuffBorderColor"] = {
							["r"] = 0.6666666666666666,
							["g"] = 0.6666666666666666,
							["b"] = 0.6666666666666666,
						},
						["shadowsightTimerY"] = -106.9030838012695,
						["petYOffset"] = 21.50006103515625,
						["rangeCheckRacial"] = true,
						["ciBorderStyle"] = "Interface\\AddOns\\Gladdy\\Images\\Border_squared_blp",
						["totemPulseTextFont"] = "Kimberley",
						["cooldownFontScale"] = 0.6,
						["powerBarTexture"] = "ElvUI Norm1",
						["trinketBorderStyle"] = "Interface\\AddOns\\Gladdy\\Images\\Border_squared_blp",
						["buffsXOffset"] = -48,
						["cooldownIconDesaturateOnCooldown"] = true,
						["cooldownBorderColor"] = {
							["r"] = 0,
							["g"] = 0,
							["b"] = 0,
						},
						["buffsBuffsXOffset"] = -48,
						["highlightInset"] = true,
						["healthBarBorderStyle"] = "1 Pixel",
						["cooldownIconPadding"] = 0,
						["powerBarFont"] = "Kimberley",
						["cooldownFont"] = "Kimberley",
						["racialYOffset"] = 0.0001220703125,
						["trinketWidthFactor"] = 1,
						["castBarFontOutline"] = true,
						["buffsIconPadding"] = 0,
						["classIconBorderStyle"] = "Interface\\AddOns\\Gladdy\\Images\\Border_squared_blp",
						["drIconZoomed"] = true,
						["drIconSize"] = 31,
					},
				},
			}
		end
	end
end
